### ISSUE TITLE
Crash on opening Pinned section in profile

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1014]
When I open the app, go to my profile and tap on "pinned" section (I have 0 pinned toots), app just restarts without any prompts. It doesn't look like crash, just restarts. If I go to my profile and tap on "pinned" section again, it crashes with default Android dialog (About app / Kill app / Send feedback)

* * * *
- Tusky Version: Tusky Nightly 4.1-c0c73f5
- Android Version: 9.0
- Android Device: Oneplus 5

**Comment by charlag** [comment]
If you have a stacktrace, it would be amazing. It's okay if not.

**Comment by charlag** [comment]
You can send it to email in the future, no problem, thanks for the stacktrace, I'll try to fix it soon!
