### ISSUE TITLE
Make a shortcut to compose a new toot

### ISSUE THREAD

**Issue by wersimmon** [tuskyapp/Tusky#1031]
It would be great if there was a long-press shortcut to go straight to the Compose Toot activity, so you could skip the timeline.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wersimmon** [comment]
(Some previous work done in #1030 )

**Comment by MasterGroosha** [comment]
By the way, there's "Compose toot" quick tile, which you can use to access toot composer from literally anywhere.
