### ISSUE TITLE
Show how much of video media is loaded

### ISSUE THREAD

**Issue by issueseverywhere** [tuskyapp/Tusky#1033]
Hi,

First, thanks a lot for maintaining Tusky!

It would be great, especially for people with low connection, to show how much of a video media is loaded, as on youtube and most video hosting websites. 

For example, by coloring in darker blue or another color the progress bar of the video according to how much of it is loaded and ready to be played.

Thanks!
* * * *
- Tusky Version: 4.1
- Android Version: 7.1.2
- Android Device: crosscall actuon-x3
- Mastodon instance (if applicable): ap.kios.cc

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by viviicat** [comment]
This is probably no longer valid. I see a different color in the progress bar to indicate the buffer load state.
