### ISSUE TITLE
Image downloading won't work when Blokada is active

### ISSUE THREAD

**Issue by zayuim** [tuskyapp/Tusky#1051]
A somewhat of a strange issue image downloading will not work when Blokada (ad blocking software is active). To be clear nothing inside Tusky stops working while Blokada is active, images still show, but the option to download to internal memory stops working. Unless you add Tusky to the whitelist.

I have the StevenBlack Unifed list as the blacklist and Cloudflare 1.1.1.1 as the DNS.

I don't know if this is really the fault of Tusky, But is anyone able to reproduce?

* * * *
- Tusky Version: 4.1
- Android Version: 8.1.0
- Android Device: Nexus 5X

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mihudevcom** [comment]
Just tested this and I can reproduce the issue. 

* Tusky Version: 5.0 beta 1
* Android Version: 9.0.0
* Android Device: Xiaomi Mi A1

**Comment by mihudevcom** [comment]
Seems like you can download only over Wifi. So it's not because of Blokada. 

@connyduck Should the app be allowed to download over a mobile network as well?

**Comment by mihudevcom** [comment]
@zayuim In Blokada whitelist make sure you add apps on your device that contain Download. I've added com.android.providers.downloads.ui and it seems to work now without having to whitelist Tusky. Can you confirm this?

**Comment by mihudevcom** [comment]
@zayuim The issue seems to be related to this: https://github.com/blokadaorg/blokada/issues/209

So it's not really a Tusky issue but and issue with Blokada itself.

**Comment by zayuim** [comment]
> @zayuim The issue seems to be related to this: [blokadaorg/blokada#209](https://github.com/blokadaorg/blokada/issues/209)
> 
> So it's not really a Tusky issue but and issue with Blokada itself.

OK I see.

Also I added `com.android.providers.downloads.ui` to the whitelist and it now does work.

Blokada has only added  `com.android.providers.downloads` to the whitelist by default. Thank you for your help, I can use Tusky as expected.
