### ISSUE TITLE
When sharing files to tusky, it doesn't return control after posting

### ISSUE THREAD

**Issue by vaartis** [tuskyapp/Tusky#1061]
Before Tusky 5 tusky returned control back to the app the file was shared from, but as of Tusky 5 beta 1 (from google play), it just opens the main timeline instead.

Steps to reproduce:
- Open any aplication that can share files with others
- Select tusky
- Send the post

Expected:
The control is transfered back to the application sharing the file

What actually happens:
Tusky opens the main timeline. An interesting detail is that in the "switch application" menu the icon is of the original application and pressing "back" while on the main timeline returns the control to that application.

* * * *
- Tusky Version: 5.0 beta 1
- Android Version: 8.0.0
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
closed by #1062
