### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by MrTeeXD** [tuskyapp/Tusky#1064]
[Tusky does not give a notification when a new toot is posted on a followed account nor any notification when a reply is added to a toot].

* * * *
- Tusky Version: 4.1
- Android Version: 8.0.0
- Android Device: Huaweii P Smart
- Mastodon instance (if applicable): https://mastodon.social

- [✔️ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bernd289** [comment]
Check your device settings and allow Tusky to run in background.
Please also check this link: https://dontkillmyapp.com/huawei
