### ISSUE TITLE
[feature request] Link preview also on timeline

### ISSUE THREAD

**Issue by lenchan139** [tuskyapp/Tusky#1075]
from #141 and #424 , there has link preview but only on detail toots.
But on Mastodon web of current version, the  link preview also on timeline like this:

![screenshot_20190224_125633](https://user-images.githubusercontent.com/3122461/53295336-0bdd0600-3834-11e9-924d-ca8b25e83f16.png)

![screenshot_20190224_125929](https://user-images.githubusercontent.com/3122461/53295337-0bdd0600-3834-11e9-84e5-dc0382d7cdac.png)

* * * *
- Tusky Version: 5.1 (play store)
- Android Version: 9.0.0
- Android Device: Sony XZ1 Compact
- Mastodon instance (if applicable):mstdn.jp / meow.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I would make it configurable, since it increases network usage, but yes we should add that feature.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/1681
