### ISSUE TITLE
Turn off media downloads

### ISSUE THREAD

**Issue by justinabrahms** [tuskyapp/Tusky#1077]
I'd like the ability to turn off image downloading to preserve bandwidth.

* * * *
- Tusky Version: 5

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
You can already do that? Go to Account Preferences and turn off "Show media previews". If you mean something else, please elaborate.

**Comment by charlag** [comment]
H-how... did I miss that?
Sorry ><

**Comment by justinabrahms** [comment]
@connyduck It looked like that setting turned off image previews, but I suspected that the images do download in the background still (given how snappy they seem to load). If they don't also download, it might be worth mentioning that on/near that setting.

**Comment by connyduck** [comment]
No, they definitely do not load in the background. You just seem to have a fast internet connection. :)
Any suggestions for better wording so its clearer? Maybe "Download media previews" instead of "Show media previews"?

**Comment by justinabrahms** [comment]
That would be much clearer to me. :)
