### ISSUE TITLE
[Feature Request] Scroll to top when tapping on current tab in profiles

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1078]
Tapping on current tab on main screen scolls you to top. However, when you open one's profiile and tap on current tab ("posts" or "posts and replies" ... ), nothing happens.
* * * *
- Tusky Version: 5.1 (nightly)
- Android Version: 9.0
- Android Device: Oneplus 5

- [ * ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
closed by #1146
