### ISSUE TITLE
custom list columns

### ISSUE THREAD

**Issue by ashkitten** [tuskyapp/Tusky#1084]
having a hard time believing nobody's asked for this yet, but seeing as custom columns were added recently it doesn't seem too much of a stretch. just want the ability to pin a list as a custom tab/column

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey
Thanks for opening it, I was also thinking that adding it should be fairly easy but was forgetting to open an issue.

**Comment by ariasuni** [comment]
Apparently, it’s been fixed in #1570, and if I’m correct this feature is available since Tusky 10.
