### ISSUE TITLE
Bad Spanish translation strings

### ISSUE THREAD

**Issue by JuanjoSalvador** [tuskyapp/Tusky#1088]
Some Spanish strings are bad translated, for example the spanish string for sending new toot, is translated as "eliminando toot", which means "deleting toot".

* * * *
- Tusky Version: 4.1
- Android Version: 7.1
- Android Device: Redmi 4A
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Please, help us fix that!
https://crowdin.com/project/tusky

**Comment by JuanjoSalvador** [comment]
I also noticed that there is some missing strings at the spanish translation
