### ISSUE TITLE
Add Esperanto on Crowdin

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#1093]
Please add Esperanto on Crowdin so I can translate it.

You will want to add an option to change Tusky language afterwards, because Esperanto is not available on Android so there would be no way to use it.

**Comment by charlag** [comment]
Related to #644 
Honestly I think that it's PITA to add custom language layer but worth keeping for now I guess

**Comment by connyduck** [comment]
According to [this article](https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758) its not that complicated. But I fear we might introduce a lot of weird bugs like with the theme switching which does not work on some Androids. I would happily merge it if somebody wants to add and test this feature.

**Comment by charlag** [comment]
Wait,  think article says about changing language on the fly (which is really possible) but to add the the language which system doesn't support (Esperanto or #644) we would need to translate each thing by hand.

**Comment by connyduck** [comment]
Ok, you got me curious so I tried it out. It works with Esperanto.
Don't mix these two things up: An Android version is translated into a language vs an Android versions `Locale` knows a language. Android 5 `Locale` knows Esperanto, even if you cannot switch to it in the language menu.

**Comment by charlag** [comment]
Oh, that's interesting. My bad than. Do you know if it helps with #644 too?

**Comment by connyduck** [comment]
Don't worry, I also did not know this until just now. 
Yes, I think it does.

**Comment by connyduck** [comment]
With this method we can check what Locales are available https://developer.android.com/reference/android/content/res/Configuration.html#getLocales()

**Comment by connyduck** [comment]
I added Esperanto on Crowdin!

**Comment by ariasuni** [comment]
I finished translating Tusky in Esperanto. Do you think it can be part of the next minor release?

**Comment by connyduck** [comment]
Yes it will be part of the next release
