### ISSUE TITLE
Black theme buttons

### ISSUE THREAD

**Issue by Juicerram** [tuskyapp/Tusky#1098]
When using the light and dark themes, the navigation buttons on screen switch to match. But when using the black theme, the buttons turn light 

* * * *
- Tusky Version: 5.1
- Android Version: 9
- Android Device: OnePlus 6
- Mastodon instance (if applicable):

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
What buttons do you mean? Can you maybe share a screenshot?

**Comment by Juicerram** [comment]
[Here's an Imgur album with 3 screenshots, one for each theme.](https://imgur.com/a/iCaYQ37) The buttons I'm talking about are at the bottom of the screen, Android's default navigation controls (not sure if there's a better name for them)

**Comment by connyduck** [comment]
Ah I see, thx! We don't style the buttons for the black theme because they are usually black, but I guess on a One Plus the white style is default?

**Comment by Juicerram** [comment]
I think so yes, though when I have the keyboard open, the bar turns black (on all themes)

**Comment by connyduck** [comment]
Ok, I will style them black. Can I send you a test build so you can confirm it works?

**Comment by Juicerram** [comment]
Thanks! And yes of course!

**Comment by connyduck** [comment]
You can download the test build here: https://app.bitrise.io/artifact/12590320/p/1d936060a0a80fe78cb04efb2b73f932

Turns out, the navigation bar is already styled, so I am not sure if this actually helps :(

**Comment by Juicerram** [comment]
Unfortunately the bar is the same as before, dark for the dark theme and light on the black theme. Thanks for trying

**Comment by connyduck** [comment]
Can you try this build please? https://app.bitrise.io/artifact/12592050/p/4cf99a0849d729cbc0a29287f8fbf720
It no longer a totally black color because I found this: https://stackoverflow.com/questions/51187710/android-navigationbarcolor-doesnt-change-to-black-only-to-black

**Comment by Juicerram** [comment]
Success! Thank you!

**Comment by connyduck** [comment]
Thx for reporting and helping!
