### ISSUE TITLE
Add support for polls

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#1102]
https://github.com/tootsuite/mastodon/pull/10111

I have not yet looked at it and I really hope its not a breaking change that will crash Tusky. 
But we definitely need to add support for displaying polls and voting very soon. 
Creating polls can wait some time, but we of course we will also add that feature.

**Comment by connyduck** [comment]
I will do this in three parts:
1) polls in timelines & voting
2) polls in notifications
3) creating polls

1) is about 60% finished

**Comment by rinpatch** [comment]
Would be nice if poll creation used `poll_limits` object from `/api/v1/instance` used by glitch-soc and (soon) pleroma instead of depending on hardcoded values
