### ISSUE TITLE
[Feature Request] Lists as submenus like Feedly?

### ISSUE THREAD

**Issue by aka-rin** [tuskyapp/Tusky#1118]
Well, yesterday I started to think about the possibility of using Mastodon as an RSS reader.

And then I found a service to convert RSS to ActivityPub account: https://bots.tinysubversions.com/convert/ . And it turns out that the 500 characters limit does not exist:

![photo_2019-03-09 15 27 18](https://user-images.githubusercontent.com/29725543/54067824-e8787900-427f-11e9-9409-318017bab681.jpeg)

So it would be handy if Tusky makes lists as submenus, like Feedly:

![Feedly on Google Play](
https://lh3.ggpht.com/zvOaxKjjIV55BMeTxoAwH0XwSvSRv7ykVVJlF6qOfWDEeIII_6WTXaIyEx_ULDH0E8ib=w1340-h730)

I know it may be a bit off the topic, but it is still an interesting thought, isn't it?

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey
I'm not sure that's our scope. We try to stay focused on microblogging. Soon you'll be able to use lists as columns but I think that there are many things in Tusky which makes this scenario not really comfortable.

I would ask Fedilab though, they have a broader scope.

**Comment by aka-rin** [comment]
I know, so the problem is, will Tusky be more comfortable for RSS users?

For example, users can customize the amount of characters in a long toot that showed on timeline. Lists can be pinned as tabs and the maximum of tabs can be more than 5. Just my two cents ...

**Comment by charlag** [comment]
Currently we don't agree that this would be a good idea for Tusky, sorry. It's a good idea for another app perhaps.
