### ISSUE TITLE
Sharing articles from news apps to Tusky

### ISSUE THREAD

**Issue by bernd289** [tuskyapp/Tusky#1132]
Sharing articles from Google News or Feedly App to Tusky looks like this:
"Title
Title
Link"

To other apps it gets shared correctly (no duplicated title) so I guess it's a bug in Tusky.

* * * *
- Tusky Version: 5.2
- Android Version: 9
- Android Device: Galaxy S9+

**Comment by connyduck** [comment]
I think this was introduced by this PR https://github.com/tuskyapp/Tusky/pull/1020
Removing the subject will make sharing from some other apps less comfortable again :/
