### ISSUE TITLE
[Feature Request] Domain Blocks

### ISSUE THREAD

**Issue by aka-rin** [tuskyapp/Tusky#1143]
To block annoying messages in federated public timeline...

API reference: https://docs.joinmastodon.org/api/rest/domain-blocks/

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Px3XjG6P** [comment]
If this the same as blocking/muting an entire mastodone instance, then it's exactly what I'm looking for.

**Comment by connyduck** [comment]
#1311
