### ISSUE TITLE
[Feature Request] Notifications Divided by Types

### ISSUE THREAD

**Issue by ghost** [tuskyapp/Tusky#1144]
According to Mastodon's [API manual](https://docs.joinmastodon.org/api/entities/#type-2), there are four types of notifications:

- follow
- mention
- reblog
- favourite

It would be great if Tusky add an extra row on notification panel to divide notifications by types. 

By the way, please add the 'clear all notifications' function (#762).  Anyway, you can put it in account preference page.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Closing, as:

- These can now be filtered by type (and muted by type as well)
- "Clear all" feature was written too.
