### ISSUE TITLE
Accessibility: Give an inserted photo a better contentDescription

### ISSUE THREAD

**Issue by MarcoZehe** [tuskyapp/Tusky#1155]
When composing a toot with an image, like when sharing from Google Photos or inserting via the Add Image facility, the inserted image gets a contentDescription of "Delete", at least in German. This is confusing because what actually happens when you double-tap this with TalkBack is that it opens a popup where you can either add a description or delete the image. So calling this simply "Delete" is inappropriate.

Suggestion: Give this a meaningful contentDescription like "Actions for Image ...", where ... can be either a number, like 1 or 2 etc., or if a description has already been provided, append that so the user already knows which of the images they are about to manipulate.

* * * *
- Tusky Version: both 5 and 6 Nightly.
- Android Version: 9
- Android Device: Google Pixel 3
- Mastodon instance (if applicable): All.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Thanks for reporting! We should definitely do that!

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/1188
