### ISSUE TITLE
Compose screen: second colon (:) breaks hashtag highlighting

### ISSUE THREAD

**Issue by hellp** [tuskyapp/Tusky#1174]
When my toot text contains two or more colons (":") hashtags after the second one are not highlighted anymore.

Example:
![Screenshot_tusky-20190402-193652](https://user-images.githubusercontent.com/32779/55424194-ff10a800-557f-11e9-8c4b-52be1351d871.png)

* * * *
- Tusky Version: 6.0
- Android Version: 8.0.0
- Android Device: OnePlus 3
- Mastodon instance (if applicable): floss.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
fixed in https://github.com/tuskyapp/Tusky/pull/1183
