### ISSUE TITLE
App closes when muting/blocking an account 

### ISSUE THREAD

**Issue by Macellatore** [tuskyapp/Tusky#1179]
Looks like the app crashes just after muting/blocking an account. After clicking on "Mute"/"Block" in the 3dots menu of a post in a timeline (tried both in local and personal timeline), the timeline reloads to hide the user's posts, that's when it crashes. If I manage to swipe fast enough while the posts are disappearing, I can avoid the crash. 
* * * *
- Tusky Version: 6.0
- Android Version: 6.0
- Android Device: Huawei Honor 7
- Mastodon instance (if applicable): tried a couple 

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Can not reproduce. It might be fixed by https://github.com/tuskyapp/Tusky/pull/1178.
Please wait for Tusky 6.1 to be released and tell us if the problem still exists.

**Comment by Macellatore** [comment]
> Please wait for Tusky 6.1 to be released and tell us if the problem still exists.
Seems fixed now, thanks.
