### ISSUE TITLE
Show "Network error" on choose instance screen

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1194]
When you're trying to login in offline mode, a generic "Failed to authenticate on that instance" error is shown:
![image](https://user-images.githubusercontent.com/2780044/56075890-45f96b80-5dd2-11e9-90c9-a4eaae2ea357.png)

It would be nice if it will show network error instead. 
Unfortunately I couldn't find network check code myself.

* * * *
- Tusky Version: 6.1 nightly
- Android Version: 9

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey
Network check code is simply `is IOException` for now.

-- 
Sincerely,
Ivan



13 Apr 2019, 08:56 by notifications@github.com:

**Comment by MasterGroosha** [comment]
@charlag Hm, in this case we cannot differ "No Internet connection" and "Cannot resolve inexisting domain" errors, right?

**Comment by charlag** [comment]
You cannot distinguish it in any case. Absence if network may result in DNS error, SSL error, whatnot. You can try and only check for ConnectionException but that's not reliable.

**Comment by MasterGroosha** [comment]
Gotcha. I'll leave this issue open, maybe a solution will eventually appear.

**Comment by charlag** [comment]
I'm not sure that the benefit is large enough compared to the (rather unreliable attempts) to distinguish them.
