### ISSUE TITLE
Videos can't load with "Firewall Without Root" app + Can't download any media

### ISSUE THREAD

**Issue by Anglodel** [tuskyapp/Tusky#1195]
(Bug already reported at ConnyDuck@chaos.social, but he told me to post it on Github too)
Hello Tusky Devs,

I'm using a firewall named Firewall without root (https://play.google.com/store/apps/details?id=app.greyshirts.firewall). When this firewall is enabled, Tusky never wants to load videos and download medias. It loads images without any problems, but still can't download any medias.
For some apps, I know that GooglePlayServices need to have access to Internet, and I thought that Tusky needed it, but even if PlayServices are allowed to access the Web, Tusky still don't load videos and download medias.

The necessary method to have the videos loaded is to completely disable the firewall, but again, one of the problems persists: the medias finally download themselves (and even then, it doesn't happen all the time), but they succeed only very rarely (and it never download anything when fire-wall is on). Some time ago, a grey background notification appeared at the bottom of the screen, but not anymore (maybe the latest updates have removed this feature?).

If you have any questions, feel free to ask me, I will certainly be able to give you more explanations if necessary.

* * * *
- Tusky Version: 6.1
- Android Version: 5.1.1
- Android Device: Huawei Y560-L01
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I cannot reproduce the issue with videos not loading on my Android 5 device. I can reproduce the issue with media not downloading, but this seems to be a general issue, it does not work on Android 5 at all, no matter if Firewall is on or off. Will fix it.
