### ISSUE TITLE
feature request: allow uploads of other types of files (like audio)

### ISSUE THREAD

**Issue by novadeviator** [tuskyapp/Tusky#1213]
monsterpit.net runs a modiefied glitch-soc fork that allows audio uploads. please allow to upload different types of files through tusky. doesn't the instance already reject the non-allowed media anyway?

* * * *
- Tusky Version: 6.1
- Android Version: 7.0
- Android Device: Huawei P9 lite
- Mastodon instance (if applicable): monsterpit.net

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey
Do you know if it's described somewhere or if we can query server for this support?

**Comment by novadeviator** [comment]
no, unfortunately I don't know. 

also, imaginair.es allows audio (MP3) uploads which it then converts to a video. as opposed to monsterpit.net which actually keeps original mp3 attachment to other instances, but on local instance it represents it with a video - or an image with an audio player which looks exactly as video player? (which works only on that instance). 

opus and ogg vorbis are rejected by imaginair.es but accepted by monsterpit, although it produces a transparent image and no player - on other instances it appears as an attachment.

**Comment by charlag** [comment]
I don't think it's feasible to try it until there's some API support for determining supported media types on the server. Let's revisit it if one emerges and works somehow reliably.
