### ISSUE TITLE
Pixelfed support?

### ISSUE THREAD

**Issue by ahstro** [tuskyapp/Tusky#1216]
This is more of a question than an issue, so sorry and feel free to dismiss it. I was wondering if there are any plans on supporting logging in to [Pixelfed](https://pixelfed.org) accounts? I'm not too familiar with the underlying tech, but as I understand it, Mastodon and Pixelfed and a bunch of other federated services use ActivityPub, so they should be able to communicate to some degree, but I'm not sure if it would be a HUGE effort to support other e.g. Pixelfed?

**Comment by connyduck** [comment]
Using Pixelfed with Tusky will be possible once they finished implementing the Mastodon Api. On our side thats not that much effort, I expect we will only have to do a few small adaptions.
