### ISSUE TITLE
Using sensitive content button once force the toot to be marked as sensitive

### ISSUE THREAD

**Issue by rapenne-s** [tuskyapp/Tusky#1217]
When tooting, if using the "Sensitive content" button twice, without filling the warning text, the toot will still be posted with sensitive parameter set to yes.

* * * *
- Tusky Version: 6.1
- Android Version: 8.1.0
- Android Device: something
- Mastodon instance (if applicable): bsd.network

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thats really weird. I can not reproduce the issue, can you give me a more detailed description or a video of the bug please?

**Comment by connyduck** [comment]
Ahh I see, it only makes a difference when adding an image to the status. Will fix!

**Comment by connyduck** [comment]
fixed #1309
