### ISSUE TITLE
Tooltips on toot actions and on compose actions

### ISSUE THREAD

**Issue by DragoCubed** [tuskyapp/Tusky#1220]

**Comment by charlag** [comment]
Would you mind expanding on this a little bit please? Tooltip as in "long press to show a toast with explanation" or?..

**Comment by DragoCubed** [comment]
Buttons that only have an icon and no label tend to have a tooltip when you tap and hold on them. I'm not asking for a toast.

https://developer.android.com/guide/topics/ui/tooltips

This link has an image of a tooltip.

**Comment by connyduck** [comment]
Compose actions have a tooltip. They only work on Android 8+ though.

**Comment by DragoCubed** [comment]
Out of curiosity, why do they only work on Android 8+?

**Comment by connyduck** [comment]
They use an Api that got introduced in Android 8. 
On older Android versions it would be quite complicated to make tooltips.
