### ISSUE TITLE
Allow auto-switch theme to black from light

### ISSUE THREAD

**Issue by DragoCubed** [tuskyapp/Tusky#1222]

**Comment by charlag** [comment]
Hey!
Would you mind explaining a little bit what you mean?

**Comment by DragoCubed** [comment]
Currently the you can set the theme to auto switch from light to dark. There isn't an option to switch from light to black automatically. The black theme can be useful on devices with AMOLED/OLED screens though some may prefer the black theme over the dark theme.

**Comment by charlag** [comment]
I think it's either:
"I have an AMOLED screen and power savings are so important to me that I use black theme"
or
"I don't have AMOLED screen or don't care about such power savings but eye comfort is important to me so I use different themes"

**Comment by DragoCubed** [comment]
Do you think an option to switch between the light and black theme would be useful?

**Comment by telroy** [comment]
Would love to see this being added because it's a huge oversight imo.

This could be implemented like in Fritter. It has Light and Dark themes and a separate toggle to select between Dark and True Black.

**Comment by toas-koas** [comment]
Is there any update?

**Comment by nikclayton** [comment]
I believe that if you set the theme preference to "Use system theme", and your Android device is configured to follow the day/night cycle for themes then Tusky will do the same.

**Comment by complex-hub** [comment]
@nikclayton the proposal by DragoCubed is to have an option to toggle between dark and black when "Use System Design" is enabled. Here is a rough design of what I mean:

![Tusky](https://user-images.githubusercontent.com/53913349/221434120-94446648-4b18-4117-91dd-73c8bd9a6f55.png)

This could be achieved with a toggle bellow the "App theme" option:

![amoled2](https://user-images.githubusercontent.com/53913349/221434355-1aafc71a-4445-4fa3-b403-f49a8f7a3949.png)
