### ISSUE TITLE
Refresh issue when existing refresh running

### ISSUE THREAD

**Issue by cefiar** [tuskyapp/Tusky#1228]
When an existing background refresh is running (eg: just opened app, timed background refresh), and the user pulls down to refresh, you get issues with toots disappearing from the Home timeline. Doesn't always happen though, but the below should allow someone to reproduce somewhat reliably.

1. Start Tusky and wait for an update to finish, so it should have all the latest toots.
2. Quit Tusky (force kill if needed so it's not running in the background).
3. Log into the web version of the Mastodon instance and wait till 2-3 new toots have appeared in the Home timeline.
4. Start Tusky and within 2-3 seconds of the UI loading, pull down to refresh.
5. Compare this list of toots with the Mastodon web version. If they are different, forcing a change of the theme seems to restore the missing toots (eg: change from Black to Dark to Black again).

Notes:
- I suspect a workaround for this would be to not allow multiple refreshes to fire if a refresh is already happening (eg: some sort of lock around the refresh function). A status icon that shows when a refresh is happening would probably help as well (at least with further diagnosis).
- The issue can happen if you manage to pull down refresh as a background timed refresh has just started as well (not just at startup).

* * * *
- Tusky Version: 6.1
- Android Version: 8.0
- Android Device: Samsung SM-G930F
- Mastodon instance (if applicable): social.chinwag.org

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thx for the detailed report. I will try to fix this for the next release.

**Comment by MasterGroosha** [comment]
wow, looks like this is most correct explanation to "disappearing toots" bug which I've been trying to reproduce for some months already, spamming ConnyDuck in PM (sorry).
