### ISSUE TITLE
[Feature Request] keep showing old toots when doing "load more"

### ISSUE THREAD

**Issue by brabalan** [tuskyapp/Tusky#1230]
As a Mastodon completionist, I really like caching and the "load more" feature. Currently I use it the following way:
- tap the "load more"
- quickly scroll up to hide it, before it loads
- repeat until I have loaded everything.
Otherwise I lose my place (I read toots from oldest to newest, i.e., from bottom to top) and I need to search for the last toot I was reading.

I would like an option to keep the position at the toot just below the "load more", to avoid doing this gymnastics. In Fedilab this option is called "Display new toots above the Fetch more button".

* * * *
- Tusky Version: 6.1, fdroid

**Comment by iMartyn** [comment]
Agreed, this is a big usability issue for me, having just switched from fedilab for yes, that reason. I think this should be an option as I'm sure not everyone uses fedi the way we do.
Tangentially it would be nice to have tusky be able to wake up and fetch more toots on a regular basis so we never see the load more button if our internet is always connected (again, optionally and probably wifi dependent for some people).

**Comment by FeministWiki** [comment]
I'm maintaining a branded version of Tusky and one of our users asked for the same thing.

We had some confusion over whether this report accurately captures what she asked for, so let me point out the important bit from the OP:

"Keep the [current] position [of the ScrollView] at the toot just below the "load more" [when the "load more" is clicked and new toots are loaded]"

So basically:

- You click on "load more"
- A number of toots are loaded and displayed *above* the load more button, but the scroll view still displays the toot that was *below* the load more button (and the button itself if there's more to load)
- You can keep clicking on "load more" until everything is loaded without losing your position in the scroll view (the toot below the "load more" button).

Thanks for the amazing app BTW. If I find time I'll see if I can implement this myself so we contribute back to the project. :-)

**Comment by ckorn** [comment]
Any news here? Really would love that feature.

**Comment by iMartyn** [comment]
It's actually got worse in the latest version where you have to have the "load more" button off-screen to keep what seems to me the "right" way to read toots (chronologically - I like to "catch up").

Before current version you could just have load more slightly off-screen and keep your reading position, current version has to be completely off-screen or you loose your position.
