### ISSUE TITLE
[Feature] IOS Client

### ISSUE THREAD

**Issue by asddsaz** [tuskyapp/Tusky#1243]
**Feature**: [Free Software](https://www.wikipedia.org/wiki/Free_software) [Mastodon](https://www.wikipedia.org/wiki/Mastodon_(software)) [IOS](https://www.wikipedia.org/wiki/IOS) [client](https://www.wikipedia.org/wiki/Client_%28computing%29).

______

Want to support this issue? Post on [bounty on it](https://www.bountysource.com/issues/73753230-feature-ios-client)! We accept bounties via [Bountysource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by connyduck** [comment]
Its not possible to build Tusky for iOS, sorry.
