### ISSUE TITLE
[Bug] Some images disappear

### ISSUE THREAD

**Issue by aka-rin** [tuskyapp/Tusky#1255]
It seems that Tusky changes the image library in 7.0 release and some images just disappear after loaded. Most of them are PNGs from pawoo.net.

PS: If you touch the eye button at the left-top corner twice it will show again, but then if you swipe up and down it will disappear again... 😂 

* * * *
- Tusky Version: 7.0
- Android Version: 9.0
- Mastodon instance (if applicable): pawoo.net

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by pandasoft0** [comment]
Looks like app has an issue with attachments with focal point set.
@connyduck app uses the centerCrop transformation when focal point not set and matrix when focal point set. I will try to update it

**Comment by connyduck** [comment]
Ahh yes I found the same thing when investigating this bug, its definitely the focal point. We should not remove the focal point funtionality though. cc @jchmrt
