### ISSUE TITLE
“Use System Design” doesn't work on Android Q

### ISSUE THREAD

**Issue by cassidyjames** [tuskyapp/Tusky#1260]
Android Q officially introduced a system-wide dark theme. However, it doesn't appear the “Use System Design” theme preference in Tusky respects this and switches the theme base on this setting.

**Comment by connyduck** [comment]
fixed by https://github.com/tuskyapp/Tusky/pull/1455

**Comment by cassidyjames** [comment]
I'm still seeing this issue in Android 10; I'm not sure if it was a regression or wasn't actually fixed. I can provide more details if needed!

**Comment by connyduck** [comment]
Works for me. Please provide more details, I'm especially interested in the exact Tusky and Android versions.

**Comment by cassidyjames** [comment]
Pixel 3, Android 10 (January security update), Tusky 9.1 (Play Store beta). Will attach a screen recording shortly.

**Comment by cassidyjames** [comment]
Ah I see now there hasn't been a release for several months, and this commit was after the latest release. I'll see if I can manually build an APK or something.

**Comment by charlag** [comment]
1. You are on beta branch, maybe beta was not updated and only main channel was
2. There's a nightly build in play store

And you've found it, good

**Comment by cassidyjames** [comment]
Yep, sorry about the confusion! I can confirm that this is fixed for me on the nightly green version. Gonna keep using that unless I hit any major issues. :smile:
