### ISSUE TITLE
[ feature request ] Show full image height  for preview images

### ISSUE THREAD

**Issue by smsn** [tuskyapp/Tusky#1265]
and add Google Translate like translate.google.cn
https://github.com/tuskyapp/Tusky/issues/134#issue-221320871
* * * *
- Tusky Version:7.0
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
Sorry, but we have already declined such requests for images in the past: #250 
Translation could be possible if we found an API which does this for free: #134
