### ISSUE TITLE
Progressively enhance images on viewing

### ISSUE THREAD

**Issue by jhaye** [tuskyapp/Tusky#1267]
Mastodon offers image thumbnails that Tusky already loads when displaying posts with images on the TL.
On a slow connection loading the full image might take some time, so when touching the image to take a closer look, one might have to wait a few seconds in order to see the image again. All this while the thumbnail is already available.

I would propose, when viewing an image in full, to display the thumbnail instead of a loading screen, and then replace it with the full resolution image once loaded.
A similar thing could be done with video thumbnails.

* * * *
- Tusky Version: 7.0

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey!
That's a good idea I think but I would like to hear others on this.

**Comment by NitroNils** [comment]
Great! Totally agree!
Who would rather see a loading symbol rather than a lowres image?
I often have a slow connection.
I saw a ref to commit - is this closed then?

**Comment by charlag** [comment]
Unfortunately I run into the problems with Transitions, apparently Android really doesn't like when you change image in the middle of the transition and I didn't have enough spoons to fix it yet
