### ISSUE TITLE
Blockquote in toots have no style 

### ISSUE THREAD

**Issue by Aldarone** [tuskyapp/Tusky#1271]
I'm using the glitch-soc flavour of mastodon which doesn't strip some nice html tags like *strong* *em* etc...

When a toot contains a blockquote there is a default style which is really not good looking compared to the web interface.

Tusky :   
![](https://i.imgur.com/gs8LPgn.jpg)

WebUI :   
![](https://i.imgur.com/AnZEhdt.jpg)

**Comment by mal0ki** [comment]
Thank you for bringing this to our attention!

**Comment by charlag** [comment]
Yup, thanks for reporting! I don't know how to easily do it though, maybe with span?.. we use automatic Android conversion from HTML for most things and it seems to ignore this thing.

**Comment by Aldarone** [comment]
I found this : https://stackoverflow.com/a/29114976

I thinking about adding a private method in `StatusBaseViewHolder` to do the formatting before setting the call to `setSpoilerAndContent`, is this the right way to do it ?

**Comment by connyduck** [comment]
Stackoverflow post looks interesting! No this should not be in `StatusBaseViewHolder`. We do a lot of span manipulating in `LinkHelper`, but I think the best place would be to do it where the HTML is actually parsed so its not called that often. Maybe `SpannedTypeAdapter` or `HtmlUtils`.
