### ISSUE TITLE
Support displaying polls with more than 4 options

### ISSUE THREAD

**Issue by rinpatch** [tuskyapp/Tusky#1272]
Some federated software like Misskey (who originally implemented polls) and soon Pleroma allow for more than 4 options in polls, however when trying to preview a post with more than 4 options in Tusky it just shows the first 4 of them. 

Mastodon does not reject/trim options on the backend and properly displays more than 4 of them in the frontend so it would be nice if Tusky displayed them all too.

* * * *
- Tusky Version: 7.0
- Android Version: N/A
- Android Device: N/A
- Mastodon instance (if applicable): N/A

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
This is a problem for Emoji Tetra! [Thread](https://vulpine.club/@EmojiTetra/102141857662051680).

**Comment by Cassolotl** [comment]
Thank you! :)
