### ISSUE TITLE
Issue with user who have no displayName at list editing

### ISSUE THREAD

**Issue by kyori19** [tuskyapp/Tusky#1280]
![](https://media.odakyu.app/media_attachments/files/000/756/214/original/2173c7ee725e3a4d.png)

Related to #1104, cc: @charlag 
Users who don't have displayName shown as if they don't have any name.
https://github.com/tuskyapp/Tusky/blob/520e0d6e7a9d478eff09f3afc32d7bffdacef752/app/src/main/java/com/keylesspalace/tusky/AccountsInListFragment.kt#L210
We should use `account.name` instead of `displayName` here.

* * * *
- Tusky Version: master 419ae80
- Android Version: 8.0.0
- Android Device: G8441
- Mastodon instance (if applicable): all

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
`account.name`? There's `acct`, `username` and `display_name`.
https://docs.joinmastodon.org/api/entities/#account
AFAIK `username` is just domain-less of `acct` for Mastodon at least. So there's not much new info there. We could use it ofc to be consistent but maybe some people really like having nothing there?

**Comment by kyori19** [comment]
@charlag 
No, `account.name` is defined in `Account.kt`.
https://github.com/tuskyapp/Tusky/blob/9311ffa391f2ab61d5f5c0476f6fd3d7d085e079/app/src/main/java/com/keylesspalace/tusky/entity/Account.kt#L51-L54
When `display_name` is not defined, `account.name` returns `username` (domain-less `acct`) instead of `display_name`.
And Mastodon shows `username` as display name for user who don't have `display_name`.
(See https://odakyu.app/@ar0_yk )
Also, empty textarea looks unbalanced.
So I think we should follow this rule.

**Comment by charlag** [comment]
Ah, sorry, my bad. Yup, we should follow it then I think.
