### ISSUE TITLE
[Feature Request] HTTP/2 or WebSocket support

### ISSUE THREAD

**Issue by aka-rin** [tuskyapp/Tusky#1293]
I'm so thrilled to see the Streaming API PR (#1289), but it would be better if WebSocket or HTTP/2 have a higher priority. 

A few weeks ago I tried to write a bot with Streaming API and it turns out that some instances do not support Streaming API with HTTP/1.1. I don't know the exact reason of it (maybe due to  Docker or NodeJS misconfigurations). 

Another reason is keeping a HTTP/1.1 connection may increase the possibility of interruption in some countries. Using HTTP/2 or WebSocket will improve the robustness of connection. 

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (Similar to #84 ?)

**Comment by charlag** [comment]
Hey
There are problems with HTTP/2 as well so it's not a silver bullet IMO.
I dot rememebr us picking specific HTTP version anywhwere.
Websocket takes lover to converge and needs more resources, also we would need an additional library for that

**Comment by aka-rin** [comment]
Thanks for your reply. I check the documentation and it seems that okhttp use HTTP/2 by default：

> https://square.github.io/okhttp/

So if the Streaming PR works, there's no need to use WebSocket and this issue can be closed. 😅

**Comment by charlag** [comment]
Great, thanks for checking it!
