### ISSUE TITLE
Images don't download

### ISSUE THREAD

**Issue by juacq97** [tuskyapp/Tusky#1304]
When I click the download button, a toast appears saying that the download start, but most of the time, the image doesn't download, I check the tusky folder and there's nothing there. Sometimes, the images download, but several minutes after I clicked the button.

* * * *
- Tusky Version: 7.1
- Android Version: 7.1.1
- Android Device: Samsung core 2

- [x] I searched or browsed the repo’s other to ensure this is not a duplicate.

**Comment by uranther** [comment]
I was having this issue as well. Other apps have the same issue, but not every app. After connecting to VPN, the Android Download Manager will start those downloads that were only queued before. This makes me think this subsystem depends on phoning home to Google, which is blocked in the area I am in currently.

Surely, Tusky media downloads work on LineageOS or other de-Googlified Androids but they have probably patched Download Manager.

**Comment by charlag** [comment]
I think that's not something about us but about DownloadManager in your ROM

**Comment by juacq97** [comment]
I tested with other apps, and the Download Manager doesn't works on some apps as @uranther said.
