### ISSUE TITLE
Setting to allow the disabling of the Clear|Filter buttons from the notification column

### ISSUE THREAD

**Issue by BNolet** [tuskyapp/Tusky#1306]
Issue raised by [Maddie|@MadestMadness@meow.social](https://meow.social/@MadestMadness)

Currently the two buttons are persistent until you scroll down, limiting the already scarce screen real-estate. I'd like to be able to disable this and possibly also disable it for a set period of time. Disabling at all is the most important. 

* * * *
- Tusky Version: 7.0
- Android Version: 8.0.1
- Android Device: Moto Z^2 Play
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
fyi in Tusky 8 the buttons will be smaller

**Comment by BNolet** [comment]
That's fantastic, but could it be possible to be able to turn them off completely?

**Comment by connyduck** [comment]
yes of course

**Comment by connyduck** [comment]
#1314
