### ISSUE TITLE
URLs are not opened inside the app

### ISSUE THREAD

**Issue by dansroot** [tuskyapp/Tusky#1307]
Although in the app settings, section "Browser", the switch for "open links inside the app" is activated (pulled right, blue), all URLs (external links) in toots are being opened in the device's default (external) browser. I would expect to open the link inside the app.

* * * *
- Tusky Version: 7.1
- Android Version: 8.0
- Android Device: Huawei P10 Lite
- Mastodon instance (if applicable): mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes, the option does not really open links inside the app, but uses a feature called "Custom Tabs" that some browsers offer. If no such browser is found, it just opens the link normally.

May I ask what language you use Tusky in, because in English the setting is called "Use Chrome Custom Tabs"?

**Comment by dansroot** [comment]
I use the German localization and there it only states to "open links in the app". I talked to a Dev on Mastodon yesterday and suggested to improve the description of this function in the app.

–---------------------------
 Sent with FairEmail
 Open Source for Android
 –---------------------------


Thu Jun 06 20:55:49 GMT+02:00 2019 Konrad Pozniak <notifications@github.com>:

**Comment by connyduck** [comment]
Was wäre eine bessere Beschreibung? "Links in Chrome Custom Tabs öffnen"?

**Comment by dansroot** [comment]
Ja, zum Beispiel. Das funktioniert übrigens auch mit Firefox (nur nicht mit WebView basierten Browsern). Daher vielleicht: "Links in der App (Browser Custom Tabs) öffnen".

–---------------------------
 Sent with FairEmail
 Open Source for Android
 –---------------------------


Mon Jun 10 21:05:41 GMT+02:00 2019 Konrad Pozniak <notifications@github.com>:

**Comment by connyduck** [comment]
👍 
https://github.com/tuskyapp/Tusky/commit/c10f3bce24912645daad2762424e45c4ff04357c
