### ISSUE TITLE
[ Enhancement ]  Adaptive poll recurence

### ISSUE THREAD

**Issue by myself12345** [tuskyapp/Tusky#1318]
I understood you don't want push notification, but it would be great to have a pull recurrence of 1 minute instead of 15 for direct conversation :
1. start with 15 minute pull recurrence
2. if direct message received/sent, set recurrence = 1 minute for 5 minutes
- After 5 minutes without direct message, reset recurrence to 15 minutes
Thank you for your app.

**Comment by connyduck** [comment]
Yes I know that would be awesome. But unfortunately we are constrained by Android which lets us schedule recurring tasks at most every 15 minutes for battery saving reasons.
