### ISSUE TITLE
Add option to disable notification LED

### ISSUE THREAD

**Issue by AaronM04** [tuskyapp/Tusky#1321]
It would be nice to disable the notification LED. If I'm trying to focus on something and my phone is in my field of view, it's very distracting seeing that LED.

* * * *
- Tusky Version: 7.1
- Android Version: 7.1.2 (LineageOS 14.1)
- Android Device: Oneplus 3T
- Mastodon instance (if applicable):

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Tusky is not controlling the notification settings, Android is. If you can't change the settings its a problem with LineageOS and not with Tusky. Here is how it looks on my Pixel 2, I can disable the notification LED.

![Screenshot_20190903-184257](https://user-images.githubusercontent.com/10157047/64192342-c81a2780-ce7a-11e9-808b-90503bb365c3.png)
