### ISSUE TITLE
Use max_bio_chars API endpoint

### ISSUE THREAD

**Issue by clarfon** [tuskyapp/Tusky#1329]
glitch-soc and co have been offering a `max_toot_chars` value via `/api/v1/instance`, and florence-masto has started offering the `max_bio_chars` value there too. Although it seems that this API won't be final, it makes sense to have code in Tusky that uses this value here so that there's at least some code that handles bio length limits on a per-instance basis. I imagine that once this is in place, it'll be easier to update if the API moves to a different location.

**Comment by connyduck** [comment]
Do you know any server wherer I can try this out?

**Comment by clarfon** [comment]
I know that bobadon.co.uk is running this version so maybe @TrechNex can help you out? This is assuming he's running it with the fix for the API installed.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/commit/ce01e6de22422fea40188a9f837b5b21cab109ac

**Comment by TrechNex** [comment]
bobadon.co.uk runs whatever the latest tagged release is (0.1.2 when I last checked).
