### ISSUE TITLE
Implement new attachment type audio

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#1334]
In the next release mastodon will add audio attachment support. https://github.com/tootsuite/mastodon/pull/11123

Note that it is not yet decided which format the audio will have, see https://github.com/tootsuite/mastodon/issues/11131

**Comment by koyuawsmbrtn** [comment]
Suggestion: Allowing attachments to be audio files **and** being able to record voice notes to send them around

**Comment by connyduck** [comment]
-> https://github.com/tuskyapp/Tusky/issues/1337

**Comment by novadeviator** [comment]
audio support is now enabled in mastodon. it's mp3 format. this issue is not clear in terms of what is supposed to be implemented - playing or/and uploading audio. #1337 is for uploading, but playback of audio does not work in Tusky currently if i'm not mistaken.

**Comment by connyduck** [comment]
This issue is about displaying the attachments correctly in timelines & playing audio.
