### ISSUE TITLE
[Feature Request] translation feature 

### ISSUE THREAD

**Issue by ebrulato** [tuskyapp/Tusky#134]
A button to translate a message in the user's language

**Comment by alerque** [comment]
Personally I find the built in "translate this" on social networks to be less useful than it should be. Even the big name folks like Twitter and Facebook don't use the best engines for each possible language. I find an external app often works better, but to make that a meaningful experience it can't be more that a tap away. For programs that have tap-to-copy features this can be combined with Google Translate's clipboard monitoring and auto translation. This brings a translation in 2 or 3 taps depending on the app. Other apps that can read content in on shares would be 4-5 taps away if #147 were to be fixed.

That's not to say I'd be apposed to an internal translator that used some API and did it in place, but it should be optional and the UI should support getting the text out to external apps as well.

**Comment by ebrulato** [comment]
I agree with you @alerque and the purpose is just to add a button to get a translation :)

**Comment by nailyk-fr** [comment]
Useless comment to subscribe. 
FI some projects use [weblate](https://weblate.org/en/). Fully open source.

**Comment by shoukolate** [comment]
Add an option in settings to auto translate all toots or an option to translate individual toots. You can use google translate API (free for unlimited use AFAIK) from google translate extension from chrome browser (someone posted it on stackoverflow)

API: https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&q=こんにちは

You can replace "auto" if with source language if you want to disable auto detection and "en" for choosing a target language. Replace "こんにちは" with text you want to translate.

JSON response:

`[[["Hello","こんにちは",null,null,1]
]
,null,"ja",null,null,null,1.0,[]
,[["ja"]
,null,[1.0]
,["ja"]
]
]
`

**Comment by suoko** [comment]
Now mastodon has added translation as a feature

**Comment by ShellWen** [comment]
I need it😭

**Comment by ozkanpakdil** [comment]
I manage to translate the text in the post but could not find a way to replace the text in the post but open a new dialog to show the translation, you can see it here [video](https://photos.app.goo.gl/TjSd3WHU3eG5sGYS8)

https://user-images.githubusercontent.com/604405/209661508-f699df43-4bb2-4976-9aaf-8f5a82b14308.mp4

**Comment by s0mt0chukwu** [comment]
This needs to be addressed in the next update

**Comment by alerque** [comment]
Another aspect of this to consider is a) choice and b) API availability. There are totally free and even open source options out there, but their quality varies for some language. Of the better free but not open translation platforms, some are better than others for certain language pairs. Lastly there are paid options that for *some* languages are even better.

For example right now DeepL is one of the best machine translation APIs out there, but it is not free except in small trial doses. This limitation would make it impractical for use by Tusky with their own API key, but if users could supply their own keys it could be awesome.

My suggestion is implement things in a generic enough way to allow the user to setup the app with preferences for which translation engine to use, and even to customize the options. Then they can choose a free platform based on preference / suitability for their commonly used language pairs, and if they select a non-free platform they can input their own API key.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/4307

**Comment by ozkanpakdil** [comment]
@connyduck how can I enable this feature in my tusky app ? on mobile ? I am not admin on the server side.

**Comment by timnolte** [comment]
@ozkanpakdil I'm pretty certain that this is completely reliant on the server supporting translations. So if you don't have the ability to translate when using the web UI for your instance then you won't have the ability to translate in the app.

**Comment by timnolte** [comment]
@ozkanpakdil so yeah, I just looked at the code changes that implemented this and it does in fact require your instance to support translations, this isn't an app/user-only supported feature.

**Comment by ozkanpakdil** [comment]
@timnolte meaning this issue still standing, and issue is closed ?

I and @Joshix-1 actually done a nice client side stranslation without hurting anyone, can you put it somewhere in the settings to have client side translation ? I know it is not the best solution but after all it will be closed until user is openning it ?

https://github.com/tuskyapp/Tusky/pull/3228

**Comment by timnolte** [comment]
@ozkanpakdil well this issue specifically doesn't really request an app-only translation option, so technically this is resolved by instance translation support.

**Comment by timnolte** [comment]
@ozkanpakdil so #3228 looks to me about using the Mastodon API and this is reliant on the instance supporting translations.

**Comment by ozkanpakdil** [comment]
About #3228 I dont know the details just saw the video and thought it was doing client side anyway you can check https://github.com/tuskyapp/Tusky/pull/3107 I know I can carry out my code and merge it to forever :) but I just want a small option in the app to do the translate
