### ISSUE TITLE
Support the moderation API

### ISSUE THREAD

**Issue by N07070** [tuskyapp/Tusky#1341]
Version 2.9.1 of Mastodon now has a moderation API. 

It would be nice to have the possibility to ban users, resolve reports and so on from Tusky. 

From the casual report, to a easy way to respond rapidly to a urgent situation, having a on-the-go way to act is important for many small instances that don't have multiples mods and/or admins. 

I don't have much time to implement this in code, but I can beta-test it, and I will be following this issue and it's discussion. 
* * * *
- Tusky Version: 🔜 
- Android Version: 🤖 
- Android Device: 🤖 
- Mastodon instance (if applicable): 🐘 

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by N07070** [comment]
The API is describes here : https://mastodonpy.readthedocs.io/en/latest/#moderation-api

**Comment by ella-kane** [comment]
Yes, please!

As a mod of several instances and also a disabled person I'd love to have this feature in Tusky. I lost count of the times I had to make the really *spoony* effort of getting into a desk just to moderate things that require those tools we only have on web right now.

Thank you in advance,
Ella_Kane

**Comment by GibsonGibson** [comment]
This is more important than ever in the coming months.

**Comment by isharacomix** [comment]
If this is implemented, please implement something like a revocable sudo mode, as I would prefer not to have a perpetually authenticated client on my phone with the admin scopes enabled.

**Comment by mal0ki** [comment]
After discussing it with Conny we reached this conclusion: 

We would spread ourselves too thin if we wanted to make this a part of Tusky, that said, we are however going to make a CTA seeing if there's any app developers out there who'd like to who'd like to create an app completely focused for Moderation in the fediverse. Starting with Mastodon (and whichever else have the API open for it thus far). 

Hopefully we can get some takers on it, and we'll happily support them in the work with what we can. 

Thing from our side we can help with: 
- Allow Tusky to offer additional functionality, like opening the moderation app from a users profile.

**Comment by connyduck** [comment]
Imho the best solution for this would be an additional app, lets call it Tusky Moderation Companion.
Users that need moderation functionality can install TMC, while others that don't can save the space on their phones. TMC would offer the moderation interface and can be used alone, but when installed alongside Tusky it tightly integrates and in both apps additional options to switch seemlessy between the apps would appear.
As maloki wrote, I just do not see capacity for that in our team right now, so I would be really glad if somebody could take that over.

**Comment by N07070** [comment]
Indeed, it would be better to have another app to deal with moderation. Now the main question is : who's can do it ?

**Comment by polymerwitch** [comment]
I commented on the thread on the fediverse that I would be interested in helping (i'm polymerwitch). I don't want to over commit myself, but i'm willing to help out and do at least a chunk of the work.

**Comment by connyduck** [comment]
So we have a new repository for the moderation app, thx @mal0ki for setting it up -> https://github.com/tuskyapp/Mod-companion/issues

I created the first issues so we can get the discussion on how to best implement this going.

**Comment by charlag** [comment]
Closing this because there's a separate repo https://github.com/tuskyapp/Mod-companion
