### ISSUE TITLE
'Parse error' when installing app

### ISSUE THREAD

**Issue by dzach** [tuskyapp/Tusky#1342]
Hi
I downloaded apk v7.1 from https://tusky.app/.
When trying to install the app to many android devices, I get a dialog saying:

> Parse error:
> -----------------------------
> There was a problem parsing this package
> -----------------------------
> Ok
> 

The same happens when trying to install older apks dowloaded from F-Droid. I have no problem installing other apps on these devices.

Any suggestion on how to proceed?
Thanks!
* * * *
- Tusky Version: 7.1
- Android Version: 4.4.2
- Android Devices:
  Phone Turbo-X_epsilon (CPU: Quallcomm MSM8212), 
  tablet Orro A990,
  tablet RainbowII 3G

- [*] I searched and browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Tusky does not support Android 4 anymore, sorry.

**Comment by dzach** [comment]
Is there any link to an old apk I can download to try Tusky on these devices?

**Comment by connyduck** [comment]
Tusky 3.1 is the newest version that still supports Android 4. There is an apk attached on the release page https://github.com/tuskyapp/Tusky/releases/tag/v3.1

**Comment by dzach** [comment]
Thanks!
