### ISSUE TITLE
American English translation

### ISSUE THREAD

**Issue by toastal** [tuskyapp/Tusky#1346]
I'd like to see an American English translation support -- as the word 'favourite' irrationally grinds my gears. Can I contribute this? It seems the translation system is homebrewed? Can it support this kind of localization to en_US when it seems there's just language codes and not region codes?

* * * *
- Tusky Version: 7.1
- Android Version: 9
- Android Device: OnePlus 5
- Mastodon instance (if applicable): cybre.space

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by akarshanbiswas** [comment]
Here: https://weblate.tusky.app/

**Comment by toastal** [comment]
@akarshanbiswas I can't create a new language though to translate to.
