### ISSUE TITLE
Filters do not work when looking at profiles or conversations

### ISSUE THREAD

**Issue by aCuteLittleBox** [tuskyapp/Tusky#1349]
when viewing a conversation/thread, or while viewing someone's profile and looking through their posts, Tusky does not apply any filters. This is a dangerous oversight for those who rely on filters for their own safety and it is important it is correctly quickly

* * * *
- Tusky Version: 7.1
- Android Version: LineageOS 15.1 (Android 8.1)
- Android Device: Samsung Galaxy S7
- Mastodon instance (if applicable):

- [✅]I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
🤔 indeed, thx for noticing
We are implementing the Mastodon filter Api, and it specifies 4 values for a filter context `home`, `notifications`, `public`, `thread`. So if Tusky is not filtering on threads thats our mistake, profiles on the other hand seem to be not meant to be filtered by the Mastodon api.

**Comment by connyduck** [comment]
OK we are now filtering correctly in threads. For the filtering in profiles we need a change in the Mastodon api.
