### ISSUE TITLE
Excessive amount of profiles in search results on Pleroma instances

### ISSUE THREAD

**Issue by dansup** [tuskyapp/Tusky#1350]
A recent update in pleroma has affected search results on Tusky for pleroma instances. When I search "pixelfed" on pleroma.site, it lists hundreds of profile accounts, requiring a lot of scrolling to get to the status results.

* * * *
- Tusky Version: 7.1
- Android Version: 9
- Android Device: Samsung S8
- Mastodon instance (if applicable): pleroma.site (pleroma instance)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I was not aware of that, thx. But we are already working on a feature to show the different search result in tabs, that should fix the problem. See https://github.com/tuskyapp/Tusky/pull/1327
