### ISSUE TITLE
[Discussion] officially support more networks than just Mastodon

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#1353]
Tusky currently works with Mastodon, Pleroma and glitchsoc, hopefully soon with Pixelfed (once they implement the api) and with Florence once they launch.
Officially we only support Mastodon though.

So I propose that we extend the official support to Pleroma as well.
This would mean
- me developing/testing more against Pleroma
- changing app descriptions everywhere
- adapting some in-app wording

I would like some thoughts about this and whether glitchsoc/Florence should be treated as a different server software or just Mastodon flavours.

**Comment by igalic** [comment]
what about Pixelfed?

**Comment by noiob** [comment]
Glitchsoc still uses Mastodon branding so I'd argue it should be treated like every modified Mastodon (monsterpit, cybre and sleepingtown don't get special treatment either, do they?). Furthermore I don't think Tusky supports any glitch-soc specific features, and saying "Tusky works with Mastodon, Pleroma, […], Glitch-soc" would suggest that to me.

**Comment by skrlet13** [comment]
Is it possible to add Friendica support? Thank you

**Comment by subpub** [comment]
Consider Misskey too

**Comment by connyduck** [comment]
Miskey and Friendica have a different api, we can't support them.

**Comment by skrlet13** [comment]
> 
> 
> Miskey and Friendica have a different api, we can't support them.

I understand, thanks for answering

**Comment by ThatOneCalculator** [comment]
@connyduck given it's now 3 years later and the popularity of Misskey (and the Fediverse in general) has grown a lot, I feel this should be revisited. 

The auth flow and endpoints for Misskey, while named differently, work almost the same as Mastodon, and as there's no really good client for Misskey on Android (sorry Milktea), I feel adding Misskey support would be beneficial to the larger Fediverse community.

**Comment by connyduck** [comment]
@ThatOneCalculator Misskey has a completely different api that is way out of scope to implement at this point.

**Comment by ThatOneCalculator** [comment]
I'm working on a cross-instance-software project right now, and they're more similar that initially lets on.

**Comment by connyduck** [comment]
Thats possible, but we are already struggling to properly support Mastodon, so no.
