### ISSUE TITLE
associate metadata with user

### ISSUE THREAD

**Issue by SoniEx2** [tuskyapp/Tusky#1355]
it's hard for me to remember ppl's boundaries (or really anything), so I'd like some sort of "notes" feature that lets me attach my own metadata to other users.

not having anxiety over whether or not I should hug someone when they give me an ambiguous reply when I offer them hugs would be nice. I don't wanna accidentally hug someone who doesn't wanna be hugged, and I don't wanna leave someone expecting a hug and never give them a hug.

I just want something that shows on their profile, perhaps immediately below their bio or something.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Support for profile notes (Mastodon feature) is available since Tusky 13.
