### ISSUE TITLE
Tusky shows html rich text in poll options

### ISSUE THREAD

**Issue by kyori19** [tuskyapp/Tusky#1362]
Mastodon WebUI [https://odakyu.app/@ars42525/102376895437413871](https://odakyu.app/@ars42525/102376895437413871) 
![Screenshot_20190703-185117](https://user-images.githubusercontent.com/27999567/60582601-1ac85c00-9dc4-11e9-835a-6f16d98ec54a.png)

Tusky
![Screenshot_20190703-185106](https://user-images.githubusercontent.com/27999567/60582709-4c412780-9dc4-11e9-9ec0-4aad6b124b56.png)

HTML tags should be escaped before showing it

* * * *
- Tusky Version: 8.0 dc76a82f 
- Android Version: 8.0.0
- Android Device: G8441
- Mastodon instance (if applicable): odakyu.app

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Just tested this, can confirm. 
On mastodon.at where I created the poll it is shown with styling while the same poll when viewed with Tusky from my other account chaos.social shows the escaped html. So seems something happened there while federating? 
Should be an easy fix on our side though.

**Comment by connyduck** [comment]
Ah, nope, not a problem with federating, the bug only occurs when we show the result of a poll.

The code in question is here: https://github.com/tuskyapp/Tusky/blob/master/app/src/main/java/com/keylesspalace/tusky/adapter/PollAdapter.kt#L77
We would need a way to show the % value in bold, but not parse the whole line as HTML like we are currently doing.

**Comment by SoniEx2** [comment]
maybe escape option.title (`HtmlUtils.toHtml` it) on the previous line? would that fix it?
