### ISSUE TITLE
Bot indicator showing in "Toot" view

### ISSUE THREAD

**Issue by mystfox** [tuskyapp/Tusky#1364]
I have the "Show indicator for bots" setting toggled off, which used to remove it everywhere, but it's started showing up when I look at the details of a message/thread. It doesn't look to be accidentally labeling the wrong people or anything like that, just showing up in this view when I don't want it ever and have the setting off.

![Screenshot_20190703-134751](https://user-images.githubusercontent.com/2127318/60620790-5ac61980-9d99-11e9-8e19-cd7029f16fc6.png)
![Screenshot_20190703-134740](https://user-images.githubusercontent.com/2127318/60620800-631e5480-9d99-11e9-8185-63061d7d10ed.png)

* * * *
- Tusky Version: 8.0
- Android Version: 9
- Android Device: Google Pixel 3
- Mastodon instance (if applicable): vulpine.club (not sure it's relevant)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Thanks, I'll look at this one
