### ISSUE TITLE
Non-bold text on reblogs' number

### ISSUE THREAD

**Issue by JuanjoSalvador** [tuskyapp/Tusky#1366]
Actually I think it's a translation issue, I found it on the spanish strings' file, but maybe other languages could be affected.

Normal text on Impulsos (aka Reblogs/Boosts), bold text on Favoritos (Favourites/Likes). I'm going to fix this by changing my own `strings.xml` and it will be fixed on Weblate before weekend.

![photo_2019-07-04_15-41-18](https://user-images.githubusercontent.com/5058655/60671577-a947e680-9e73-11e9-83d4-5d22f12cdc0d.jpg)

* * * *
- Tusky Version: 8.0
- Android Version: MIUI Global 10.2 (Android 7.1.2)
- Android Device: Xiaomi Redmi 4A
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JuanjoSalvador** [comment]
Actually it seems fixed on Weblate.

**Comment by connyduck** [comment]
The strings were wrong in several languages, a problem with Weblate maybe?

fixed in https://github.com/tuskyapp/Tusky/commit/d631305e208634431b2b5637520d639cf5772cd2

**Comment by JuanjoSalvador** [comment]
Not really, Weblate suggest to use `<b>` as an XML tag, and that makes Android going crazy. So, the solution is using the escape tags `&ltb&gt` and &lt/b&gt`.
