### ISSUE TITLE
Theme autoswitch doesn't work with main timelines

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#1370]
If Tusky is alive when the "automatic at sunset" time comes, the timelines don't switch theme (although other activities do, so the app switches between light and dark as the user navigates between different activities).

* * * *
- Tusky Version: Nightly/`master`
- Android Version: 9
- Android Device: Pixel 2 XL
- Mastodon instance (if applicable):

- :ballot_box_with_check: I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I think this was fixed by https://github.com/tuskyapp/Tusky/pull/1455
