### ISSUE TITLE
Hide blocked instances

### ISSUE THREAD

**Issue by SoniEx2** [tuskyapp/Tusky#1383]
If an instance (not an user) blocks you, you can still see posts from that instance. To detect if such an instance has blocked you, you can simply follow the steps:

1. send a follow request to an open account
2. re-check if you're following the account

if it says "pending request" or anything like that then the instance should be hidden. otherwise just send an unfollow request.

ideally this would be done by mastodon federating the instance-wide blocks, but it currently doesn't. so just implement it with a small hack.

I'd use tusky on desktop (android emulator) if it had this feature.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Dataanti** [comment]
I really miss the old pro freespeech, pro freedom, anti war, anti big tech/corporation, tree loving hippy left wing. this wall that is being erected in the fediverse is full of bad vibes and negativity. im ashamed to see it coming from the side i thought i identified most with :( It is a sad time, but a changing time. i think im gonna move out to the freeverse (the other side of this silly digital wall) to be free and keep spreading the message of live and let live.

and before anyone calls me what ever insult of the day it is, just know that you are pushing people like me away. like im all for a star trek style future, UBI, pro choice, 420 friendly and eco friendly future. but free speech is an essential tool to speak truth to power and make that future a reality. and you wont be able to change the mind of those you disagree with if you try and wall them off and not talk to them. this sort of behaviour will never get us to the the future we all dream of :/ i wish you guys could see this. it is kind of ironic, considering censorship was a tactic actually heavily used by the nazis in WW2

so long fediverse, hello gab and the freeverse

**Comment by SoniEx2** [comment]
what does that have anything to do with the vulpine.club admins blocking me? the fuck.

go the fuck away. nobody wants you here.

**Comment by Dataanti** [comment]
> what does that have anything to do with the vulpine.club admins blocking me? the fuck.
> 
> go the fuck away. nobody wants you here.

i dunno man, im pretty stoned atm. i re read it and i dunno, i just got carried away with the blocky words since it is kind of controversial in the fediverse atm

XD its just a stoned post, dont worry about it :P

**Comment by charlag** [comment]
There's no reliable way to detect that and that's by design. You propose sending a follow request to everyone? What if it succeeds? This doesn't make too much sense to me tbh.

**Comment by SoniEx2** [comment]
if it succeeds, you undo it.

it's quite reliable. so reliable in fact that I'd say it's 100% accurate.

if making users suicidal is by design then I don't want that design. user blocks are federated, why not remote user suspends? it's really no different from federating an user block, unlike a remote instance suspend.

**Comment by charlag** [comment]
And if we fail to undo it? Also the person will receive the notification that you followed them. So we will sent info to someone's server each time we open their profile?

It's not very nice to be blocked and not know about that. I experienced it. Unfortunately when harassers know that they're blocked, it's stirring them up.

I'm sorry, but it it a huge hack and it has many downsides while also empowering harassers so i am persnally against it.

I only deleted your comment, apparently someone else deleted other comments. I'm not sure how it works.

**Comment by SoniEx2** [comment]
having to ask my friends to move instances because I'm blocked on their instance is worse than knowing I'm blocked on those instances.

also, that still doesn't answer, why do we allow blocks to hide posts if we don't allow suspends to hide posts?

**Comment by SoniEx2** [comment]
not hiding them means abusers still see them and are free to comment on them and so on.

those comments etc get shared to other instances. it enables dogpiling and harassment.

not hiding them gives assholes the ability to attack others.

don't talk to me until this feature is implemented.

**Comment by connyduck** [comment]
No. This problem needs to be solved serverside.
