### ISSUE TITLE
Work with federation software developers to provide in-app instance blocks that can't be bypassed server-side

### ISSUE THREAD

**Issue by SoniEx2** [tuskyapp/Tusky#1385]
Basic idea: put something in .well-known that if poked with the current instance's domain, returns 200 for blocked or 4xx/timeout for unblocked.

This provides backwards compatibility and allows Tusky to fully hide toots from instances that don't want to let you see them, providing extra safety to the ppl on those instances.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This would degrade perf for all users while being easily bypassable by malicious ones (they can just use a client that does not implement this check).

**Comment by SoniEx2** [comment]
the response body (as a whole) should be a TTL, in seconds. if it doesn't exist, it should default to 300 (5 minutes). this keeps the performance pretty good.

it doesn't matter if it is easily bypassable. that's beside the point.
