### ISSUE TITLE
Rename "show more" and "show less" to "consent" and "unconsent" respectively

### ISSUE THREAD

**Issue by SoniEx2** [tuskyapp/Tusky#1395]
The buttons "show more" and "show less" should be "consent" and "unconsent" respectively. Additionally, CWs should be referred to as "consent warnings". This should lead to ppl using them more.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JuanjoSalvador** [comment]
I'm going to ask... Why? Also, CW stands for Content Warning, not consent. Give us more details about your request, please.

**Comment by SoniEx2** [comment]
Consent Warning is a more useful term, because CWs are a consent mechanism. By calling them consent warnings you're telling your users "this is a consent mechanism", whereas by calling them content warnings you're telling your users "this is a censorship mechanism" - which it is not. CWs were created as a consent mechanism. just ask the ppl who originally implemented and asked for them. but half the fediverse refuses to see them that way and nobody is willing to explain to them that, no, consent warnings are a consent mechanism.

the best way to protect vulnerable ppl is to call them consent warnings. keep in mind you can retract consent at any time (case in point: "unconsent" button).

**Comment by connyduck** [comment]
No, we will keep the same names as Mastodon and Pleroma for the buttons to not confuse anybody.
