### ISSUE TITLE
Crash when displaying notification from a user who has been deleted from instance.

### ISSUE THREAD

**Issue by noln** [tuskyapp/Tusky#1398]
1. Have two accounts on different instances.
2. One user was deleted from the instance by admin.
3. The other user, who was in conversation with the deleted user, on a different instance (pleroma.site) crashes on login in Tusky.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6524043/61386397-37fc3080-a882-11e9-87af-cde338627030.gif)

* * * *
- Tusky Version: 8.1
- Android Version: 9
- Android Device: Pixel 2 XL, Pixel 3 XL
- ~~Mastodon~~ Pleroma instance: networked.space (user deleted from), pleroma.site (user still exists, crashes on login when trying to display notification from the former)

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by noln** [comment]
Problem is [here](https://github.com/tuskyapp/Tusky/blob/707f3e605c0af717d7a510588ffbecbef2307159/app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java#L155).

The string being passed to `CustomEmojiHelper.emojifyString(..)` is null, the method annotates that as `@NonNull`.

**Comment by connyduck** [comment]
Looks like a bug in Pleroma, have you reported it to them as well?

**Comment by noln** [comment]
Drafting the issue now with some sample responses.

**Comment by noln** [comment]
Having spoken to the Pleroma team, have confirmed it's a server-side issue.

Raised here: https://git.pleroma.social/pleroma/pleroma/issues/1104

Closing, as it's not a bug in Tusky.

**Comment by connyduck** [comment]
Thx very much!
