### ISSUE TITLE
[Feature Request] sending a toot in background and the ability to resend it if a technical error is raised

### ISSUE THREAD

**Issue by ebrulato** [tuskyapp/Tusky#140]
<< when the user send a toot, the application do it in background. If a technical error is raised, the user can try to resent it later. An option may allow the application to try to resent it regularly 3 or 10 times >>

This feature may be checked with the mastodon api (I don't know it)

**Comment by raphaelm** [comment]
Might be useful to tackle together with #142

**Comment by ebrulato** [comment]
yes @raphaelm these request are very close

**Comment by connyduck** [comment]
This will be in Tusky 1.6
