### ISSUE TITLE
[Feature request] Notifications customisation

### ISSUE THREAD

**Issue by fufik** [tuskyapp/Tusky#1401]
I'd be glad to see in Tusky an ability to customise notifications depending on what they notify about, for example: change their leds, sounds, ibration — all individually.
As well as the aforementioned ability to customise the LED colour.

**Comment by connyduck** [comment]
Tusky provides 5 channels for each logged-in account, you can change most of these things individually for each channel. We cannot add more options since they are managed by Android and not by Tusky.
