### ISSUE TITLE
Talkback not working with content warnings

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#1427]
According to a user, it is not possible to interact with content warnings and they are never read even when manually expanding them.

* * * *
- Tusky Version: 8.1

**Comment by charlag** [comment]
I will check that but it was definitely working (through accessibility actions).


30 Jul 2019, 23:37 by notifications@github.com:

**Comment by charlag** [comment]
I checked Nightly on my phone and indeed narrator reads out:

[display name]
Content Warning:
[content warning]

And it is possible to expand them with actions (up & right gesture, actions, show more).
Should work the same for notifications I think?

So we need more info

**Comment by connyduck** [comment]
Thx for checking! User just did not know it works this way.
