### ISSUE TITLE
FreeTusky app in F-Droid

### ISSUE THREAD

**Issue by Nutomic** [tuskyapp/Tusky#1446]
Since a few weeks, F-Droid is providing an app called "Free Tusky", which is a fork of Tusky with the sole purpose of removing the Gab block that Tusky implemented. This is very problematic, especially because the name "Free Tusky" implies that the app is somehow better (more free) than the original Tusky. A lot of people who dont know better will install the app just for that reason.

We can use this issue to discuss what to do about this problem. Here are some ideas:

- Tusky maintainers can contact F-Droid maintainers, and tell them that they are not okay with this
- ask mastodon, pleroma etc devs to block the Free Tusky client, and direct users to Tusky instead
- report Free Tusky to Github, if we can find that they violated some rule
- register a trademark on the Tusky name, to make sure forks have to change their name

**Comment by JuanjoSalvador** [comment]
The idea of register a trademark could be useful. Reporting Free Tusky on Github, maybe not, because license. 

Trademark and contact to F-Droid maintainers seems the better options. Should this be on the Tusky Matrix channel?

**Comment by charlag** [comment]
No one seems to be willing to spend time on this instead of developing Tusky, sorry. Feel free to report etc.
