### ISSUE TITLE
Duplicate toots on home timeline

### ISSUE THREAD

**Issue by FoxAstronaut** [tuskyapp/Tusky#1451]
Occasionally toots will be duplicated on the follow timeline. These are the exact same toots including favourited state. I've had this happen a couple times recently.

Sorry that I don't have any more info

![Screenshot_20190814-101630](https://user-images.githubusercontent.com/14159938/63009767-02e0ff00-be7d-11e9-8aac-c7a4222d3255.png)
![Screenshot_20190814-101638](https://user-images.githubusercontent.com/14159938/63009777-083e4980-be7d-11e9-8add-2ec5f3c635fe.png)

* * * *
- Tusky Version: 8.1
- Android Version: 9
- Android Device: Google Pixel 3a XL
- Mastodon instance (if applicable): notbird.site

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
@FoxAstronaut is it still relevant? Maybe we fixed it already
