### ISSUE TITLE
Poll text and options aren't filtered

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#1454]
Neither text nor options for polls are filtered.

* * * *
- Tusky Version: 8.1/master
- Android Version: 9
- Android Device: Pixel 2XL
- Mastodon instance (if applicable): cybre.space

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Well poll text is just the regular toot content or what am I missing?
Are options filtered in the web version?

**Comment by Fidgetcetera** [comment]
https://github.com/tootsuite/mastodon/issues/11128 Poll options are filtered on web mastodon, as of when this issue was closed.
