### ISSUE TITLE
Tusky X timeline design improvements

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#1494]
For Tusky 10 aka Tusky X I would like to do a few changes to how we display statuses:

- Rounded corners for preview images
- round corners for the poll result bars
- new icon for boosted statuses, see https://github.com/tuskyapp/Tusky/issues/1413
- use an icon to mark gifs instead of the same big play button we use for videos http://materialdesignicons.com/icon/gif
- use display name instead of @ name in "X boostet"

And possibly more, I will keep updating this issue. This issue should only be about visual changes, lets track bugs and functional changes elsewhere.

**Comment by ariasuni** [comment]
I guess you could edit the issue and use checkboxes; at least 3 out of the 5 items are solved now.
