### ISSUE TITLE
[Bug] Icons in the top right seem to randomly disappear

### ISSUE THREAD

**Issue by noiob** [tuskyapp/Tusky#1497]
I have no idea what causes this bug, but the icons in the top right of the screen seem to randomly disappear for me. This is not for a specific screen but in the entire app, e.g. I won't see the eye button when I view a thread with CWs, and I also won't see the three dots when I view a profile. Restarting the app will fix the issue. I usually have screen rotation locked so I don't think it's related to that.

* * * *
- Tusky Version: 9.0 (Beta channel)
- Android Version: 9
- Android Device: LG G6
- Mastodon instance (if applicable): n.a.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
This is an old bug without other reports, I will close it

**Comment by noiob** [comment]
yeah I'm pretty sure it's been resolved in the meantime, at least I haven't noticed it in a while
