### ISSUE TITLE
Videos are stretched in landscape playback

### ISSUE THREAD

**Issue by katktv** [tuskyapp/Tusky#1505]
When putting videos in fullscreen and setting to landscape mode the videos appear stretched. Example: playing 16:9 videos on the screen with non-standard aspect ratio like on my phone or (likely) many other modern phones.

* * * *
- Tusky Version: 9.0
- Android Version: 9.0 Pie (OxygenOS OP6 Beta 25)
- Android Device: OnePlus 6

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Can reproduce. It happens also in portrait orientation.
