### ISSUE TITLE
9.0 ,A bit of lagging when clicking top icon and sliding.

### ISSUE THREAD

**Issue by star2056** [tuskyapp/Tusky#1511]
I can see some lagging when clicking top icons(homepage,notifications, local timeline...)
Seems the app can only respond after complete the "sliding animation".
Sorry my english is not good.

* * * *
- Tusky Version:9.0
- Android Version:6.0
- Android Device:HUAWEI MLA-AL10
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
this should be fixed by https://github.com/tuskyapp/Tusky/pull/1544
