### ISSUE TITLE
Repeated crash on retrieval of pixelfed notifications

### ISSUE THREAD

**Issue by mrvdb** [tuskyapp/Tusky#1521]
Added a pixelfed.social account to tusky. Posts are retrieved and shown correctly. One or more notifications are retrieved and android signals them. After that, tusky crashes. On restarting Tusky, this repeats.  There is just enough time to logout from the pixelfed account to prevent a lockup.

* * * *
- Tusky Version: 9.1
- Android Version: 8 (xiaomi.eu rom)
- Android Device: Xiaomi Mi Mix
- Mastodon instance (if applicable): pixelfed.social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
  ( posibly overlaps with #1038 )

**Comment by connyduck** [comment]
This is a problem on Pixelfeds side, their support of the Mastodon api is still experimental. We are working with them to get these issues resolved.

**Comment by mrvdb** [comment]
Fair enough, although not crashing the app would be a bit more elegant.
