### ISSUE TITLE
Customisable Notifications (Sound, LED, Screen)

### ISSUE THREAD

**Issue by weinland** [tuskyapp/Tusky#1522]
I can only set Tusky to send all notifications or none at all on my device. This includes sound, LED and screen notifications.
I would like to have a feature (like in k-9-mail or signal messenger) to customize the types of notifications so I can set Tusky to just show me a screen notification and maybe let my phone’s LED blink in a predifined color.
I would love to see this implemented.
Cheers,
Tristan

* * * *
- Tusky Version: 9.1
- Android Version: LineageOS 16.0 (Android 9)
- Android Device: Fairphone 2
- Mastodon instance (if applicable): 

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
The notifications are managed by Android, nothing we can do here. It should offer you all these things though. 
Here is how it looks on one of my devices.
![device-2019-10-05-183816](https://user-images.githubusercontent.com/10157047/66257920-4ed66300-e79f-11e9-846c-57be1bb239a3.png)
