### ISSUE TITLE
Tusky does not obey "Disclose application used to send toots" mastodon account setting

### ISSUE THREAD

**Issue by mister-monster** [tuskyapp/Tusky#1525]
* * * *
- Tusky Version: 9.1
- Android Version: 9
- Android Device: 
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Just tried it out on mastodon.social: If you look at you own toots, you will always see the application (both Mastodon Webinterface and Tusky), but if someone else looks at your toots, the setting is respected (also in Tusky, since the Mastodon server does not even delivery this information).
