### ISSUE TITLE
“Open As” feature broke with new Tusky release

### ISSUE THREAD

**Issue by caoimhechaos** [tuskyapp/Tusky#1526]
“Open As” used to open the same post with a different account. With the new Tusky from f-droid, this functionality stopped working; Tusky switches accounts but then opens the “Open URL intent” chooser, which of course doesn't offer to open Tusky, so the original link is lost.

![Screenshot_20191009-090451_1](https://user-images.githubusercontent.com/36062/66459237-f3dd8e00-ea74-11e9-9ea4-5391f10de305.png)

![Screenshot_20191009-090501_1](https://user-images.githubusercontent.com/36062/66459256-fc35c900-ea74-11e9-90d2-ec4c5ef6f489.png)

![Screenshot_20191009-090517_1](https://user-images.githubusercontent.com/36062/66459284-05bf3100-ea75-11e9-8fc0-6709e1a322fb.png)

* * * *
- Tusky Version: 8.1
- Android Version: 10 (October 5 2019, build QP1A.191005.007) 
- Android Device: Pixel 3
- Mastodon instance (if applicable): anticapitalist.party, eldritch.cafe

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thx for reporting!

No I don't think the feature broke. This happens when the post cannot be found from the other account and because we use the same logic as for general link opening (which is: try if the link is a post that can be found by the current account, then open in Tusky, otherwise open the browser). We should change this so it just shows a toast with a message in this case.
cc @Tak

**Comment by Tak** [comment]
Makes sense, I'll look into improving the failure experience

**Comment by caoimhechaos** [comment]
Just FYI, this is happening on every single post for me, even when I'm following the person on both accounts.

**Comment by Tak** [comment]
Could there maybe be an issue with search? When I was testing #1531, I had to give up and send myself a DM to use because I couldn't find a post that would reproduce the problem (although I have seen it occasionally in the past).

**Comment by connyduck** [comment]
There where multiple issues with search on Mastodon, but both instances are on 3.0.1 so they should be resolved 🤔 

Does the search generally work for you? And if you put in the URL to a status? @caoimhechaos

**Comment by caoimhechaos** [comment]
Searching by content is disabled on ACP and enabled on eldritch. Searching by URL works from both, on the web interface. From the Tusky app, searching by URL or text does not work on either instance.

**Comment by connyduck** [comment]
What exactly is "does not work"? Just no result, or an error message...?
Searching by URL also does not work with one of my accounts, but that instance is still on v2.9.3, on v3 instances it works as expected 🤔

**Comment by caoimhechaos** [comment]
There are no error messages, just the search dialog stating that no results have been found:

![2019-10-13 14 09 34](https://user-images.githubusercontent.com/36062/66715590-6fb53e80-edc5-11e9-8421-cf654a43f129.png)

**Comment by Tak** [comment]
Was this maybe affected by #1666 ?

**Comment by caoimhechaos** [comment]
I'm not sure. Right now, the release version of Tusky from f-droid (8.1) is still broken, but it's 4 months old.

**Comment by connyduck** [comment]
F-Droid currently has 9.1. 
This problem does not occur with 9.1 and Mastodon 3. Tusky 10 will have additional improvements to search.
