### ISSUE TITLE
Import/export credentials

### ISSUE THREAD

**Issue by BenLubar** [tuskyapp/Tusky#1534]
It'd be nice to have a way to migrate credentials (and possibly other app-internal settings) from one Tusky instance to another, especially for development cases like copying a live device's state to an emulator or running the staging version of the app and the release version of the app on the same device without having to log in twice.

**Comment by charlag** [comment]
I'm not sure if it's worth it besides development (and you can copy things with adb if you really need to)

**Comment by pawelngei** [comment]
I second this being a useful feature when moving phones, I have a lot of settings like followed hashtags, wellbeing options etc that would be great to transfer.
