### ISSUE TITLE
Tusky repeatedly submits status

### ISSUE THREAD

**Issue by marnanel** [tuskyapp/Tusky#1558]
On Chapeau, a fediverse server under development, Tusky can successfully submit a status. However, it goes on to submit the status over and over again.

How to reproduce:
 - log in to instance sandy-heath.thurman.org.uk with username "tusky" and password "keylesspalace"
 - post a status
 - Tusky submits the status
 - Tusky continues to submit the status indefinitely, unless you log out

It's possible that the problem's on my end, but I haven't yet found it if it is.

* * * *
- Tusky Version: 9.1
- Android Version: 9
- Android Device: LM-V500EM
- Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes this issue is on your end, you don't return a status object.

**Comment by marnanel** [comment]
Thank you!
