### ISSUE TITLE
Tusky crashes if Mastodon API responses are malformed

### ISSUE THREAD

**Issue by marnanel** [tuskyapp/Tusky#1559]
If a server's response to /api/v1/accounts/verify_credentials is missing the "avatar" or "header" fields, Tusky crashes with an SQL error. These fields are required, so this can't happen with a properly-configured server. But Tusky probably shouldn't crash, anyway.

- Tusky Version: 9.1
- Android Version: 9
- Android Device: LM-V500EM
- Mastodon instance (if applicable): none

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
> can't happen with a properly-configured server
