### ISSUE TITLE
Bookmarks button is shown for instances not supporting them

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1564]
The title says it all. I'm on https://mastodon.ml instance now which is using Mastodon 3.0 (before bookmarks), however the button is present in UI. Might be confusing for some users, I guess.

* * * *
- Tusky Version: 9.1-d9694df
- Android Version: 9.x
- Android Device: Oneplus 5
- Mastodon instance (if applicable): https://mastodon.ml

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes this is intended behavior. We could start to adapt to specific Mastodon versions, but I am not sure if we should because it will add a lot of additional complexity to the app.

**Comment by JuanjoSalvador** [comment]
What about add an alert box showing a "Your instance does not support this feature yet"? A catched exception.

Also it will confuse other ActivityPub services like Pleroma, but I suppose that doesn't seem important at this moment.
