### ISSUE TITLE
Memory leak or slowdown when repeatedly switching tabs

### ISSUE THREAD

**Issue by viviicat** [tuskyapp/Tusky#1569]
I've noticed if I switch tabs between home and federated repeatedly, the app gets slower and slower, as if there's a memory or other leak. If I inspect the memory usage it slowly builds from 150MB to 400MB and around that point it becomes unusable.

Repro (attempted 5 times, seen 5 times on two different phones/accounts):
1. Open fresh instance of app to home timeline.
2. Switch to Federated timeline by tapping the tab.
3. Switch back to Home timeline by tapping the tab.
4. Repeat steps 2 and 3 25-35 times (50-70 switches total) until the app begins to freeze up, freezing continues in longer and longer intervals. App eventually goes into Not Responding mode.

* * * *
- Tusky Version: 9.1
- Android Version: 9 & 10
- Android Device: Moto x4 & Pixel 2
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by viviicat** [comment]
I just built the latest code and it appears to be resolved there as far as I can tell. I wasn't able to reproduce on the virtual device or on my actual device.

**Comment by connyduck** [comment]
yes this is fixed by https://github.com/tuskyapp/Tusky/pull/1544
