### ISSUE TITLE
[App Crash] Favorite notification bug makes Tusky crash

### ISSUE THREAD

**Issue by lapineige** [tuskyapp/Tusky#1578]
When someone add your toot as a favorite, then remove it ~instantly (let's say in less than 1-2 sec), sometimes it creates a kind of bug in the web UI, with just «[somebody] added your toot as a favorite» and no message displayed.
On the web UI, reloading the page solves the issue.

But on Tusky, this message doesn't disappear, and it makes Tusky crash after a few seconds. Even with no interaction with the app.
Clearing all notifications seems to be the only workaround…

Exemple here: https://framapic.org/DqYZqW7EwtLz/zpgDTJlp50Zk.jpeg

* * * *
- Tusky Version:9.1
- Android Version: 9
- Android Device: Wileyfox Swift Crackling
Note: when this problem occurred, internet connection was activated, but not the app. It occurs too when the app is currently used.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
What software is the server running?

**Comment by lapineige** [comment]
Mastodon (3.0), for both the origin and final server.

**Comment by charlag** [comment]
@lapineige can you get a stack-trace/log somehow?

**Comment by lapineige** [comment]
How can I do that ?
An adb logcat could be enough ? Is there an easier method ?

**Comment by charlag** [comment]
@lapineige it should be enough, yes
not really, there's a MatLog but it needs adb anyway

**Comment by lapineige** [comment]
(cc @Fipaddict)

**Comment by lapineige** [comment]
Additional information: this issue seems to happen only if the (broken) notification is still visible on screen. If newer notifications hide it, it doesn't happen.

**Comment by kyori19** [comment]
This stacktrace is what I saved when I encountered same bug.
I think it will help you!
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Date com.keylesspalace.tusky.viewdata.StatusViewData$Concrete.getCreatedAt()' on a null object reference
	at com.keylesspalace.tusky.adapter.NotificationsAdapter.bindViewHolder(NotificationsAdapter.java:211)
	at com.keylesspalace.tusky.adapter.NotificationsAdapter.onBindViewHolder(NotificationsAdapter...
```

**Comment by charlag** [comment]
@kyori19 thanks for the stacktrace, although it seems like it doesn't match the actual code (master or develop, line 211 is a `break`).

I will try to reproduce it

**Comment by charlag** [comment]
I'm sorry but I'm not able to reproduce it? You can try to make it happen for my account @charlag@birb.site

What's the server software for both of you?

**Comment by kyori19** [comment]
@charlag Sorry, I'm using my fork of Tusky.
Corresponding line is here.
https://github.com/tuskyapp/Tusky/blob/d0ce43dfca8ac2212d13104545961886e5193e23/app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java#L207

**Comment by lapineige** [comment]
@charlag can you reproduce the fav issue on the web interface ? (it often needs another account t fav you and unfav quickly, or spam with fav')

**Comment by charlag** [comment]
@lapineige I was not able to, I used my old mastodoc account to fav/unfav posts of my birb.site account quickly but it didn't occur

**Comment by charlag** [comment]
I spammed it that much now that it's -1 favs on mastosoc but on birb.site I just have a couple of favorite notifications
![Screenshot from 2019-12-08 16-29-25](https://user-images.githubusercontent.com/3099142/70391666-ee9ab200-19d7-11ea-8010-f9e059fc1864.png)

**Comment by lapineige** [comment]
Uh… I experienced that it occurs more often with laggy connections (such as mobile phone internet).

But indeed it doesn't happen to me very often… while other people experience it frequently.
I don't know how to help you there…

**Comment by lapineige** [comment]
Uh… I experienced that it occurs more often with laggy connections (such as mobile phone internet).

But indeed it doesn't happen to me very often… while other people experience it frequently.
I don't know how to help you there…

**Comment by lapineige** [comment]
(Sorry, that was a wrong click 😅)

**Comment by connyduck** [comment]
Will try to fix, but this should be reported to Mastodon as well.

**Comment by lapineige** [comment]
Ok great, thanks a lot. I'll see about where we can report this to Mastodon. (I suppose it already was reported)

**Comment by janboddez** [comment]
I've also had this happen a few times. The most recent occurrence seems to be caused by this:
```
{
	"3": {
		"id": "1139",
		"type": "poll",
		"created_at": "2021-10-02T09:16:03.213Z",
		"account": {
			"id": "7178",
			"username": "brainblasted",
			"acct": "brainblasted@social.libre.fi",
			"display_name": "Chris",
			"locked": true,
			"bot": false,
			"discoverable": false,
			"group": false,
			"created_at": "2020-02-28T00:00:00.000Z",
			"note": "Admin of social.libre.fi. GNOME developer.<br>DMs from mutuals are okay, and boosts are okay for all public posts.<br><br>Blank profiles and FOSS-only profiles will be rejected.<br><br><a class=\"hashtag\" href=\"https://social.libre.fi/tag/actuallyautistic\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#actuallyautistic</a>",
			"url": "https://social.libre.fi/users/brainblasted",
			"avatar": "https://media.geekcompass.com/geekcompass/cache/accounts/avatars/000/007/178/original/aaf07701b4726dcb.png",
			"avatar_static": "https://media.geekcompass.com/geekcompass/cache/accounts/avatars/000/007/178/original/aaf07701b4726dcb.png",
			"header": "https://media.geekcompass.com/geekcompass/accounts/headers/000/007/178/original/712f28da941cf933.jpeg",
			"header_static": "https://media.geekcompass.com/geekcompass/accounts/headers/000/007/178/original/712f28da941cf933.jpeg",
			"followers_count": 1685,
			"following_count": 643,
			"statuses_count": 90,
			"last_status_at": "2021-10-04",
			"emojis": [],
			"fields": [
				{
					"name": "Patreon",
					"value": "<a href=\"https://www.patreon.com/chrisgnome\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">https://www.patreon.com/chrisgnome</a>",
					"verified_at": null
				},
				{
					"name": "Pronouns",
					"value": "he/him/his or they/them/theirs",
					"verified_at": null
				},
				{
					"name": "GitHub Sponsors",
					"value": "<a href=\"https://github.com/sponsors/BrainBlasted\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">https://github.com/sponsors/BrainBlasted</a>",
					"verified_at": null
				}
			]
		},
		"status": null
	}
}
```

All I can really tell right now is that `status` is in fact `null`.
