### ISSUE TITLE
Media upload progress resets when the screen is rotated. 

### ISSUE THREAD

**Issue by N07070** [tuskyapp/Tusky#1580]
The title describes the issue. 

To reproduce, use the following configuration and try to upload a large media. ( 10Mo on my test ). Wait a bit for the media to upload, and rotate your device. You should then see that the upload progress has reset to 0. 

* * * *
- Tusky Version: 9.1
- Android Version: LineageOS 16 
- Android Device: x
- Mastodon instance (if applicable): x

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
This will go away with #1541

**Comment by charlag** [comment]
I think this should be closed now, please reopen if it happens on nightly
