### ISSUE TITLE
[Feature Request] RSS or Nitter support

### ISSUE THREAD

**Issue by ignamiranda** [tuskyapp/Tusky#1585]
There's a lot of bot accounts in Mastodon that mirror popular twitter accounts or post articles from certain news sources. Adding a way of subscribing to Nitter's RSS feeds or RSS in general would eliminate the need for these and make it easier for those who don't want to set up bots or want to just follow friend accounts without making a bot for everyone to see.

**Comment by charlag** [comment]
Hi
I see your point but I don't think it's our scope to be an RSS reader, there are special apps for that.
cc @connyduck
