### ISSUE TITLE
Alt text shows up behind video

### ISSUE THREAD

**Issue by noiob** [tuskyapp/Tusky#1587]
alt text shows up behind video

this is kind of an extreme edge case but hey

![Screenshot_20191215-231648](https://user-images.githubusercontent.com/8197071/70870247-22a24400-1f91-11ea-8911-6da9b5dd21ef.png)

the toot is https://sleeping.town/@zoe/103313947271456843

* * * *
- Tusky Version: 
- Android Version: 9
- Android Device: LG G6

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by noiob** [comment]
still happening in Tusky 12.1

**Comment by TobiasMaximilianAlexandreBasten** [comment]
Please for the love of blind people!
Please fix this. Make it popup in a snackbar or something.
It can hide your whole description if you have a portrait mode video.

**Comment by snail-coupe** [comment]
Still happening in 20.0

![Screenshot_2023-01-15-16-17-27-927_com keylesspalace tusky](https://user-images.githubusercontent.com/53581981/212552908-ae4ef523-a3cf-43c5-a9ed-266273b0eb41.jpg)
