### ISSUE TITLE
Reasons to switch over to Weblate?

### ISSUE THREAD

**Issue by Sasha-Sorokin** [tuskyapp/Tusky#1589]
Hi! I'm a passionate self-taught translator from English to Russian and a regular Mastodon user. Previously I've been translating and proofreading Discord, but they have closed their project, now after a long time, I finally found joy to be part of Mastodon's Russian translation team and recently was promoted to proofreader.

Recently I've adopted and improved my documentation from Discord for Mastodon's project. When writing, I searched how and where each app being translated. It saddened me to see that not a lot of developers prefer to set up integration with any translation platform, but Tusky was one of the projects who worked on that.

Unfortunately, I'm raising this issue to pay attention to the problem translators' experience: the usage of Weblate. I like the idea that it is FOSS, and so on, but unfortunately, when preferring open source *v.* good experience, I'd chose the second.

You may ask what is wrong with Weblate, but let me fill here a few bullets:

- As with many open-source products, the chance it has been developed primarily by the programmers is very high. And as a result, it is very complicated. I just don't get how to work in it, I have to read documentation, I have to get used to that and this is not good already.

- Not only it is complicated, but it is also underdeveloped in user experience. Just as an example — almost every action requires to reload the page, it is about a second just to submit a translation. This is **painful**.

I checked GitHub for open issues and discovered that you have used Crowdin previously and I just can't get in my mind why you switched away.

If this was a paid project, then I wouldn't care about any experience, but this is all voluntarily and unfortunately, I don't want to deal with Weblate. Even Transifex, which suffers from performance issues, would be a better option. Weblate may be a good option for project managers, but not translators themselves.

The truth is that the easiest and nicer you can welcome your further contributors, the better your project will be. I'm willing to contribute to your project as it is *directly* connected to Mastodon and it has a point for us to have consistent translations, but this one issue stopping me, and I even cannot promote everyone to jump in.

So, the main questions:

- What were the reasons to switch away from the Crowdin platform in the first place? I found issue #213, which does not answer this question.

- How you can convince your further translators to work with Weblate? Considering it still uses Bootstrap 2 for design, it's just doesn't look promising that things will improve in the future.

Looking forward to hearing from you and thanks for checking out this issue.

---

*I'm leaving the note here, that any of these words in this issue are not meant to be read in a negative tone. Also, I'm nowhere affiliated with Crowdin, but I'm passionate about their project too, because they do a great job, providing me as a translator, great tools to work with.*

**Comment by connyduck** [comment]
I cannot find the original discussion either (it should be an issue here on GitHub), but the important points to switch to Weblate were 1) its open source 2) we can host it ourselves. Also we liked the way Weblate is sending PRs more.

**Comment by Sasha-Sorokin** [comment]
> 1) its open source 2) we can host it ourselves

How both first and second reasons help me as a translator? I get that with open source and self-hosting you can control your project better when it comes to data and costs, but this is not the case for the Tusky translation project.

Given that the app itself is open source and strings, contexts and other data can be exported manually and closed source solutions such as Crowdin or Transifex supply open source projects with free premium licenses, it just does not make a lot of sense to use a solution with underdeveloped UX and tooling.

> Also we liked the way Weblate is sending PRs more.

Aren't they do it the same way? Well, Crowdin creates a separate branch in the repository itself, but it does not hurt to have, because it's based on master, you can always switch to it to check out your newest translations. The other difference is co-authoring, yeah, this is something to improve. Other than this, there are no big differences.

**Comment by charlag** [comment]
Crowdin was spamming PRs at us all the time.
If you think that Weblate is missing something, I think we should fix it in Weblate and not hope that proprietary platforms will start to fix things.

**Comment by Sasha-Sorokin** [comment]
> Crowdin was spamming PRs at us all the time.

What do you mean by that? It sees new translations, it creates a new branch (or rebases existing) and opens PR for it, it commits new translations and that's all. Isn't Weblate doing it the same way? It also could mean the project was more active back then.

> I think we should fix it in Weblate

So, you wish to rewrite it? Because I'm not, I'm a translator and only partially developer with some experience in TS, not employeed and not paid, so fixing Weblate isn't a thing I wanted to do, neither getting used to it after my *unpleasant* experience.

> not hope that proprietary platforms will start to fix things.

Well, did you try at least report it to them? I can do it if you tell me what's the deal with spam. They are committed to supporting open source projects, so they treat you as a customer with needs, I believe. I've contacted Crowdin support a few times, they were nice and helped resolving some problems for me in shortest time. And more, you could have always used their CLI tool/API to sync Crowdin translations your way any time you want to, I'm not even sure why you need Pull Requests for it.

**Comment by connyduck** [comment]
Weblate sends one update per day, Crowdin was sending one commit for every translated string iirc.

Its nice that you so dedicated, but I really do not think we will switch back to Crowdin as that will consume quite a bit of our already limited time and Weblate works well for us.
