### ISSUE TITLE
Hitboxes of  buttons in compose sheets are too small

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1593]
I've marked areas which are not interactive.
![изображение](https://user-images.githubusercontent.com/2780044/71262080-eafc1900-234f-11ea-865b-e4672a37e605.png)
![изображение](https://user-images.githubusercontent.com/2780044/71262390-9c02b380-2350-11ea-940f-1b9a5af92184.png)

* * * *
- Tusky Version: 9.1-8770fbe
- Android Version: 9.x (Pie)
- Android Device: Oneplus 5

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by viviicat** [comment]
Slightly unrelated but I find the cw button has too small of a hitbox, too.
