### ISSUE TITLE
Long Poll options are cut off

### ISSUE THREAD

**Issue by tastytea** [tuskyapp/Tusky#1608]
Long poll options are cut off. I think they should be multi-line.

![Screenshot_20191228-185933](https://user-images.githubusercontent.com/3681516/71547841-047b1180-299d-11ea-987a-a929c4afe23a.png)

* * * *
- Tusky Version: **9.1**
- Android Version: **7.1.2**
- Android Device: **Moto G 2014 LTE**
- ~Mastodon~ Pleroma instance (if applicable): **likeable.space**

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
I think we decided against it because it would make some options look bigger. Do you know what other apps do?

**Comment by a1batross** [comment]
Maybe enable text sliding always or on click event? 

In terms of UX, for example, I made long filenames of attachments slide and in fact it doesn't even look bad. It's ComposeActivity, yep.

![one](https://i.ibb.co/bFd46NZ/Screenshot-20191228-233128-Husky.png)
![two](https://i.ibb.co/rpgzJz0/Screenshot-20191228-233108-Husky.png)

**Comment by tastytea** [comment]
@charlag I don't use any other mobile apps, but Mastodon and Pleroma use multiple lines.

![screenshot_2019-12-28T22-36-33](https://user-images.githubusercontent.com/3681516/71549727-977a7280-29c2-11ea-9aa2-66c854646af1.png "Poll on mastodon.social")

@a1batross I would expect that if I click on an option text, the checkmark is toggled. But sliding might be a good idea?

**Comment by a1batross** [comment]
Sliding for all items at once may be a bit annoying.

Multiline is just ugly IMHO.

**Comment by Tak** [comment]
I ran into this again today. ( https://elekk.xyz/@wigglytuffitout/105456610934341124 )

Could we maybe let poll options be multiline and then factor them the existing into long post collapsing mechanism?

**Comment by charlag** [comment]
I will need @connyduck's call here

**Comment by connyduck** [comment]
Having them be multiline is ugly but probably the best solution.

**Comment by qoheniac** [comment]
Or maybe a long press could give a tooltip with the full answer.

**Comment by bannmann** [comment]
Here's another example:

![Screenshot_20230129-082834.png](https://user-images.githubusercontent.com/3303967/215311882-052bf099-2b86-4afb-b5d5-9099d3e6b6bc.png)
https://writing.exchange/@cyborg_writer/109733666086939301

Tapping, long-pressing or swiping would be really annoying when there are multiple long-text options. Also, none of them would be discoverable.

So as @connyduck wrote, line wrapping would be the best option here.

**Comment by pascoda** [comment]
I stumbled across several polls with this issue, so I'm bringing it back up.

**Comment by connyduck** [comment]
Huh? I was sure this is fixed with #3459 and #3608, are you sure this still happens in Tusky 23.0 @pascoda?

**Comment by pascoda** [comment]
yeah, right, it's fixed. as the issue was still open I did not bother to check whether it was actually still happening - I just remembered that it used to.

sorry :disappointed:

**Comment by connyduck** [comment]
no problem, thanks for confirming
