### ISSUE TITLE
Can't authorize with Tor Browser on mastodon.social

### ISSUE THREAD

**Issue by ryanprior** [tuskyapp/Tusky#1609]
With Tor Browser as my default system browser app, I can sign in to mastodon.social just fine, and when I click "authorize" it does a little loading animation like it's sending data. But then nothing happens, and as many times as I click authorize, Tusky doesn't log-in and doesn't show up in my web UI's list of authorized applications.

As a workaround, I can set Firefox as my system browser app and authorize Tusky no problem. Of course, if I needed to use Tor for privacy reasons, that workaround would not be viable.

* * * *
- Tusky Version: **9.1**
- Android Version: **8.1.0**
- Android Device: **Palm PVG100-03**
- Mastodon instance: **mastodon.social**

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I'm pretty sure Tor browser just refuses to open the app afterwards. I had the same problem with Firefox Preview. This could only be worked around if we implemented login in the app or if Tor browser changed it.
