### ISSUE TITLE
Boosted posts show up again after blocking a user and refreshing

### ISSUE THREAD

**Issue by szyszyszyszy** [tuskyapp/Tusky#1620]
Steps to reproduce:

1. Using a boosted post on one's home timeline
2. Block or mute the user who authored the boosted post
3. The boosted post disappears, as expected
4. Refresh the timeline
5. Boosted post reappears

* * * *
- Tusky Version: 9.1
- Android Version: 10
- Android Device: Nokia 7.1
- Mastodon instance (if applicable): All instances I use.

- [YES] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
I think it means that it comes from the server still?..
Can you confirm that it disappears from the web version as well when you do this?

**Comment by szyszyszyszy** [comment]
It does still appear on the web version, apparently.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by charlag** [comment]
Thanks
either server only filters out new posts or server doesn't filter out boosts

**Comment by charlag** [comment]
So I think it's a problem with the server, we can't do much because we clients don't apply block filters, sorry.
