### ISSUE TITLE
"Hide media" button overlaps with CW button

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1639]
Easy to reproduce: start composing a toot, upload an image, delete it and then compose it again. After that, "hide media" button will overlap the CW button as show below:
![изображение](https://user-images.githubusercontent.com/2780044/72406059-05b58800-376c-11ea-938a-68691f8d02b3.png)
Not critical, since you can just press that "mixed" button and it will fix itself, but still a bug.

* * * *
- Tusky Version: 9.1-21a7201 (Nightly)
- Android Version: 9
- Android Device: Oneplus 5
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
I've seen it couple of times too but I could not reproduce it with 9.1-92e9c9a. It blinks oddly but disappears like it should.

**Comment by MasterGroosha** [comment]
I can reproduce it with the latest Tusky 9.1-77fb4df
YouTube video: https://youtu.be/uFD8pV_aD5c

Also, sorry for the interface in Russian, however I cannot change it to any other language (another bug with Tusky, changing language simply doesn't translate the app for me).

**Comment by charlag** [comment]
@MasterGroosha hi, thanks for the video, Russian doesn't trouble me a single bit, если ты понимаешь, о чём я :wink: 

I could reproduce it by doing it twice like you did. Now we can solve it!
