### ISSUE TITLE
Closing compose screen with close icon doesn’t display confirmation dialog anymore

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#1653]
On latest Tusky, closing the compose screen with the close icon displays a confirmation dialog to let the user save her toot if she wants to.

On `develop`, it closes the compose screen immediately, losing the toot for good. Using the Android back button to quit the screen still display the confirmation dialog, though.

* * * *
- Tusky Version: 9.1-77fb4df6
- Android Version: 9
- Android Device: One Plus 5

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Cannot reproduce. Its definitely not happening everytime. Can you please provide exact steps or a video? There must be something I'm missing.

**Comment by ariasuni** [comment]
I cannot reproduce now and don’t remember exactly how I did it…? I’ll reopen the bug if this happens again.
