### ISSUE TITLE
Can't log in with Firefox Preview

### ISSUE THREAD

**Issue by pepijndevos** [tuskyapp/Tusky#1664]
When I first open the app and enter my instance, it opens Firefox Preview, asks me to log in, but when I click Authorize nothing happens. The loading bar flashes for a fraction of a second, and then nothing.

When I change the default browser to Fennec (F-Droid Firefox), everything works as expected. Clicking authorize brings me back to the app and logs in.

* * * *
- Tusky Version: 9.1
- Android Version: 9
- Firefox Preview version: 3.0.2
- Android Device: Motorola Moto G5 Play
- Mastodon instance (if applicable): freeradical.zone

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
It's a bug in Firefox preview because they don't open app registered URLs yet
