### ISSUE TITLE
Cannot login via browser

### ISSUE THREAD

**Issue by toby3d** [tuskyapp/Tusky#1674]
After installing the application and entering the domain name of the node, the browser (Firefox 68.4.1esr) opens the link https://mstdn.io/auth/sign_in. If I am already logged in through the browser, then a redirect to the profile occurs. If I close the browser, then the application freezes with the status "Connecting ...". The link seems to be invalid and should contain parameters and identifiers.

In any case, I can’t use the application, if it doesn’t even come out to log in to it. The behavior is repeated in the stable version. :man_shrugging: 

* * * *
- Tusky Version: 10.0 beta-6f8e8a6.2831
- Android Version: LineageOS 16.0 (Android 9)
- Android Device: Xiaomi Mi5S Plus
- Mastodon instance (if applicable): mstdn.io

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Can you try using Chrome, please

**Comment by toby3d** [comment]
In combination with chrome, authorization runs fine. But I would like chrome not to appear in the system requirements of the application as the only compatible browser. Otherwise, I will have to download it every time if authorization is reset.

**Comment by charlag** [comment]
It's just not an issue in Tusky. Firefox worked too before (I used it), FirefoxPreview and Tor did not work.

**Comment by charlag** [comment]
(I closed it by accident, sorry but if you believe it's really a bug on our side, let us know)
