### ISSUE TITLE
Support for stickers

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tuskyapp/Tusky#1676]
My instance and some others seem to use the sticker feature I made as a simple CSS hack. It would be nice to have such a feature implemented into Tusky. Right now every custom emoji starting with `sticker_` will be treated as a sticker.

* * * *
- Tusky Version: any
- Android Version: any
- Android Device: any
- Mastodon instance (if applicable): koyu.space, absturztau.be and perhaps others

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
I think we would need some API support for that if we decide to adopt that.
I'm not sure what this is, how big the adoption is (is it just your instance?) and if we can do anything. Could you provide more details?

**Comment by koyuawsmbrtn** [comment]
> I think we would need some API support for that if we decide to adopt that.

No API needed, every custom emoji that starts with `sticker_` becomes automatically a sticker.

> I'm not sure what this is, how big the adoption is (is it just your instance?) and if we can do anything. Could you provide more details?

It's basically 128x128 pixels big custom emojis. The adoption rate is my instance and 2-3 others. Not big enough, but the `sticker_` prefix isn't in use by any other instance so it should be safe to do it like this.

**Comment by charlag** [comment]
This is a custom convention on some instances, I am not sure we should implement this
