### ISSUE TITLE
Light theme background no longer white

### ISSUE THREAD

**Issue by bremensaki** [tuskyapp/Tusky#1687]
The light theme background has been white for me in every Tusky version up until the 10 nightly that I recently installed to check out. Now it has a distinct blue cast and is kind of hard on my eyes. 

* * * *
- Tusky Version: 10 nightly
- Android Version: 9
- Android Device: Moto X4

![Tusky - all versions to and including 9.1](https://user-images.githubusercontent.com/4737927/74483923-a7ff9180-4f0b-11ea-8b3a-9ecb5d3e4312.png)
![Tusky - 10 nightly](https://user-images.githubusercontent.com/4737927/74483936-af269f80-4f0b-11ea-8f2d-9a815ac9f74e.png)

Edit: Now I'm looking at it on Github, it wasn't plain white before either - but it definitely wasn't blue.

**Comment by connyduck** [comment]
This is intended and not a bug. I will go a little lighter and less blue though as it might indeed be a bit much.

**Comment by bremensaki** [comment]
I just got updated to Tusky 10 on my phone this morning, and the background colour is unchanged from the nightly. If it's been lightened, I can't tell the difference. Comparing previous screenshots looks like it's unchanged. Is there something odd about my phone?

I hate to complain, I love your work, but this pretty much makes the app unusable to me - I have real trouble focusing on this.
