### ISSUE TITLE
Add support for Announcements

### ISSUE THREAD

**Issue by w4tsn** [tuskyapp/Tusky#1693]
Since Mastodon 3.1.0 it is possible to send Announcements to all users of an instance.

At this moment I'm not able to see these announcements in the app on my Android Phone. I'm only able to see them in the web UI which makes it pretty easy to miss them.

* * * *
- Tusky Version: 9.1
- Android Version: 9
- Android Device: Fairphone 3
- Mastodon instance (if applicable): 3.1.1

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes we should add support for announcements.
Any ideas how we can include them in the interface in a nice way?

**Comment by Tak** [comment]
The web ui has them as a popout from the home timeline - we could maybe do a similar thing there that we're doing in notifications, with sub-tabs?

IMO the thing that will be most difficult/annoying to implement is that announcements support emoji reactions.

**Comment by dkter** [comment]
Now that Tusky has an app bar, it seems like a "view announcements" button could be put in the app bar, maybe to the left of the search button or something
