### ISSUE TITLE
Searching for a post by url gives an infinite list of that post

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#1694]
Searching for a post by url gives an infinite list of that post.

![Screenshot_20200216-124641](https://user-images.githubusercontent.com/142250/74604053-695c0980-50ba-11ea-9399-32bc95b0ed42.png)

* * * *
- Tusky Version 10.0 beta 1-f2683a2b
- Android Version: 10
- Android Device: Pixel 2 XL
- Mastodon instance (if applicable): cybre.space

- ✅ I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
its a Mastodon bug https://github.com/tootsuite/mastodon/issues/13083
but we should still fix it
