### ISSUE TITLE
"Show Less" button not functioning for cw'd toots in a thread

### ISSUE THREAD

**Issue by fakefred** [tuskyapp/Tusky#1713]
How to reproduce:
- find a cw'd toot in a thread
- view the toot in the thread
- tap "show more" (toot expands)
- tap "show less" (toot does not collapse)
Same goes for other toots in the thread.

* * * *
- Tusky Version:
- Android Version: 10.0 beta 1
- Android Device: Mi 6 (sagit), Mokee (lineageos derivative), Android 8.1.0

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Please upgrade to Tusky 10.

**Comment by fakefred** [comment]
Oh no, I had risky tusky version filled in Android version field. I'm on tusky 10.0 beta 1.
________________________________
