### ISSUE TITLE
Preview text going to CW space

### ISSUE THREAD

**Issue by ismirth** [tuskyapp/Tusky#1715]
With the latest version of Tusky 10.0-dd8abad android.... when I go to share a post to Tuskegee it is grabbing the preview text and putting it into the content warning spot instead of into the text area I'm having to select all cut and move it down to the correct place so that I can add my comments etc.

* * * *
- Tusky Version: 10.0-dd8abad
- Android Version: 10 security patch feb 5th
- Android Device: pixel3 xl
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
This is coming from #1712 - the preview text is getting passed to Tusky as the "subject" of the share

**Comment by ismirth** [comment]
Thank you I read that description originally but I could not tell if it was
the same thing or not.

Bells Craig
Pronouns: he/she
Honorific: Sir, Mr or Mx (pronounced "mix")
+1 424-422-3557

**Comment by frumble** [comment]
Hello, I’m annoyed too by this feature. I don’t want titles of articles as CW of my posts. That’s not my toothing style. And it’s even illogical: CWs are typically used to warn you about a content, but with this implementation, you are pasting the headline right into the CW field.

**Comment by charlag** [comment]
I also don't do this normally and without easy way to clear the CW it's quite cumbersome I think. I don't suffer from it since I don't share many links but I can imagine this being annoyed. Losing info from share is also not good, maybe someone has an idea for the smart solution here?

**Comment by ismirth** [comment]
I completely agree and I despise it... I have to go in there when there is
an actual content warning and select all and cut and paste it into the body
of the message and then go back to the content warning and put with the
content warning is such as disturbing imagery or description of murder or
sexual abuse etc.

I really really despise this setup. If there were anything I could do to
fix this I would... And currently the only way I know to fix it is by going
to a different app and the last time I checked this was still the best
app... So I literally might have to go find a new app if you guys don't fix
this in the next like 6 to 8 weeks.

Bells Craig
Pronouns: he/she
Honorific: Sir, Mr or Mx (pronounced "mix")
+1 424-422-3557

**Comment by ksclarke** [comment]
I agree that this doesn't seem logical, since CWs are used as a warning about the following text and the preview text isn't really a "warning" about the shared text/link that follows. I imagine though that this was an intended behavior by the dev. I wonder whether a "fix" would be to allow disabling this feature so that something that is just shared is shared as a toot without the content warning? I could see that as a toggle option in the preferences. It's pretty annoying now to have to copy and paste the preview text to get it outside of the CW and into the toot's body.

**Comment by connyduck** [comment]
So - lets change this back? @Tak

**Comment by Tak** [comment]
Sure, works for me

**Comment by ismirth** [comment]
Yes I would rather have it changed back or to have it be a toggle that we
can select... Either put preview in CW or put preview in text box... But
whichever is the least amount of dev work because honestly it's really
frustrating when I want to put actual content warnings and my only option
is to either delete all of the text that's in the content warning already
or select it all and then cut and paste it into the body and then write my
content warning etc... It takes 10 times the amount of time that it used to
take.

Bells Craig
Pronouns: he/she
Honorific: Sir, Mr or Mx (pronounced "mix")
+1 424-422-3557
