### ISSUE TITLE
[Accessibility Request] Option To Toggle Swiping Between Tabs

### ISSUE THREAD

**Issue by CyberneticCody** [tuskyapp/Tusky#1718]
I recently updated to the latest version of Tusky and have been fighting with the swipe to change tab feature. It would be great if we had an option in the settings to disable swiping between tabs. Often when scrolling because of how my thumb moves, I will swipe by accident instead of scrolling.

**Comment by charlag** [comment]
Hi
It's a problem with Android library. Many deveelopers including us aren't happy about this so we expect them to change this

**Comment by RX14** [comment]
@charlag can tusky offer an option to disable this as a short-term workaround? Tusky being difficult to use until this is fixed isn't fun :(

**Comment by CyberneticCody** [comment]
Agreed, especially considering a lot of people have Android phones that won't be getting updates to the OS and people that will get them far behind everyone else...

**Comment by charlag** [comment]
We would really prefer to mot include such an option just as a workaround. It's not tied to Android version at all, it's support library

**Comment by RX14** [comment]
I'm pretty sure it worked fine on the old tusky version. Aren't the support libraries bundled in the apk?

**Comment by CyberneticCody** [comment]
> Letting tusky accessibility be harmed because of a third party dependency isn't a good look... It's not like end users can change this or choose to avoid it.

I can agree with this, However, even with the library being up or downgraded this would still be a nice option to have.

**Comment by szyszyszyszy** [comment]
I have experienced this issue as well. Frankly it's an accessibility issue.

**Comment by NeckbeardedDragon** [comment]
I've never intentionally swiped between tabs, I always use the tab indicators at the top. An option to disable swiping between tabs would be very useful.

**Comment by konomikitten** [comment]
This is driving me up the wall also and making Tusky unusable. I'd really like to see this fixed.

**Comment by Powersource** [comment]
Does anyone have a link to more info about the library issue?

At least for me going back to the old behavior is fine, I don't need the toggle.

**Comment by a1batross** [comment]
That's why people shouldn't rely on support/androidx libraries. They aren't tested well. It's a enourmous hole full of bugs made by low-qualified Google employers,

**Comment by charlag** [comment]
> Does anyone have a link to more info about the library issue?
> 
> At least for me going back to the old behavior is fine, I don't need the toggle.

the library is `androidx.viewpager2:viewpager2:1.0.0`

There's a hack: https://medium.com/@al.e.shevelev/how-to-reduce-scroll-sensitivity-of-viewpager2-widget-87797ad02414

There was an alpha version from the 1st of April which did not include any changes to sensitivity so it looks like it works as "intended" for them.

**Comment by charlag** [comment]
I am sorry that it is like that, I expected that they will revert it very quickly.

**Comment by ashkitten** [comment]
i think regardless of whether or not this bug is fixed in a timely manner, there should still be an option to disable swiping between tabs as multiple people have suggested here already.

**Comment by CyberneticCody** [comment]
Thank you, that's all I was asking for.

**Comment by TheOtherDoctor** [comment]
The conflicts mentioned in #1752 stopped this from getting into the nightly yet? Cannot find yet (latest looked into 10.0-0ccd2c4). :-(

I'd be very happy if that swiping function got turned off, as I also never intentionally used swiping since the tab headers are so easy to reach.

Related to the tab-switching swipe I'd like to ask about the effect on an issue which I think might be related, see my recent comment on #1677: does the fix #1752 also cover the unwanted swiping into message details when trying to bookmark? 
I perceive that one even worse because it cannot be easily undone by sweeping back, but only the top left back arrow brings the view back to the timeline.

**Comment by charlag** [comment]
@TheLastProject it doesn't cover anything besides tab switching
