### ISSUE TITLE
Posts are scheduled 24 hours before the datetime chosen in the date-picker

### ISSUE THREAD

**Issue by ddelabru** [tuskyapp/Tusky#1720]
When I schedule a post, after going through the date-picker, if I tap the clock button again, the app shows that the post is scheduled for a time 24 hours before what I specified. (I am in Eastern Standard Time or New York time, in case this is relevant.) If I choose to schedule a post one hour from now, for example, the post will actually be scheduled 23 hours in the past. If I tap "Toot!", this results in my post being published immediately.

* * * *
- Tusky Version: 10.0
- Android Version: LineageOS 16.0 (equivalent to Android 9.0)
- Android Device: OnePlus 5T (dumpling)
- Mastodon instance (if applicable): todon.nl

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ddelabru** [comment]
I just upgraded Tusky to 10.0 (the non-beta release) and the issue persists.

**Comment by charlag** [comment]
Hi
I can reproduce it with your time yone

**Comment by charlag** [comment]
Bug in DatePicker:
https://github.com/material-components/material-components-android/issues/882
