### ISSUE TITLE
Posting status with CW and media doesn't mark media as sensitive 

### ISSUE THREAD

**Issue by compufox** [tuskyapp/Tusky#1721]
when you are drafting a post and add a content warning it disallows you from toggling sensitive or not. however, when you actually post the status it does not mark the media as sensitive. 

if you mark the media as sensitive *before* adding the CW the media gets marked as sensitive as expected

* * * *
- Tusky Version: 10.0
- Android Version: 9
- Android Device: Essential PH-1
- Mastodon instance (if applicable): social.computerfox.xyz

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
I couldn't reproduce that behavior. Can you list exactly the order in which you're doing things to get it to fail?

**Comment by compufox** [comment]
I tested with another instance and it seemed to work as intended.

I think it may just be an issue with my server's mastodon instance.

Sorry about this, I'll close this issue.
