### ISSUE TITLE
[BUG] Video upload failed

### ISSUE THREAD

**Issue by prismplume** [tuskyapp/Tusky#1727]
I'm unable to upload a video for some reason even when I made it shorter because of the 40mb file upload limit. I even made sure to check my internet connection, which was fine when I tried uploading the video again.

![Screenshot_20200311-213144_Tusky](https://user-images.githubusercontent.com/62063926/76422987-150a2800-63e1-11ea-84f6-9df6c3294fbb.jpg)

* * * *
- Tusky Version: 10.0
- Android Version: 9
- Android Device: Samsung Galaxy S8
- Mastodon instance (if applicable): mastodon.art

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
It's really hard to say without more information. Do you know which format/codec the video is in?

**Comment by prismplume** [comment]
Hi!

The video codec is H264-MPEG-4 AVC (part 10) (avc1) while the audio code is
MPEG AAC Audio (mp4a).

Hope this helps.

**Comment by charlag** [comment]
Thanks!
I made a patch to add ability to send logs for when it's merged you will be able to send/analyze logs so we will know what's going on.

**Comment by ariasuni** [comment]
What about the logs you’re talking about @charlag? I still don’t have any log when media upload fails in 16.0 beta 2… See https://github.com/tuskyapp/Tusky/issues/995#issuecomment-1035046360

**Comment by charlag** [comment]
Closing in favor of #995
