### ISSUE TITLE
Support “Mute conversation” like in Mastodon Web

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#1731]
Tusky doesn’t provide a “Mute conversation” action. Contrarily to what the name implies, it is used to mute a thread, and not a conversation in the direct message sense.

![bildo](https://user-images.githubusercontent.com/2446451/76897570-462ca180-6894-11ea-9151-70a5bbae8973.png)

On Mastodon Web, the action is available on our own toots, and for any toots that’s displayed in the notifications (mentions, fav, boosts, poll ended, etc.).

The API are described on [joinmastodon.org](https://docs.joinmastodon.org/methods/statuses/) (search “Mute conversation” and “Unmute conversation”).

- `api/v1/statuses/:id/mute`
- `api/v1/statuses/:id/unmute`

* * * *
- Tusky Version: 10.0
- Android Version: 9
- Android Device: Oneplus 3

**Comment by charlag** [comment]
Closed by #1732 I suppose
