### ISSUE TITLE
Show preview of thread in reply creator

### ISSUE THREAD

**Issue by lapete** [tuskyapp/Tusky#1745]
When composing a reply to an toot, currently there's no possibility to see the original toot. When it comes to longer posts, I often want to check some wording or so in the original toot, and currently I have to copy the draft, close the reply editor and look, create a new reply and paste the draft. 

It would be great to have some feature that shows the toot where the reply goes to, or even the whole thread, without losing the progress.

* * * *
- Tusky Version: 10.0
- Android Version: 9
- Android Device: Xiaomi Mi A1
- Mastodon instance (if applicable): All

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
hi
there is a possibility, click on "replying to" with down arrow on top of the screen
