### ISSUE TITLE
In multiple choice polls, percentage and total are not counted as in Mastodon web

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#1759]
![Screenshot_20200416-221718_Firefox_Beta](https://user-images.githubusercontent.com/2446451/79622464-a6269a00-8117-11ea-8429-85940f64e706.png)

Mastodon web:
- Both options are at 89%
- Counts 9 *voters* (homoj on the screenshot = people)

Tusky:
- Both options are at 50%
- Counts 16 *votes* (voĉdonoj on the screenshot)

How’s that counted?
- 9 voters
- 8 votes for each option
- Mastodon: 8 votes / 9 voters ≈ 89%
- Tusky: 8 votes / 16 total votes ≈ 50%

It seems the current behavior is how Pleroma works, according to a quick search in their source code ([percentage](https://git.pleroma.social/pleroma/pleroma-fe/-/blob/ac9985aedbc2ed53121eec06a95013186c4eefd4/src/components/poll/poll.js#L69), [Total votes](https://git.pleroma.social/pleroma/pleroma-fe/-/blob/ac9985aedbc2ed53121eec06a95013186c4eefd4/src/components/poll/poll.vue#L59)).

I don’t know what/if something should be done, but since Tusky is Mastodon-oriented project and that there is at least one Pleroma-oriented fork, maybe that’s OK to just always display polls the way Mastodon do.

* * * *
- Tusky Version: 10.0

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
We changed it in #1733 but I guess it is not on stable branch yet. Could you please check it on master?

**Comment by charlag** [comment]
*on nightly
sorry

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/1733

**Comment by ariasuni** [comment]
Oops I forgot to answer, thanks for the quick answer and link to the PR :)
