### ISSUE TITLE
Visually indicate that a toot has-a reply (in addition to "is-a reply")?

### ISSUE THREAD

**Issue by TheOtherDoctor** [tuskyapp/Tusky#1767]
Currently I can see immediately when a toot _is_ a reply. But often I'd be interested if a (question-type) toot already _has_ some replies, because I have the same question and would like to see the answers. I open the toot, there is nothing, I close it again... not so nice. 

For adding a visual indicator, the simplest I could imagine is just some "..." below the "reply" arrow icon to indicate "more to come below this one".

Having even a count of the follow-up replies would be the luxury solution. ;-)

I'd see this proposal as one pragmatic approach for making discussion threads usability improved, in that sense it's related to #1766.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
At least I gave my best on it. ;-)

**Comment by aleqssss** [comment]
I'm not in favor of counters everywhere but if we could have a different arrow color when a toot has a reply it will be the perfect app for me ^^

**Comment by TheOtherDoctor** [comment]
Just wondering if it makes most sense to have a simple way to directly jump to the original post of a discussion thread? 
When I get a message into my timeline which is a reply (to a thread I do not yet know), the first thing I do is navigate up to the very top (possibly level by level through lots of replies) to get an idea what this is actually about. If there would be some button "jump to origin of thread", or a config option to make tap-for-message-details behave like this, I'd always use that...

**Comment by TheOtherDoctor** [comment]
I also like the proposal to change color of the arrow icon if message is-a reply. 
Brings me to the idea to "grey out" the whole message text if it is a reply and the discussion root is yet assumed-unknown (i.e., pragmatic, if thread root is not listed in current timeline).

Currently even have replies turned off in my home timeline to avoid being annoyed by lots of replies which I cannot understand without knowing the context

**Comment by TheOtherDoctor** [comment]
To it seems that #1469 is somewhat similar to the suggestion here - maybe both can be handled together?

**Comment by charlag** [comment]
see #2467 (I think #1496 is a different thing still)
