### ISSUE TITLE
Detekt-hint integration

### ISSUE THREAD

**Issue by Mkohm** [tuskyapp/Tusky#1770]
Hi!

I am working on a tool for detection of violations on design principles in my master thesis (read more about it here: https://github.com/Mkohm/detekt-hint), and is looking for an open source project where I can integrate my tool for some feedback and testing. Would you welcome such an integration? It would mean a lot, and I hope it can continue to improve the maintainability of this project.

It only requires creating a configuration file and a new GitHub action. Please let me know if it is of any interest, and I will create a PR with the required changes.

**Comment by connyduck** [comment]
I just ran the tool on our codebase, it seems to fail analyzing some classes with `The original exception message was: Value at CLASS must not be null for CLASS` and then reports some `InterfaceSegregationPrinciple` code smells. Does not look particularly useful to me.

**Comment by Mkohm** [comment]
Thank you for finding the error and for being the 1st known person to test the tool! 

> Does not look particularly useful to me.

That's a fair thing to say. Would you mind explaining why you don't find it useful? What should be improved for you to consider using it?

**Comment by connyduck** [comment]
Well, the Tusky codebase has a lot of problems, if I would introduce a static code analyzer into our build pipeline (which we should tbh), I would first look for something that detects actual bugs & crashes before something that goes after design principle violations.
