### ISSUE TITLE
Accessibility: font size and display size

### ISSUE THREAD

**Issue by testuser51** [tuskyapp/Tusky#1780]
- Tusky Version: 10.0
- Android Version: 10
- Android Device: Redmi Note 7

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

If: settings - Accessibility - font size and display size = largest
![88](https://user-images.githubusercontent.com/53906414/81280381-0fd3fd00-9061-11ea-9ab9-c26ef1c333fc.jpg)

Then:
![11](https://user-images.githubusercontent.com/53906414/81280473-31cd7f80-9061-11ea-9a5d-91a40d203ca2.jpg)

![22](https://user-images.githubusercontent.com/53906414/81280486-398d2400-9061-11ea-8cce-cf806607e29e.jpg)

![33](https://user-images.githubusercontent.com/53906414/81280501-3e51d800-9061-11ea-8040-66b57f65345e.jpg)

![44](https://user-images.githubusercontent.com/53906414/81280521-47db4000-9061-11ea-98ab-d6b0fb2fcc11.jpg)

![95](https://user-images.githubusercontent.com/53906414/81282530-f4b6bc80-9063-11ea-82c3-587b73b0d44d.png)

**Comment by connyduck** [comment]
Whats the problem on the three last screenshots?

**Comment by testuser51** [comment]
This is not a critical issue, but the “cancel” and “ok” are too close to each other

**Comment by connyduck** [comment]
Ah yes. Thats not related to font size though, it happens all the time.
