### ISSUE TITLE
Tusky and pixelfed crash. Can someone deofuscate please.

### ISSUE THREAD

**Issue by cannod** [tuskyapp/Tusky#1781]
I'm trying to see is Tusky works with pixelfed. Tusky crashes when going to notifications. I have searched and it seems like pixelfed might not be sending correct data or no data at all for some of the API calls. Can someone please help me out and deofuscate the following stack trace as I'm not sure sure how to do it.

Thanks.

`05-08 13:44:43.989  4455  4455 E AndroidRuntime: FATAL EXCEPTION: main
05-08 13:44:43.989  4455  4455 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 4455
05-08 13:44:43.989  4455  4455 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at v1.f.a.t1.e2.a(SourceFile:368)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at v1.f.a.t1.e2.a(SourceFile:90)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at v1.f.a.t1.g2.a(SourceFile:25)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at v1.f.a.t1.s1.b(SourceFile:156)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at v1.f.a.t1.s1.a(SourceFile:18)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.a(SourceFile:178)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$c.a(SourceFile:10)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:149)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:136)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.c(SourceFile:127)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:8)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:9)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(SourceFile:20)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(SourceFile:1)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.scrollBy(SourceFile:6)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at v1.f.a.y1.p1$d.b(SourceFile:8)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at t1.x.e.i.a(SourceFile:4)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at t1.x.e.y.a(SourceFile:64)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at t1.x.e.e.run(SourceFile:6)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-08 13:44:43.989  4455  4455 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

* * * *
- Tusky Version: 11.0 beta 1 (also tried 10)
- Android Version: 10
- Android Device: MotoG3
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
No I cannot obfuscate that, sorry. But we are working closely with Pixelfed to improve compatibility.
