### ISSUE TITLE
Unable to send schedule toot

### ISSUE THREAD

**Issue by mashirozx** [tuskyapp/Tusky#1782]
Cannot send schedule toot.

![Screenshot_2020-05-09-07-03-21-639_com.keylesspalace.tusky.test.jpg](https://s3-view.2heng.xin/aws_cached/2020/05/09/Screenshot_2020-05-09-07-03-21-639_com.keylesspalace.tusky.test.jpg)

* * * *
- Tusky Version:11.0 beta1-864ba37
- Android Version:9
- Android Device:Redmi note 8 pro
- Mastodon instance (if applicable):https://hello.2heng.xin

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
I don't see a problem?

**Comment by mashirozx** [comment]
toot won't be sent when click the toot button

**Comment by mashirozx** [comment]
Cannot reproduce this problem after reboot
