### ISSUE TITLE
Failed authenticating with that instance

### ISSUE THREAD

**Issue by stodge** [tuskyapp/Tusky#1794]
I'm trying to log into the venera.social instance but I get the error:

Failed authenticating with that instance

* * * *
- Tusky Version: 11.0
- Android Version: 10
- Android Device: Samsung Galaxy Tab S6 (SM-T860)
- Mastodon instance (if applicable): venera.social

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
venera.social is a Friendica instance, Tusky is not compatible with Friendica.
