### ISSUE TITLE
Back from image/media toot issue in the feed

### ISSUE THREAD

**Issue by alexandre1985** [tuskyapp/Tusky#1795]
When I click to see a image on some toot and after that I click to close the image, back into the toots feed, Tusky brings the user to the top of the toots feed.

Is there a way to, instead, bring back to the corresponding image toot in the toots feed?

Right now as it is, after viewing an image, I have to rescroll/reswipe a lot to continue in my last standing read toot position in the feed.

_Enviado do meu Galaxy J3(2017) usando [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by connyduck** [comment]
> Tusky brings the user to the top of the toots feed

I don't know what you mean with that. It works as expected for me. Can you maybe show us a video of the problem? Also please provide the Tusky & Android versions you use.

**Comment by alexandre1985** [comment]
- Android version: 9
- Tusky version: 10.0

With this video it can be seen what I mean by: when I get out of an image or media, Tusky brings me to the top of the feed, and not to the toot in question

https://streamable.com/ofcgwt

**Comment by charlag** [comment]
Hm, activity kicked out of memory but I'm not sure why.

**Comment by alexandre1985** [comment]
@charlag ok.
So this does *not* happen with your Tusky app?

**Comment by charlag** [comment]
@alexandre1985 no, it doesn't we would fix this already (it's like 90% of bugs out there, need very special conditions).
To be clear: you didn't enable developer option to stop all activities on pause? I wonder if Samsung does something.

**Comment by alexandre1985** [comment]
@charlag You would need to tell me which is the specific Android Developer Option in Portuguese :disappointed: I am not expecting that you actually tell me this.

For what I understand, it does not happen with other smartphones, which is cool.

My Android is kinda a mess. You know, it is an Google Android OS :roll_eyes:

**Comment by charlag** [comment]
In English it's like this, first one in Apps category for me
![Screenshot_20200524-120027](https://user-images.githubusercontent.com/3099142/82751245-38c0f580-9db6-11ea-8c67-b5bab8b492bf.png)

**Comment by alexandre1985** [comment]
@charlag This option was enabled by myself. I disable it, rebooted and now this issue is resolved.
:+1: :+1: :+1: :100: :1st_place_medal:
