### ISSUE TITLE
[Feature Request] Ability to move toolbar to bottom

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1798]
Tusky already has an option to prevent changing timelines with swipes. This is great and prevents accident timeline changes. Now, please, allow us to move toolbar (timeline buttons) to the bottom. Devices are getting bigger each year, and sometimes it's not comfortable to tap those icons in top.

* * * *
- Android Device: Oneplus 7T Pro (its display is huge)
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I am symphatetic to the cause but it goes against the usage of the component. Tabs are meant for "same but different" content, bottom navigation is for different parts of the app. Tabs are dynamic, bottom navigation is static. I don't think there's a good solution.

**Comment by connyduck** [comment]
I am very much in favor of this, but there is already an issue https://github.com/tuskyapp/Tusky/issues/796
