### ISSUE TITLE
Audio playback stops when screen is off or switched to another app

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1802]
Current implementation of audio playback in Tusky doesn't allow listening in "backgroud", either with screen off or with another app in foreground.

How to reproduce: start listening to audio, then open app switcher or just turn screen off.

* * * *
- Tusky Version: 11.0-1c09441
- Android Version: 10
- Android Device: Oneplus 7T Pro
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate (search keywords: [audio](https://github.com/tuskyapp/Tusky/issues?q=is%3Aissue+audio), [playback](https://github.com/tuskyapp/Tusky/issues?q=is%3Aissue+playback), [music](https://github.com/tuskyapp/Tusky/issues?q=is%3Aissue+music))

**Comment by connyduck** [comment]
I don't think this is a bug, its how Android apps should behave unless they are dedicated music apps

**Comment by MasterGroosha** [comment]
That's sad to see. By the way, where does Tusky store downloaded audio files? I pressed "Download" several times, but didn't find file afterwards.

**Comment by connyduck** [comment]
There should be a folder called "Tusky" somewhere on your external storage and the downloads should be in there. If you can't find it its maybe buggy and we need to fix it.
Also, the download experience can definitely be improved, e.g. by offering to open or share the downloaded file
