### ISSUE TITLE
The official website is down

### ISSUE THREAD

**Issue by kodfodrasz** [tuskyapp/Tusky#1803]
The official website https://tusky.app is down

* * * *
- Tusky Version: n/a
- Android Version: n/a
- Android Device: n/a
- Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thx, but it works fine now? Maybe GitHub Pages had a problem

**Comment by kodfodrasz** [comment]
Its fine now. Well sure it didn't work when I opened the bug. Sry for the noise then.
