### ISSUE TITLE
Selecting more than one image to pixelfed posts them in reverse order

### ISSUE THREAD

**Issue by igalic** [tuskyapp/Tusky#1811]
when posting multiple images to pixels.helpchangethe.world, they appear in the reverse order from what i specified in Tusky

* * * *
- Tusky Version: 11
- Android Version: 8
- Android Device: OnePlus 5T
- Pixelfed instance: pixels.helpchangethe.world

**Comment by connyduck** [comment]
This might not be related to Pixelfed, I got similar reports on different platforms. Also image descriptions sometimes get mixed up.

**Comment by connyduck** [comment]
Duplicate of https://github.com/tuskyapp/Tusky/issues/1577 (has more information)
