### ISSUE TITLE
Posting hashtags on pixelfed is all kinds of broken

### ISSUE THREAD

**Issue by igalic** [tuskyapp/Tusky#1812]
Posting Hashtags on pixelfed results in all kinds of broken behaviour. but since i cannot tell which of my posts are made with which version, here's one from the latest:

https://pixels.helpchangethe.world/p/meena/171878860978262016

this image was shared with the following text:

```
#TransOnATrain #TrainSelfie #MaskSelfie
```
in Tusky, none of these are clickable, while on the site itself, nothing shows up

* * * *
- Tusky Version: 11
- Android Version: 8
- Android Device: OnePlus 5T 
- Pixelfed instance: pixels.helpchangethe.world

**Comment by connyduck** [comment]
that is definitely a Pixelfed bug, and I think its has been fixed
