### ISSUE TITLE
The 'more' button [...] should move to the edge

### ISSUE THREAD

**Issue by guntbert** [tuskyapp/Tusky#1813]
Currently the more button (on every toot in the timeline) has a margin on the right side. This causes me to miss it and tap between the button and the edge, thus opening the toot. 

I want the button to be as close to the edge as possible.
PR is incoming

* * * *
- Tusky Version: 11.0
- Android Version: 8.1, 10
- Android Device: doesn't matter
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by pespin** [comment]
I confirm I can reproduce this issue most of the time. Whenever I want to press the "more" button, I end up clicking the toot, even if really focusing on doing it right.

**Comment by charlag** [comment]
Related PR is closed so I will close this issue too
