### ISSUE TITLE
Toot composing UI unusable on extra-high displays

### ISSUE THREAD

**Issue by PeterCxy** [tuskyapp/Tusky#1821]
My device is one of those very very exotic phones: it has a display of 21:9 aspect ratio. On this device, the toolbar at the bottom of the compose UI overflows the width of the display, making the "send" button out of reach partly or completely. This makes it impossible to send a toot.

Though this currently happens only on exotic devices, fixing this may prevent similar issues from happening on other phones in case the options in the toolbar gets longer in the future. Adding a horizontal scroll view wrapper should suffice as a fix for these ultra slim displays.

* * * *
- Tusky Version: 11.0
- Android Version: 10.0
- Android Device: DuoQin Qin 2 Pro (21:9 display)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

![Screenshot_20200603-235914](https://user-images.githubusercontent.com/4532423/83738056-62b3cb00-a686-11ea-8ec1-03bb48009a70.png)
![Screenshot_20200603-235930](https://user-images.githubusercontent.com/4532423/83738060-63e4f800-a686-11ea-9472-0be9c02509b4.png)

**Comment by a1batross** [comment]
I've fixed that by putting option buttons into a ScrollLayout in my fork. This isn't best but at least gave me freedom to add more option buttons and save the UI/UX of ComposeActivity.

If this is fine solution, I can rebase my patch on Tusky codebase and submit it here.

**Comment by charlag** [comment]
I think that scroll is not a solution but maybe we could fold some options into "more" menu, group some or move some to the top. Maybe moving character count out of the bar would also be helpful (since it can be quite big too)

**Comment by a1batross** [comment]
@charlag I would move character count to the top bar, maybe to the right of close button. 

Emoji button can be placed between atButton and profile image.
Probably, composing UI should encourage users to use emoji search more than keyboard. I've noticed that not everyone knows about autocomplete by shortcode.

Yes, having "more" button is nice but how to decide what should be hidden? For me, there is only button that is rarely used -- scheduling. Replacing one button with another doesn't help resolve this issue. 

By the way, why we have "@" and "#" button that can be accessed through with Android keyboard and placed so high, where it's uncomfortable to press them at all?

**Comment by charlag** [comment]
Is this still relevant? I think we did a few changes to compose screen
