### ISSUE TITLE
unable to fetch replies to a pixelfed 

### ISSUE THREAD

**Issue by igalic** [tuskyapp/Tusky#1823]
Tusky is able to post replies to a pixelfed post, but not fetch them.

That seems like a rather odd asymmetry.

Here's an example post, where i posted a comment, with Tusky, that doesn't show up in Tusky:
https://pixels.helpchangethe.world/p/SpunkyAlpaca/174932261832101888

* * * *
- Tusky Version: 11.0
- Android Version: 10 (OxygenOS) 
- Android Device: OnePlus 5t
- Pixelfed instance: pixels.helpchangethe.world

**Comment by charlag** [comment]
I think it has something to do with how Pixelfed implements threads in Masto API rather than with us.
I think @connyduck was already trying out some Pixelfed instances? I could also make an account if needed.

**Comment by connyduck** [comment]
Pixelfed just does not deliver anything on the `api/v1/statuses/:id/context enpoint`. I guess its just not implemented on their end. @dansup ?

**Comment by igalic** [comment]
i don't know.
that instance went down, and i haven't found a new home yet, nor have i been able to setup a pixelfed instance myself

**Comment by charlag** [comment]
Judging by the comments above it was not a problem with Tusky
