### ISSUE TITLE
Can’t translate some changelog entries (character limit < source character count)

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#1834]
So, sometimes I can’t translate entries because the character limit is too short; sometimes even shorter than the source string, e.g.:

https://weblate.tusky.app/translate/tusky/tusky-app/fr/?checksum=4c599ca7e320c390
(I saw @connyduck tried to set the limit to 700 characters after we discussed it on the Fediverse, but Weblate sees it as an explanation field)

I guess the limit exists because it’s using the Google Play format, see [this issue comment on Weblate’s repository](https://github.com/WeblateOrg/weblate/issues/1525#issuecomment-464720742). But it doesn’t seem to be used for Google Play since some source strings don’t fit the Google Play 500 characters limit.

Are the translations of the changelog entries used anywhere right now? F-Droid has its own system to translate applications metadata, which includes changelogs, so I’m not sure it’s used there. Also, it’s not used on https://tusky.app/ either.

So… where are these translations used; if they’re used, how to be able to translate them properly?

**Comment by gerazo** [comment]
The lately committed weblate key "changelogs/80.txt:1" for the v14.0 release description has a 500 char limit on it. Even the original English text does not fit into such a small space.
It is definitely used in F-Droid and this way, translators will not be able to translate everything. Do we have to intentionally reduce the translation to 500 chars?
@connyduck @BoFFire

**Comment by connyduck** [comment]
The changelogs are shown on Fdroid. There is no way to tell Weblate to up the limit and I think Fdroid truncates changelogs after 500 characters. I'll make it shorter.
