### ISSUE TITLE
Feature: Changable Date Format for absolute timestamps

### ISSUE THREAD

**Issue by samuel-p** [tuskyapp/Tusky#1842]
I just activated absolute timestamps in the settings. It would be great if I could change the used format for posts with a date to: `DD:MM hh:mm:ss` or something simmilar. 

Maybe you can add a new setting to set the format individually or choose from a list if you activate absolute timestamps.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by maxtar** [comment]
Yes, current format not equals regional system setting. I think need to get them from system.

**Comment by kirenida** [comment]
@charlag any updates on this?
