### ISSUE TITLE
Mute not working from Pleroma instance

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [tuskyapp/Tusky#1847]
I am logged in to a Pleroma account and when I try to mute somebody who is on either Mastodon or Pleroma it just says "An error has occurred". I can block fine.

If I mute them from another app I am able to unmute them in Tusky but still can't mute. The list of muted users is correct though.

* * * *
- Tusky Version: 11.0
- Android Version: 9
- Android Device: OnePlus 5
- Mastodon instance: shitposter.club

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by a1batross** [comment]
It's broken in Pleroma develop. Same happens on my instance.
