### ISSUE TITLE
[Feature Request] add image expand in timeline

### ISSUE THREAD

**Issue by FinecoFinit** [tuskyapp/Tusky#1853]

**Comment by charlag** [comment]
I'm sorry, could you provide at least some explanation? I have no idea what you are proposing. Thanks.

**Comment by WeFenFinit** [comment]
@charlag In the news feed, all images are cropped, add the ability to disable cropping
Sorry for my English language

**Comment by charlag** [comment]
I think we decided against uncropped images before.

**Comment by FinecoFinit** [comment]
@charlag It's really uncomfortable tap and close every time to watch full picture. My timeline is filled only with them

**Comment by xGian18** [comment]
Yeah I have a lot of cropped images too.
Can't u do a setting to let user chooses?

**Comment by charlag** [comment]
Duplicate of #1995
