### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by Vibhigupta** [tuskyapp/Tusky#1865]
So I customized Tusky for my instance but recently we moved to pleroma and wanted update the app but we customized it locally so I forgot everything what is where.

Can you tell me where all the files related to solace screen where login button shows up?

**Comment by connyduck** [comment]
I don't think we can help you there, how should we know which files you changed? Maybe it helps if you check the diff of your local repo?

**Comment by Vibhigupta** [comment]
Sorry i didn't mention it i was asking in Your Tusky , Well tell me where it is located in Tusky own app not mine. i tried diff but didn't get anything good in results.

**Comment by connyduck** [comment]
Well, there are a lot of ways you could have customized Tusky, how should I know which files you touched. Login button comes from `LoginActivity`, maybe start from there.
