### ISSUE TITLE
[Feature Request]Option to block instance

### ISSUE THREAD

**Issue by Oymate** [tuskyapp/Tusky#1874]
Option to block instance

* * * *
- Tusky Version: 11.0
- Android Version:Android 9
- Android Device:Xiaomi Redmi Note 7
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
You can already do so? Go to any profile -> three dot menu -> mute instance
