### ISSUE TITLE
[Feature Request] Notifications for new toots from accounts (like Youtube's "bell" feature) 

### ISSUE THREAD

**Issue by codedust** [tuskyapp/Tusky#1898]
With a growing number of followings, following an account becomes less meaningful. In order not to miss any news from specific accounts, e.g., a news bot or an organization that only toots from time to time, it would be helpful to enable notifications for specific accounts. This would create a notification for every future toot of this account.

ActivityPub has the potential to provide a more interactive alternative for RSS/Atom feeds. Many organizations already offer news feeds via messengers (e.g., [Tagesschau](https://www.tagesschau.de/inland/messenger-109.html) or [bpb](https://www.bpb.de/dialog/257145/deine-taegliche-dosis-politik)). Telegram uses the *Channel* feature to provide people with the [latest news about the Coronavirus](https://telegram.org/blog/coronavirus). Mastodon could be the perfect platform to provide a new home for these kind of services.

* * * *
- Tusky Version: 12.0
- Android Version: n/a
- Android Device: n/a
- Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by a1batross** [comment]
IMHO, this should be done on backend part.

For example, Pleroma already implements that and provides an API to subscribe to notifications.

**Comment by charlag** [comment]
I remember that we had an issue for that and we didn't want to implement it because it can be abused for harassing.

**Comment by codedust** [comment]
I don't really see why that could be the case. Can you elaborate on this or give any hints where I could find the discussion about it?

**Comment by charlag** [comment]
I couldn't find it but it was said that if you want to harass someone each time they post something, this would work very well

**Comment by codedust** [comment]
Ah, I see. That's not so easy to answer then. However, what about only enabling this feature for accounts that flag themselves as being a bot?

**Comment by TheOtherDoctor** [comment]
This ease-of-harassment concern sounds for me similar to the reason not to implement full text search (not even in the subset of messages which the user has already viewed), and I wonder if the risk of misuse isn't present in all the functions which have significant potential to improve app usability and ease of communication - and consequently I'd ask if the focus is set correct when usability is kept low due to these concerns; I'd expect that such monitoring features could also make it much easier for any victim of harassment to track back the aggressor. Furthermore, extrapolating these decisions, I worry that in the long run we win little if the lack of usability pushes users back into the birdcage...

**Comment by moshpirit** [comment]
@charlag if you want to harass someone you can already use RSS to get notifications of when someone toots anything. Also, you can create an account just for harassment. I don't really think this feature makes thisuch worse in comparison to the benefits, TBH.

**Comment by TheOtherDoctor** [comment]
Don't get me wrong - I'd love to see technical features to make it easier to keep the instances nice and friendly... I just have some doubt we can achieve such this way, as also just mentioned there are plenty other ways for stalking somebody (at least as long as posts are created in any public way - and also followers-only is easily broken with a 2nd account). In the end the moderators take the burden to stop unwanted communication to the instance community as a whole, if the targeted receiver cannot get along with just blocking an aggressive person or instance.

**Comment by moshpirit** [comment]
Exactly, the right way to avoid harassing people to via admin.

**Comment by draedr** [comment]
I'm sorry, but now that Mastodon has added a subscribe function, is it possible for tusky to implement the fucntion? Currently, when i receive a notification of this kind, tusky just shows an empty one, other than, obviously, having to go throught my instance web interface to un/subscribe accounts.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2012
