### ISSUE TITLE
The tab with hashtags doesn't update

### ISSUE THREAD

**Issue by Hund** [tuskyapp/Tusky#1911]
I added a tab with 3 hashtags and everything worked as expected. A few days later I added a bunch of more hashtags, the issue now is that it doesn't update that tab with new posts from the hashtags I added.

* * * *
- Tusky Version: 12.0 (F-Droid)
- Android Version: 10
- Android Device: Pixel 3a

**Comment by Hund** [comment]
I added a new tab with all the hashtags at the same time and it looks like it's only showing the first 3 hashtags.

**Comment by connyduck** [comment]
What Mastodon instance?

**Comment by Hund** [comment]
It's Fosstodon.org.

**Comment by Hund** [comment]
I noticed today that I can only remove a current hashtag if I add a new one at the same time.

It also looks like it's showing the first 4 hashtags for me now.

**Comment by Hund** [comment]
This is still an issue for me.

**Comment by connyduck** [comment]
which version are you on now?

**Comment by Hund** [comment]
12.1 from F-Droid.

**Comment by connyduck** [comment]
Can you check the 13 beta as well please?

**Comment by Hund** [comment]
Sure. How do I do that without installing my current installation?

**Comment by connyduck** [comment]
it should be available on Fdroid as well

**Comment by Hund** [comment]
I did not know that. I upgraded, but it didn't help.

**Comment by connyduck** [comment]
Oh wow I can finally reproduce it. It is an mastodon server bug that occurs on the webpage as well.
https://github.com/tootsuite/mastodon/issues/15194

**Comment by Hund** [comment]
Considering that Mastodon [won't fix this issue](https://github.com/mastodon/mastodon/issues/15194#issuecomment-742015124) would you consider working around this in Tusky? I find it stupid that you're limited to **four** hashtags by default in Mastodon and that he's refusing to fix it.

**Comment by charlag** [comment]
IIs not something we can fix, we do not assemble timelines.

**Comment by Hund** [comment]
> IIs not something we can fix, we do not assemble timelines.

You don't assemble timelines? I'm pretty sure I have a timeline of post from people that I follow, a public timeline of the posts from the instance and a public timeline of all federated posts in Tusky. I'm also able to search for posts, users and hashtags. 

Perhaps I'm mistaken, perhaps I'm using some other client with the same name? ;)

**Comment by charlag** [comment]
Perhaps you do or perhaps you misunderstand what we do.
We ask server "give us timeline with this name in this range". We do not go and load all the posts on the fediverse, check which of them have the tag and assemble them in the timeline.

Working around would involve making multiple requests and then combining them and I am not even sure it works with paging.

We need better server software, not client hacks.

**Comment by Hund** [comment]
> Perhaps you do or perhaps you misunderstand what we do.

No, I don't. :)

> We ask server "give us timeline with this name in this range". We do not go and load all the posts on the fediverse, check which of them have the tag and assemble them in the timeline.
> 
> Working around would involve making multiple requests and then combining them and I am not even sure it works with paging.

I'm not a fully fledged programmer as you, so I don't know how it works in detail, but I know enough to know that if you can have a search feature that lets you search for any hashtag, that it's then possible to do the exact same thing, but with slightly different clothes, so to speak.

And the different clothes in this context being that the search query is made by me opening the tab with my preset hashtags.

> We need better server software, not client hacks.

I totally agree with this. And I can understand that you don't want to add too many ugly hacks for shit that Mastodon can't get right or just outright refuse to implement and/or fix because of no reason at all, but in this instance you should really consider solving this issue or outright removing the feature all together.

And I'm sorry if I even sounded like an annoying end-user. I don't want to come of as ungrateful for the work you put into Tusky. I do appreciate it, but having to deal with a broken feature for more than a year gets frustrating. No matter who's fault it is.
