### ISSUE TITLE
Posts for Lobsters feed are not displayed

### ISSUE THREAD

**Issue by dector** [tuskyapp/Tusky#1915]
![Screenshot_2020-08-26-03-00-10-089_com.keylesspalace.tusky.png](https://user-images.githubusercontent.com/265872/91236216-68322600-e748-11ea-847f-ae45ff5c9db3.png)

**Comment by charlag** [comment]
It's something with your server: either instance is suspended (which is normal with botsin) or it's just not federated yet.

**Comment by dector** [comment]
@charlag Thanks for the answer.

This feed displayed fine in the web https://botsin.space/@lobsters .
But profile feed in SubwayTooter is not shown as well. =/ But the toast with "end of the list" message is shown.

Maybe it's a good idea to notify user that there are some issues as well?

**Comment by charlag** [comment]
There are no issues. There's a message on top of your screenshot which is related.
