### ISSUE TITLE
toot notification crashes android interface

### ISSUE THREAD

**Issue by jondor** [tuskyapp/Tusky#1916]
Every notification of a new toot seems to crash the android interface.
I see the notification bar (on top) disappearing after which I get a wifi notification that the network connection is being made. Finally, the lock screen shows with the tusky notification. 

* * * *
- Tusky Version: 12.1
- Android Version: 6.0.1
- Android Device: Samsung s5neo
- Mastodon instance (if applicable): photog.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
I'm not sure if we can do anything about it without more info

**Comment by NotAFile** [comment]
This is happening to me too now, unfortunately I'm not familiar enough with Android to know how to help out further, it just crashes instantly.

**Comment by NotAFile** [comment]
I managed to solve it by opening my notifications in another client. There I discovered that a message I had been mentioned in was deleted by the server admins. That might help, but of course I can unfortunately no longer reproduce it now.

**Comment by charlag** [comment]
If you have crash reports for play enabled then @connyduck might have received the stacktrace
