### ISSUE TITLE
Wrong Context Added to Filters by Tusky

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [tuskyapp/Tusky#1917]
1. In Tusky, add a word in the Public timelines filter.

2. In Web App > Preferences > Filters, you'll see that that word will be filtered from your conversations and not public timelines.

* * * *
- Tusky Version: 12.0
- Android Version: 10

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/1904

**Comment by iknownothingaboutcomputers** [comment]
Oops! Sorry.
