### ISSUE TITLE
Search Custom Emojis

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [tuskyapp/Tusky#1918]
I'm on an instance with >1K custom emojis. Scrolling to find the one I need is PITA so a search-feature would be great. Possible?

* * * *
- Tusky Version: 12.0
- Android Version: 10

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
You can start typing colon (:) and see autocompletion results

**Comment by iknownothingaboutcomputers** [comment]
@charlag Thank you! Closing this issue.
