### ISSUE TITLE
[Feature Request] Add option to allow open in app button in Firefox(or open supported links)

### ISSUE THREAD

**Issue by Oymate** [tuskyapp/Tusky#1920]
[Issue text goes here].
I can't see the option to "open in app" while visiting a mastodon account.

* * * *
- Tusky Version: 12.0
- Android Version: N/A
- Android Device: N/A
- Mastodon instance (if applicable): All

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
It's not possible because there isn't a single domain we can register for.

**Comment by Oymate** [comment]
@charlag Fedilab has this with supported links please reopen this.

**Comment by charlag** [comment]
What do "supported links" mean? Do they keep track of each domain?

**Comment by Tak** [comment]
Aren't they doing something like we do with the quick "is this a fediverse url" check for in-app lookups?

**Comment by charlag** [comment]
Isn't this mechanism static and you tell in manifest which URIs you can handle?

**Comment by Tak** [comment]
🤷

**Comment by Oymate** [comment]
Please reopen this.
![Imagepipe_10](https://user-images.githubusercontent.com/50857856/91686379-f3634f80-eb7e-11ea-8ff3-4dc44be8e199.jpg)
