### ISSUE TITLE
RLO character in user name breaks notification text

### ISSUE THREAD

**Issue by compilin** [tuskyapp/Tusky#1921]
Hi,

I recently got a notification from a user who has a RIGHT-TO-LEFT-OVERRIDE character (U+202E / \&#8238;) in their name, like this: "Name [RLO] some emojis". When receiving a "favourited" notification from this user, the expected "[Name] [emojis] has favourited your toot" (I have it in French so that may not the be the exact wording), it becomes "[Name] toot ruoy detiruovaf sah [emojis]". The web version handles this fine (that is, the emojis are displayed in reverse order, but the rest of the text is LTR as expected). 
Here's what it looks like. Tusky :
![image](https://user-images.githubusercontent.com/40794281/91723068-7db9ac80-eb9b-11ea-9d5d-8d4c125809b4.png)
Web :
![image](https://user-images.githubusercontent.com/40794281/91723425-06384d00-eb9c-11ea-9ba6-f7daa9eac029.png)

(I'd imagine a LRO character would similarly break the notification text if the system language is RTL, but I haven't tested it)

* * * *
- Tusky Version: 12.1
- Android Version: 10
- Android Device: Pixel 3
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (I found some issues about text direction but I didn't find any about notifications, user names or RLO, sorry if I missed one)

**Comment by Tak** [comment]
Is this in the android notification, or in the notifications page inside Tusky?

**Comment by compilin** [comment]
Screenshot is the android notification (more precisely, from the notification log because it was the only place you could see the whole text), but the same goes for inside the app :
![image](https://user-images.githubusercontent.com/40794281/94904966-69b7e200-049c-11eb-94a5-d9bc1303aef3.png)

**Comment by clarfonthey** [comment]
Adding more to this: I think that the fix is to essentially do a BIDI isolate on any user-specified text. In CSS this is done with `unicode-bidi: isolate` but if you need to do it with pure unicode characters you can wrap the text in U+2068 and U+2069; see https://unicode.org/reports/tr9/#Explicit_Directional_Isolates

**Comment by Tak** [comment]
The unfortunate part is that we _are_ already doing this, e.g. https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java#L332

**Comment by clarfonthey** [comment]
Oh, huh. That makes me question Google's Unicode implementation then :(
