### ISSUE TITLE
Editing a scheduled toot doesn't remove the previous one

### ISSUE THREAD

**Issue by YohannLYD** [tuskyapp/Tusky#1924]
When editing a scheduled toot, either by changing the content and/or the publishing time, the previous toot isn't removed so we end up with an additional one.

It gets confusing when only the publishing time is edited since we end with duplicates and can't know which toot is the right one.

* * * *
- Tusky Version: 12.1
- Android Version: 9
- Android Device: SM-G900F

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by garritfra** [comment]
@connyduck Any remarks? I can work on this.
