### ISSUE TITLE
[Feature Request] Setting for deactivation of dark patterns

### ISSUE THREAD

**Issue by niklas-fischer** [tuskyapp/Tusky#1941]
I'd like to have the possibility to deactive dark patterns like:
- pull to reload
- infinite scroll 

As an alternative to infinite scroll there could be a pagination of toots. 

* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by clarfonthey** [comment]
Those aren't dark patterns, but agree that other options would be nice

**Comment by charlag** [comment]
Pull to refresh is a "dark pattern"? :thinking: 
For infinite scroll see #2471 (we don't even have infinite scroll?)
