### ISSUE TITLE
[Feature request]: Detect gemini:// links

### ISSUE THREAD

**Issue by PaperMountainStudio** [tuskyapp/Tusky#1944]
I would like to be able to click on links using the gemini protocol in posts and in bio. Protocols like http or gopher are detected, but gemini isn't.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by garritfra** [comment]
> Protocols like http or gopher are detected

Gopher links are not detected. Neither Gopher nor Gemini links are even supported by Mastodon itself.
Another issue is that there are no (not as I know of at least) gemini browsers for android, so even if you could make them clickable, there is no way to open the actual gemini page.

**Comment by PaperMountainStudio** [comment]
You are correct, I didn't know the gopher links were not detected in regular posts, but they are detected in bio whike gemini links are not detected anywhere. There are at least 2 gemini clients for android, but I am not sure if they can open gemini:// URLs.

**Comment by connyduck** [comment]
I'd prefer if Tusky would not insert links where the server did not put any. But Mastodon added support for gemini:// links and once that code runs on your instance they should start working in Tusky as well (as long as you have an app that supports gemini:// installed)

https://github.com/tootsuite/mastodon/pull/15013
