### ISSUE TITLE
FEATURES I THINK SHOULD BE ADDED

### ISSUE THREAD

**Issue by ucheibe** [tuskyapp/Tusky#1953]
I would like it if you added the feature that allows you to send a Dm(direct encrypted message to someone. Another feature I would like is addition of 2FA (2 Factor Authentication). 
* * * *
- Tusky Version: Tusky 12.1
- Android Version: 9 (Pie) 
- Android Device: Huawei Y9 2019

**Comment by AkazaRenn** [comment]
For DM I think you can, just choose `Direct` visibility when sending a toot and @ the person you want in the content.

**Comment by ucheibe** [comment]
Okay thanks a lot. That was quite helpful 🙂
