### ISSUE TITLE
pixelfed broken in current nightly?

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#1955]
As of yesterday, virtually everything involved with pixelfed.social account stopped working in tusky nightly: No timeline refresh, no access to remote profiles, "error" screen while trying to access notifications. Any way to track down what happens? Much likely an issue on pixelfeds end but hard to track down; it seems to work with pixeldroid or pixelcat.

* * * *
- Tusky Version: 12.1-8e2e815
- Android Version: 10 (LineageOS 17.1)
- Android Device: Moto G 3
- Mastodon instance (if applicable): pixelfed.social

**Comment by connyduck** [comment]
Maybe your auth token just expired. Tusky does not handle expired tokens and Pixelfed expires them after some time (in contrast to Mastodon). 

Can you try logging out and in again? That should resolve the issue.

(Yes we should fix that issue but that is a different topic 😅 )

**Comment by kr428** [comment]
Thanks. Seems indeed it either was a temporary issue with pixelfed (happens once in a while, still 'til today) or just an expired token. No way to reliably track this down, so closing that.
