### ISSUE TITLE
Lists Toot Compose

### ISSUE THREAD

**Issue by rober42539** [tuskyapp/Tusky#1962]
It would be nice if I could go Lists, then select the list I want to Toot from, and have a compose floating action button. 

For now, my new list says 'nothing here' but unless I add the list to my custom tabs (which is limited to 5 tabs, but I have a number of lists), I can't compose toots to them directly from each list in the the list listing.

It would also be nice to be able to edit existing toots and place them in certain lists.

Thanks for the great work you all are doing! 

![Screenshot_20201018-033545.png](https://user-images.githubusercontent.com/282862/96353179-f812a180-10f3-11eb-94ba-e95c48e78199.png)

**Comment by connyduck** [comment]
Are you confusing lists with hashtags? You cannot toot to a list.

**Comment by rober42539** [comment]
Yes, I think so. I'm not really understanding the purpose of lists. In my mind, I would like to narrow audiences down for specific groups of my friends, without making groups. The list feature looks to be used differently than that.

**Comment by connyduck** [comment]
Yes it is used differently. The feature you want is currently in development for Mastodon (and will be called "circles"). Once it is done we will add it to Tusky as well.

**Comment by rober42539** [comment]
Awesome! That sounds great!
