### ISSUE TITLE
accept self-signed certificates,

### ISSUE THREAD

**Issue by AnonymousWebHacker** [tuskyapp/Tusky#1965]
add that it can accept self-signed certificates, just like browsers, peertube, element matrix .. etc

**Comment by charlag** [comment]
Why would we do that?

**Comment by AnonymousWebHacker** [comment]
If you have a self-signed certificate in your mastodon, the android apk, I could not connect, because it has not implemented to accept an invalid certificate, just like firefox does.

**Comment by connyduck** [comment]
Sorry, but accepting self-signed certificates would weaken security for everyone. If you require that feature, please build Tusky from source yourself.

**Comment by AnonymousWebHacker** [comment]
> Sorry, but accepting self-signed certificates would weaken security for everyone. If you require that feature, please build Tusky from source yourself.
Sorry, but 
Accepting self-signed certificates would NOT weaken security, being self-signed does not mean that the communication travels encrypted. Only if you create your own CA, and certificates, you cannot use the APK, because it does not accept these certificates
