### ISSUE TITLE
[Feature Request] remove tracking elements from URLs

### ISSUE THREAD

**Issue by Swrup** [tuskyapp/Tusky#1967]
Many websites use tracking elements in the URL (UTM parameters).
They are not necessary for a website to be displayed or work correctly and can therefore be removed.
Sometimes users inadvertently toot or click on a link with utm parameters.

To protect their privacy, I propose to warn a user before he toots an URL with tracking elements or automatically clean it for him.
Tusky could also remove tracking elements from every toots so the user doesn't click on them.

The add-on ClearURLs already does that and keep a list of UTM parameters to remove :
https://gitlab.com/KevinRoebert/ClearUrls

**Comment by charlag** [comment]
Hi, I really think it's out of our scope, browser extensions can do this much better than us
