### ISSUE TITLE
Support for federated content as files

### ISSUE THREAD

**Issue by Porrumentzio** [tuskyapp/Tusky#1969]
It would be great to have a treatment as files for audios (from Funkwhale) and videos (from Peertube), just like it's [done on Mastodon web interface](https://github.com/tootsuite/mastodon/pull/11189).

Currently Tusky only posts URLs. What do you think about this?

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Porrumentzio** [comment]
Any opinion? It has passed more than a year already

**Comment by AnonymousWebHacker** [comment]
Anyway, I've been waiting for this for a long time

**Comment by connyduck** [comment]
I'm not sure what you mean, can you give me an example status that Tusky should handle differently?

**Comment by AnonymousWebHacker** [comment]
@connyduck For example, when you share an embedded Peertube video on Mastodon Web, you can play the video. Through the tusky app you cannot play the video, it only shows a URL, it does not let you preview the video.

**Comment by charlag** [comment]
@AnonymousWebHacker I don't think it's federated content, I think it's certain embed features, I don't think we can do this

**Comment by AnonymousWebHacker** [comment]
I was reading that https://github.com/tuskyapp/Tusky/issues/503
and this is good  https://github.com/tuskyapp/Tusky/issues/503#issuecomment-390981393

@Gargron How could I use the API that I use in Mastodon Web, to be able to embed videos in tusky as a Mastodon client?
 https://github.com/mastodon/mastodon/pull/5848/commits/6919ffb671308e58ef564c5c5c0dae66d5885ae9

The idea is to be able to view the videos as can be done on Mastodon Web.

**Comment by charlag** [comment]
If we get media from API, we display it. If there's no media given to us by API we can't do anything about it.
