### ISSUE TITLE
Add option to confirm boosting 

### ISSUE THREAD

**Issue by Null-Senpai** [tuskyapp/Tusky#197]
It would be nice if an option to confirm before boosting something could be added.

**Comment by alerque** [comment]
I'm going to disagree and say that adding more friction to basic actions would make the whole app seem clumsy. Boosting and favoriting toots are such basic and common operations that they should be low friction as possible.

What's your actual concern here? It's possible you're trying to solve a problem that has a better solution.

**Comment by daycode** [comment]
I agree with @alerque don't add more click to basic actions 😉

**Comment by alxlg** [comment]
He said "an option", it means that who want the confirmation dialog can enable it in the settings.

I would appreciate it too since I already boosted and favorite a lot of toots by mistake.

**Comment by Null-Senpai** [comment]
My issue is that it is very easy to accidentally boost something while scrolling or trying to catch your phone while accidentally dropping it. Sounds stupid, I know, but it's a real issue.

Anyway, the reason I think you should consider implementing this is that, as alxlg stated, I did put 'option', so this would not be forced on people that do not want it. 
It would also be more consistent with the desktop version. I might be wrong here, since different instances might have different customizations, but on the instance I use we get a confirmation dialog to confirm
![rms](https://cloud.githubusercontent.com/assets/13616397/25399312/f44349d0-29e6-11e7-8c3a-3e623498967d.png)

**Comment by daycode** [comment]
but default, mastodon don't do that, and you can unboost if you do something wrong 😉

**Comment by alerque** [comment]
As @daycode said the upstream Mastodon web interface doesn't do this either. And yes you can undo by clicking it again. Technically this works, but it also has site effects. It will no longer show up in your timeline as boosted, but any other instances that were following you do not actually get notified of the change of status and may still display the boost to followers on that instance.

This is actually an issue that should be considered at the protocol level because it causes miss-information to be shown. And it does make the current low friction UI somewhat more problematic. It's easy to make a mistake that you can't actually fully undo.

**Comment by Null-Senpai** [comment]
Okay sorry, my bad, I thought that was part of standard mastodon.
For me, the undo has never worked (see attached file). I always assumed this to be due to 'it already being out there' (on other instances's servers), and thought the fact that you can unpress the button a bug or something.
If the protocol itself handles undo's badly, would that not be a reason _for_ having an optional confirmation dialog box, at least until mastodon itself handles undoing actions better?

[SCR_20170426_144637.zip](https://github.com/Vavassor/Tusky/files/958612/SCR_20170426_144637.zip)

**Comment by alerque** [comment]
@Null-Senpai Yes, not having good undo support baked into the protocol across instances would be an argument to make an option that adds friction to the action in the first place.

**Comment by charlag** [comment]
Same as #460
