### ISSUE TITLE
Allow opening of all attachments

### ISSUE THREAD

**Issue by tastytea** [tuskyapp/Tusky#1970]
Please allow me to open text files. Right now Tusky seems to handle text files like images.¹

Pleroma doesn't seem to do much in regards to mime type detection (text files are listed as “application/octet-stream”), but the HTTP header of the file contains a more useful `content-type`.

If you don't want to do a HEAD request, maybe the attachment could be opened in a browser, like a normal hyperlink?

Example status: <https://likeable.space/api/v1/statuses/A0W5dJuDC1feh2Lpho>

``` json
  "media_attachments": [
    {
      "description": "",
      "id": "-1638291662",
      "pleroma": {
        "mime_type": "application/octet-stream"
      },
      "preview_url": "https://likeable.space/media/b61f79ba4a6e70e99d04e2bd7eb68250b45278f0a564c79228c016f66f78cdb5.org",
      "remote_url": "https://likeable.space/media/b61f79ba4a6e70e99d04e2bd7eb68250b45278f0a564c79228c016f66f78cdb5.org",
      "text_url": "https://likeable.space/media/b61f79ba4a6e70e99d04e2bd7eb68250b45278f0a564c79228c016f66f78cdb5.org",
      "type": "unknown",
      "url": "https://likeable.space/media/b61f79ba4a6e70e99d04e2bd7eb68250b45278f0a564c79228c016f66f78cdb5.org"
    }
  ],
```

* * * *
- Tusky Version: 12.1
- Android Version: 7.1.2
- Android Device:
- Mastodon instance (if applicable): likeable.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

¹ ![Screenshot_20201025-113118](https://user-images.githubusercontent.com/3681516/97104635-ba92b300-16b5-11eb-80b2-778b13917897.png)

**Comment by a1batross** [comment]
It's not hard to implement. I already did that and users seems completely fine with that.

However, how it should be displayed in UI? Maybe instead of image view, display it in same way how music attachments are handled? Just instead of music drawable, something else would be shown, telling it's binary data.

**Comment by tastytea** [comment]
Maybe just as hyperlinks called “attachment *Number*.*Extension*”?
