### ISSUE TITLE
Mastodon cannot load on the Tusky application.

### ISSUE THREAD

**Issue by parkchanyeols** [tuskyapp/Tusky#1975]
@Gargron 
![Screenshot_2020-11-04-14-52-53-11](https://user-images.githubusercontent.com/73933692/98088463-0dd5e400-1eb4-11eb-8df8-a7ba01d90e89.png)

* * * *
- Tusky Version: 12.1
- Android Version: 7.1.1
- Android Device: oppo
- Mastodon instance (if applicable): why can't my mastodon account be loaded via the tusky application? is the server down? 

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Which instance are you using?

**Comment by Gargron** [comment]
This is likely neither a software nor an app issue. If a specific server is temporarily (or event permanently) unavailable there's nothing I can do for you.
