### ISSUE TITLE
[Feature Request] Digital wellbeing mode

### ISSUE THREAD

**Issue by garritfra** [tuskyapp/Tusky#1980]
In todays world, we're surrounded by social media noise that hurts our mental wellbeing. I'd like to have a mode that cuts down on this to focus purely on the aspect of interacting with others. This might include:

* Hide stars/boosts count on toots
* Disable "Someone stared/boosted your toot" notifications
* Disable follower/following count on profiles
* [Your Suggestion Here]

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by resynth1943** [comment]
Pinafore has a wellbeing mode, and it makes the screen grayscale. There are other options too:

![Screenshot_20201212-123645](https://user-images.githubusercontent.com/49915996/101984073-dc9cc080-3c76-11eb-87f6-2613ca7d6692.png)

I couldn't find the guidelines they reference here (it just links to https://humanetech.com).
