### ISSUE TITLE
No option to see replies to a post in the feed

### ISSUE THREAD

**Issue by vishoope** [tuskyapp/Tusky#1986]
One of the things that bothers me, is that I can't see post replies in my feed. Though, I can see them if I click on a post. I think it's would be nice to have an option to see post replies in my feed. The web version of Mastodon has the option where it is possible to switch the replies.

* * * *
- Tusky Version: 12.1
- Android Version: 10
- Android Device: Samsung Galaxy A71
- Mastodon instance (if applicable): թութ․հայ

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by vishoope** [comment]
Here's the screenshot of the features that are i'm looking for. The screenshot is taken on the firefox running the web version of Mastodon. I miss thes options in Tusky, so the app is mostly uncomfortable for me.

![reply](https://user-images.githubusercontent.com/31819785/99532995-97aaa480-29be-11eb-8708-0ff559ce853a.png)

**Comment by connyduck** [comment]
Tusky has these settings, they are a bit hidden in Preferences -> Tabs though
