### ISSUE TITLE
Tapping "authorize" in the web browser when logging in does nothing

### ISSUE THREAD

**Issue by grishka** [tuskyapp/Tusky#2004]
I enter the instance domain, then my web browser (Vivaldi 3.4.2066.108) opens, I log in, it asks me one more time if I want to authorize the app, I confirm and then nothing happens. The following line appears in the devtools console:

```
Navigation is unreachable: oauth2redirect://com.keylesspalace.tusky/?code=xxx
```

The system doesn't seem to be recognizing any URL handlers despite there [being one in the manifest](https://github.com/tuskyapp/Tusky/blob/3558d441a467e4aa4ad47bbe71b5d7c47ee8ccca/app/src/main/AndroidManifest.xml#L49):
![image](https://user-images.githubusercontent.com/1478258/100625751-f6184100-3335-11eb-9649-642254d570ad.png)

* * * *
- Tusky Version: 12.1
- Android Version: 11 (build RP1A.201105.002)
- Android Device: Google Pixel 4a
- Mastodon instance (if applicable): mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Try another browser please.

**Comment by grishka** [comment]
Okay, it worked in Firefox. I'll report this to Vivaldi then.
