### ISSUE TITLE
Please make your app movable to SD card.

### ISSUE THREAD

**Issue by fckwan** [tuskyapp/Tusky#2037]
[Issue text goes here].

* * * *
- Tusky Version: 13.1
- Android Version: 9
- Android Device: Samsung Galaxy S8+
- Mastodon instance (if applicable): noc.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

http://programmerguru.com/android-tutorial/how-to-create-android-app-with-movable-to-sd-card-feature/

Please follow the instruction in the above page to enable the android app to be movable to sd card.

**Comment by connyduck** [comment]
No. Installing Tusky on removeable storage will led to it not working reliably.
See https://developer.android.com/guide/topics/data/install-location#ShouldNot
