### ISSUE TITLE
Please Default to Camel Case Hashtags

### ISSUE THREAD

**Issue by DerekCaelin** [tuskyapp/Tusky#2038]
[Accessibility guidelines](https://www.boia.org/blog/make-your-hashtags-accessible) suggest that hashtags follow camel case (for example, "#DesignJustice") to allow for easier legibility and readability by screen readers. 

When typing a hashtag in Tusky, an autocorrect menu suggests a number of fully lowercase options, so that if the user selects one they are directed to a less accessible hashtag.

Please consider displaying camel case versions of hashtags.

* * * *
- Tusky Version: 13.1
- Android Version: 11
- Android Device: Pixel 3a
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
duplicate
