### ISSUE TITLE
During initial login, Tusky sometimes opens authentication window in external browser

### ISSUE THREAD

**Issue by sorenstoutner** [tuskyapp/Tusky#2040]
When starting Tusky for the first time and logging into an instance, if certain browsers are set as the default browser for the OS, Tusky opens them after selecting the instance instead of handling authentication within the app.  This results in the browser being logged into the instance instead of Tusky.

For example, if Privacy Browser is installed and set as the default browser this behavior is manifested.

https://f-droid.org/en/packages/com.stoutner.privacybrowser.standard/

However, if the default browser is set to be Chrome, while leaving Privacy Browser installed, this doesn't happen.

Without looking at the code, my guess is that, for some reason, after the instance is selected, an intent is called that, depending on the intent filters of the default browser, will launch it instead of handling the authentication within Tusky.  If such is the case, the solution would be to modify Tusky so that it does not use an intent that attempts to match against an external app.

* * * *
- Tusky Version:  13.1
- Android Version:   11
- Android Device:  Pixel 5
- Mastodon instance (if applicable):  fosstodon.org

- [ X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2371
