### ISSUE TITLE
(Bug) Can't set caption for a picture on a scheduled toot 

### ISSUE THREAD

**Issue by dwaynedtw** [tuskyapp/Tusky#2050]
When adding a picture to a scheduled toot, and trying to set a caption either it won't allow for the send button to be pressed or it will say "failed to set caption" 

* * * *
- Tusky Version: Tusky Test 13.1-5fbd459
- Android Version: 10
- Android Device: Galaxy S10e
- Mastodon instance (if applicable): mastadon.art

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I think this is a problem on Mastodon's side, see https://github.com/mastodon/mastodon/issues/17676

**Comment by connyduck** [comment]
Confirmed, and it is already fixed
