### ISSUE TITLE
[enhancement] toot copy to clipboard improvements

### ISSUE THREAD

**Issue by categorille** [tuskyapp/Tusky#2051]
# Toot copy to clipboard improvements
## Current behaviour
Currently, long-clicking a toot's content when in toot view (not in the timeline, but after having clicked a specific toot) instantly copies all of its text content to the system clipboard.

## Suggested enhanced behaviour
Long-clicking a toot's content when in toot view allows selecting portions of the text with the system text selecting handles. Additionally, an option in the "more" menu (three horizontal dots) of the toot view allows the user to copy the entirety of the text.

## Motivation
It may useful to select only certain words from a toot, for example in order to paste them in a dictionary if the toot is in another language, or to look them up online.

* * * *
- Tusky Version: 13.1
- Android Version: 7.0
- Android Device: Samsung Galaxy A5 2016 (SM-A510F)
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi, this is implemented now in detailed view
