### ISSUE TITLE
nightly #2032 crashing on drafts

### ISSUE THREAD

**Issue by jesopo** [tuskyapp/Tusky#2053]
I opened drafts, opened old drafts, clicked on an old draft, then pressed hardware back button on toot compose and selected "save" when asked if I wanted to save a draft.

any attempt to open drafts screen crashes

* * * *
- Tusky Version: nightly #2032 
- Android Version: 10
- Android Device: Huawei p20
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Anything special about that old draft? Media attached, poll, mention?
Is it the new or the old drafts screen crashing?

**Comment by jesopo** [comment]
nothing special, just text. it's the new draft screen that's crashing. are there logs i can pull from somewhere?

**Comment by connyduck** [comment]
No, I could just reproduce it. Thx!
