### ISSUE TITLE
[Enhancement] Download notification after file is downloaded

### ISSUE THREAD

**Issue by kitsunesensei** [tuskyapp/Tusky#2066]
When opening and trying to download some file, a notification with the text "filename.xx downloaded" pops up instantly, though the file hasn't been downloaded yet (because the file wasn't fully loaded yet, for example).

Bringing up the notification after the file has been downloaded for sure would improve the user experience and give more confidence in the process.

* * * *
- Tusky Version: 13.1
- Android Version: 10
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
@kitsunesensei hi, notification should only show up after downloading, does it still occur to you?

**Comment by kitsunesensei** [comment]
I've switched OS recently and can no longer test the behavior.
