### ISSUE TITLE
[Feature request] Ability to schedule boosts/re-toots

### ISSUE THREAD

**Issue by KopfKrieg** [tuskyapp/Tusky#2069]
It's possible to schedule toots, but I didn't find a way to schedule boosts/re-toots.

Could this be implemented? Use-case is similar to scheduled toots.

* * * *
- Tusky Version: 13.1
- Android Version: 10
- Android Device: Motorola G8+

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
No, I don't think this is supported by Mastodon
