### ISSUE TITLE
Stop posting if media upload failed

### ISSUE THREAD

**Issue by kyori19** [tuskyapp/Tusky#2078]
# Steps to reproduce

1. Type status content.
2. Attach some medias
3. Click toot button before upload finishes
4. Turn on and off airplain mode (or change network by turning Wi-Fi off, or any other ways causes error on upload) while upload dialog showing

# Actual behavior

Post appears without selected medias

# Expected (ideal?) behavior

Some error message should be shown

* * * *
- Tusky Version: 7a14296
- Android Version: 10
- Android Device: TIINO P710
- Mastodon instance (if applicable): odakyu.app

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
@kyori19 hi, does it still happen? I think it might have been fixed already

**Comment by kyori19** [comment]
@charlag I confirmed that this problem does not happen now.

**Comment by charlag** [comment]
Thank you!
