### ISSUE TITLE
Consider supporting Plemora

### ISSUE THREAD

**Issue by trymeouteh** [tuskyapp/Tusky#2086]
I know Husky exists but it has not had an update in seven months and may not be a supported app going forward. May be consider integrating Plemora support in Tusky and have Tusky be both for Mastodon and Plemora?

Husky source code
https://git.mentality.rip/FWGS/Husky

**Comment by a1batross** [comment]
I guess this is wrong place but anyway.

Husky isn't abandoned, I'm working on in my free time. Chats, status preview and other Pleroma stuff is in development.

You can check unstable versions at https://github.com/FWGS/Husky/releases

**Comment by alan-ford** [comment]
@a1batross I'm glad to hear that the project has not been abandoned. Please consider updating the board on Fdroid.

**Comment by charlag** [comment]
We do have minimal support, we do not have capacity for specific features at the moment.
