### ISSUE TITLE
Plural forms for translations?

### ISSUE THREAD

**Issue by gunchleoc** [tuskyapp/Tusky#2096]
I just started translating into Scottish Gaelic and I need correct fetching of plural forms. Does your system allow that?

* %d new interactions

My translation would look like this for different numbers:
```
2 eadar-ghabhail ùr
3 eadar-ghabhailean ùra
...
11 eadar-ghabhail ùr
...
```
ETA: Found 3 more strings that need plural markup:

- Describe for visually impaired\n(%d character limit)
- maximum of %1$d tabs reached
- You cannot upload more than %1$d media attachments.

Note that Slavic languages need plural forms for big numbers too, so all these strings will need it.

**Comment by connyduck** [comment]
Thx! I'll fix it, it will be visible in Weblate in a few days

**Comment by connyduck** [comment]
I don't think we need it for `Describe for visually impaired\n(%d character limit)` though? it will always be something large (>1000)

**Comment by gunchleoc** [comment]
> I don't think we need it for `Describe for visually impaired\n(%d character limit)` though? it will always be something large (>1000)

Yes we do, for Russian - c.f. the plural rules: https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#ru

**Comment by connyduck** [comment]
Oh wow, did not know that. Then I'll change it as well.
