### ISSUE TITLE
Option to disable swipe turned itself back on without consent

### ISSUE THREAD

**Issue by brion** [tuskyapp/Tusky#2102]
I turned off swipe gestures a year or so ago because they're unstable and cause undesired column switches. Today I found the swipes re-enabled but I have not touched the settings in months. Something changed my settings without my consent.  

* * * *
- Tusky Version: 14.0
- Android Version: 11
- Android Device: Pixel 5
- Mastodon instance (if applicable): mastodon.technology

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That is super weird.

The setting was introduced in this commit https://github.com/tuskyapp/Tusky/commit/f52fd355d8dd615310abd5195eba17299b25853a and later refactored here https://github.com/tuskyapp/Tusky/commit/f52fd355d8dd615310abd5195eba17299b25853a. I can't find any other changes to it and its identifier always was `enableSwipeForTabs`. 
The code is definitely fine.

What language do you use Tusky with?

**Comment by brion** [comment]
Language would be en-US.

**Comment by brion** [comment]
Note that I originally installed Tusky on a Pixel 2 and transferred apps and data to the Pixel 5 a few months ago. I don't have any recollection of having any swipe problems in the last few months, though, I just noticed it last night and then switched it back off.

**Comment by brion** [comment]
(It's conceivable that none of the settings transferred, it reinitalized with swipes on, and I didn't notice until yesterday. But that seems weird if so; the swipe gestures are so troublesome it makes the app very hard to use so I expect I would have noticed it during months of regular usage.)

**Comment by connyduck** [comment]
Ok, I can also rule out a bug in the translation if you use the default one.
It is most likely due to the transfer.

**Comment by brion** [comment]
Thanks for checking! Hopefully a transfer related one off issue :)
