### ISSUE TITLE
Muting Gives Error

### ISSUE THREAD

**Issue by Simmonz** [tuskyapp/Tusky#2107]
When I try to mute any user in Tusky it says "An error occured". It doesn't give any more info. It has been happening the last few days, I think since I have installed version 14.0. I tried muting people when logged into Mastodon via web browser and it works there.

* * * *
- Tusky Version: 14.0
- Android Version: 10.0
- Android Device: Teracube 2e
- Mastodon instance (if applicable): Fosstodon.org

- [ yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
It is a Mastodon bug. https://github.com/tootsuite/mastodon/pull/15516
New Mastodon release comes soon I hope.
