### ISSUE TITLE
Notifications don't appear in Web interface when using Tusky

### ISSUE THREAD

**Issue by kuba-orlik** [tuskyapp/Tusky#2118]
As long as I have Tusky authorized with a Mastodon account, that account does not receive notifications on the web interface. The notifications are there, but they are all marked as read, so the bell icon does not have a number next to it, even though there are notifications that I haven't yet seen.

It seems that Tusky marks notifications as read while downloading them, not only when actually viewing them in the app

* * * *
- Tusky Version: 14.0
- Android Version: 8.1.0
- Android Device: LG Nexus 5X

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Weird. We fetch notification markers so we don't show notifications that were already viewed on the web, but we do not write anything. (@charlag please confirm?)
Which Mastodon server are we talking about?

**Comment by kuba-orlik** [comment]
It was happening to me both on my private instance (toot.kuba-orlik.name, as well as on 101010.pl)

**Comment by charlag** [comment]
We maybe mark as read but we don't clear them for you.

**Comment by kuba-orlik** [comment]
I've just tested on a new phone (Android 11) and this issue doesn't affect me anymore. Not sure if that's a matter of Android version or what, but it seems that noone else is affected by this now, so I'm closing the issue for now :)
