### ISSUE TITLE
Tusky not available on Google Play

### ISSUE THREAD

**Issue by mibzman** [tuskyapp/Tusky#2120]
When I try and open the [Google play link](https://play.google.com/store/apps/details?id=com.keylesspalace.tusky&utm_source=github&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1), I get an error that says "We're sorry, the requested URL was not found on this server." 

Is the link in the Readme old? Or has the app been removed recently? The nightly version is still visible. 

* * * *
- Tusky Version: N/A
- Android Version:N/A
- Android Device:N/A
- Mastodon instance (if applicable):N/A

- [✅] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes, the app has been removed by Google. 😱 
 Thanks for notifying me

**Comment by connyduck** [comment]
it is back
