### ISSUE TITLE
[Feature Request] Show parent toot of replies that appear in a timeline

### ISSUE THREAD

**Issue by kolgza** [tuskyapp/Tusky#2128]
On Twitter, replies in a timeline include the parent tweet in the thread that the reply is for (see below).

![image](https://user-images.githubusercontent.com/46303203/113736102-d2da1580-96ca-11eb-93f7-46cf35af5bf1.png)

In Tusky, this is not the case. Replies appear in timelines with any context (see below).
![signal-2021-04-06-104957_001](https://user-images.githubusercontent.com/46303203/113736589-3b28f700-96cb-11eb-89ad-c18007e824c2.png)

[(For added clarity, here is the link to the parent toot.)](https://skull.website/@Laser/106015445830185637)

It would be nice if Twitter's behavior were replicated. 

* * * *
- Tusky Version: `14.0`
- Android Version: `10`
- Android Device: `Essential PH-1`

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kolgza** [comment]
Here is a screenshot from [Halcyon](https://www.halcyon.social), which has this feature.

![image](https://user-images.githubusercontent.com/46303203/114067386-c391ce00-986a-11eb-8b2c-1ecdd73dc328.png)

**Comment by kolgza** [comment]
Here is a screenshot a timeline from [Halcyon](https://www.halcyon.social), which has this feature.

![image](https://user-images.githubusercontent.com/46303203/114068148-97c31800-986b-11eb-9646-118a0e6245d0.png)

**Comment by charlag** [comment]
@kolgza Mastodon doesn't have it. Halcyon does but they explicitly want to copy Twitter. Without server support we need to do a lot of requests.
Is there some criteria when it is shown?

**Comment by kolgza** [comment]
I don't really know, to be honest. I've approached this issue from the perspective of what I, as a user, wanted to see.

**Comment by charlag** [comment]
Unless Mastodon API provides us with some other data in home timeline we can't implement in in an efficient way.
