### ISSUE TITLE
Move translations to a dedicated utility

### ISSUE THREAD

**Issue by alerque** [tuskyapp/Tusky#213]
Managing translations by hand is doable for now (e.g. #212) but it's quickly going to get out of hand. We should figure out  what translation management service works best for such open source projects and migrate the actual translations process there. Besides saving a lot of work and mess this will also make it easier for non developers to contribute.

**Comment by alerque** [comment]
Possibilities include

* [Transifex](https://www.transifex.com/) (proprietary platform, <strike>but free for OSS projects</strike>)
* [Weblate](https://weblate.org/) (offers free hosted version of tools to OSS projects)
* [Zanata](http://zanata.org/)

**Comment by Vavassor** [comment]
The translator who contributed the arabic translation used transiflex. https://www.transifex.com/opendz/tusky-in-arabic/

I know [Crowdin](https://crowdin.com) and [POEditor](https://poeditor.com) (both proprietary) also have free applications for open source projects.

**Comment by alerque** [comment]
For reference here is the [upstream issue](https://github.com/tootsuite/mastodon/issues/1241). It would probably make sense to use the same platform for translation as Mastodon itself, especially if that platform supports cross-project translation suggestions.

**Comment by thor-the-norseman** [comment]
As a translator, I've been very tempted to implement some kind of 3-way merge tool for language files. It would:
- Compare the strings in the new English language files (from the Mastodon release you want to translate) to the old ones (the release that was previously translated)
- Check for CHANGED strings in the English language files, SUFFIX the equivalent strings in the other language files with `_OLD` and INSERT the changed English strings right below those.
- Check for explicitly REMOVED strings in the English language files and REMOVE them from the other language files. Strings that were never mentioned in the English language files to begin with should NOT be removed from the other language files. Because the Mastodon developer(s) tend to provide hardcoded English default values for strings anyway, they often miss strings that need entries in the English language files.
- Check for INSERTED strings in the English language files and INSERT them into the other language files in appropriate positions.
- The final order of strings in the local language files should always be made to match that of the English language files.
- The tool could also conform the formatting of all language files, if this is desired.

**Comment by alerque** [comment]
@thor-the-norseman That's all great stuff, but isn't this workflow already pretty established and implemented by extant tools we could just adopt. This sounds a bit like re-inventing the wheel to me. Tusky doesn't seem to have any particular needs that other apps haven't already had to contend with.

**Comment by thor-the-norseman** [comment]
@alerque I just edited my comment. There's a bit about workflow there too now.

**Comment by thor-the-norseman** [comment]
@alerque I'm stating what I would implement, knowing nothing of the YAML/JSX translation tools out there. Heck, I don't even know if YAML and JSX are common formats for language files, or if they're just something Eugen rolled on his own.

**Comment by thor-the-norseman** [comment]
The system looks kind of home-cooked to me. My locale has the ISO code `nb_NO` and I'd expect a proper locale system to use those, for example. The English translation is in American English, so it should be `en_US`. JSX files are executable code (not sure why they aren't JSON files instead) and shouldn't really be used for translation files.

**Comment by thor-the-norseman** [comment]
The language names are also hard-coded in multiple places in the source and the JSX files are included directly into it. As other translators have remarked on other issues, the system isn't a particularly good fit for common translation tools. There are two paths to take here, in other words:

1. Change the entire locale system and make it compatible with the more common translation tools
2. Implement and roll out the merge tool I described above, or some other solution that can work with the existing language file formats.

Solution 1 is nicer, but is probably more labor intensive for the developers than solution 2.

**Comment by Vavassor** [comment]
@thor-the-norseman This is all good, but these comments should be in the Mastodon issue. They're not really relevant here for Tusky.

**Comment by BoFFire** [comment]
Hi,
Yep I used Transifex in a hurry to translate some Tusky strings to arabic but I prefer Weblate.
OSMAnd is using Weblate : https://translate.osmand.net/
Check the commits here for example comming from Weblate : https://github.com/osmandapp/Osmand/commits/master
Yunohost is using Weblate : https://translate.yunohost.org/projects/yunohost/

**Comment by ahangarha** [comment]
Any update on this issue? I prefer weblate since it is itself a Free Software project.

I want to improve Persian translation. Should I edit the file directly or use some service?

**Comment by charlag** [comment]
One one is actively working on this. If there's a champion, we would be glad to accept some help on this.
I'm okay with anything, maybe @connyduck can say about his preferences

**Comment by ahangarha** [comment]
So, should I edit files manually?

**Comment by charlag** [comment]
Feel free to do so. Some people use Stringlate.


23 Dec 2018, 14:50 by notifications@github.com:

**Comment by charlag** [comment]
We use Crowdin now.

**Comment by ahangarha** [comment]
May I know what made you choose Crowdin over Weblate?

**Comment by charlag** [comment]
Honestly I'm not sure, according to @connyduck 
> yes its similar to weblate, you can edit translations without having to touch xml files or git
> also it gives you fancy recommendations
> some translators wanted to have it

**Comment by ahangarha** [comment]
I wish we would use something FOSSy for translation of a FOSSy application.

Anyway, all the bests

**Comment by connyduck** [comment]
Yes Weblate is FOSS, but it doesn't host itself. Host it for us and we can use it.

**Comment by ahangarha** [comment]
This is their website: https://weblate.org/en/

You may have problem with pricing (they are open to negotiation for free software projects) or features. But there are already many free software projects hosted there for translation.

By the way, I don't have any affiliation with them :)

**Comment by ahangarha** [comment]
I cannot find Tusky page on crowdin

![image](https://user-images.githubusercontent.com/11241315/65899071-d008b100-e3bf-11e9-81e8-b992bf23e9e6.png)

**Comment by connyduck** [comment]
https://weblate.tusky.app

**Comment by ahangarha** [comment]
This is great
Please share it on readme.md. should I send PR?

**Comment by prashantkodali** [comment]
Hello, how can a new language be added in weblate?

**Comment by connyduck** [comment]
I think there is a button to request it somewhere and we will get notified. Or you can just tell me here which one I should add.

**Comment by prashantkodali** [comment]
Punjabi (pa) and Telugu (te). i tried adding new languages but I didnt have the permissions.

**Comment by connyduck** [comment]
@prashantkodali I added them!
