### ISSUE TITLE
implement login via app

### ISSUE THREAD

**Issue by dioraman** [tuskyapp/Tusky#2134]
I have the same problem as https://github.com/tuskyapp/Tusky/issues/1609 . As per https://github.com/tuskyapp/Tusky/issues/1609#issuecomment-571240178 , implementing login via app would be much appreciated. Hence, I open the current issue with due title.
**EDIT:** if the default browser is not supported, one shall remove the default behavior, then login, then restore the default browser. Newcomers will think the app does not work.

* * * *
- Tusky Version: 14.0
- Android Version: 10QKQ1.191215.002
- [yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- Suggested labels: priority-medium, bug, refactoring, accessibility, privacy

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2371
