### ISSUE TITLE
Fetch full thread

### ISSUE THREAD

**Issue by davidoskky** [tuskyapp/Tusky#2137]
I'd like to have the possibility to read the whole thread.
Replies from people who are not federated with my instance are not registered by my instance and thus not shown in the thread.
With the web interface I can open the instance of the original toot to read all the replies.

Would it be possible to fetch the replies to a particular toot from the original instance in order to read the full thread?

* * * *
- Tusky Version: 14.0
- Android Version: 10
- Android Device: Xiaomi Redmi 7
- Mastodon instance (if applicable): mastodon.uno

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Mastodon already has mechanisms for fetching the whole thread. It is the job of the server to do it. You can still click menu and open the original thread in browser if you wish to do so.
