### ISSUE TITLE
Setup CI server

### ISSUE THREAD

**Issue by alerque** [tuskyapp/Tusky#214]
Some sort of continuous integration server should be setup on this repository checking PR's and making sure everything builds. This would make it a lot easier to review and test contributions as well as give non-developers a way to run test builds.

I've done this with Travis and with Gitlab's CI runner, but never for building Android apps so I'm not sure what the best choice would be. Anybody have experience with this?

**Comment by SkyzohKey** [comment]
You basically avec to install Tusky dependencies and then launch something like `./gradlew run -x build -x parallel` I guess. Feel free to check how does the others Android apps (ie. Antox/Antox)

**Comment by connyduck** [comment]
I set up bitrise for this repository
