### ISSUE TITLE
[feature] add Idempotency Key

### ISSUE THREAD

**Issue by BenLubar** [tuskyapp/Tusky#2152]
This would prevent duplicate statuses in the case of server slowness or other situations that cause Tusky to retry making a post.

1. Generate a random string (for example, a UUID) for a post that is about to be created.
2. Set the `Idempotency-Key` HTTP header to this random string when creating the post.
3. If the post request needs to be retried for any reason, use the *same* `Idempotency-Key` header.

**Comment by connyduck** [comment]
we already do that
https://github.com/tuskyapp/Tusky/blob/886ff2f06b69e67ca459e02d0633f4d69c5b21da/app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt#L130

**Comment by BenLubar** [comment]
It looks like the idempotency key might be generated per send request rather than per composed toot.

So if someone presses the send button multiple times, they get multiple idempotency keys.

**Comment by connyduck** [comment]
You can't press the send button multiple times
