### ISSUE TITLE
Left hander scrolling without switching columns

### ISSUE THREAD

**Issue by spate** [tuskyapp/Tusky#2176]
Scrolling down the feed on a tablet with one's right thumb registers as diagonal, which causes the app to switch to the alerts column. 

* * * *
- Tusky Version: 14.0
- Android Version: 9
- Android Device: Samsung SM-T380
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
You can disable swiping to switch tabs in the Preferences

**Comment by spate** [comment]
I like swiping; I'm interested in a higher threshold for moving left and right, like Twitter has.

**Comment by connyduck** [comment]
then this is a duplicate of https://github.com/tuskyapp/Tusky/issues/2112

**Comment by spate** [comment]
Thanks, I'll follow that one. Sorry for the dupe.
