### ISSUE TITLE
cosmetic: Make "LOAD MORE" button more visible

### ISSUE THREAD

**Issue by pespin** [tuskyapp/Tusky#2177]
99% of the time when reading toots top to bottom (newer to older toots) in my timeline I am unable to realize I passed through the "LOAD MORE" button until a while after when I realize I am looking at toots far older and I have to scroll back up to find the button. That means, I pass the "LOAD MORE" button unnoticed and hence I don't press on it, meaning I loose content while for instance following news feeds.

It's really annoying because I have to really focus on actively looking for the "LOAD MORE" section while scrolling down and reading toots.

The main problem imho is that current UI is not making that "LOAD MORE" section colorful or shiny enough so that it's really easy to lose it while scrolling. Some ideas on how to improve it:
* Use bolder text, probably in red color?
* Make the frame around LOAD MORE larger, so that the empty gap in between news becomes larger and hence more difficult to pass by unnoticed.

* * * *
- Tusky Version: 15.0

- [ X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
@mibzman it is the place indeed but I would suggest to propose a design change first, that's probably the hardest part and only then implement it

**Comment by mibzman** [comment]
@charlag this just occurred to me today, what if the background the same color as the main navigation bar, and the text the same color as the action icons?

That to me would indicate a system-level thing to do, not content.

**Comment by charlag** [comment]
@connyduck what do you think about this issue? I think it's indeed a bit easy to miss at the moment

**Comment by mmahmoudian** [comment]
How about a style to show that the timeline is "cut" mid way? Somehow show that the flow is disconnected. For instance in toot! app they have used some zigzag to illustrate that the roll of paper is torn at this point. 

Alternatively you can add some minor shadow as if this LOAD MORE box is embossed.

Also making the box longer would help
