### ISSUE TITLE
[bug]: Compose view crashes when attempting to add image alt text

### ISSUE THREAD

**Issue by jeyemwey** [tuskyapp/Tusky#2184]
The compose screen crashes when I attempt to add an image description (alt text) to an uploaded image.

To reproduce:
1. Open Tusky
2. Create a new toot
3. Add an image and upload it to the server
4. Add a description

The description prompt will open briefly, then the compose dialog will close without creating a draft. You are back on the home timeline view.

Expected behavior: Don't crash, show the image description prompt like before.

* * * *
- Tusky Version: 15.0
- Android Version: 11
- Android Device: Google Pixel 4a 5G
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
#2165
