### ISSUE TITLE
(Bug) Not able to see pictures

### ISSUE THREAD

**Issue by Thewisem** [tuskyapp/Tusky#2192]
[Issue text goes here].
I cannot see any pictures on my instance. Evenrything is blurred out and I can't even load them.
* * * *
- Tusky Version: 15.1
- Android Version: 7.1.1 Nougat
- Android Device: Samsung Galaxy Tab A SM P555
- Mastodon instance (if applicable): fosstodon

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Works with my fosstodon account 🤔 

Do they load in your browser? Have you checked a different internet connection? Are you using the proxy feature in Tusky?

**Comment by Thewisem** [comment]
No. Not the proxy feature.

**Comment by Thewisem** [comment]
Ok they do not load on my browser

**Comment by Thewisem** [comment]
Ok some of them do

**Comment by Thewisem** [comment]
Ok I see that using a vpn fixes this? Didn't have to use until now

**Comment by connyduck** [comment]
Sounds like there is some networking issue on your end and not a bug in Tusky
