### ISSUE TITLE
[Feature request] Data saving options

### ISSUE THREAD

**Issue by rBok6** [tuskyapp/Tusky#2195]
Can you add an settings option to save cellular data, like compressing images, turning off auto play videos, how many tooths to load on the time-line. Also on images there should be a "load full quantity image" just like Twitter does when data saving is activated. 

* * * *
- Tusky Version: 15.1
- Android Version: 9
- Android Device: Alcatel 1S 
- Mastodon instance (if applicable):

- [✔️ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey
We already have most of that, directly or not? e.g. you can disable loading of images. We don't have autoplay. We load full quality image when you open it fullscreen so we could make it notbload full version automatically.

**Comment by charlag** [comment]
@rBok6 is there anything else we should add? I don't think it's worth changing how many statuses are loaded at once, it's already not a big number

**Comment by rBok6** [comment]
> @rBok6 is there anything else we should add? I don't think it's worth changing how many statuses are loaded at once, it's already not a big number

Alright then. What about selecting the quality of videos? Like 480, 720, etc?

**Comment by charlag** [comment]
@rBok6 I don't think Mastodon keeps videos in multiple qualities. I don't recall any other social network do it either.

**Comment by rBok6** [comment]
> @rBok6 I don't think Mastodon keeps videos in multiple qualities. I don't recall any other social network do it either.

Facebook does it on its full version, not on the lite one though. But anyways, it seems Mastodon has many limitations in that regard. Maybe try implementing the ones that are more plausible. That would be it, thanks for everything.
