### ISSUE TITLE
Blocking of Instances

### ISSUE THREAD

**Issue by lisbonjoker** [tuskyapp/Tusky#2224]
Isn't the denying access of users a breach of the GPL3 License? I saw that spinster.xyz is blocked and there has been requests to block more https://github.com/tuskyapp/Tusky/pull/2223? Isn't this limiting users freedom?

**Comment by lisbonjoker** [comment]
Good argument was also made here, https://github.com/tuskyapp/Tusky/pull/1303#issuecomment-498012164

**Comment by charlag** [comment]
No it is not

**Comment by lisbonjoker** [comment]
Still seems a bit of a break in trust as implied by https://github.com/tuskyapp/Tusky/pull/1303#issuecomment-498012164. The blocking should be made by the user, not the client.
