### ISSUE TITLE
Picture is shown with collapsed CW

### ISSUE THREAD

**Issue by tastytea** [tuskyapp/Tusky#2227]
The picture in [this post](https://likeable.space/notice/A9Y9fTeYpFNhAeL808) is shown with collapsed CW in Tusky. The media is not marked as sensitive but I think that shouldn't matter for CW-ed posts.

I've also noticed that for pictures marked as sensitive there  are placeholders shown. Why not hide them too, like the text?

![screenshot_2021-07-22T16:45:14](https://user-images.githubusercontent.com/3681516/126659034-3b482ad4-b006-4e44-b488-3d461ceb69ad.png)
![Screenshot_20210722-164158](https://user-images.githubusercontent.com/3681516/126659064-02a26387-79e0-4577-bb76-1a8613de32af.png)

* * * *
- Tusky Version: 15.1
- Android Version: 7.1
- Android Device: Motorola Moto G 2014 LTE
- Mastodon instance (if applicable): likeable.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I think we are matching what Mastodon is doing. If there's media, it will show it, CW or not. But if you add CW post is always marked sensitive so it will be behind the blurhash.

**Comment by connyduck** [comment]
Yes, exactly what Mastodon is doing. I think its fine.

**Comment by tastytea** [comment]
> we are matching what Mastodon is doing.

Mastodon is doing it wrong.

> But if you add CW post is always marked sensitive so it will be behind the blurhash.

In Pleroma you have to explicitly set it to sensitive, even with CW.
