### ISSUE TITLE
Replacing twitter with nitter links

### ISSUE THREAD

**Issue by modelmat** [tuskyapp/Tusky#2234]
In the vein of https://github.com/mastodon/mastodon/issues/12145, it would be great if it were possible to replace URLs to twitter with a nitter (or similar) link, when viewing through Tusky.

Perhaps this could be enabled (off by default) in settings.

This would help a bit, especially as Twitter's mobile experience really nags me to sign in every time I click a post.

**Comment by connyduck** [comment]
You can use an app like UntrackMe if you want this feature. It works great with Tusky.
https://fedilab.app/wiki/untrackme/
