### ISSUE TITLE
"Scheduled toot" not working

### ISSUE THREAD

**Issue by KopfKrieg** [tuskyapp/Tusky#2235]
I'm trying to use the "scheduled toot" feature, but unfortunately, it's not working as expected. I can create a toot, set a date and a time, but the toot will never be made public. Even way past the date and time I set before, nothing will happen.

* * * *
- Tusky Version: 15.1 (F-Droid)
- Android Version: 10
- Android Device: Motorola G8+
- Mastodon instance (if applicable): https://troet.cafe/

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
hi, sorry for the late response, I think this is a server issue
