### ISSUE TITLE
Notifications tab crashes on status `null`?

### ISSUE THREAD

**Issue by janboddez** [tuskyapp/Tusky#2252]
Had this happen a few times, and I'm fairly sure the object below is what triggers the latest occurrence (the web app seems to display it fine, Tusky just crashes):
```
{
	"3": {
		"id": "1139",
		"type": "poll",
		"created_at": "2021-10-02T09:16:03.213Z",
		"account": {
			"id": "7178",
			"username": "brainblasted",
			"acct": "brainblasted@social.libre.fi",
			"display_name": "Chris",
			"locked": true,
			"bot": false,
			"discoverable": false,
			"group": false,
			"created_at": "2020-02-28T00:00:00.000Z",
			"note": "Admin of social.libre.fi. GNOME developer.<br>DMs from mutuals are okay, and boosts are okay for all public posts.<br><br>Blank profiles and FOSS-only profiles will be rejected.<br><br><a class=\"hashtag\" href=\"https://social.libre.fi/tag/actuallyautistic\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">#actuallyautistic</a>",
			"url": "https://social.libre.fi/users/brainblasted",
			"avatar": "https://media.geekcompass.com/geekcompass/cache/accounts/avatars/000/007/178/original/aaf07701b4726dcb.png",
			"avatar_static": "https://media.geekcompass.com/geekcompass/cache/accounts/avatars/000/007/178/original/aaf07701b4726dcb.png",
			"header": "https://media.geekcompass.com/geekcompass/accounts/headers/000/007/178/original/712f28da941cf933.jpeg",
			"header_static": "https://media.geekcompass.com/geekcompass/accounts/headers/000/007/178/original/712f28da941cf933.jpeg",
			"followers_count": 1685,
			"following_count": 643,
			"statuses_count": 90,
			"last_status_at": "2021-10-04",
			"emojis": [],
			"fields": [
				{
					"name": "Patreon",
					"value": "<a href=\"https://www.patreon.com/chrisgnome\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">https://www.patreon.com/chrisgnome</a>",
					"verified_at": null
				},
				{
					"name": "Pronouns",
					"value": "he/him/his or they/them/theirs",
					"verified_at": null
				},
				{
					"name": "GitHub Sponsors",
					"value": "<a href=\"https://github.com/sponsors/BrainBlasted\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">https://github.com/sponsors/BrainBlasted</a>",
					"verified_at": null
				}
			]
		},
		"status": null
	}
}
```
The poll is still online, too (like, no longer active, but not deleted either). Makes me wonder if this is really a server issue. (Regardless, it "works" in the web app. That is, it doesn't display much at all, beyond "A poll has ended," likely because there isn't much here, but it doesn't crash either.)
* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device:
- Mastodon instance (if applicable): geekcompass.com (Mastodon v3.4.1), though the originating instance (see above) seems to be Pleroma

- [x] ~~I searched or browsed the repo’s other issues to ensure this is not a duplicate.~~ Not sure if duplicate or not, to be honest, but decided to submit a new issue after our little chat on Mastodon.

**Comment by connyduck** [comment]
Can you please post a screenshot how the webapp displays it? Does it just say "a poll has ended" without telling you which one?

**Comment by janboddez** [comment]
Yes, exactly. It doesn't even properly display a divider/`hr`/`border-bottom` below.

![afbeelding](https://user-images.githubusercontent.com/8428432/136197478-4264b640-3f3e-401a-9f96-1a633b982928.png)

**Comment by ariasuni** [comment]
Maybe something similar to https://github.com/tuskyapp/Tusky/issues/1578?
