### ISSUE TITLE
clicking between tabs causes a refresh

### ISSUE THREAD

**Issue by protodrew** [tuskyapp/Tusky#2261]
When clicking or swiping from something like the notifications tab to the home tab, it sends you to the top rather than preserving position. 

* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: galaxy s20 ultra

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi, is it still a thing? I only does send you to the top if you are already in that tab

**Comment by protodrew** [comment]
This seems to have been fixed in an update along the way.
