### ISSUE TITLE
Unable to boost followers-only toots to followers

### ISSUE THREAD

**Issue by viv-milcom** [tuskyapp/Tusky#2263]
Create a followers only toot. The boost button is disabled. This button is available for the toot to be boosted to the same audience in the Mastodon Web Interface.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
The option "boost to original audience" is available from the three-dot-menu on every followers-only status.
