### ISSUE TITLE
Unable to set open by default when clicking links

### ISSUE THREAD

**Issue by DraginEye** [tuskyapp/Tusky#2264]
[Issue text goes here].

* * * *
- Tusky Version:15.1
- Android Version:11
- Android Device:OnePlus 9 pro 5g
- Mastodon instance (if applicable):
Baraag

![Screenshot_20211031-172732](https://user-images.githubusercontent.com/93495126/139604854-0881513d-a637-4bd5-80ce-e700feb20142.jpg)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by DraginEye** [comment]
I forgot to edit the issue text, but the issue is in the title

**Comment by mal0ki** [comment]
I think the biggest problem with this is that there's so many different servers, and not necessarily any good indicator that it's mastodon/pleroma? Unless there's new things in the API that could help now?

 I think we've been thinking about it in the past, and not found a good solution. 

Correct me if I'm wrong @connyduck @charlag  ?

**Comment by connyduck** [comment]
Yes. Adding a list of all known servers is unfeasible, offering to open all links bad user experience when you accidentally open non-Mastodon links. It would be cool if we could offer the feature only to users who opt in & know what they are doing but I'm not sure if that is possible.

**Comment by DraginEye** [comment]
Make like a toggleable option with a massive warning that screams, "If you don't know what you're doing back away, enabling this setting may brick your application if not used properly" something like that?

**Comment by mal0ki** [comment]
I kind of just wish there could be some kind of api point that would help :shrug: I don't know how this stuff works.

**Comment by DraginEye** [comment]
Then it looks like I'll be switching to an app that actually does have this functionality, but thank you for trying
