### ISSUE TITLE
pixelfed: Images display as attachments only

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#2269]
A few weeks earlier, pixelfed images started to appear just as attachments within tusky (title and paperclip icon, no image preview). Most likely this is due to some change in pixelfed API. Is it possible to fix this?

* * * *
- Tusky Version: 15.1 and 15.1-b62ccd91
- Android Version: 11
- Android Device: Samsung 
- Mastodon instance (if applicable): pixelfed.social 

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Ok, I tried two instances, pixelfed.social seems to work, pixelfed.de returns media types `Image` (instead of `image`). We can fix this in Tusky, but it seems like a problem in pixelfed that is already fixed?

@dansup what do you think about this?

**Comment by kr428** [comment]
Just checked, seems to work with recent version (16.x) on pixelfed.social so I am fine here. Thanks for checking though. :)

**Comment by dansup** [comment]
@connyduck This is a bug in Pixelfed, we return the type `Image` instead of `image`. I'm working on a fix, and I opened an issue on my side! 

https://github.com/pixelfed/pixelfed/issues/3281

**Comment by connyduck** [comment]
Thx!
