### ISSUE TITLE
Error displaying poll that ends in the 119th century

### ISSUE THREAD

**Issue by codl** [tuskyapp/Tusky#2272]
The post in question: https://hellsite.site/@goat/107343819401163044
<details>
<summary>JSON as returned from chitter.xyz</summary>
<pre>
{
  "id": "107343819647393796",
  "created_at": "2021-11-26T14:24:57.000Z",
  "in_reply_to_id": null,
  "in_reply_to_account_id": null,
  "sensitive": false,
  "spoiler_text": "",
  "visibility": "public",
  "language": "en",
  "uri": "https://hellsite.site/users/goat/statuses/107343819401163044",
  "url": "https://hellsite.site/@goat/107343819401163044",
  "replies_count": 0,
  "reblogs_count": 0,
  "favourites_count": 0,
  "favourited": false,
  "reblogged": false,
  "muted": false,
  "bookmarked": false,
  "content": "<p>:blank:​</p>",
  "reblog": null,
  "account": {
    "id": "86933",
    "username": "goat",
    "acct": "goat@hellsite.site",
    "display_name": "Goat",
    "locked": false,
    "bot": false,
    "discoverable": false,
    "group": false,
    "created_at": "2019-03-04T11:18:22.942Z",
    "note": "<p>Admin of hellsite.site<br>Instance Necromancer and Scourge of The Fediverse <br>Tentatively Immortal, Possibly Divine<br>Sometimes a Kobold, Sometimes a Goat</p>",
    "url": "https://hellsite.site/@goat",
    "avatar": "https://media.chitter.xyz/cache/accounts/avatars/000/086/933/original/f3ff55bcdd4ef061.png",
    "avatar_static": "https://media.chitter.xyz/cache/accounts/avatars/000/086/933/original/f3ff55bcdd4ef061.png",
    "header": "https://media.chitter.xyz/cache/accounts/headers/000/086/933/original/325e8256230b060d.jpeg",
    "header_static": "https://media.chitter.xyz/cache/accounts/headers/000/086/933/original/325e8256230b060d.jpeg",
    "followers_count": 1121,
    "following_count": 1030,
    "statuses_count": 1007279,
    "last_status_at": "2021-11-26",
    "emojis": [],
    "fields": [
      {
        "name": "Pronouns",
        "value": "She/Her",
        "verified_at": null
      },
      {
        "name": "Discord",
        "value": "🐐🐐🐐#1383",
        "verified_at": null
      },
      {
        "name": "LastFM",
        "value": "<a href=\"https://www.last.fm/user/goatofhellsite\" rel=\"nofollow noopener noreferrer\" target=\"_blank\"><span class=\"invisible\">https://www.</span><span class=\"\">last.fm/user/goatofhellsite</span><span class=\"invisible\"></span></a>",
        "verified_at": null
      }
    ]
  },
  "media_attachments": [],
  "mentions": [],
  "tags": [],
  "emojis": [
    {
      "shortcode": "blank",
      "url": "https://media.chitter.xyz/cache/custom_emojis/images/000/053/066/original/d5ccbc427992e18a.png",
      "static_url": "https://media.chitter.xyz/cache/custom_emojis/images/000/053/066/static/d5ccbc427992e18a.png",
      "visible_in_picker": true
    }
  ],
  "card": null,
  "poll": {
    "id": "59024",
    "expires_at": "11878-05-15T14:24:57.000Z",
    "expired": false,
    "multiple": true,
    "votes_count": 9,
    "voters_count": 9,
    "voted": false,
    "own_votes": [],
    "options": [
      {
        "title": ":blank:​",
        "votes_count": 8
      },
      {
        "title": ":blank:​",
        "votes_count": 1
      },
      {
        "title": ":blank:​",
        "votes_count": 0
      },
      {
        "title": ":blank:​",
        "votes_count": 0
      }
    ],
    "emojis": [
      {
        "shortcode": "blank",
        "url": "https://media.chitter.xyz/cache/custom_emojis/images/000/053/066/original/d5ccbc427992e18a.png",
        "static_url": "https://media.chitter.xyz/cache/custom_emojis/images/000/053/066/static/d5ccbc427992e18a.png",
        "visible_in_picker": true
      }
    ]
  }
}

</pre>
</details>

The post caused the federated timeline to show "An error occured" when it was on the first page of it, Goat's profile also shows the same error at the moment, pasting the URL into search says "Failed to search", and if I favourite or bookmark the post on the web, the favourite and bookmarks screens then error out on Tusky.

I suspect this has to do with the attached poll being set to end nearly 10,000 years from now, in a five-digit year, which breaks the ISO 8601 datetime format. The Mastodon web UI also has trouble with it, but deals with it more gracefully, only saying "Ending in NaN".

* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: Poco X3 NFC
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by codl** [comment]
Here's another one since the original post is gone: https://hellsite.site/@goat/107846769337798404

<details>
<summary>JSON</summary>
<pre>
{
  "id": "107846770177946180",
  "created_at": "2022-02-23T10:11:44.000Z",
  "in_reply_to_id": null,
  "in_reply_to_account_id": null,
  "sensitive": false,
  "spoiler_text": "",
  "visibility": "public",
  "language": "en",
  "uri": "https://hellsite.site/users/goat/statuses/107846769337798404",
  "url": "https://hellsite.site/@goat/107846769337798404",
  "replies_count": 1,
  "reblogs_count": 2,
  "favourites_count": 0,
  "content": "<p>HERE IS A TEST. TEST TEST TEST</p>",
  "reblog": null,
  "account": {
    "id": "86933",
    "username": "goat",
    "acct": "goat@hellsite.site",
    "display_name": "Dungeon Goatse",
    "locked": false,
    "bot": false,
    "discoverable": false,
    "group": false,
    "created_at": "2019-03-04T00:00:00.000Z",
    "note": "<p>Admin of hellsite.site<br>Instance Necromancer and Scourge of The Fediverse <br>Tentatively Immortal, Possibly Divine<br>Sometimes a Kobold, Sometimes a Goat</p>",
    "url": "https://hellsite.site/@goat",
    "avatar": "https://media.chitter.xyz/cache/accounts/avatars/000/086/933/original/88ff47310185ed9a.png",
    "avatar_static": "https://media.chitter.xyz/cache/accounts/avatars/000/086/933/original/88ff47310185ed9a.png",
    "header": "https://media.chitter.xyz/cache/accounts/headers/000/086/933/original/325e8256230b060d.jpeg",
    "header_static": "https://media.chitter.xyz/cache/accounts/headers/000/086/933/original/325e8256230b060d.jpeg",
    "followers_count": 1185,
    "following_count": 1039,
    "statuses_count": 994252,
    "last_status_at": "2022-02-23",
    "emojis": [],
    "fields": [
      {
        "name": "Pronouns",
        "value": "She/Her",
        "verified_at": null
      },
      {
        "name": "Discord",
        "value": "🐐🐐🐐#1383",
        "verified_at": null
      }
    ]
  },
  "media_attachments": [],
  "mentions": [],
  "tags": [],
  "emojis": [],
  "card": null,
  "poll": {
    "id": "65464",
    "expires_at": "11878-08-12T10:11:44.000Z",
    "expired": false,
    "multiple": true,
    "votes_count": 5,
    "voters_count": 4,
    "options": [
      {
        "title": "TEST",
        "votes_count": 4
      },
      {
        "title": "TEST",
        "votes_count": 1
      }
    ],
    "emojis": []
  }
}

</pre>
</details>

**Comment by charlag** [comment]
@codl thanks for the report but I think Mastodon should not send us improperly formatted dates

**Comment by charlag** [comment]
@codl having posts in the correct format is the smallest thing we can ask of API. The behavior in web is hardly more correct, it happens accidentally because they don't really parse anything besides `JSON.parse()` and then propagate invalid state further. We could filter out invalid posts but I really don't think it's something that we need to focus on.

**Comment by codl** [comment]
Got it, thanks.
