### ISSUE TITLE
The CloudFlare elephant in the room

### ISSUE THREAD

**Issue by ObiSandwich** [tuskyapp/Tusky#2279]
So I can't seem to get some instances to be recognised with the Tusky app without getting the "**Failed authenticating with that instance**" error :( I have tested Tusky with other instance addresses (eg. mastodon.social), which were all recognised by the app with no errors.

Unfortunately I have been unable to get a response from the Admin of these instances using their official email addresses. But I understand this to be a CloudFlare issue, is there a particular reason why Tusky has to be so sensitive to CloudFlare?

A much wiser and (unrelated) instance Admin once told me...

> The instances you are trying to access use CloudFlare. This makes any requests to their domains go to CloudFlare first before reaching the instance. I suspect that something with either the TLS/SSL certificate that CloudFlare uses or the protection from attacks they implement is triggering an issue with Tusky. Either Tusky solves the problem or the instances need to disable CloudFlare Proxy.

* * * *
- Tusky Version: 15.1 (Fdroid)
- Android Version: GrapheneOS
- Android Device: Pixel 3a
- Mastodon instance (if applicable):

**Comment by connyduck** [comment]
Which instances are affected by this?

**Comment by a1batross** [comment]
That can be completely unrelated to Tusky.

It's just Cloudflare bad and replaces intercepts API requests with captcha page. I even had the federation issues because AP is HTTP based and thus also affected by Cloudflare.

**Comment by connyduck** [comment]
I don't think there is anything Tusky can do about this.
