### ISSUE TITLE
[bug] second account on the same instance

### ISSUE THREAD

**Issue by Thorgrimson** [tuskyapp/Tusky#2280]
I have one private acount and one for my blog on social.tchncs.de . I use tusky for the private one quite a while and try now to add the blog account. After I choose my instance I was asked to authenticate my private account once again and cant choose to login to my blog-account. When I use another instace there is the loginscreen of this instance.

* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: Fairphone 3

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Is this maybe about credentials or session state being cached in the browser?
i.e. If you log out in the browser before trying to add the second account in Tusky, do you see the same behavior?

**Comment by Thorgrimson** [comment]
That helped, thank you ;)
