### ISSUE TITLE
Hyperlinks beginning with # are treated as hashtags

### ISSUE THREAD

**Issue by tastytea** [tuskyapp/Tusky#2283]
Consider this post: <https://likeable.space/notice/AEumkGbxcWAwPmyg7c>. It has a hyperlink to a matrix room and one to an IRC channel in it. Both begin with a `#`. If I click on them in Tusky, it thinks they are hashtags. 

In Pleroma they behave like normal hyperlinks and in Mastodon the Matrix-link works like a hashtag when I left-click but opens the Matrix-URL when I open it in a new tab.

* * * *
- Tusky Version: 15.1
- Android Version: 11 (LineageOS 18.1)
- Android Device: Xiaomi Mi 8
- Mastodon instance (if applicable): likeable.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
:thinking: I guess we need to check whether we're clobbering existing url spans when finding hashtags (and probably mentions) to mark up

**Comment by connyduck** [comment]
The correct way to fix this is to use the list of `Tag`s that is returned for each status/account by the Mastodon Api, similar to the list of `Mention`s. That is a pretty big refactoring for such a small bug but I guess we should do it for the sake of using the Mastodon Api as intended.
