### ISSUE TITLE
Pinned posts appear twice

### ISSUE THREAD

**Issue by garritfra** [tuskyapp/Tusky#2293]
The "Pinned" Tab of a user profile contains each post twice.
    <details>
        <summary>Example Screenshots</summary>
         ![image](https://user-images.githubusercontent.com/32395585/149494222-e4b87d67-3aa5-4358-a7c6-45b8448d5189.png)
![image](https://user-images.githubusercontent.com/32395585/149494237-22c941e2-9b8c-4525-baf2-9feb48b8820f.png)
    </details>   

[Matrix Chat](https://matrix.to/#/!PWkUGGpeMZWDPmdfRE:matrix.org/$16421464602nnSsr:matrix.slashdev.space?via=matrix.nailyk.fr&via=matrix.org&via=tchncs.de)

* * * *
- Tusky Version: 15.1-fe350ccf (Nightly)
- Android Version: 11
- Android Device: OnePlus Nord (AC2003)
- Mastodon instance (if applicable): fosstodon.org

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Confirmed, I experience the same
