### ISSUE TITLE
Panning a zoomed-in image stops under certain conditions

### ISSUE THREAD

**Issue by kuba-orlik** [tuskyapp/Tusky#2297]
Steps to reproduce:

1. Find a post with an image attached
2. Open the image
3. Zoom in the image so its height is larger than the screen height
4. Pan the image so the upper edge of the image is aligned with the upper edge of the screen
5. Try to pan the image left or right while moving the finger slightly downwards
6. See that the panning is stopped as if there is no more picture in that direction (even though there is)

It seems that the application confuses the upper edge meeting the end of the screen with the side edge meeting the end of the screen. 

Here's a video of that:

https://video.kuba-orlik.name/videos/watch/ad085c55-deaf-4e31-859e-44f678512bdb

* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: Pixel 3a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by cobratbq** [comment]
I would love to see this fixed. Especially crippling for very wide or very high images.

**Comment by charlag** [comment]
Hi, we are aware that image viewer (still) doesn't work as expected, we might need to replace/rewrite it again

**Comment by 9Lukas5** [comment]
I'm gonna give this issue a bump, as I really like using Tusky and this is the number one thing bothering me regularly scrolling through the Fediverse :grimacing:

**Comment by nikclayton** [comment]
Fixed in https://github.com/tuskyapp/Tusky/pull/3894
