### ISSUE TITLE
Custom emoji not shown in announcement

### ISSUE THREAD

**Issue by codl** [tuskyapp/Tusky#2307]
If an instance announcement contains a custom emoji, tusky doesn't show it, it instead shows the shortcode.

* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: Poco X3
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Do you maybe know an instance that currently has an announcement containing a custom emoji?

**Comment by codl** [comment]
https://chitter.xyz, I can provide an invite if that helps

**Comment by connyduck** [comment]
yes please

**Comment by codl** [comment]
dm'd
