### ISSUE TITLE
Favourites list doesn't display all favourites

### ISSUE THREAD

**Issue by PhotonQyv** [tuskyapp/Tusky#231]
Similarly to my other issue, when selecting favourites from the menu, not all of the toots that I've favourited are displayed.

**Comment by wxl** [comment]
I noticed this, too. Pulling the screen down to refresh doesn't help, either. I show 20 on mine.

**Comment by KonomiKitten** [comment]
This also happens for Followers and everything else in Tuskys profile view I presume, though I have not tested it (I can confirm it does for followers though). This should be a bit of a priority because you can't manage your follows etc without this being fixed.

**Comment by charlag** [comment]
@connyduck is this on our side? Does it happen?

**Comment by KonomiKitten** [comment]
@charlag I'll do some tests and get back to reporting specifics here later

**Comment by charlag** [comment]
@KonomiKitten cool thanks!

**Comment by KonomiKitten** [comment]
Sorry for the delay.

**Tusky:** 1.4.1
**Android:** 7.1.2

**My own profile:**
**Posts:** All posts load
**Media:** Some images are gray and do not load
**Favourites:** All posts load
**Mutes users:** Unable to test (I don't have enough people muted)
**Blocked users:** Unable to test  (I don't have enough people muted)

**Another users profile:**
**Posts:** All posts load
**Media:** Some images are gray and do not load
**Favourites:** You can't see other users favourites
**Mutes users:** You can't see other users mutes
**Blocked users:** You can't see other users blocks

**Comment by KonomiKitten** [comment]
Okay so after checking a bit I found out my server had actually lost a lot of media so the media tests are not applicable at all. I'm going to do some more tests and report back again and just for favourites this time so this can be either closed or confirmed.

**Comment by KonomiKitten** [comment]
I'd say this is fixed, I tested 1.7.0 and scrolled 125 days of favourites comparing between the WebUI and Tusky, I didn't see any missing favourites and I think 125 days is enough of a test (my finger didn't want to scroll anymores).

**Comment by charlag** [comment]
Yup, I'd say it's good, thanks for testing!
