### ISSUE TITLE
«The upload failed.» toast is masking the toot toolbar

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#2325]
(stole the screenshot from #1727)

When a media upload fails, the toast is covering the editing toolbar during several seconds, making it very frustrating if e.g. I wanted to try to retry the upload immediately, or if I wanted to toggle the CW field at the same time the upload failed.

![image](https://user-images.githubusercontent.com/2446451/153438853-9310b1df-42bf-4cd3-bd82-7fb5884c7674.png)

* * * *
- Tusky Version: 16.0 beta 2
- Android Version: 10
- Android Device: Oneplus 5 (cheeseburger)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ariasuni** [comment]
Oh, nice. It’s not really obvious, though, since it looks like a toast; maybe it should be, or above the toolbar. What do you think?

**Comment by connyduck** [comment]
Yes, it should be above the toolbar
