### ISSUE TITLE
max_characters from instance API

### ISSUE THREAD

**Issue by shleeable** [tuskyapp/Tusky#2328]
`We couldn’t find any code matching 'max_characters' in [tuskyapp/Tusky](https://github.com/tuskyapp/Tusky)`

Hey team, I've noticed that tusky doesn't pull down or use the max_characters from my instance. There was a ticket #1423 that assumes that tusky was waiting for Mastodon to support this value - now that it does have that available. 

https://aus.social/api/v1/instance shows the correct value.
![image](https://user-images.githubusercontent.com/17537000/153547023-98f66dde-7b76-4a02-86cc-73bf6121a9a8.png)

Please investigate.

**Comment by connyduck** [comment]
This is a new api that Tusky does not yet support. It is planned for Tusky 17.

**Comment by shleeable** [comment]
Love to see it. Thanks.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2341
