### ISSUE TITLE
When redacting a toot with a poll, the character limit of poll options is 25 instead of 50

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#2338]
It’s now 50 characters by default, and the current value is at `configuration.polls.max_characters_per_option` in `/api/v1/instance` now.

Right now, Tusky only supports Pleroma API and fallbacks on 25 characters if not found.

Relevant code:

https://github.com/tuskyapp/Tusky/blob/2cc53d67725b935db084f2c88ec40cb63218f610/app/src/main/java/com/keylesspalace/tusky/entity/Instance.kt#L33

https://github.com/tuskyapp/Tusky/blob/2cc53d67725b935db084f2c88ec40cb63218f610/app/src/main/java/com/keylesspalace/tusky/components/compose/ComposeViewModel.kt#L508

* * * *
- Tusky Version: 16.0 beta 2
- Mastodon instance (if applicable): any Mastodon instance

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Using #2328 to track "implement the new instance defaults api"
