### ISSUE TITLE
[Feature Request] Filtering of follows/followers list by instance

### ISSUE THREAD

**Issue by PhotonQyv** [tuskyapp/Tusky#234]
Would be nice if you could filter the followers\follows lists by instance so that one could immediately see all those following or being followed on each instance. Use case: I was looking to block\ remove the vast majority of followers from pawoo since they appear to be bots in the main, and this would have been made easier if I could have selected to only see users from that instance in my followers list.

**Comment by torrentcome** [comment]
Which filters do you want apply to this enhancement ?

Something like, take the full list and compare(Object object1, Object object2) or do you think to another way ?

Cheers

**Comment by charlag** [comment]
I'm not even sure if it's needed in the app tbh

**Comment by charlag** [comment]
Is this still relevant to anyone?

**Comment by charlag** [comment]
I am closing it because it doesn't seem like anyone's interested.
