### ISSUE TITLE
Load more button doesn't always show

### ISSUE THREAD

**Issue by AstraLuma** [tuskyapp/Tusky#2350]
When I'm catching up after a long period, the Load More button sometimes doesn't show up

![Screenshot_20220221-091239.jpg](https://user-images.githubusercontent.com/401438/154971906-ba136c77-5082-494f-8490-a214e13a1a00.jpg)

Version: 16.0 beta 2

**Comment by connyduck** [comment]
should be fixed by https://github.com/tuskyapp/Tusky/pull/2348
