### ISSUE TITLE
bug: Disabling header display hides access to menu and settings

### ISSUE THREAD

**Issue by ne20002** [tuskyapp/Tusky#2358]
I just updated to Tusky 16. If I disable text headers for top naivagation in settings, the main icon in upper left whith acces to settins and menu is gone, also the search icon.

No way to get the settings back ... :(

* * * *
- Tusky Version: 16.0
- Android Version: 12
- Android Device: S10e
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Long-press on the side of the screen.
(Not a bug, it works as intended)

**Comment by ne20002** [comment]
> Long-press on the side of the screen. (Not a bug, it works as intended)
Thanks. Took a while to figure out how to do this.

**Comment by iheinscher** [comment]
> > Long-press on the side of the screen. (Not a bug, it works as intended)
> > Thanks. Took a while to figure out how to do this.



> Long-press on the side of the screen. (Not a bug, it works as intended)

I have the same probleme. Pressing on the side if the screen does not help. 
Tusky-Version 20.0 , Android 12
