### ISSUE TITLE
I'm experiencing some visual glitch in the notifications tab

### ISSUE THREAD

**Issue by Hund** [tuskyapp/Tusky#2370]
I'm experiencing some visual glitch in the notifications tab. I included a screenshot on it as I really don't know how to describe it. It has happened two times for me now.

![IMG_20220306_134056](https://user-images.githubusercontent.com/320498/156923783-aec117cb-7f3a-40ad-a8f5-aaba00df32f5.jpg)

* * * *
- Tusky Version: 16.0
- Android Version: 11
- Android Device: Google Pixel 3a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That happens when there is a notification that Tusky does not understand.

Can you please check what the webinterface shows so we can identify the problem?

**Comment by Hund** [comment]
It's new accounts, but they're not following me. I'm a moderator on the instance, if that could have anything to do with it?

**Comment by kyori19** [comment]
After this change is merged, this issue should be solved.
* #2357

**Comment by Hund** [comment]
Thanks!
