### ISSUE TITLE
Please add an option to select text in post

### ISSUE THREAD

**Issue by joenepraat** [tuskyapp/Tusky#2379]
Sometimes I want to research a word or a line, in e.g. Wikipedia or I want to translate a word using a translation app. This is not possible, because you can't only select all text or nothing. So please make text selectable, like in a web-browser.

* * * *
- Tusky Version: 16.0

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2472
