### ISSUE TITLE
Miscounts URL contribution to character limit, sometimes fails to save draft on error 422

### ISSUE THREAD

**Issue by digitalcircuit** [tuskyapp/Tusky#2399]
## In brief
* Tusky doesn't correctly count characters when mixed with a URL
  * Despite notification, **failed toot may be lost, not saved to drafts**
  * Affects glitchsoc-based instance with raised custom toot length (`"max_toot_chars":1312`)
  * Example given below

### Steps
1.  Open Tusky, start composing a toot on an instance
    * In this case, https://vulpine.club/ with a length limit of 1312 characters
2.  Set privacy to Direct (to avoid spamming others)
3.  Add a content warning:
```
Test post
```
4.  **Test A:** Fill the body of the toot with the following:
```
https://example.com 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
```
5.  **Add or remove `1`'s as needed to have exactly zero characters available/remaining**
6.  Try to send toot in Tusky
7.  Check drafts if sending toot fails
8.  Paste this into the web UI of the instance, compare character count
     * On vulpine.club, the above results in Tusky showing 0 characters left, while the web UI shows it as -4 characters (i.e. 4 characters over)
9.  **Test B:** Repeat steps 1-8 with the following toot, using the same content warning as before, **adding or removing `1`'s as needed to have zero characters available**, like before:
```
https://example.com/?testing_post_chars_here 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
```

### Expected
Tusky shows the test toot as hitting 0 characters remaining.  The toot posts successfully.

If it fails to post, Tusky successfully saves the toot as a draft.

### Actual
Tusky gives 4 more characters than the web UI allows.  The toot fails to send.

When the toot fails to send, Tusky **occasionally does not save the toot in drafts, losing work** despite the notification's claim!  It seems to be random, usually not saving to drafts but sometimes succeeding.

(Note: I have other draft messages in Tusky's list of drafts.  Tusky does properly save toots to drafts if e.g. sending a toot while offline, then canceling the operation.)

### Extra details

**NOTE:** This appears to break the glitchsoc web UI, too!  Trying to post the above statuses when the web UI claims there's 0 characters remaining results in…
`422: Validation failed: Text character limit of 1312 exceeded`

…despite the length limit appearing to be set correctly (both web UI and backend report a limit of 1312 characters).

After filling the toot with `1`'s until the web UI reports 0 characters remaining, I have to delete a single `1` from the toot for it to post on the web UI (1 character free) for both **Test A** and **Test B**.

For Tusky to post correctly, after filling the toot with `1`'s until Tusky reports 0 characters remaining, I have to delete five `1`'s from the toot content in **Test A**, and only one `1` from the toot content in **Test B**.

I think there's multiple bugs here, possibly including a bug in glitchsoc or Mastodon itself.

* * * *
- Tusky Version: `16.0`
- Android Version: `12 (SP2A.220305.012)`
- Android Device: `Pixel 4 XL`
- Mastodon instance (if applicable): https://vulpine.club/ (features custom max toot length, 1312 characters as shown in web UI and Tusky)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thanks for the detailed report, I can reproduce it on mastodon.social

**Comment by Tak** [comment]
It looks to me like mastodon is adding the maximum url length value (default 23) for urls, even when the url is shorter.
I don't think this was always the case, and I strongly suspect the regression came in with configurable url size limits (`instance/configuration/characters_reserved_per_url`)

**Comment by digitalcircuit** [comment]
@Tak Good point!  After digging around, that's actually not a regression, but an intentional change that came earlier in 2017:
["Count all URLs in text as 23 characters flat, do not count domain part of usernames" #4427](https://github.com/mastodon/mastodon/pull/4427 ).

My guess would be that reserving the maximum URL length value strongly discourages using URL shorteners.

### Additional details
When the instance configuration metadata was added in 2021, this already existed:
https://github.com/mastodon/mastodon/commit/275fa4746b1b25ff3d59c09111c8129ef8e1ccda
```diff
   MAX_CHARS = 500
-  URL_PLACEHOLDER = "\1#{'x' * 23}"
+  URL_PLACEHOLDER_CHARS = 23
+  URL_PLACEHOLDER = "\1#{'x' * URL_PLACEHOLDER_CHARS}"
```

`URL_PLACEHOLDER` is used to string-replace any URLs, so it'd always be a fixed size.

**However**, the fact that the Web UI *also* shows the wrong character length, requiring me to delete a single character from both **Test A** and **Test B** (*i.e. fill with `1`'s until the web UI says there's zero characters left available, then try to send and delete `1`'s until it works*) suggests that there might be something broken with either glitchsoc or upstream Mastodon's URL/character handling, in addition to what Tusky gets wrong.

**Comment by Tak** [comment]
🤔 I would have sworn that only urls longer than 23 characters were resized before, because we complicated our code and wrote a test to account for this. If this behavior is intentional, then we can simplify things.

**Comment by connyduck** [comment]
I reported the part that definitely is a Mastodon bug here: https://github.com/mastodon/mastodon/issues/17860

@Tak can you take care of whatever is wrong in Tusky? I think it is indeed that we don't count all urls as 23 characters.

**Comment by digitalcircuit** [comment]
@connyduck For what it's worth, I *think* Tusky is also subject to the same bug as the Mastodon web UI frontend, since even when I use a >23 character URL (`https://example.com/?testing_post_chars_here`, see **Test B**), I have to delete one of the `1`'s (so Tusky claims there's 1 character available, *not* 0) for it to post.

Separately, the bug with Tusky failing to save a draft message (contrary to the notification's claim!) appears to be a race condition of some sorts - when a toot that failed to send gets saved as a draft, I can keep trying to send it from the drafts page and it'll eventually not get saved.

(To be clear, *sometimes the failed toot never gets saved as a draft in the first place*.  Losing about half an hour typing a long post because it failed to save to drafts after failing to post is what prompted me to file this issue.)
