### ISSUE TITLE
Please make the gesture bar transparent

### ISSUE THREAD

**Issue by Y32Gcnte8z** [tuskyapp/Tusky#2403]
[Issue text goes here].

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

In Android 12, the system gesture bar cannot be hidden, but its color is not the same as tusky app, especially when navigation bar is in the bottom.

**Comment by connyduck** [comment]
You want these two bars to have the same color?
![Screenshot_20220325_073555](https://user-images.githubusercontent.com/10157047/160067581-d74e732d-af4d-41fc-bfb3-6baf934a3a1f.png)

**Comment by Y32Gcnte8z** [comment]
> You want these two bars to have the same color? 

I don't mean the 3-button navigation, I mean the gesture navigation bar.
![Screenshot_20220325-222211](https://user-images.githubusercontent.com/62335203/160139053-b2b9af59-19b0-4b11-b8ae-d326edcc0f07.png)

**Comment by connyduck** [comment]
Yes, from an app point of view those are the same.

I agree that it would be nicer to have it in the same color as the bottom nav bar, but on other views or when the navigation is on top the darker color is a better fit.

**Comment by charlag** [comment]
@connyduck should I close it then?
