### ISSUE TITLE
Number emojis aren't displayed in toot draft screen when using Twemoji

### ISSUE THREAD

**Issue by realpixelcode** [tuskyapp/Tusky#2407]
When using Twemoji, the emojis *️⃣0️⃣0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣ aren't displayed in the toot draft screen. However, the remaining characters counter is decreased. Also, the issue didn't occur when using the system's emojis.

https://user-images.githubusercontent.com/52963327/160700845-4a929033-cb3b-4f27-b48f-3fbc927311bf.mp4

* * * *
- Tusky Version: 16.0
- Android Version: 11
- Android Device: Fairphone 3

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Can reproduce.
@C1710 is this a bug in the font?

**Comment by C1710** [comment]
I'm testing, but I think I have a working fix 😄
