### ISSUE TITLE
Media upload fails with Friendica 

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#2409]
Recent versions (beta, nightly) seem unable to upload images to Friendica instances. No matter whether sharing images via Android share or choosing media file in Tusky post editor - upload will go to 100% and then the image dissappears, leaving a message that media could not been uploaded. No way to work around by now. 😔

* * * *
- Tusky Version: 17.0 beta 1
- Android Version: 11
- Android Device: Samsung M51 stock ROM
- Mastodon instance (if applicable): loma.ml 

- [ X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kr428** [comment]
Yes, it did. Seems to broke just very recently.

**Comment by connyduck** [comment]
This is a bug in friendica - they do not support the `POST api/v2/media` endpoint of the Mastodon api. Tusky used `POST api/v1/media` until version 16.0 , starting with 17.0 it will use v2 because it provides better performance. Please report this to friendica.

**Comment by annando** [comment]
@connyduck thanks for the hint. I haven't realized that there are other endpoints. Are there other `v2` that you plan to implement?

Memo to myself: Having a look at the Mastodon API and all recent changes :-)

**Comment by annando** [comment]
I just read in the documentation that `api/v2/media` is nearly similar to `api/v1/media` except that the returned JSON has got some fields set to `null` and that a `202` is returned. Are you checking anything of these? It is easier for me to just route the `v2` endpoint to the `v1` endpoint.

**Comment by connyduck** [comment]
No we don't check either of those (we only need the media id), but other clients might, so be careful

**Comment by kr428** [comment]
(Seems to work again with latest Friendica RC 2022-05.)
