### ISSUE TITLE
With 17.0 beta 1 it's no longer possible to refresh under the timeline

### ISSUE THREAD

**Issue by sandzwerg** [tuskyapp/Tusky#2423]
With the previous versions I was able to refresh the timeline "above" my currently last read toot. So I would scroll the "load more" button to the top of my timeline so it's barely visible and then refresh, new toots would load but I'd stay at my current place in the timeline. With the 17.0 beta 1 version I'm no longer able to do that. My "view" is always "above" the newly loaded toots, while before I was able to keep it below. The downside is that if I want to continue to read my TL chronological from where I stopped to now I have to scroll, refresh, scroll refresh. That is a bit annoying. If #89 would be introduced that would probably fix this as well.

One the plus side: I never encountered the missing messages bug from tusky 16 again, thanks for that <3

* * * *
- Tusky Version: 17.0 beta 1 (Google)
- Android Version: 11
- Android Device: OnePlus Nord CE 5g
- Mastodon instance (if applicable): chaos.social (but doesn't matter)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by shello** [comment]
I can confirm I'm seeing this behaviour since the non-beta update as well. It was certainly a less than ideal workaround for loading the timeline without losing track of its position, but it worked for a few versions. I'm glad the timeline issues seem to be fixed, however!

**Comment by b1rger** [comment]
First of all: thanks a lot for Tusky, I am using it for years and I like it!

I have the same problem and I am wondering if I am using Tusky the wrong way or how it is intended to be used. Do users usually remember the place in the timeline before updating and scroll down to that place and then scroll back up?

(I am back on Tusky 16 for now)

**Comment by sandzwerg** [comment]
In the meantime, I was able to recreate the behavior, but it's tricker than before. One needs to make sure that one is below the "reload" part. For me this works best with two hands, with one tap the reload with the other quickly swipe a screen down, repeat. Works, but a function that remembers where I was in timeline would be highly appreciated.

**Comment by shello** [comment]
I can confirm that scrolling the "load more" area off screen reproduces the old workaround for refreshing above the timeline! Thank you @sandzwerg!

https://user-images.githubusercontent.com/30915/164725629-ddee2ed1-7b12-496c-9dda-61d9e265c7b3.mp4

**Comment by JasXSL** [comment]
Getting the old behavior back would be nice. Sometimes it just loads too fast to perform the workaround.

**Comment by charlag** [comment]
Hello fine people
Sorry that we don't react, we are all either overwhelmed our out of spoons, we do see the issues.
This will need some investigation, I will try to get some attention to it.

**Comment by connyduck** [comment]
So the main problem here is that some people would prefer to read newest posts first and others would like to read their whole timeline from oldest to newest, yes?

Here are some possibilities how we could solve this:

1) restore the old behavior with the scroll position that influences how the posts load. We now use a different api to do the loading so it might not be possible, but I can look into it
2) offer options 
 - Refreshing mode "always newest". There will be no placeholders at all, if you pull to refresh or reopen the app you will just get newest tweets from the top.
 - Refreshing mode "oldest first". Same behavior as now, but "load more" loads the oldest posts in the gap first.
3) Have two buttons in the gap placeholder. "Load above" and "Load below".
4) other?

**Comment by digitalcircuit** [comment]
Another potential option:

* Automatic loading happens based on which direction you scroll towards the timeline gap
   * If scrolling from current to older, it'll `Load below`, but if scrolling from oldest to newer, it'll `Load above`, trying to fill in the gaps before you see them
   * Tusky may want to add a "jump to top" action button
   * Some folks likely will **not** want this (infinite scrolling), so it may need to be an option

For context, my other primary infinite scrolling experience is [with Quasseldroid](https://quasseldroid.info/ ), where IRC messages are automatically fetched avoiding gaps as you scroll (*newest to older works, older to newest is a work-in-progress*).  However, expectations for a synchronous chat app may differ from an asynchronous social media app.

**Comment by charlag** [comment]
You can scroll to top by tapping on tab

**Comment by digitalcircuit** [comment]
> You can scroll to top by tapping on tab

I'm happy with this.

Though, if Tusky is to use infinite scroll by default, I'd suggest this behavior is not immediately obvious.  It might be worthwhile having a brief, easily dismissed "Tap \[tab icon\] to scroll to top" tip bubble.

(I'm not sure what Google refers to this design pattern as - it's been used to highlight the Cast button in the YouTube app.)

**Comment by foss-** [comment]
Two cents incoming: Prefering option 2. Solution 1 sounds like it would not always result in wanted behavior for me and you even mention it may not be possible API wise. I think users have a clear preference to either read from old to new or vice versa. So setting this once in preferences sounds like the best approach. I would not want to have an additional layer shown everytime I `Load more` whether I want to load above or below. In my case I would always pick the same option, since that is my preference and having to repeat this on every load more option would become annoying rather quickly I think.

**Comment by charlag** [comment]
> Though, if Tusky is to use infinite scroll by default, I'd suggest this behavior is not immediately obvious. It might be worthwhile having a brief, easily dismissed "Tap [tab icon] to scroll to top" tip bubble.

Official app shows a button in the title when there's something new (which is a "dark pattern" from one bird-themed app if you ask me) but we do hide the title so it would be tricky for us to do even from a technical point.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/2788
