### ISSUE TITLE
registration notifications are not displayed

### ISSUE THREAD

**Issue by Tealk** [tuskyapp/Tusky#2428]
With 3.5.0, the notification for new accounts was added, but these are not displayed in the app, there is only an empty line to see.

> Add notifications for moderators about new sign-ups (https://github.com/mastodon/mastodon/pull/16953, https://github.com/mastodon/mastodon/pull/17629)

* * * *
- Tusky Version: 17.0 beta1 but the "problem" existed in earlier versions as well
- Android Version: CalyxOS 3.4.0
- Android Device: Pixel&
- Mastodon instance (if applicable): https://rollenspiel.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2357
