### ISSUE TITLE
Following a locked account fails

### ISSUE THREAD

**Issue by Vavassor** [tuskyapp/Tusky#244]
Reported from elsewhere:
> i tried to follow someone with a locked account on a remote instance from my instance which is running the latest master. this failed with an error in Tusky, but not the web UI

My thoughts:
In ```AccountActivity```, the ```follow()``` call checks a field ```following``` to decide whether it should issue a request to follow or unfollow. But ```following``` is obtained asynchronously through a request to the API endpoint```/api/v1/accounts/relationships```. My guess is its state isn't getting initialized correctly and/or the call to that endpoint fails. So, ```following``` somehow ends up always true and thus when you hit the button it makes a call to try to _unfollow_ the account and fails repeatedly.

There really isn't much logic associated with following, otherwise, so I'm not sure what else it could be?

**Comment by daycode** [comment]
perhaps, we should open an issue in mastodon-api repository, because the API should send an error when we can't follow an account 🤔

**Comment by connyduck** [comment]
this works now
