### ISSUE TITLE
Client have to wait for the end of media post process after upload

### ISSUE THREAD

**Issue by kyori19** [tuskyapp/Tusky#2442]
After Mastodon received `POST /api/v2/media`, it starts media processing.
Calling `POST /api/v1/statuses` immediately after media upload causes validation error (422).
We have to poll `GET /api/v1/media/:id` to check whether media process finished.

WebUI's behaviour:

`POST /api/v2/media` -> 202
`GET /api/v1/media/:id` -> 206 (still processing, wait 1000ms)
`GET /api/v1/media/:id` -> 206 (still processing, wait 1000ms)
`GET /api/v1/media/:id` -> 200 (process completed)
`POST /api/v1/statuses` -> 200 (post succeeded)

Current bahaviour:

`POST /api/v2/media` -> 202
`POST /api/v1/statuses` -> 422 (validation error: image still processing)

FYI: https://fedibird.com/@noellabo/108145762415387597 (Sorry for Japanese conversation)

* * * *
- Tusky Version: 17
- Android Version: 10
- Android Device: N/A
- Mastodon instance (if applicable): N/A

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Did not know that. Thx for the information, will fix.
