### ISSUE TITLE
Option to reverse the order of posts on the timeline

### ISSUE THREAD

**Issue by kuba-orlik** [tuskyapp/Tusky#2450]
I think it would be awesome to have an option to change the ordering of entries in the timeline, so the newest entries are on the bottom, and the oldest ones are on the top. It would make reading a little bit easier, as reading in the natural top-to-bottom direction would let us read posts chronologically

* * * *
- Tusky Version: 17.0
- Android Version: 11
- Android Device: Pixel 3a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/2788
