### ISSUE TITLE
Redesign the Bot Badge

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#2453]
The current badge does not change based on theme and looks a bit dated. I propose we replace it with an improved badge over the avatar, or a new text based badge:

|       | dark theme | light theme |
| --- | --- | --- |
| Text variant - account list | ![account_badge_dark_2](https://user-images.githubusercontent.com/10157047/164765427-7d7f4e5e-c436-4b9e-8952-efe550bedeeb.png) | ![account_badge_light_2](https://user-images.githubusercontent.com/10157047/164765422-b9680662-d889-4ee2-be12-f8f61223dd7c.png) |
| Text variant - timeline| ![timeline_badge_dark_2](https://user-images.githubusercontent.com/10157047/164765244-dfcaf998-777b-4b82-af35-77b80404b3fd.png) | ![timeline_badge_light_2](https://user-images.githubusercontent.com/10157047/164765250-b7c1c7eb-0592-48b1-9d8a-10ec4759aea0.png) |
| Badge over avatar variant - account list | ![account_badge_dark_1](https://user-images.githubusercontent.com/10157047/164765803-b101c7c3-caf7-434b-9fd3-835e5180fe84.png) | ![account_badge_light_1](https://user-images.githubusercontent.com/10157047/164765813-4e7dc125-e337-4dc9-bb00-79b1c982b23d.png) |
| Badge over avatar variant - timeline | ![timeline_badge_dark_1](https://user-images.githubusercontent.com/10157047/164765534-9abbad36-bb28-488f-9c64-311b0bc9fd60.png) | ![timeline_badge_light_1](https://user-images.githubusercontent.com/10157047/164765529-6ec28409-f4e8-4552-835d-ebd0eb750f0e.png) | 

The text badge has the advantage of also showing up on boosts, but it needs more space.
It would also be possible to combine both variants, e.g. show the text badge in the timeline and the badge over avatar in account lists. The space created by the text badge could also be used for other badges, e.g. a "follows you" badge.

Thoughts?

**Comment by Tak** [comment]
Makes sense - graphic design was never my passion 😛 
I prefer the over-avatar style where possible, because it takes up less space, but I'm flexible

**Comment by realpixelcode** [comment]
The space between the icon and the label shouldn't be bigger than the padding IMO. But for the rest, I like it 👍

**Comment by a1batross** [comment]
Looks awesome!

**Comment by jmbmkn** [comment]
To offer an alternate opinion I prefer the new text based badge. The over avatar badge is similar to the 'boost' avatar overlays. I also imagine bringing it out and inline would work better for screen readers.

**Comment by charlag** [comment]
I would prefer non-inline ones. We control how we read the post for screen readers regardless

**Comment by BANOnotIT** [comment]
> The over avatar badge is similar to the 'boost' avatar overlays.

I boost posts will text badge show up? And if it will how to know if bot boosted a human or a human boosted bot?

**Comment by connyduck** [comment]
After playing with it for way longer than I'd like to admit, I think this version is pretty good. It is not much different from the current badge so it does not disrupt anything, but it fits way better into the app themes.

![badge_dark](https://user-images.githubusercontent.com/10157047/165601965-0ffa6750-6c59-40c8-b4d5-d323b59ff89a.png)
![badge_light](https://user-images.githubusercontent.com/10157047/165601983-0b8df0b8-e1a5-4610-9dad-daf246bba64e.png)
