### ISSUE TITLE
Display sign up notification correctly

### ISSUE THREAD

**Issue by just1602** [tuskyapp/Tusky#2457]
Hello!

Since the latest release of mastodon, when you are admin, you have notification that show the new signed up accounts. Actually, there's items for those notifications in the list, but they're not displayed.

* * * *
- Tusky Version: 17
- Android Version: 11
- Android Device: Galaxy A50
- Mastodon instance (if applicable): kolektiva.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

---

![tusky-screenshot1](https://user-images.githubusercontent.com/427123/165310241-4dcca96f-f3d0-41b8-a54c-b9f24891cfc6.jpeg)

All the empty lines are signup notifications that are not displayed.

**Comment by connyduck** [comment]
fixed here https://github.com/tuskyapp/Tusky/pull/2357

**Comment by just1602** [comment]
Oh really sorry for the duplicate then, I searched the issues and PR, but not the merged one. Really sorry for the bothering.
