### ISSUE TITLE
Support setting toot language

### ISSUE THREAD

**Issue by Natureshadow** [tuskyapp/Tusky#2459]
It would be great if the toot language could be set when sending a new toot.

The API seems to support this: https://github.com/mastodon/mastodon/issues/8753

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by hex-m** [comment]
> Add language dropdown to compose form in web UI

Version [3.5.3](https://github.com/mastodon/mastodon/releases/tag/v3.5.3) of the Mastodon Web-Interface supports this. It will probably be used more regularly in the future.

**Comment by chrysn** [comment]
As #2651 didn't explcitly contain a "Closes: #245", this wasn't closed automatically, but I think it can be now.

**Comment by mmahmoudian** [comment]
Considering that #2651 was merged about 3 months ago and there is a mass migration to mastodon, I would like to suggest releasing the next version. But I wonder if there is already a timeline or is there a defined release cycle?

**Comment by connyduck** [comment]
@mmahmoudian https://chaos.social/@ConnyDuck/109355257388353984
You could also join the dev chat on matrix where we discuss releases

**Comment by connyduck** [comment]
This release was delayed by Google play, we couldn't publish for a while

**Comment by Natureshadow** [comment]
Rumour has it there are other ways to publish software besides Google Play.

**Comment by charlag** [comment]
> Rumour has it there are other ways to publish software besides Google Play.

Excuse me? what is this passive-aggressive entitled statement is supposed to mean? Do you not know we are distributing on F-Droid? Would *you* like to set up a nightly F-Droid build?  (there is is one nightly repo by @nailyk-fr to my knowledge)

**Comment by Natureshadow** [comment]
> Excuse me? what is this passive-aggressive entitled statement is supposed to mean? Do you not know we are distributing on F-Droid? Would *you* like to set up a nightly F-Droid build?  (there is is one nightly repo by @nailyk-fr to my knowledge)

You may want to read my comment again, and also the one I replied to.

The argument was that a release was entirely impossible because issues with Google Play.

So, if you think my remark is wrong, please enlighten me on why Google can prevent a release to F-Droid.

**Comment by charlag** [comment]
Because we are people who do this in our free time and we have limited resources and we doing the release at the same time everywhere. I misunderstood your comment but you tone was still demanding.

**Comment by nailyk-fr** [comment]
Google is not friendly at all and I'd happy to explain why. But this is another topic :slightly_smiling_face: 

About the original question, the nightly is available on my F-Droid repository : https://releases.nailyk.fr/repo/
I am using it everyday and the code quality is so good that it is rare to have issues with the nightlies :blush: 

If you have any issue with my repo, please let me know.
