### ISSUE TITLE
Can't upload images to Pixelfed

### ISSUE THREAD

**Issue by kvibber** [tuskyapp/Tusky#2463]
I'm able to sign into Pixelfed, read my timeline, comment, favorite, etc., but whenever I try to post an image, the upload circle gets *almost* all the way around and then stops, an error pops up saying "The upload failed," and then the image thumbnail disappears.

This happens whether I'm using the paperclip button or using the share intent to send it from my gallery to Tusky.

Image uploads work just fine to my Mastodon account.

* * * *
- Tusky Version: 17.0
- Android Version: 12, with the April 5, 2022 security update
- Android Device: Pixel 5
- Pixelfed instance: pixelfed.social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/pixelfed/pixelfed/issues/3405
