### ISSUE TITLE
log in loop

### ISSUE THREAD

**Issue by niccokunzmann** [tuskyapp/Tusky#2470]
when I open the app for the first time,
I enter the instance toot.wales
then I am prompted to enter the email and password
I do that, and see the oauth web page
I click authorize
I am back at the start screen with the instane name

* * * *
- Tusky Version: 17.0
- Android Version: 6
- Android Device: Moto
- Mastodon instance (if applicable): toot.wales

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
fixed here https://github.com/tuskyapp/Tusky/pull/2432
