### ISSUE TITLE
Sidebar unreachable when you enable "Hide the main navigation" with Android 10+ gesture navigation

### ISSUE THREAD

**Issue by frumble** [tuskyapp/Tusky#2473]
Modern Android versions default to gesture navigation. But with gesture navigation, you cannot reach the side menu in Tusky anymore since there is no button for it.

* * * *
- Tusky Version: 17.0
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Long-press the side of the screen to access the menu

**Comment by frumble** [comment]
Doesn’t work on my Samsung ROM.

**Comment by connyduck** [comment]
well then you can only clean app data

**Comment by frumble** [comment]
No, it doesn’t work system-wide. A long-pull is always a back gesture here on my still Android 10 based Galaxy Note 9.

**Comment by connyduck** [comment]
Well, then either clean the app data to get the button back or temporarily disable the gesture navigation.

**Comment by frumble** [comment]
I know, but this issue shouldn’t be closed. Does it work on your device with gesture navigation?

**Comment by connyduck** [comment]
Yes it does (stock Android). I'm just pressing at the edge of the screen and the menu pops right up. Maybe you can change your swipe sensitivity settings and it will work for you as well.

But the option to hide the top bar confuses so many people, we should probably get rid of it altogether.
