### ISSUE TITLE
Profile screen improvement: show account creation date

### ISSUE THREAD

**Issue by JPLeBreton** [tuskyapp/Tusky#2477]
When viewing another user's profile, their account's creation date should appear beneath everything else in the profile view (and above their toots etc). Mastodon's web UI has this info, and it's useful - particularly during periods like now (late April 2022) when lots of accounts are following you.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2480
