### ISSUE TITLE
Top bar setting issue

### ISSUE THREAD

**Issue by Talavolva** [tuskyapp/Tusky#2485]
Hello I am new to tusky and I was going through the Preferences. I found that once i hide the top toolbar it would disappear forever, along with the side bar and the preferences button. And it seems  there's no other way but to reinstall the app to dig it back out.  

Also would there be a feature that could pin the top toolbar? That would be lovely.

Xx
* * * *
- Tusky Version:17.0
- Android Version:11
- Android Device:one plus 9r
 

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Alex0007** [comment]
Why is this closed? I just faced same situation
