### ISSUE TITLE
Scheduled toots not showing up in scheduled posts

### ISSUE THREAD

**Issue by GlitzSmarter** [tuskyapp/Tusky#2493]
I have scheduled 2 toots (with a date & time) and they don't appear in my scheduled posts. I do know I scheduled them as they don't appear in my profile.

The instance I'm on did have some downtime today (the day I'm posting this issue) due to maintenance so that may be why it isn't showing up, but I wanted to post this issue just to check.

* * * *
- Tusky Version: 17.0
- Android Version: 12
- Android Device: Pixels 4a
- Mastodon instance (if applicable): don't think this is needed

- [✓ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
@GlitzSmarter doesn't seem like there's anyone else, I think it's an issue with the server, I will reopen it if there are more reports
