### ISSUE TITLE
Preferences redesign 

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#2504]
Current problems with the settings:

- It is often not clear which setting is found in "Account preferences" and which in "preferences"
- Users wish for more settings to be account specific, especially the reply/boost filters https://github.com/tuskyapp/Tusky/issues/1881 https://github.com/tuskyapp/Tusky/issues/1338
- Some settings are just there to work around problems in the app
  -  "Hide compose button when scrolling" - in short timelines posts at the bottom were covered by the button
  - "show notification filter" - users wanted more space or accidentally deleted their notifications
  - "Enable swipe gesture to switch between tabs" -> swiping is too sensitive https://github.com/tuskyapp/Tusky/issues/2112
  - ...
- Some settings are misunderstood or cause problems, e.g. the "Hide title of top toolbar" https://github.com/tuskyapp/Tusky/issues/2481
- "Animate avatars" and "Animate Emojis" can be combined into one
- Some settings need more or other options https://github.com/tuskyapp/Tusky/issues/2461
- There are probably settings that we don't have but that make sense
- ...

I propose the following course of action:
- First, get the internat refactoring done so we have nice code to work from https://github.com/tuskyapp/Tusky/pull/2393
- Collect more problems and whishes from users, e.g. by asking on our mastodon account
- Try to get rid of as many settings as possible
- Lastly, organize the remaining ones in a better way

**Comment by connyduck** [comment]
<details>
  <summary>Example of cool setting design</summary>
  
I really like how the wikipedia app does this. We could have a similar setup were we display a example post in the seetings so users immediately see what a setting does. 
The font-size slider is also super cool. 

![Screenshot_20220504_204640](https://user-images.githubusercontent.com/10157047/166805499-c60dad37-01af-401e-b026-d7065bd8bc01.png)

  
</details>

**Comment by connyduck** [comment]
Updates:
- The problem with the "Hide title of top toolbar" being confusing has been solved: https://github.com/tuskyapp/Tusky/pull/2973
- I think "Hide compose button when scrolling" should be removed and all lists with action buttons should get a padding at the bottom so the button does not hide anything.

**Comment by ichier** [comment]
> "Hide compose button when scrolling" - in short timelines posts at the bottom were covered by the button

well - i actually don't want to have a compose button floating around at all... i would prefer it sitting in the top menu, where is plenty of space.
i would actually put it instead of search, because search could be a tab; that way search results could be kept in there until further search!
