### ISSUE TITLE
Feature request: Option to set the amount of loaded toots on refresh

### ISSUE THREAD

**Issue by andre-dierker** [tuskyapp/Tusky#2511]
Since many new people have joined the Fediverse, and I follow many people and other accounts, I very often see the "Load more" button. Unfortunately, the behaviour of the button is not optimal. So I miss a lot and I don't dare to follow news bots because they fill the timeline. 
So I wanted to suggest that, if the Mastodon API allows it, Tuski gets an option to set the number of loaded toots. 
For example: 50, 200, 500, "all".

regards

* * * *
- Tusky Version: all
- Android Version: all
- Android Device: -
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by andre-dierker** [comment]
Yes I see it every time I open tusky. I would like to see more pr loaded posts.

**Comment by sandzwerg** [comment]
I think I have the same issue. For me it means that if I come back on a busy day a  single "load more" will only get me the tooths of around 15mins. But if I was away for half the day I have to "load more" very often. If I could load more toots at once with every "load more" that would make my live easier.

**Comment by yoshimo** [comment]
I think refreshing automatically while keeping the last read toot active would make this less of an issue

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/2788
