### ISSUE TITLE
More than five tabs

### ISSUE THREAD

**Issue by chris-y** [tuskyapp/Tusky#2512]
Please can we have more than five tabs - either by squashing them together a bit more or by allowing to scroll the tabs bar left/right to see the ones which are out of view?

Home, Mentions, Local, Federated, Direct Messages is already five tabs before adding ones for lists or hashtags.

**Comment by davidbtc2009** [comment]
I agree with this idea with one adjustment. Make the last tab a three vertical dots menu and have other tabs in that menu such as hashtags you wish to follow. That way you could see the name of the tab you are about to click and accessibility for talkback users is preserved.

**Comment by aslmx** [comment]
I'd also like some improvement to be able to follow multiple hashtags more easily. The current implementation is okay, but it mixes hashtags in one tab and I am not always interested in all particular hashtags.

**Comment by kr428** [comment]
Adding myself to the list. With trying to keep messages, notifications and home timeline at least in place, this 5-tab limit really hurts.

**Comment by akien-mga** [comment]
> I'd also like some improvement to be able to follow multiple hashtags more easily. The current implementation is okay, but it mixes hashtags in one tab and I am not always interested in all particular hashtags.

You can add separate tabs for each hashtag to keep them separate. But then yes the current 5 tabs limit means you won't be able to get more than 2 or 3 pinned hashtag this way.

Here's an example:
![IMG_20221104_135409](https://user-images.githubusercontent.com/4701338/200074939-bf0d71d7-fad5-4c82-b5b8-8ded4bc75c1e.jpg)

**Comment by muenznej** [comment]
Hey there, just wanted to push this issue since it triggered me so hard.
The 5 tabs limit is such an arbitrary and bad limit and should be removed or increased.
You really need lists and hashtags to follow multiple topics in a controlled manner and after timeline(s), notifcations and direct messages you are left with 1-3 tabs for hashtags and lists.
In addition, this significant improvement of usabilty would come at almost no development cost (i suppose) since the arbitrary limit of 5 could just be changed.

best,

**Comment by fuzzblob** [comment]
Just wanted to chime in and mention that the Tusky fork [Yuito](https://github.com/accelforce/Yuito) does not have the 5 tab limit.

**Comment by sl1txdvd** [comment]
For the record, the tab limit makes it hard for me to use the fediverse the way I'd like to.

**Comment by goodevilgenius** [comment]
I'd like to add that on my tablet, the tab bar has a lot of empty space, making the five tab limit even more frustrating.

I could easily fit ten tabs before collapsing them under a menu.

**Comment by kr428** [comment]
The actual problem here: Some things, such as local or global timelines, can't even be accessed through the slide-out menu so when I remove them from the tabs, they seem to become all unreachable.

**Comment by marcusti** [comment]
+1 for a scrollable tab bar.

A dotted sub menu requires too many clicks for my taste.

**Comment by davidbtc2009** [comment]
> +1 for a scrollable tab bar.
> 
> A dotted sub menu requires too many clicks for my taste.

A scrolling bar is worse for accessibility though. That is why i suggested a submenu as the last option

**Comment by turgaer** [comment]
I'd like to support this feature request. The mastodon universe experienced some real growth in the past weeks. It feels stranger with each day to be limited to just five tabs.

**Comment by julesbl** [comment]
Yes, I'd like to support more than 5 tabs, especially as if you remove, say, events you can no longer access that list at all

**Comment by quicoto** [comment]
I also felt limited on my options when seeing the 5 tab limit.

Can we explore another design options to allow for more? (horizontal scroll, slide in side menu, etc)

Thank you
