### ISSUE TITLE
Automatically remove Android notifications only when read

### ISSUE THREAD

**Issue by Discostu36** [tuskyapp/Tusky#2528]
At the moment, Android notifications are automatically removed when the Tusky app is open(ed). Instead, they should only be removed, when the corresponding Mastadon notification has been seen.

**Comment by charlag** [comment]
I'm not sure if it should work like that to be honest. Compare to other apps, like messengers, don't they remove notifications as well?
We could however indicate it inside the app

**Comment by 9Lukas5** [comment]
I'm fine with the system notification being removed directly on opening the app, but a counter on the bell icon of all unread notifications would be a good thing.

**Comment by Lakoja** [comment]
Bump.

Was about to open this issue as well.

Maybe a somewhat easier (intermediate) step would be to remove notifcations only once the notification timeline is opened.

**Comment by Discostu36** [comment]
> Compare to other apps, like messengers, don't they remove notifications as well?

This depends on the messenger. WhatsApp, for examples, removes notifications as soon as the app is opened. Telegram, on the other hand, only dismisses notifications once the specific chat is opened that the notification is for.
