### ISSUE TITLE
Decrease threshold of vertical to horizontal swiping sensitivity 

### ISSUE THREAD

**Issue by Nacho-King** [tuskyapp/Tusky#2530]
Currently I find that the vertical swiping action is often interpreted as a horizontal swipe, if your vertical swipe is not perfectly straight. Could this detection threshold be changed somehow? 

* * * *
- Tusky Version: 17.0
- Android Version: 12
- Android Device: Pixel 4a

- [ ✅ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
Duplicate of #2112

**Comment by charlag** [comment]
No worries
