### ISSUE TITLE
Feature request: material you themed icon.

### ISSUE THREAD

**Issue by Filyx20** [tuskyapp/Tusky#2533]
Hi there, i am currently wondering if adding support to having themed icons for Android 13 could be added?
Added [Here](https://developer.android.com/about/versions/13/features#themed-app-icons) is the URL towards the android developer site about the new feature.

Have a wonderful day and thanks you.

* * * *
- Tusky Version: 17.0
- Android Version: 13 (TPBB.220414.015)
- Android Device: PIXEL 6 PRO 128GB 
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes, we will do that when we add support for Android 13 which will happen once it is officially released.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2683
