### ISSUE TITLE
Filters don't work anymore?

### ISSUE THREAD

**Issue by Discostu36** [tuskyapp/Tusky#2546]
With the new version, filters don't seem to work correctly anymore. I see several posts with the hash tags #cats #caturday or #catsofmastodon in the app while they are filtered in the web interface.

I have only tried with homepage filters, they are the only type that I use.

![Screenshot_20220521-225427.png](https://user-images.githubusercontent.com/30999326/169668638-05f6e5cf-f894-4af0-a69d-d3d3ffa661a4.png)
![Screenshot_20220521-225412.png](https://user-images.githubusercontent.com/30999326/169668645-12962665-e21b-40ef-b41a-c8b9893dbdbb.png)

**Comment by charlag** [comment]
I had this once, it worked after restart, could you check if it's the same?

**Comment by Discostu36** [comment]
After killing the app, deleting cache and opening the app again the problem is still there. Or did you mean device restart?

**Comment by charlag** [comment]
Hi, no, just the app restart. Something is definitely off.

**Comment by eposicee** [comment]
Please fix it. Filter NEVER work. Ever since people flooded in weeks ago I added three pages of filter words. I'm dying. I need it works or I can't even use mastodon.

**Comment by Minoru** [comment]
@eposicee If you've installed Tusky from F-Droid, you can install an earlier version where filters still worked, and wait for the fix. Nagging the developer just pushes them closer to burnout, so let's avoid that ;)

**Comment by charlag** [comment]
We are on it, sorry for not answering
