### ISSUE TITLE
UnifiedPush registration missing FEATURE_BYTES_MESSAGE

### ISSUE THREAD

**Issue by karmanyaahm** [tuskyapp/Tusky#2547]
https://github.com/tuskyapp/Tusky/blob/9ec5d6e3b032a582b6d95091e56122e80ae07c9c/app/src/main/java/com/keylesspalace/tusky/components/notifications/PushNotificationHelper.kt#L90

TL;DR I'm guessing that line just needs to be replaced to something like:
```kotlin
 UnifiedPush.registerAppWithDialog(context, account.id.toString(), features = [UnifiedPush.FEATURE_BYTES_MESSAGE]) 
```
, but I don't know Kotlin and don't have a build environment set up.

---

https://github.com/UnifiedPush/android-connector/blob/d9bf79a8dfe20d3ed85771f01c7fb706896a096a/connector/src/main/java/org/unifiedpush/android/connector/Utils.kt#L42-L51

The 'features' argument needs to be set to `[FEATURE_BYTES_MESSAGE]` as mentioned on the UP Android docs. This is because without this argument, UnifiedPush v1 distributors like Gotify-UP are still allowed. The problem with the existing v1 version of Gotify-UP is that when there's (certain types of, I haven't narrowed down what) binary data, it sends no notification at all, rather than sending a corrupted notification. Since Gotify-UP (probably) won't be updated, users might accidentally select it and will be confused about why their notifications don't work.

cc @PeterCxy

* * * *
- Tusky Version: Tusky Test (recent version, it doesn't matter which)
- Android Version: n/a
- Android Device: n/a
- Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by PeterCxy** [comment]
The reason I did not set `FEATURE_BYTES_MESSAGE` in the original PR is because of the fact that it actually worked for me on ntfy when it was still on v1... and I'm pretty sure Gotify-UP (kind of?) worked as well.

**Comment by karmanyaahm** [comment]
The problem is with the Go postgres database (probably doesn't happen with sqlite due to dynamic typing), which prevents Gotify with Postgres from working properly
```
gotify-linux-amd64[851]: 
gotify-linux-amd64[851]: (/proj/database/message.go:23)
gotify-linux-amd64[851]: [2022-05-22 02:55:04]  pq: invalid byte sequence for encoding "UTF8": 0x00 
```

Since the webpush message contents are bytes not UTF/Unicode strings, Tusky should request `FEATURE_BYTES_MESSAGE`
