### ISSUE TITLE
 Replace federated timeline with direct messages as default

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#2552]
I'd like to change the default tabs from [Home, Notifications, Local, Federated] to [Home, Notifications, Local, Direct] because I think it is more useful to new users.

Changing the default tabs will not interfere with the setup of already logged in users or remove any feature from Tusky.

Additionally, it might make sense to put timelines into the side menu when they are not set as tab (similar to how the search goes into the side menu when the toop bar is disabled).

Thoughts?

**Comment by charlag** [comment]
I think this is a good idea

**Comment by Doomsdayrs** [comment]
I disagree. Direct messages are second to federation.

You're more likely to communicate on federation via post replies then DM. And many instances rely on the federation for its content stream to react to, since they are small.

**Comment by Tak** [comment]
Is it feasible to make the tab bar scrollable and include all of them by default?

**Comment by charlag** [comment]
Nooo, that's bad!
It mightvbe subjective but I never got any value out of federated timeline. I can't say confidently what is more useful for new people

**Comment by Doomsdayrs** [comment]
> Is it feasible to make the tab bar scrollable and include all of them by default?

Navigation bars should never be scrollable, it violates material design guidelines.

> Nooo, that's bad! It mightvbe subjective but I never got any value out of federated timeline. I can't say confidently what is more useful for new people

While you might not be getting value, For the vast majority of instances federated is life and blood.

---

I personally believe this trend of trying to get rid of federated timelines is toxic to the federation.

The belief that it is "easier" for new users to not see the federation is catering to centralization, and Mastodon was built to be against centralization, as it is a *federated* platform.

--- 

A far more elegant solution is to simply append the navigation bar with a direct message icon.

**Comment by connyduck** [comment]
Of course we could just add the direct messages tab (at which position?), but I feel like 5 tabs is already very overloaded on small devices.

**Comment by a1batross** [comment]
Federated timeline is usually cluttered with random content. I can understand if users don't need it, direct messages are usually more useful.

But speaking about tabs, 5 tabs limit is not enough, I've increased the limit to 9 in my builds but actually never used more than 7, which is enough for most modern devices. Even with the narrowest screen aspect ratio, it isn't much of a problem.

**Comment by Doomsdayrs** [comment]
> Of course we could just add the direct messages tab (at which position?), but I feel like 5 tabs is already very overloaded on small devices.

I agree with @a1batross regarding 5 tabs, it is to be noted that material IO states the limit at 5 tabs, and after that it becomes excessive.

I have utilized small devices with Tachiyomi for example, and the 5 button navigation is not overwhelming. 

---

If you truly have concern for small devices, Consider providing legacy navigation, in which navigation is relegated into the side drawer. This of course is an issue for the future, as you will have to rearrange the UI of the drawer to compensate for 5 more items.

Point to state is that the navigation bar has never been an item in favor of small devices. It has always been an item to justify larger screens. A drawer navigation is what is useful for small screens.

**Comment by Buntbart** [comment]
I suggest adding a fifth icon. Many other apps like F-Droid, Fedilab or VLC do it this way and are not too cluttered. Users are already used to it.

**Comment by Doomsdayrs** [comment]
This should not be considered also due to that its a spelling point of Tusky now. Where people swap from the official limited app to Tusky for the federated timeline

**Comment by connyduck** [comment]
Another argument for removing the federated timeline from the default tabs is that it causes a lot of load for Mastodon servers.

> This should not be considered also due to that its a selling point of Tusky now. Where people swap from the official limited app to Tusky for the federated timeline

It won't be gone if it is not in the defaults anymore, 5 clicks and it is back.

**Comment by Doomsdayrs** [comment]
> Another argument for removing the federated timeline from the default tabs is that it causes a lot of load for Mastodon servers.

Can you provide statistics in regards to this? How does one provide statistics in regards to this? 

After all, a great deal of strain currently is related to thousands joining the fediverse as of late, so how much would statistics currently accurately represent the specific features impact?

**Comment by Doomsdayrs** [comment]
> > This should not be considered also due to that its a selling point of Tusky now. Where people swap from the official limited app to Tusky for the federated timeline
> 
> It won't be gone if it is not in the defaults anymore, 5 clicks and it is back.

You state that 5 clicks, as if that is trivial. Pushing the work onto the end user to figure things out when they wonder what everyone means by "the fediverse".

A better decision would be, after retrieving login details for the first time, ask the user *explicitly* if they want to see the federated timeline, and provide a proper warning in regards to enabling it. 
```
Would you like to enable the federated timeline?

This let's you see the all posts from all servers, not just your own. But there might be unacceptable content present that is not regulated by your server or the application developers.

YES NO
```

**Comment by Jonseed** [comment]
Yeah, finding and adding the federated timeline is difficult now. It's buried. Had to search around to find this thread to figure out how to add it to the navigation.
