### ISSUE TITLE
Tłumaczenie postów.

### ISSUE THREAD

**Issue by TurekCom** [tuskyapp/Tusky#2560]
Chciałbym zaproponować opcje tłumaczenia postów i komentarzy. Dużo jest wpisów na mastodonie w innych językach. Niestety nie ma łatwej opcji przetłumaczenia postów.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/134 
https://github.com/tuskyapp/Tusky/issues/2188
