### ISSUE TITLE
Failure to sync character limit from instance

### ISSUE THREAD

**Issue by AmberCronin** [tuskyapp/Tusky#2575]
Hi, I am a member on hellsite.site with a post character limit of 1000000. This character limit used to sync but stopped a couple weeks/months ago (can't remember the exact date). Now it only shows the default of 500. This persists after a relog. 

* * * *
- Tusky Version: 18.0
- Android Version: 12
- Android Device: Pixel 4
- Mastodon instance (if applicable): hellsite.site

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
That's weird, did the number change recently?

**Comment by AmberCronin** [comment]
Yes, it was somewhere around a month or two ago. I contacted my instance's admins right after posting this issue and apparently it's a known issue with the instance, so this might be a false alarm, sorry. Feel free to close this I suppose, haha.

**Comment by connyduck** [comment]
Yes, I remember talking to your admin. hellsite has a poll duration limit that is higher than what an Integer can store and so the whole instance configuration fails to parse.
