### ISSUE TITLE
Multi instance client loses ability to swipe update empty notifications tab

### ISSUE THREAD

**Issue by devnull69** [tuskyapp/Tusky#2582]
I've observed this behavior only when switching between instances

When the notification tab is empty on one instance and the user switches between instances, the empty notifications tab can no longer be swipe updated

* * * *
- Tusky Version: 18.0
- Android Version: 9
- Android Device: Huawei P10
- Mastodon instance (if applicable): several

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I don't think it has anything to do with multiple accounts, it is just not possible to refresh an empty notifications tab. Will fix, thx for reporting.
