### ISSUE TITLE
New App icon

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#2591]
I'd like to have a new app icon that is the head of our [elephant friend](https://github.com/tuskyapp/artwork/blob/master/art/tusky_elephant_friend.svg), kinda like the [avatar placeholder](https://github.com/tuskyapp/Tusky/blob/develop/assets/avatar_default.svg). 
I'm gonna commission [Dzuk ](https://dzuk.zone/) to see how that would look.

I think the current icon is really outdated and will not work well as [themed app icon](https://github.com/tuskyapp/Tusky/issues/2533).

**Comment by connyduck** [comment]
And here is the new icon 
![7ee92476d9bae218](https://user-images.githubusercontent.com/10157047/189540769-fa39dcf9-d0bb-4da1-a492-865ba23177ed.png)
regular - themed - notifications

**Comment by connyduck** [comment]
svg assets can be found at https://github.com/tuskyapp/artwork

**Comment by MagicLike** [comment]
Looks stunning! 😲
