### ISSUE TITLE
No warning before erasing drafts with "Re-login for push notifications"

### ISSUE THREAD

**Issue by digitalcircuit** [tuskyapp/Tusky#2593]
## In brief
* `Re-login for push notifications` wipes drafts and not synced account settings
  * Tusky doesn't warn before starting the process
  * Drafts and other not synced account settings (e.g. selected timeline tabs and order) are not restored afterwards
  * Exporting drafts is a manual process (no easy backup and restore)

### Steps
1.  Install Tusky v18.0 (or any version without support for push notifications)
2.  Sign into a Mastodon account
3.  Compose a new toot, then save it to `Drafts`
4.  Upgrade to Tusky v19.0 beta 1
5.  Go to `Account Preferences` and tap `Re-login for push notifications`
6.  Sign in again
7.  Once signed in, check `Drafts` and other not synced account settings

### Expected
*Either…*
A.  Tusky saves drafts and other account settings, restoring them after re-logging in

*…or…*
B.  Tusky warns that drafts (and other settings?) will be erased, providing an opportunity to cancel and manually copy one's drafts (an export option might be a nice future enhancement)

### Actual
Tusky does not warn that drafts will be erased and drafts are not restored after logging in.

## Extra details
In general, a way to easily export drafts (if not also import them) might be useful.  Arguably, Mastodon itself should support drafts and expose that over the API for cross-device support.

In my case, the drafts weren't critical and arguably I should've saved 'em elsewhere.  However, I imagine others might not expect this.

* * * *
- Tusky Version: `19.0 beta 1`
- Android Version: `12 (SQ3A.220605.009.A1)`
- Android Device: `Pixel 4 XL`
- Mastodon instance (if applicable): `vulpine.club`

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by codl** [comment]
Can confirm my drafts were also lost. The message explicitly says that drafts are migrated over so this is a bug.
