### ISSUE TITLE
Message schedule time is lost when saving draft

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#2616]
After saving a draft of a scheduled message and then reopening the draft, the scheduled time is lost.

Steps to reproduce:
- Compose message
- Set scheduled posting time
- Save the message as a draft
- Open the saved draft

Expected behavior:
The reopened draft preserves the scheduled posting time

Actual behavior:
The reopened draft does not preserve the scheduled posting time

* * * *
- Tusky Version: 19.0 nightly
- Android Version: 11
- Android Device: Pixel 2XL
- Mastodon instance (if applicable): glitch.taks.garden (glitch-soc 3.5.2)

- ✅ I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gryzor** [comment]
Should the Scheduled Posts show "scheduled drafts" too? (I think not)
Should the Drafts list show the scheduled date (if any)? (I think maybe, why not).
