### ISSUE TITLE
Retain thread while storing draft reply after send error

### ISSUE THREAD

**Issue by guerda** [tuskyapp/Tusky#2621]
I replied to a toot, it wasn't sent out due to an error but stored to the drafts. I resent it from the drafts folder and now it does not show up in the thread but as a separate toot. 
This feels like a bug.

It seems that in only occured as the sending failed. I tried to reproduce it by storing a reply to the drafts and the publush it. This worked out fine.
https://ruhr.social/@guerda/108667329801737436

Here's the original lost reply toot: https://ruhr.social/@guerda/108666907964379014​

I additionally found out that I could not tap on Android notification which stated that an error occured during sending and my toot was stored to the drafts.

**Comment by connyduck** [comment]
Can not reproduce, reply is correctly restored after sending failed, both due to network and server error. Maybe the original post that you wanted to reply to was deleted? Tusky should show a Toast in that case.

What version of Tusky did this happen on?
