### ISSUE TITLE
UnifiedPush notifications don't work at all

### ISSUE THREAD

**Issue by BlackLight** [tuskyapp/Tusky#2623]
I have installed the latest version of Tusky. I logged out and logged in again, as suggested by the instructions for UnifiedPush support. I saw a prompt that asked me whether I wanted to use ntfy or NextPush for notifications, and I opted for ntfy. Oddly, that screen is only shown once. Once you select an option, there's no way in the settings to change it.

I see the ntfy channel created in the ntfy app by Tusky, but no notifications are forwarded to that channel. When I receive a notification, my phone notifies me only when I open the app.

**Comment by connyduck** [comment]
Does ntfy work with other apps? Is it removed from battery optimizations?

**Comment by BlackLight** [comment]
@connyduck ntfy works (meaning that the device can receive real-time notifications) when I push notifications via the websocket API. ntfy has also the "Don't optimize" battery option ticket - does Tusky need to have battery optimizations disabled as well?

**Comment by binarydad** [comment]
I'm having this issue as well. I feel like ever since the version 19 RTM came out it seemed to have stopped working, mostly... I do, rarely, receive a notification from Tusky/NTFY, but it's not often when it otherwise should send a notification. 

In my case, I also u se NTFY for Element/Matrix, which seems to work fine. 

Today I'm going to load up the UP URL in my browser and see if there's a disconnect between my Mastodon instance -> NTFY server, or from NTFY -> Tusky app.

**Comment by binarydad** [comment]
As a test, I opened the ntfy interface in a browser and subscribed to the same topic as the one on my android phone. I waited for a reply and noticed that the notifications populated instantly, but nothing showed up on the phone, even after the Tusky app was recently opened. 

Seems like a disconnect between the ntfy app and Tusky. And as mentioned, Element (which is also using ntfy on the same android device), works just fine for notifications. 

Hope this helps. Let me know what else I can provide or troubleshoot. Thanks!

![image](https://user-images.githubusercontent.com/1760607/181587815-411a0686-3b9d-493b-84e9-d63ecc178076.png)

**Comment by binarydad** [comment]
I did a reinstall of the app and so far it's working, so I'm keeping an eye on it. I'll comment later if it's still working fine. 

@BlackLight, have you tried reinstalling the app?

**Comment by BlackLight** [comment]
@binarydad it's also working for me now. I did two things:

- Reinstalled the app
- Ticked the "Don't Optimize" option in the battery section

I'm not sure which one did the trick though.

**Comment by binarydad** [comment]
Same. I too did both of those steps. All good now.

**Comment by motoridersd** [comment]
How do I know which notification service I am using? I get push notifications with Tusky, but they tend to be very delayed. 20-30 minutes. I am testing other Mastodon Android apps, and the ones using FCM get notifications much faster (assuming Tooot and Fedilab use Google's code vs a pull). I understand the choice to not use Google code for the notifications, so I'm wondering if I should be getting notifications as fast as the other apps that are probably using FCM or are Tusky's always going to be slower?

**Comment by karmanyaahm** [comment]
@motoridersd If you install a [UnifiedPush distributor](https://unifiedpush.org/users/distributors/), you can get instant notifications.

**Comment by roughnecks** [comment]
Sorry but I didn't want to open a new issue for this problem..

I just installed Tusky from F-Droid and I'm already using ntfy with Schildichat, but I don't see any option in Tusky to choose push notifications provider. I also logged out and back in as suggested by @BlackLight to no avail.. So how do I set this up?

Thanks

**Comment by karmanyaahm** [comment]
Does Tusky show up in the ntfy topic? If so, it's registered

**Comment by roughnecks** [comment]
oh yes, it did it without me touching anything. Thanks!

Il 3 febbraio 2023 20:27:28 CET, Karmanyaah Malhotra ***@***.***> ha scritto:

**Comment by teohhanhui** [comment]
There should be a way to troubleshoot notifications / diagnose notification issues like what Element Android has (and actionable next steps like re-registering when it does detect problems). Otherwise the user is left wondering whether their notifications still work...
