### ISSUE TITLE
Accessibility: keep draft image descriptions

### ISSUE THREAD

**Issue by davidbtc2009** [tuskyapp/Tusky#2626]
It is too easy to close the image description box and loose the text you have entered for the description by accidentally tapping outside of the dialog. The current text should be saved unless the "cancel" button is pressed

* * * *
- Tusky Version: 19
- Android Version: 11
- Android Device: Motorola One 5G Ace
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
fixed by https://github.com/tuskyapp/Tusky/pull/2693
