### ISSUE TITLE
crash on ipv6 only instances

### ISSUE THREAD

**Issue by davidbtc2009** [tuskyapp/Tusky#2631]
Tusky totally crashes when using an ipv6 only instance

1. Create an account on https://ipv6.social
2. Once verified log in with tusky (login flow works fine)
3. As soon as the home timeline view loads tusky crashes every time

* * * *
- Tusky Version: 19
- Android Version: 11
- Android Device: Motorola One 5G Ace
- Mastodon instance (if applicable): https://ipv6.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That has nothing to do with ipv6, the server is misconfigured. Tell you admins they need to generate vapid keys. https://docs.joinmastodon.org/admin/config/

**Comment by telmich** [comment]
@connyduck Thanks for the pointer. I'm the admin of ipv6.social and just enabled the VAPID keys!

**Comment by davidbtc2009** [comment]
Yep, that solved the problem
