### ISSUE TITLE
Display if user is admin

### ISSUE THREAD

**Issue by MagicLike** [tuskyapp/Tusky#2645]
Display an "Admin" badge on the profile, if the user is administrator.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
We would love to, but it looks Mastodon still does not expose this information through the api, so we can not.

**Comment by MagicLike** [comment]
I just opened an issue at mastodon to expose the Admin status to the API.

**Comment by Tak** [comment]
Needs server side support
