### ISSUE TITLE
Pressing "<user> requested to follow you" android notification sends user to wrong UI

### ISSUE THREAD

**Issue by pespin** [tuskyapp/Tusky#2655]
Pressing "<user> requested to follow you" android notification doesn't present the user with the "Follow Requests" UI. Instead, it presents it with the "Notifications" UI, but I'm not sure this is always the case, it could be another too.

This is really confusing from user point of view because there's nothing to do in the "Notifications" UI. Then the user needs to remember to go press the menu app button, and go to the "Follow Requests" UI, then remember the user which showed up in the notification and press the user in the list to finally be able to accept or not.

When the "<user> requested to follow you" android notification is pressed, the user shoul be presented either with:
A) The "Follow Requests" UI
B) The user's profile, where the "Accept Request" + "Follow" buttons should be available.

* * * *
- Tusky Version: 19.0
- Android Version: 11
- Android Device:
- Mastodon instance (if applicable): mastodon.social

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeyemwey** [comment]
Hi, just wanted to bump this issue back up, this issue makes me shake my head far too often, even after using Tusky for almost 3 years now. :/
