### ISSUE TITLE
[Friendica] Navigation to hashtags / profiles doesn't work?

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#2657]
Using Tusky for talking to Friendica, it seems both hashtags (#) and accounts (@ mentions) are somehow "mixed up": They appear as links in the app but they don't toggle profile or hashtag view in the app (as they do while using Mastodon) but apparently are full HTTP URIs pointing to (profiles) the user profile URL on its home instance or (hashtags) an URL to search the particular friendica instance for these hashtags. Sample: 

![tempFileForShare_20220808-112409](https://user-images.githubusercontent.com/685879/183385717-d57fccb7-8efe-4bfa-8d10-23db3cee59f0.jpg)

In this case, for my instance, clicking on "photo" will get me to https://instance/search?tag=photo .  Is there some way in Tusky to work around this? Seems it's a Friendica specialty yet still it would be cool to have this work well. :)

* * * *
- Tusky Version: 19.x Test
- Android Version: Samsung M51
- Android Device: Android 12
- Mastodon instance (if applicable): Friendica loma.ml

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That is because friendica does not include the # and @ in the link which Tusky uses to detect if it is a hashtag/mention or a standard link.

**Comment by kr428** [comment]
Is there any way (or motivation) to work around this on Tuskys end? Or should it be modified by Friendica then?

**Comment by connyduck** [comment]
I'd like Tusky to be compatible with Friendica and i could fix it in Tusky but having the #/@ not part of the link is really weird and I think it would be better if it was fixed on Friendicas side. Can we get a Friendica dev to comment on this?

**Comment by kr428** [comment]
Ok, thanks. Created a corresponding issue with Friendica, hope someone will be able to look into this and provide some feedback here.

**Comment by MrPetovan** [comment]
Hi @connyduck , this is an accurate analysis, we intentionally do not include the #/@ (and !) characters inside the mention link, I assume for aesthetics purposes. This means we have to convert inbound mentions to our format, and convert outbound mentions to the expected target platform format.

We could switch the Friendica API from one format to another but it would be a backward-breaking change so I'm not very comfortable with the idea. Do you mind chiming in @annando ?

**Comment by connyduck** [comment]
Ok so let's fix it on Tuskys side then. If anyone wants to take this over, feel free to do so, I don't know when I will have time for it.

**Comment by annando** [comment]
@MrPetovan Question is if there are other systems that expect a different behaviour. AFAIK we have got a separate mode for our BBCode for API posts.

**Comment by MrPetovan** [comment]
Yes, but we don’t discriminate by client, so if we switch for API posts, it would also affect Twidere, Friendiqa, etc…

**Comment by kr428** [comment]
For the tests at least of Mastodon clients with Friendica I did, it seems most of them behave just the way tusky does here, maybe except for recent fedilab that also seems to take care of that by itself...

**Comment by annando** [comment]
We can add this behind some config variable, so that this can be tested until we are sure that it can be used per default.

**Comment by MrPetovan** [comment]
Can you test with all the Mastodon-compatible clients?

**Comment by kr428** [comment]
> Can you test with all the Mastodon-compatible clients?

Can offer testing for tusky, fedilab, andstatus, tooot, fedi, twidere (x) and subway tooter if needed; these are the ones I'm aware of. However I don't have an instance of my own so which one should I connect to test that against?

**Comment by MrPetovan** [comment]
Thanks for the offer, now someone™️ has to create this config switch to enable tests on the develop branch.

**Comment by kr428** [comment]
Seems fixed in Friendica dev, meanwhile with the recent Tusky Test build against released Friendica this has become somewhat worse:

![Screenshot_20221107-190823_Tusky Test](https://user-images.githubusercontent.com/685879/200391338-3d87cd85-bb04-4a88-a95e-72913d202979.jpg)

**Comment by connyduck** [comment]
Ok this is hilarious @Tak

**Comment by Tak** [comment]
Yeah, this is kind of a pathological case 😬

**Comment by kr428** [comment]
Apparently that's how it currently works in Friendica - hashtags and profiles generally seem to be full links to the actual instance - so it might be required, in this case, to strip off the actual links and only use the link text if it starts with # or @?

**Comment by annando** [comment]
It would be best, if Tusky had a look for the `rel="tag"` in the link to detect that this is a tag.

**Comment by kr428** [comment]
> It would be best, if Tusky had a look for the `rel="tag"` in the link to detect that this is a tag.

Is there something similar for profiles too? Not really sure how the data looks in the message, here.

**Comment by Tak** [comment]
> Apparently that's how it currently works in Friendica - hashtags and profiles generally seem to be full links to the actual instance - so it might be required, in this case, to strip off the actual links and only use the link text if it starts with # or @?

…but that's the problem - the link text *doesn't* start with `#` in this case

**Comment by kr428** [comment]
> > Apparently that's how it currently works in Friendica - hashtags and profiles generally seem to be full links to the actual instance - so it might be required, in this case, to strip off the actual links and only use the link text if it starts with # or @?
> 
> …but that's the problem - the link text _doesn't_ start with `#` in this case

Ah ok, wasn't aware of that. In this case, maybe go for @annando s recommendation and really evaluate the rel - attribute here? Seems the most robust approach I'd say.

**Comment by MrPetovan** [comment]
No, our hashtag links are `#<a>text</a>` by convention.

**Comment by kr428** [comment]
@MrPetovan Maybe slightly off: Is this something covered by activitypub standard in some way? Also, wondering how this has been fixed or addressed in the Friendica change linked above? Will this particular problem cease to exist once Friendica instances have moved to the next release...? Reading the code / changes, I'm unsure...

**Comment by Tak** [comment]
The new link domain advertisement behavior should *also* be fixed by the new behavior in https://github.com/friendica/friendica/pull/12122 - if somebody has a link to a post on a server with the changes, I'm happy to verify

**Comment by kr428** [comment]
(If that stuff works for both profiles and hashtags in the coming Friendica version, I'd close this off as fixed. Would be good to know that, though. 🙂️)

**Comment by kr428** [comment]
As most of the Friendica instances seem still on 2022-10, I assume this won't see a tusky-side fix anymore for release 20...? At the moment, this setup isn't really fun... 😉
