### ISSUE TITLE
[Friendica] Favourites aren't correctly displayed

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#2681]
Recent tusky nightly with Friendica: Whenever I add a favourite to a post, this is apparently stored on the server (verified by using the web interface) but not updated in tusky. I wonder whether this could be caused by this behaviour that also caused trouble with recent fedilab build:

https://github.com/friendica/friendica/issues/11604#issuecomment-1147489405

Or is this a different issue on tusky?

**Comment by connyduck** [comment]
Favouriting posts works as expected with my account on opensocial.at.

Please give me additional details, which server are you on, what are the exact steps you took for the error to occur, Tusky version and so on

**Comment by kr428** [comment]
I'll try with opensocial.at then. Again, noting: Favoriting posts works. It just doesn't immediately update in tusky nightly (all of them, recently). Using several friendica instances for testing (loma.ml, squeet.me, ...).

**Comment by connyduck** [comment]
Again, it works for me. opensocial.at, home timeline, freshly logged in, Fairphone 4, Android 11, Tusky 19.0-c638ad7e. Clicking on any post, it is favourited as expected.
So please tell me more about what exactly you are doing (maybe provide a video) and your setup or I have no chance at finding the problem.

**Comment by kr428** [comment]
Let's see if this works:

https://anonymfile.com/oBxe/screen-recording20220906-165707tusky-test.mp4

**Comment by foss-** [comment]
@kr428 can you provide more context? Version of app you are using, version of OS, device, link to post that can be seen in video, etc?

**Comment by kr428** [comment]
Yes, of course. Android 12 on a Samsung M51. Stock ROM. Tusky 19.0-c638ad7e (but it is happening the same way with the current stable version on Play or F-Droid, as it has been happening with every version for as long as I can remember). Instance is Friendica 2022.06 hosted at loma.ml. Link in the video: Will look this up but it doesn't matter. This effect can be reproduced with every post I encounter in this setup. Behaviour is always the same:

- Tap on "star" -> star will turn "yellow".
- Reload -> "star" is "empty" again.
- Check the entry -> the favourite is displayed but the "star" is still empty.

I don't really know what other information to provide or how else to describe this... It's not a "blocker" as it does send the favourite correctly it seems, but it makes the app a little less usable because you never know. 😔️

**Comment by foss-** [comment]
Did some brief testing and could not reproduce, but the friendica instances I am testing on are running 2022-09dev.

**Comment by kr428** [comment]
Seems fixed in 2022-10, tested on loma.ml.
