### ISSUE TITLE
Indicate that the link is hypertexted or it is the real address that is rendered as a link

### ISSUE THREAD

**Issue by mmahmoudian** [tuskyapp/Tusky#2694]
## The problem

Considering that there are plenty of services use ActivityPub and many let the user to create hyperlinks for part of the text, it is possible to have something like `<a href="https://malicious.url">https://safe.url</a>` and it would render it as [https://safe.url](https://malicious.url). Therefore, user would not know that what they are clicking on will take them. A less malicious thing would be to hide some tracking code but the text only shows the main website.

## My suggestion

Show an icon at either end of the link to indicate that the link is hyperlinked text and is not a URL that is rendered as a link in Tusky.

* * * *
- Tusky Version: 19.0
- Android Version: -- Not Applicable --
- Android Device: -- Not Applicable --
- Mastodon instance (if applicable): -- Not Applicable --

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
fixed by #2698
