### ISSUE TITLE
Confusing UI wording when editing scheduled post

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#2704]
Tried editing a scheduled post and the language confused me.

**Observed behavior:**

Wrote a post. Tapped "schedule". Scheduled for 1 week. Went into left side bar, scheduled posts, clicked the pencil. Changed the text. Backed out.

[<img width="300" src="https://user-images.githubusercontent.com/277318/191592117-8a27daa1-4682-46ab-9f1f-42eb747ca6e9.png"  />](https://user-images.githubusercontent.com/277318/191592117-8a27daa1-4682-46ab-9f1f-42eb747ca6e9.png) [<img src="https://user-images.githubusercontent.com/277318/191592074-4b8491c5-4fe6-4ca2-8826-78d9a12fed5c.png" width="300" />](https://user-images.githubusercontent.com/277318/191592074-4b8491c5-4fe6-4ca2-8826-78d9a12fed5c.png)

The post button read "toot". The back out dialog asked if I wanted to "Save a draft" and said "Delete" and "Save".

**Problems:**

Minor: Button saying "Toot" would be more accurate saying "Update" or "Save"

Major: Back out dialog is inaccurate. It's really asking if you want to save your *changes* to the scheduled tweet. Moreover, **neither button does as it says.** "Delete" does not delete and "Save" does not save. In either case you return to the scheduled posts listing with your changes discarded.

**Expected behavior:** In addition to maybe altering the "Toot" button, the dialog should reference a scheduled post rather than a draft. The buttons should be changed in any of the following ways:

1. Text should ask if you want to save changes to scheduled post. Buttons should say "Discard" and "Save"; clicking one should discard changes and the other should save them.

2. Text should ask if you want to save changes to your scheduled post. Buttons should allow continuing to edit the post and discarding changes.

3. Buttons can stay the same but the functionality really should either delete or save the post. (This is my least preferred option personally but it would match the behavior with drafts.)

* * * *
- Tusky Version: Self built develop branch 7684f06938
- Android Version: 12
- Android Device: Sony Xperia 5 III USA
- Mastodon instance (if applicable): Mastodon dot social

**Comment by mcclure** [comment]
More small thoughts:
- The "TOOT!" button is maybe correct because if you remove the schedule from the scheduled tweet it does just become a normal toot that you are tooting. But it still confused me a little.
- I say above if you click "Save" on the scheduled tweet nothing happens. This is wrong, it actually does save it as a draft. But that is not desirable either because now you have two copies of the post, one in scheduled posts and one in drafts.

**Comment by nikclayton** [comment]
I'm working on this -- there are similar problems with how discarding edits to drafts are handled. PR to come...
