### ISSUE TITLE
UnifiedPush multiple entries 

### ISSUE THREAD

**Issue by Tealk** [tuskyapp/Tusky#2707]
I have newly switched to UnifiedPush(ntfy) and have two entries for tusky?

* * * *
- Tusky Version:19.0
- Android Version: CalyxOS 4.1.4
- Android Device: Pixel6
- Mastodon instance (if applicable): rollenspiel.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Are you logged in with two accounts in Tusky? Then this is expected.
