### ISSUE TITLE
Creating a new post with image: if status check fails it will try forever

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#2714]
When creating a new status with an image, first the image will be uploaded.
After that an image description and status text can be entered.
Now when sending that status this will be shown as a notification "sending..." forever. And no status is actually created on the instance.

Technically:
The code in SendStatusService#sendStatus (serviceScope.launch) will try to get the status in a loop.
Here only 200 http code is checked and accepted.

There is no time or retry limit.
Especially I suspect that the only other acceptable return code here would be 406.
Everything else should lead directly to an error?

Currently my instance returns here a 422 code.

* * * *
- Tusky Version: newest develop version (8th of October); relevant code didn't change in recent history

**Comment by connyduck** [comment]
Yes that should work differently indeed.
I think the correct way would be 
1) proceed on 200
2) retry on 201 or networking errors
3) fail on any other statuscode
