### ISSUE TITLE
Lists - why error message "nothing here"?

### ISSUE THREAD

**Issue by gitbq** [tuskyapp/Tusky#2717]
I am new to tusky and mastodon in general. It appears nearly impossible to get any clear documentation on how some features work.

I assume lists should allow me to view certain accounts only at the same time. For example i could put my "news" feeds in the same list, then when i open that list, i should see all the news feeds only as a timeline. Is that right?

Whenever i open a list it spread the message "nothing here". Is there a reason for this?

Thanks again.

* * * *
- Tusky Version: 19
- Android Version: 13
- Android Device: pixel 4
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
}

**Comment by connyduck** [comment]
Yes, lists work like that but I think you will only see the posts that an account made after it was added to the list. So a freshly created list will always be empty until the first account in the list makes a new post.

This is a Mastodon thing btw, Tusky is just the frontend that displays whatever it gets from the Mastodon server.
