### ISSUE TITLE
Muting a post does not remove it from timeline

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#2726]
In my testing, if I tap … on a post in my Notifications and hit "Mute", it successfully mutes the person, but the posts already in the notifications feed don't go away. This differs from mastosoc behavior and @connyduck says it is different from Tusky's spec'd behavior. Conny also says that this may be fixed by the upcoming notification fragment refactor. Filing this here so it is recorded, we should remember to re-test this if notification refactors land.

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: Sony XPeria 5 III
- Mastodon instance (if applicable): mastodon dot social

**Comment by nikclayton** [comment]
Can you reproduce this with https://github.com/tuskyapp/Tusky/pull/3159 ?

**Comment by mcclure** [comment]
Will reply in #3159
