### ISSUE TITLE
Suggestion: Store backup of Following list in the client

### ISSUE THREAD

**Issue by lethargilistic** [tuskyapp/Tusky#2731]
A friend of mine was Very Concerned about switching to the Fediverse because they were worried about what happens when a network hypothetically goes down, especially the fact that they would lose the list of people they were following. I analogized the Fediverse to email and explained the key difference. Fediverse services store the list of people you follow within the server (in a way only facially similar to corporate social networking) because that information is necessary for the server's federation feature. Email servers do not federate, so they don't need to store your contacts, so they don't--your email client is where your contacts are. And we think that's fine because we don't expect email to do something completely unnecessary. (Or we use free email and the server does keep our contacts because we're being tracked exactly like on corporate social networking, but you know what I mean.)

Which got me thinking. Why _don't_ Fediverse clients store your contacts in case an instance goes down? Has that been considered for Tusky?

**Comment by charlag** [comment]
Most fediverse servers support export of your followers/following lists, doesn't it help with the situation of a server disappearing?

**Comment by lethargilistic** [comment]
Imagine the Fediverse server has already gone down. You cannot export a list of the people you are following from a server that does not exist anymore.

Maybe this needs a point of clarity: I'm not talking about moving Following list _from_ the server to the client. I'm talking about storing a second, _backup_ copy of the Following list within the client. Maybe tucked away in the options menu or something.

**Comment by lethargilistic** [comment]
Or, even: When we tell people to export their followers list in case the server goes down, we are basically telling them to store it as a text file on their computer somewhere. That is sensible advice from a Fediverse _server_ project like tech.lgbt. However, Tusky is a Fediverse _client_ project.

Why would client software tell you to export data from the server and store it elsewhere?

**Comment by charlag** [comment]
I think that "server going down" and backups are server problems after all.
We would need to build a lot of things just for this specific case and there's not even an API to follow accounts end masse.
I won't argue further but I see this as out of scope.

**Comment by connyduck** [comment]
Definitely out of scope
