### ISSUE TITLE
[Feature request] two separate tabs for mentions and notifications

### ISSUE THREAD

**Issue by Wurzelmann** [tuskyapp/Tusky#2735]
I'd love to have a tab with separate mentions and notifications, respectively two separate tabs for them. Currently, there's one notification tab which can be filtered, but re-applying the filters to change the type of notifications is annoying IMO. Thanks in advance!

* * * *
- Tusky Version: Version 19.0
- Android Version: 12 (LineageOS 19-20221025-NIGHTLY-dumpling)
- Android Device: OnePlus 5T
- Mastodon instance (if applicable): -

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by thebino** [comment]
possible duplicate: #2378

**Comment by Wurzelmann** [comment]
Damn, sorry about that. Yes, I want exactly what you did in your mock up.
