### ISSUE TITLE
Application crashes when switching tabs on second account

### ISSUE THREAD

**Issue by rakoenig** [tuskyapp/Tusky#2736]
Have setup 2 accounts, the primary works as expected. 
On the secondary account Tusky crahes every time I try to switch from the "home" tab to another tab. 

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Google Pixel 7
- Mastodon instance (if applicable): primary = augsburg.social  secondary = pixelfed.de

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Probably a bad (=not conforming to api specs) notification. Since it is pixelfed the problem is likely on their side. We would need the stacktrace or api responses in order to investigate this.

**Comment by rakoenig** [comment]
Agree with you, also Fedilab crashes the same when switching to the notification tab. The only difference is that Fedilab is able to access the local und public timeline while Tusky is crashing there too. Will see if I can resolve this issue with pixelfed.de. Thanks.
