### ISSUE TITLE
with hashtag search, make current text entry always top of list

### ISSUE THREAD

**Issue by Eli-the-Bearded** [tuskyapp/Tusky#2739]
Search hashtags for `#fun`

Expected behavior: see results for that hashtag.

Actual results: Instead I see a list of hashtags that I can click (touch) for results. Okay, kinda get that. But `#fun` is not anywhere I can find it in the results. I don't know how it is ordered, but random seems likely. The list goes on longer than I care to scroll, but starts like this:

![screenshot evidence](https://i.imgur.com/3mFa9b4.jpg)

None of the first page of suggestions seem to have results. (Funeral Twins? Do I want to know)

Search posts for `#fun`

Expected behavior: see results with that hashtag

Actual results: "No results" page

Search posts for `fun`

Actual results: first response is a `#fun` hashtag second is a post (from me) using that word, but no hashtag

![screenshot evidence](https://i.imgur.com/JVlhE5q.jpg)

* * * *
- Tusky Version: 19.0
- Android Version: 11
- Android Device: oneplusn10
- Mastodon instance (if applicable): mstdn.io (not sure if applicable)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by sammykatta** [comment]
Same issue here on Tusky 19.0/Android 13 on mastodon.social - I believe the exact text match for the hashtag should be at the top. I don't particularly mind the random ordering for everything after that, since it's good for discovery of new hashtags that I might not have thought to search.

**Comment by connyduck** [comment]
This seems to be an instance specific thing. On chaos.social (Mastodon 3.5.3) it works fine both on web and on Tusky, on mastodon.social (4.0.0-rc1) the searched tag is indeed not at the top, again both web and Tusky.
I think a Tusky bug can be ruled out.
I'd say this is a Mastodon 4.0.0-rc1 problem, but apparently it also happens on mstdn.io which is 3.5.3 as well 🤔

**Comment by connyduck** [comment]
Yes, Mastodon bug confirmed https://github.com/mastodon/mastodon/issues/19575 https://github.com/mastodon/mastodon/issues/17494
Apparently only on instances that use Elastic Search
