### ISSUE TITLE
If posting with an image takes a long time, the post+image can be lost with user not informed

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#2740]
On 2022-Oct-31 mastodon.social was under heavy load due to the Twitter buyout and attempts to post images could hang for many minutes, or indefinitely. Tusky reacted incorrectly to the long delays.

Repro steps:
- Attach an image to a post
- Immediately tap "Post"
- This screen appears
    [<img width=300 alt="Finishing server upload..." src="https://user-images.githubusercontent.com/277318/199138227-fcc3108e-37db-4320-9cd2-af7d8d1e1e93.png">](https://user-images.githubusercontent.com/277318/199138227-fcc3108e-37db-4320-9cd2-af7d8d1e1e93.png)
- Press the Android "Home" button to go to the home screen. Wait a bit
- [[ In the background: the Tusky client gets oomkilled ]]
- Reopen Tusky

Assuming the server is taking long enough to accept an upload that the upload has still not completed, at this moment the **OBSERVED BEHAVIOR** is that when Tusky reopens, the screen flashes as if the Tusky app is rebooting and the feed is shown. The post does not get posted and in fact is **permanently lost**. There is no way to recover the text and if the image you uploaded was a crop created with "create image", there is no way to recover the image because we only keep our crop images in temporary storage.

**EXPECTED BEHAVIOR**

My **minimum expected behavior** is that when the post gets lost, Tusky notices it, moves the post to "Drafts", and on next boot pops up a warning saying a post failed to post.

A **best case expected behavior** is that Tusky continues attempting to make the post after uploading, and only falls back to "draft + notify" if the post outright fails. It is kind of irritating that you have to keep your phone looking at Tusky's "uploading..." box and not switch to another app, and there is no notification to the user that they need to do this so they are likely to switch away assuming it is safe. @connyduck made the observation in discord: "It would be extremely awesome if we could handoff uploading from that screen to the service when user hits send, but that is probably very complicated". But if this is complicated we should at least warn the user they lost a post.

**CONFIGURATION**

I tested and saw this with both version 19.0 on my main account and develop branch 5887af37721b (20.0 prerelease) on my test account.

I also saw an unusual variant on older develop branch commit 85a6b2d96be8 where [the post did appear on mastodon.social after Tusky was closed, but the image was stripped away](https://mastodon.social/@mcc_test_tusky/109264122068656974). This is the worst possible behavior (if we fail we should fail cleanly rather than posting a malformed post) **BUT** @connyduck believes this could have been because that test did not include the fix in 2481bc0523f4.

All testing was on Android 12 on Sony Xperia 5 III on mastodon.social.

**Comment by ateuber** [comment]
I also experienced the stripped away image with Tusky 19.0 on Android 12.

**Comment by mcclure** [comment]
In testing this is fixed by #2947, although as I posted there 2947 has other problems.
