### ISSUE TITLE
German translations of action_reblog and action_unreblog are confusing

### ISSUE THREAD

**Issue by alexs77** [tuskyapp/Tusky#2742]
The german translations of the actions `action_reblog` and `action_unreblog` are:

```xml
    <string name="action_reblog">Teilen</string>
    <string name="action_unreblog">Boost entfernen</string>
```

This is confusing, as not the same words are used. When something is "reblogged", Tusky shows a prompt, asking if the toot should be "Teilen" (shared).

To undo that, by clicking on the button again, `action_unreblog` is invoked. But, according to what's shown on screen, a different thing is done: "Boost entfernen" (remove boost).

Unless the user is aware of the inner workings of Mastodon, this is confusing - undo does a different thing then the do action.

* * * *
- Tusky Version: commit 5887af37721b99e39d362530ba0d9580fe801786
- Android Version: n/a
- Android Device: n/a
- Mastodon instance (if applicable): n/a

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
You can change the translation yourself on https://weblate.tusky.app if you want

**Comment by alexs77** [comment]
Didn't I do that in the PR?


Am Mi., 2. Nov. 2022 um 12:55 Uhr schrieb Konrad Pozniak <
***@***.***>:

**Comment by connyduck** [comment]
Oh sorry, missed that one. Preferred way to change strings is via Weblate but PR works as well.

**Comment by alexs77** [comment]
Gotcha 😁
Next time, I'll use weblate.

Konrad Pozniak ***@***.***> schrieb am Mi., 2. Nov. 2022,
13:29:

**Comment by alexs77** [comment]
You don't see it?

![image](https://user-images.githubusercontent.com/781361/199499512-b3acf0ae-54d0-4676-899e-d96442c6d9ce.png)

**Comment by connyduck** [comment]
It is a commit, but not a pull request I can merge

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2760/
