### ISSUE TITLE
[Feature request] make copying handle from profile to clipboard easier

### ISSUE THREAD

**Issue by trutzig89182** [tuskyapp/Tusky#2744]
Hey, I am using Tusky with multiple accounts. Every now and then I get on a profile, which I want to follow from one of my other accounts. This is quite complicated. I think one simple thing could make it more comfortable. 

I suggest, that a long click on the handle in the profile, or on the handle/username of a currently active post, copies the handle to the clipboard. Then it would be possible to simply switch the account and copy the handle to the search field.

An alternative could be to add  a "copy handle" option to the dropdown menue that opens, when you click the three dots in the profile.

* * * *
- Tusky Version: 19.0
- Android Version: 11
- Android Device: Fairphone 4
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Isn't it easier to pick `Open as…` from the context menu of either the post or the profile?

**Comment by fbatschi** [comment]
What about a small icon or three dots drop-down next to the follow button where you could choose the account to follow from? (Given you have more than one account added)

**Comment by trutzig89182** [comment]
Hi @Tak and @fbatschi, thanks. Not my brightest day apparently, I did not understand that this option would do that, even though in retrospective it is only logical. I close the issue.
