### ISSUE TITLE
Can't access main menu/preferences after disabling header

### ISSUE THREAD

**Issue by wjt** [tuskyapp/Tusky#2749]
Today when installing Tusky on a new device and moving the tab switcher to the bottom, I decided to try the "hide top bar" option. (I can't remember what it's called.)

Once I left the preferences page, I realised that the menu button lives on the top bar, so it is now apparently impossible to access the preferences and turn the option back off.

![Screenshot_20221105-114245](https://user-images.githubusercontent.com/86760/200118869-82d62377-94aa-479c-b615-60ddbabaf6b0.png)

* * * *
- Tusky Version: 19.0
- Android Version: 
- Android Device: Google Pixel 3

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
You can long press the side of the screen and the menu will appear.

**Comment by wjt** [comment]
How is one supposed to discover that?

**Comment by wjt** [comment]
(I can't figure out where to long-press. Swiping from the side of the screen triggers the system Back gesture. I have long-pressed every widget on the screen.)

More generally, is a "break my app" preference really advisable?

**Comment by kyori19** [comment]
@wjt 
Do not swipe, hold until side menu appears.
Refer other duplicates below.

@connyduck 
We should show some instructions about how to open the menu before enabling this option as similar issues are raised periodically.
I think maintainers should not be troubled by such issues.

duplicate of #2481 #2473

**Comment by wjt** [comment]
Even knowing how to do it, it's almost impossible to trigger, and I have the system back gesture sensitivity set to its lowest level. (And in my experience fro

**Comment by connyduck** [comment]
We will probably do something like [this](https://github.com/tuskyapp/Tusky/blob/3fb766fc68cee4c742264c390015a6521c28e9e7/fastlane/metadata/android/en-US/images/phoneScreenshots/01_timeline.png) again, but we'll discuss this in another place

**Comment by giltayar** [comment]
My 2 cents. I had to get to this issue to figure out how to show the menu. And even then it works like 30% of the times I've tried, so I've te-enabled the top bar.

Saying it so you'll have feedback. I understand this is not my project. And thank you for a great client.
