### ISSUE TITLE
Expanded message collapses when favourited

### ISSUE THREAD

**Issue by ashemedai** [tuskyapp/Tusky#2758]
(Note: Doing this from GitHub mobile, so apologies if I miss something. It doesn't support templates on issue creation, so I copied from another issue and fixed it up.)

When you encounter long messages, the ones where the `show more` prompt triggers, and expand the message by tapping the button, you now have the full message. However, when you then favourite the message, it will collapse the message back to the first `show more` prompt.

---

Tusky Version: 0.19

Android Version: 12

Android Device: OnePlus 8T

Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Where does this happen? Everywhere, in some kind of timeline, on profiles, in details?

**Comment by ashemedai** [comment]
@connyduck Thanks for reminding me to add that. In this particular case I was in a thread of messages that I found via someone's profile.

**Comment by connyduck** [comment]
I can not reproduce it with content warnings, but with "show more" buttons that are inserted into long posts, with Tusky 19.
The issue does not appear in a recent build, I think it was fixed with https://github.com/tuskyapp/Tusky/pull/2617

**Comment by ashemedai** [comment]
@connyduck Alright, thanks for verifying. I'll close this for now then.
