### ISSUE TITLE
Add option to edit posts

### ISSUE THREAD

**Issue by sl1txdvd** [tuskyapp/Tusky#2759]
With Mastodon 4 there is the option to edit a post after it has been posted. Tusky should support it.

* * * *
- Tusky Version: 19
- Android Version: LineageOS 19 (Android 12)
- Android Device:
- Mastodon instance (if applicable): mastodon.social and all others running Mastodon 4 RC1 and later

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by beyond9thousand** [comment]
Yes hopefully this will be added soon

**Comment by stpierrevincents** [comment]
Excited for this! ♥️

**Comment by buckysrevenge** [comment]
Looking forward to seeing this addition 👍

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2828
