### ISSUE TITLE
Stuck notification

### ISSUE THREAD

**Issue by ratcatcher** [tuskyapp/Tusky#2762]
Tusky 19.0
Android 11
Moto G 5G
mastodon.ie

I tried to post a toot with an image.  The notification just sat there saying it was posting.  After a while I gave up and hit cancel.

The notification changed to one telling me that posting had been cancelled and that a copy had been saved to my drafts folder.

Clicking on that notification does nothing.  It doesn't take me to my drafts folder as expected (or open Tusky at all).  There is no way to clear the notification other than by forcibly stopping Tusky.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thank you for reporting! This is a known issue in Tusky 19, it is already fixed for 20. see https://github.com/tuskyapp/Tusky/pull/2671
