### ISSUE TITLE
Translate posts

### ISSUE THREAD

**Issue by chris-y** [tuskyapp/Tusky#2764]
As far as I can tell, the only way to translate posts in Tusky is to:
1. Tap the post menu
2. Go to Share 
3. Tap "Content of post"
4. Choose "Google Translate"
5. Select the correct options

It would be great to have an in-place translation feature in the post menu to make this much easier.

**Comment by connyduck** [comment]
Yes. We will implement the Mastodon 4.0 translation api soon. https://github.com/tuskyapp/Tusky/issues/2188 https://github.com/tuskyapp/Tusky/issues/134

**Comment by chris-y** [comment]
Apologies, I searched the issues but nothing came up for translation!
