### ISSUE TITLE
Revert to using browser redirects for auth (or at least provide the option)

### ISSUE THREAD

**Issue by virtualdxs** [tuskyapp/Tusky#2767]
Asking users to enter third-party credentials inside a webview is bad practice for a few reasons:

- The user has to trust your app not to harvest the credentials (and it teaches users to implicitly trust that with all apps)
- The user has to re-enter their credentials regardless of whether they're logged in in their browser (especially relevant with SSO-integrated instances)
- Webauthn cannot be used, preventing login to any instances/accounts that require it
- At least for me, Android's built-in password manager doesn't work with it
- The user does not have control of the webview, preventing them from working around issues like #2703

The first two were mentioned in the commit message for 4d8289b2. Providing the option to use a browser redirect would resolve some of these, but ideally the webview auth feature is removed entirely as it is considered bad practice for security and UX reasons.

It has also been mentioned that reverting this would help work around issues such as #2462.

Related: PR #2371 which introduced the change

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: Galaxy S10
- Mastodon instance (if applicable): N/A

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes we need to do something, logging in with the WebView seems to cause all kind of problems. 
Logging in with the browser was also not perfect, mainly because it only worked with Chrome or Firefox.
So we will probably need some kind of option or automatic detection.

**Comment by virtualdxs** [comment]
Interesting, do you know why it doesn't work with other browsers?

As a stopgap, I'd suggesting adding a menu option to the current webview that redirects to the browser.

**Comment by connyduck** [comment]
They did not redirect back to Tusky

**Comment by virtualdxs** [comment]
Looks like the official app uses [Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/). Seems like a good solution - wide browser support, callback whenever a navigation event happens, and shares cookies etc. with the user's browser.

**Comment by connyduck** [comment]
We had that as well https://github.com/tuskyapp/Tusky/blob/841373e94700a65594b5f194a550e22949cb8380/app/src/main/java/com/keylesspalace/tusky/LoginActivity.kt#L339

**Comment by virtualdxs** [comment]
If you were using custom tabs, why did you need the browser to redirect back to you? From my understanding as long as they stay in the custom tab you should be able to capture the final redirect event, grab the token from it, and close the custom tab. (Apologies if I'm going off an incorrect assumption; I've never worked with this myself)

**Comment by charlag** [comment]
I think we *can* actually get navigation even which is nice

https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsCallback#onNavigationEvent(int,android.os.Bundle)

**Comment by Tak** [comment]
Implemented in #3165
