### ISSUE TITLE
[bug] nightly crashes when opening a gallery of images

### ISSUE THREAD

**Issue by jeyemwey** [tuskyapp/Tusky#2774]
I am on the 8e9b3560 nightly, and it seems to crash reliably when I try to open a gallery of images. The timeline preview is fine, the single-post view is fine, Posts with just one image work fine, but not with multiple images.

In the release version, everything works as expected.

Example of a post that triggers the issue: https://mastodon.art/@Curator/109304194249763120

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2773
