### ISSUE TITLE
[pixelfed] Testing doesnt allow logging in to pixelfed.social anymore

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#2776]
pixelfed support seems kind of broken in recent test build. No real error, just entering pixelfed.social as instance name and being prompted immediately that it's impossible to log in to that instance. Anything to debug that?

**Comment by connyduck** [comment]
It was an issue with pixelfed.social, should work again.

**Comment by kr428** [comment]
Unfortunately not - same effect on latest testing again...? This time however it at least _seems_ to try and redirect to a web view but immediately returns to the app saying "login page could not be loaded"?

**Comment by connyduck** [comment]
Do you use some kind of web filter on your device?

**Comment by kr428** [comment]
No... meanwhile however, I seem to have solved it by re-installing the app. Weird. Doesn't really reproduce _this time_.

**Comment by connyduck** [comment]
Same issue as https://github.com/tuskyapp/Tusky/issues/2703
https://github.com/tuskyapp/Tusky/issues/2767 related
