### ISSUE TITLE
Feature request: Add an option to automatically display all images

### ISSUE THREAD

**Issue by fiso** [tuskyapp/Tusky#2779]
See title. I am not bothered by images, and find it tedious to have to tap every image to see it. Please make this possible. 

* * * *
- Tusky Version: N/A
- Android Version: N/A
- Android Device: N/A
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Account preferences -> always show sensitive content
