### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MeraOrd** [tuskyapp/Tusky#2780]
I would love if I could sort my feed in a few more timelines:
All from people I follow
People I follow without their boosts
People I follow without boosts and answers

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: Samsung galaxy ultra 22
- Mastodon instance (if applicable): Mastodon.se

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This is out of scope without server support sorry.
