### ISSUE TITLE
Draft caption lost

### ISSUE THREAD

**Issue by jsoref** [tuskyapp/Tusky#2782]
Follow-up to #869

I was composing a very long and indicate alt text description for a tiny picture. I'm not sure what caused me to lose my text, it might have been a task switch or it might have been tapping out of the dialog or something else.

Please don't lose alt text compositions. This is the second time I've lost one and it's really frustrating. I think the best approach is to just treat alt text as posts and if you think the user is leaving/cancelling, create draft posts with the alt text as the body (splitting into multiple if necessary). Worst cases: user copies then and stitches them back together or sees them in drafts and deletes them. 

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: Pixel 3A
- Mastodon instance (if applicable): mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/2626

**Comment by jsoref** [comment]
Upon further review, it appears that my lost item did end up in drafts. I'm really not sure what happened. So things weren't actually lost. But, clearly, I was confused and frustrated.

If I figure out what actually happened, I'll file a more detailed report...
