### ISSUE TITLE
Add a view for followed hashtags

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#2785]
There is an api for that `/api/v1/followed_tags`, but no frontend implements it yet as far as I know.
I think it should go into "Account Preferences" between "Tabs" and "Muted users" and just be a simple list where one can unfollow the hashtags again. It would be cool if we could do feature detection for this, but once most instances are on Mastodon 4.0 it shouldn't be a big problem if we don't-

**Comment by Tak** [comment]
I can pick this up when I get a minute

**Comment by stephan75** [comment]
Fedilab has this new  feature to handle followed hashtags that are tied to your Mastodon account at least since version 3.7.4 ...

But that list feature inside fedilab (at least in 3.8.0) has problems to display German umlaut characters like Ä Ö and Ü

**Comment by Tak** [comment]
Implemented in #2794
