### ISSUE TITLE
Apparently broken date formatting (poll, ‘absolute time’ option enabled)

### ISSUE THREAD

**Issue by dsalt** [tuskyapp/Tusky#2786]
“11-09” looks wrong, and I initially read it as 11 September. Checking via other means, I see that that poll ends at 14:34 GMT tomorrow (09/11) and _not_ in approx. 10 months' time.

* * * *
- Tusky Version: 19.0
- Android Version: 12

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
Can confirm this with a twist. I also have "absolute timestamps" activated.
Now (?, develop version yesterday https://github.com/tuskyapp/Tusky/commit/667a728dd566463f0ad29fd56a45a9e8136210d5) it shows me a technical format: "ends" 2023-11-17 01:56

And that date is the creation date.

**Comment by Lakoja** [comment]
Cannot confirm any longer. Seems to be fine. Both with relative and absolute timestamps...

**Comment by Tak** [comment]
Fixed in #2800
