### ISSUE TITLE
Feature Request: share a list publicly 

### ISSUE THREAD

**Issue by SheilaMAverbuch** [tuskyapp/Tusky#2810]
I agree with the open issue List Edit Mode #2768 ... I'm adding request to share a list publicly. I'm one of the first people in my community (children's book writers) to join and start making lists, and I know I can save them a lot of time if I could share my lists with them.

* * * *
- Tusky Version: 19.1
- Android Version: 12
- Android Device: POCO F3
- Mastodon instance (if applicable): mstdn.social

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by fadookie** [comment]
Tusky is just a client for Mastodon, a feature this large would need to be implemented into Mastodon itself before it could be supported by Tusky. You can find that issue at https://github.com/mastodon/mastodon/issues/18292 .
