### ISSUE TITLE
Bug, A11y: animated emojis are animated in emoji drawer even with "animate custom emojis" turned off

### ISSUE THREAD

**Issue by missmatsuko** [tuskyapp/Tusky#2820]
I have "animate custom emojis" turned off in the app settings and my phone settings, but they are still animated in the emoji drawer.

I'm not sure if it's a Tusky bug or Android bug.

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Google Pixel 4a
- Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That is a Tusky thing, but it is actually deliberate. Because there could be an emoji that changes its meaning during the animation and that would led to embarassing posts.

**Comment by missmatsuko** [comment]
I think it is more important to respect animation settings because people with light-sensitive epilepsy use it to prevent seizures. 

You could say the same thing about animated emojis that change meaning when they are still. That's going to happen for some people, too.

**Comment by connyduck** [comment]
yeah true, will change
