### ISSUE TITLE
[Feature Request] language button in editor

### ISSUE THREAD

**Issue by thesix** [tuskyapp/Tusky#2821]
Hi there,

the webinterface provides a button in the edit window that allows me to change the language setting of the toot I am writing. This would be very nice to have in tusky too.

Thanks for your effort!

* * * **
 - Tusky Version: future
- Android Version: n/a
- Android Device: n/a
- Mastodon instance (if applicable): all

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
This is available in Tusky nightly, and will be part of the next Tusky release
