### ISSUE TITLE
Feature request: copy user ID

### ISSUE THREAD

**Issue by Oreolek** [tuskyapp/Tusky#2824]
Tusky does not show the full user@instance ID in full if it does not fit the screen width. And neither it lets me copy the ID to the system clipboard. 

Example: if I want to add a user to a list, I need to open the list, type the ID by memory and pray that the server will find this person in my follows (most likely not unless I type the exact ID). (This issue is not a duplicate of #2815 but it would help.)

* * * *
- Tusky Version: 19.0
- Android Version: 7.0
- Android Device: Moto C Plus

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by dpreuss321** [comment]
This is especially important, since there is no feature on the profile page to add account to a list. 
While we wait for that, the workaround is a pain, made worse because of cannot-copy-user-id + #dyslexia
It is keeping me from using Mastodon, as I primarily want to curate lists. Thanks

**Comment by nikclayton** [comment]
Would copying the user ID if it's long-pressed on either a post or the profile screen solve this problem for you?

**Comment by dpreuss321** [comment]
Sounds perfect! 
Long-press, Share, Copy 👍

**Comment by mcclure** [comment]
Longpress to copy @@ name (plus a share menu for profiles) was implemented in PR #3120. Should this can be closed?

**Comment by dpreuss321** [comment]
I'm long-pressing display name, @@name, avatar - nothing is copied.

I also do not see Share in the profile's ... menu

Google pixel 7, latest OS
:-(

**Comment by mcclure** [comment]
The 3120 change is in Tusky 21.0, which has not been released yet. You can try out Tusky Nightly on the Play Store, where the change either has appeared today or will appear tomorrow, or wait for 21.0. Note Tusky Nightly might be less stable than the regular releases because it is basically the beta-test channel.

**Comment by dpreuss321** [comment]
Aha! Thanks. :-)
