### ISSUE TITLE
Feature Request - Mute video playback

### ISSUE THREAD

**Issue by egooner** [tuskyapp/Tusky#2840]
Video playback, would be good to have an option to mute videos by default and unmute when playing optionally!!
Some videos do not need the sound but when watching in a crowded area it would be nice not to have to keep turning mobile volume down!

**Comment by thibaultmol** [comment]
Is this a duplicate of
https://github.com/tuskyapp/Tusky/issues/2675
?

**Comment by egooner** [comment]
Apologies - it is - I probably searched another issue before making this
one and neglected to search for this!

Thanks

Richard
