### ISSUE TITLE
Unordered post language selection

### ISSUE THREAD

**Issue by cziegenberg** [tuskyapp/Tusky#2844]
The language selection when creating a new post is completely unordered (system language German), so when I want to switch to English or another language (would be great if configurable), I have to search the complete list, to find it there... (see screenshot)

![Screenshot_20221116-212526](https://user-images.githubusercontent.com/1983424/202288105-5559cb8c-815c-4537-b591-2fbeadaef6ea.png)

* * * *
- Tusky Version: Tusky Test 19.0-9f7cd2fa
- Android Version: 13
- Android Device: Pixel 6a
- Mastodon instance (if applicable): phpc.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
It's currently ordered by the language's shortcode (which I agree is very opaque)
I'd like to improve this in the future, ideally *without* adding more preferences (maybe by prioritizing languages the user has chosen in the past? or an autocomplete box?)

**Comment by cziegenberg** [comment]
The languages should be ordered by the translated name IMHO, but remembering the previously used languages would really help for the selection.

What I mean with the configuration is setting the default language for post (per account). So the app language is German, but I want to post in English by default and with another account I prefer to post in German by default.

And a related question for the next step: How can I filter the posts shown in tabs by language? Thought that this is the purpose of this new feature, but I couldn't find the option for it.

Thanks!

**Comment by Tak** [comment]
> How can I filter the posts shown in tabs by language?

We don't have a UI for this currently - you can set this in the web UI, and it will affect the timelines provided by the server.

**Comment by marcin-kozinski** [comment]
How about only preferred languages in the drop-down with a button to open the full list in a full-screen ui? This opens up the possibility to add a search box or other advanced features to the full-screen full-list ui, while keeping the drop-down experience simple for the most common scenarios.
