### ISSUE TITLE
[Bug] 'Invalid E-mail address or password error' when both are correct

### ISSUE THREAD

**Issue by SheilaMAverbuch** [tuskyapp/Tusky#2846]
When moving from Tusky to "open in browser" I was prompted to to enter my email address and password. I received the error 'Invalid E-mail address or password' even though both were correct. I requested a link to reset the password, clicked the link, and pasted in the same password again instead of resetting it. When I tried to log in again, it worked, but I've since experienced the same error message 'Invalid E-mail address or password'.

* * * *
- Tusky Version: 19
- Android Version:12
- Android Device:POCO F3
- Mastodon instance (if applicable): mstdn.social

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
You were probably opening a post or profile from another instance and that instance does not have public pages (or the post was not public) and you can not log into other instances without having an account there.
Related: https://github.com/mastodon/mastodon/pull/20946
