### ISSUE TITLE
Feature Request: Timeline in chronological order (not reverse) 

### ISSUE THREAD

**Issue by politas** [tuskyapp/Tusky#2848]
Corporate media has gotten us accustomed to algorithm-driven feeds where what's important is the latest trending things. We see the end of a conversation first, without the background, and tend to react, increasing drama and "engagement", rather than understanding and reasoned vision. 

On the other hand, when reading a history book, we tend to start at the early points of a timeline and track the changing situation as it unfolds over time, so we have an understanding of how we got to where we are.

Some individual posts take up more than a screen, so to read the feed, we need to scroll up to the start of a post, then scroll down as we read it, then scroll all the way back up past it to get to the next post. 

Please, can we have an option to put the timelines in forward chronological order, to enhance understanding, reduce unnecessary drama, and reduce annoying back and forth scrolling?

**Comment by connyduck** [comment]
see https://github.com/tuskyapp/Tusky/issues/2788
