### ISSUE TITLE
Handle Twitter Accounts being mentioned 

### ISSUE THREAD

**Issue by yoshimo** [tuskyapp/Tusky#2849]
Quite a few people post  Twitter content  on Mastodon

```
RT @fanCRTCProfling@twitter.com

Institute of Science and Technology Austria (ist[.]ac[.]at) ransomwared/rooted. 
```

I think the first line should be smaller and in italics as it is unnecessary metadata. Also the twitter handle should be a click able link. 

* * * *
- Tusky Version: 19
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
No, we won't add special handling for a proprietary social network. Also, things like this should be implemented on serverside.
