### ISSUE TITLE
[Feature request] Editing post on Mastodon 4.x instances

### ISSUE THREAD

**Issue by Draky50110** [tuskyapp/Tusky#2851]
Hello.

Possible to edit posts with the app, on  Mastodon 4.x instances (like mastodon.social forme) ?

Didn't see this request here so asking...

Thanks.

**Comment by LinkofHyrule89** [comment]
Already being worked in. https://github.com/tuskyapp/Tusky/pull/2828

**Comment by Draky50110** [comment]
:+1:
