### ISSUE TITLE
Hashtags with umlauts open in browser

### ISSUE THREAD

**Issue by paxed** [tuskyapp/Tusky#2860]
Clicking on hashtags containing eg. ä or ö open in the web browser instead of in tusky itself.

* * * *
- Tusky Version: 19.0
- Android Version:
- Android Device:
- Mastodon instance (if applicable): mastodon.lol

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Which instance are you using? Please link one such post where the problem occurs.

**Comment by connyduck** [comment]
No longer needed, can reproduce on Mastodon.social

**Comment by connyduck** [comment]
fixed by https://github.com/tuskyapp/Tusky/pull/2700
