### ISSUE TITLE
Don't show own direct messages in Home

### ISSUE THREAD

**Issue by ikashnitsky** [tuskyapp/Tusky#2861]
Direct messages are treated as toots with limited audience. That's great. Yet, I find it highly unnecessary to see these toots in the Home feed. It seems more natural for them just to live in the Messages tab

![Screenshot_20221119-123612](https://user-images.githubusercontent.com/10271163/202848962-1e8f9bc3-ef59-4166-855a-6127332304ba.png)

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Google Pixel 4a
- Mastodon instance (if applicable): fosstodon.org

- [✅ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thats a mastodon thing and should be addressed on their side
