### ISSUE TITLE
Schedule a boost

### ISSUE THREAD

**Issue by thibaultmol** [tuskyapp/Tusky#2863]
Being able to schedule a boost of a post would be useful.
I sometimes want to boost a post. But might want to wait an hour or two. Because boosting a post right after it's created, might mean that it won't be viewed by people a couple minutes later. While if you could schedule a boost, that spreads out the chance of it being viewed over a longer period

* * * *
- Tusky Version: n/a
- Android Version: n/a
- Android Device: n/a
- Mastodon instance (if applicable): n/a

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
There is no server support for this, please ask Mastodon,

**Comment by thibaultmol** [comment]
There's no server support for scheduling posts either though, right?
But that's done trough the app

**Comment by connyduck** [comment]
No, scheduling posts has server support. There is just no interface it in the web app.

**Comment by thibaultmol** [comment]
Oh I see.
Btw, fedilab does have schedule boosting. It just does it in the app itself.
(same how it can do both server side and client side post scheduling it seems)
![image](https://user-images.githubusercontent.com/1010226/202905657-70d9dad3-2f6a-4aea-9f91-5f9bb4955f70.png)

![image](https://user-images.githubusercontent.com/1010226/202905665-020a8dd2-039f-4219-a33b-63d2d3c59d43.png)


![image](https://user-images.githubusercontent.com/1010226/202905673-aac84cfb-48be-4d72-adf6-a3a9566bf316.png)

**Comment by thibaultmol** [comment]
Consider opening this issue again  @connyduck , this is an actual Feature request

**Comment by connyduck** [comment]
Yes I totally understand why one would want this feature, it is just not something that should be in client software in my opinion. There is too much that can go wrong, device being offline, device being shut off, server being offline, original post being deleted, app being battery optimized by Android and probably more. The scheduling will be unreliable and error handling complicated, both creating a bad user experience. When Mastodon adds support for this, we will implement it but not client only. I think Fedilab has different thoughts about this and provides the feature if you really want it.
