### ISSUE TITLE
Add list column 

### ISSUE THREAD

**Issue by monofurioso** [tuskyapp/Tusky#2865]
This is a feature enhancement request, not a bug.

It would be amazing if we could customize columns to swipe through left and right.  Allowing the ability to add columns for lists, in addition to, or in place of, the local or federated time lines would be vastly useful.

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Pixel 7 Pro
- Mastodon instance (if applicable):

- [* ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That feature already exists? Go to Account preferences -> Tabs
