### ISSUE TITLE
[Bug/Feature request] Display requested hashtag first in search

### ISSUE THREAD

**Issue by Lukastos** [tuskyapp/Tusky#2867]
When searching for a hashtag, let's say "PixelArt" for instance, in the hashtag search menu, I'm getting all sorts of hashtags first instead of the one I was looking for. In the example, I'm going to get "pixelartist, pixelartapp, [...], pixelart". The searched hashtag is very down the list even though it matches perfectly the request. Sometimes there are few pages of hashtags before I can find the one I was looking for.

It would be nice to have the request put at the top of the list if there is a 100% match.

* * * *
- Tusky Version: 19.0
- Android Version: Android 9
- Android Device: Nokia 6
- Mastodon instance (if applicable): mamot.fr

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
It is up to mastodon, please open an issue there
