### ISSUE TITLE
[Feature Request] Disable swipe gesture between profile tabs

### ISSUE THREAD

**Issue by ivadham** [tuskyapp/Tusky#2874]
The “`Enable swipe gesture to switch between tabs`” setting only affects main screen tabs. It might be a good idea to apply the same setting to profile tabs: POSTS | WITH REPLIES | PINNED | MEDIA

* * * *
- Tusky Version: 20.0 beta 1
- Android Version: 10

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Also Search (swipe between Posts/Accounts/Hashtags).
