### ISSUE TITLE
Parts of content warning posts still shown

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#2875]
Regarding profile setting "Always expand posts marked with content warnings":

Even with this setting disabled some contents are shown: all user handles in the text and the images.

* * * *
- Tusky Version: 20.beta.1

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
It works like expected, mimicking web UI. Handles are shown to see that this is a conversation. Images in CWd posts are marked as NSFW my mastodon. Only text is hidden.

**Comment by GPHemsley** [comment]
> It works like expected, mimicking web UI. Handles are shown to see that this is a conversation. Images in CWd posts are marked as NSFW my mastodon. Only text is hidden.

Expected by whom? I don't use the web UI, I only use Tusky. I frequently see posts clearly marked with a content warning, yet the images or videos are still shown without user interaction, despite my settings. I have also seen other apps where this is not the case.
