### ISSUE TITLE
Allow Search Filter "local instance only"

### ISSUE THREAD

**Issue by dpreuss321** [tuskyapp/Tusky#2881]
I want to use the search, but only on my instance, sometimes.

I was excited to be on a Canadian server.
But now I see that I cannot search just my server, I must search the whole fedi. 
And not everyone is putting geolocation tags in toots. :-(

Allow a filter "search my instance only".
Thanks

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: Pixel3
- Mastodon instance (if applicable): mstdn.ca

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
@dpreuss321 does mastodon itself have support for this?

**Comment by dpreuss321** [comment]
I'm new to Mastodon. I don't know.
Maybe we should kill this until I undetstand it all better ...

**Comment by kylegoetz** [comment]
it does not appear you can filter a search by just local. Here is the API documentation for search API actions: https://docs.joinmastodon.org/methods/search/

**Comment by dpreuss321** [comment]
I'm not a developer. I'm an end user, so the API doc does not help me. 

I looked for end user help for search but dis not find. If you can point me to end user search parameter doc, that would be great.

I'll close this item and work on understanding search better, first. (I don't know why Search Posts always comes up empty, for instance).

**Comment by dpreuss321** [comment]
My request is unclear, closing to remove it.

**Comment by connyduck** [comment]
Can only be done with server support, sorry.
