### ISSUE TITLE
Webauthn (Yubikey) doesn't work

### ISSUE THREAD

**Issue by joel0** [tuskyapp/Tusky#2884]
"This browser doesn't support security keys" when trying to log in.
![IMG_20221120_143911](https://user-images.githubusercontent.com/8691351/202930203-2b991762-150d-4115-8c76-a89e15c3145c.jpg)

I can use the security key in Firefox, Vivaldi, and Chrome, but not Tusky.

* * * *
- Tusky Version: 19.0
- Android Version: 12 - LineageOS 19-20221107-NIGHTLY-cheeseburger
- Android Device: OnePlus 5
- Mastodon instance (if applicable): social.linux.pizza

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
covered by https://github.com/tuskyapp/Tusky/issues/2884

**Comment by mashedkeyboard** [comment]
> covered by #2884

uh, this is #2884 @connyduck :sweat_smile:

**Comment by connyduck** [comment]
Oh sorry. https://github.com/tuskyapp/Tusky/issues/2767

**Comment by joel0** [comment]
Ah, perfect. Somehow I missed that in my search for duplicates. Sorry about that.
