### ISSUE TITLE
HEIF / heic images not supported

### ISSUE THREAD

**Issue by dancapper** [tuskyapp/Tusky#2886]
If I set my inbuilt camera app to create "high efficiency pictures" (heic extension) I am unable to insert the resulting images from the gallery

This works seamlessly on most apps

I haven't tested high efficiency video (hevc)

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: Samsung A52s 5G
- Mastodon instance (if applicable): cloud island.nz

- [ X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kylegoetz** [comment]
Do you know what version of the server your Mastodon instance is running on? Mastodon until recently didn't support HEIC. When I try to add an HEIC image to a status, Tusky gives an error, but upon investigating the error, it's an HTTP error returned by the Mastodon instance I'm connected to. Digging further, until 4.0 HEIC was definitely not supported: https://mastodon.social/@austinkocher/109294719267373593

And I think my instance is running 4.1 or 4.2, and it's still giving a 500 error when uploading HEIC images.

**Comment by dancapper** [comment]
I sort of assumed it would do the conversion, but if it's a coming feature on mastodon can understand if there's better ways to spend the time 👍 appreciate the quick response!
