### ISSUE TITLE
[Feature request] Highlight image descriptions; esp. when missing composing

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#2890]
Followup (or refinement) of https://github.com/tuskyapp/Tusky/issues/1049

Missing media descriptions are a nuisance for some and could help a lot of users (I like to see them as well).
One problem with this is that people are not aware that image descriptions are helpful and encouraged. Or that they even exist..

Therefore I'd like to make them a bit more prominent:

- When viewing a status with images mark the ones with description; i. e. with a small "T" in a corner
- When composing add a small warning icon in the top bar as long as there is media without description. Tapping that icon will show a short dialog or toast message.

This is in the range of light nudging and not so obtrusive as a dedicated warning dialog when sending.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Some users asked about a warning for image descriptions when composing. So far we have two things:

 * when composing the icon in the corner of the image will switch between black and blue
 * when reading a post one can long-press to show the description as a toash

but we could improve on that

**Comment by connyduck** [comment]
I like the idea of having an option that prevents posting without descriptions when enabled.
Also an "ALT" icon in the corner of images when they have descriptions (like Twitter does it) would be cool.

**Comment by Lakoja** [comment]
Is merged.
