### ISSUE TITLE
Tap on follow request opens notifications instead of follow requests 

### ISSUE THREAD

**Issue by guerda** [tuskyapp/Tusky#2896]
By default Tusky filters follow requests from the notification list, as there's a separate menu entry for follow requests.

If a follow request comes in and you tap ok the notification, the notification section is opened.

It would make more sense if the separate menu entry is opened instead of the notifications.

**Steps to reproduce**
1. Setup account to request approvals for followers
2. Let anybody follow you
3. Tap on the notification from Tusky

I'm using Tusky 19 on Android 13.

**Comment by connyduck** [comment]
fixed in https://github.com/tuskyapp/Tusky/pull/2757

**Comment by guerda** [comment]
Also happens on Tusky 20.0 beta 1, nice icon btw.

**Comment by connyduck** [comment]
o_0
investigating

**Comment by connyduck** [comment]
Can not reproduce.
Just to be sure we are talking about the same thing:
1) Click on a Tusky notification about a new follow request in the Android notifications (not in the Tusky interface)
2) Tusky opens showing its notification column

For me it correctly opens the Follow request view. Tusky 20 beta 1.
@guerda

**Comment by guerda** [comment]
Thank you for looking into it so quickly!
You are right, it is fixed in 20.0b1! Sorry for the confusion
