### ISSUE TITLE
[20.0b1] Language dropdown has three identical English options

### ISSUE THREAD

**Issue by ashemedai** [tuskyapp/Tusky#2900]
With the latest beta, when I use the language dropdown I am greeted at the top with three visually identical versions of English. My guess is that they are probably en_US, en_GB and another.

![Screenshot_2022-11-22-08-09-56-03_c38dddb2ed334becc5defa8615851593.jpg](https://user-images.githubusercontent.com/610865/203251027-3b1e34e4-4185-4918-a5d8-8ccb64ff1afb.jpg)

Edit: If this is based on the keyboards I have configured, then we need to employ some deduplication since I have:

- EN/IS/NL
- IS/NL/EN
- NL/EN
- JP
- KR
- RU

Leaving aside that I need to double check the settings for these keyboards, it picks up the three English from these, but misses Icelandic and Russian, but finds Japanese and Korean.

---

Tusky Version: 20.0b1

Android Version: 12

Android Device: OnePlus 8T

Mastodon instance (if applicable): mastodon.social 

- [x]  I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
They are probably duplicates from the keyboards you have configured. We are attempting to deduplicate them, but apparently need to attempt harder.

**Comment by ashemedai** [comment]
@Tak, that's what I later realised and added, see the Edit text. Good to have confirmation, hadn't looked at the code base yet. Still wondering why it did not pick up Icelandic or Russian though.

The settings for EN, IS, NL allowed me to also tick the other two, under the primary language, for the case where you write a text in a primary language but use terms etc from the other language(s).

Now that I look closer, why does this happen for English, but not Dutch though? 🤔
