### ISSUE TITLE
Sync with default posting language

### ISSUE THREAD

**Issue by yuvalne** [tuskyapp/Tusky#2902]
Currently, the default posting language is the app interface language. This is an issue when your main posting language is a language not yet available in the app interface languages (e.g. Hebrew), or if you have multiple accounts posting in various languages. I find myself needing to switch language every time I post (and hope I don't forget to do so).

The app should instead sync with the default posting language as it is set on the server:

<img width="1060" alt="Screen Shot 2022-11-22 at 13 13 29" src="https://user-images.githubusercontent.com/97384040/203301770-308c0ca2-0123-45e7-89c7-fc89ae42a94d.png">

Ideally one should even be able to set the posting language in-app and have it sync with the server, similarly to _Default post privacy_:

![signal-2022-11-22-132022](https://user-images.githubusercontent.com/97384040/203301928-37a73899-dee7-4439-8943-1eaa36ac11c2.jpeg)

* * * *
- Tusky Version: 20.0 beta 1
- Android Version: 12
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Let's leave this one open until we have the prefs UI, I shouldn't have tagged the commit as closing it

**Comment by connyduck** [comment]
Oh sorry didn't see, I just created https://github.com/tuskyapp/Tusky/issues/2926, I'll close again
