### ISSUE TITLE
Login using Authentik SSO provider fails

### ISSUE THREAD

**Issue by vranki** [tuskyapp/Tusky#2904]
At sauna.social we use Authentik for single sign-on. It works fine with browser login.

With Tusky the login flow works but in the end Tusky's webview just displays the Mastodon web UI logged in and account is not really added into the app.

I cannot guarantee this isn't misconfiguration on Authentic side, but the login succeeds with browser. If needed, I can supply an test account for developer for investigating.

Thanks for great app!
* * * *
- Tusky Version: 19.0
- Android Device: Cosmo Communicator
- Mastodon instance (if applicable): sauna.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
What does "not really added" mean?
Duplicate of https://github.com/tuskyapp/Tusky/issues/2462?

**Comment by vranki** [comment]
It means if i go back to Tusky from the login webview, the new account is not in the accounts list.

Duplicate of #2462.
