### ISSUE TITLE
No notifications 

### ISSUE THREAD

**Issue by Ptmc518** [tuskyapp/Tusky#2905]
I'm not getting notifications for favorites and boosts. I've made sure the permission is set for the app and made sure that thinks like well-being in the app aren't enabled. I tried uninstalling and reinstalling and no change.

![Screenshot_20221122-082805](https://user-images.githubusercontent.com/66734755/203325930-f8c62afb-29e6-4ca2-885c-16a4f052beb9.png)

* * * *
- Tusky Version: 20.0 beta 1
- Android Version: Android 13
- Android Device: Pixel 6 Pro
- Mastodon instance (if applicable): mastodon.coffee

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Ptmc518** [comment]
> Did you install an open source notification system as ntfy ?

No, I don't have any notification management apps installed. I am getting notifications in Tusky but they're very delayed and seem to come in waves. So I'm not sure if it's the app for sure or not though I don't have the issue on other apps.

**Comment by jy-fr** [comment]
you should install ntfy, as mentioned in the Faq, tusky does not support push notifications from google.  they have a notification system that checks every quarter of an hour at best.  If you are interested I could find the link for you.

**Comment by Ptmc518** [comment]
> you should install ntfy, as mentioned in the Faq, tusky does not support push notifications from google. they have a notification system that checks every quarter of an hour at best. If you are interested I could find the link for you.

Thanks, I appreciate it. I'll take a look and let you know if I need assistance setting it up.
