### ISSUE TITLE
Display Issue on Tablets

### ISSUE THREAD

**Issue by bama35453** [tuskyapp/Tusky#2916]
When scrolling all the way down in the conversation view the last post at the bottom is cut off. In this case the text is completely visible but the buttons for replying, boosting etc. are outside the display.
This behavior occurs in both landscape and portrait mode.
The device is a Samsung Galaxy Tab S7 (11 inch display)
![Screenshot_20221123_105842_Tusky.jpg](https://user-images.githubusercontent.com/118128192/203522215-c9136a25-289d-454a-8422-92944976fa87.jpg)
![Screenshot_20221123_111915_Tusky.jpg](https://user-images.githubusercontent.com/118128192/203522997-fc62a3dc-6fbb-43e4-afe0-7c969a641ab8.jpg)

**Comment by connyduck** [comment]
Can reproduce, will fix
