### ISSUE TITLE
Option for Load More to insert above the current selection point

### ISSUE THREAD

**Issue by Clfh47** [tuskyapp/Tusky#2929]
Feature request: I prefer to read timeliness from oldest to newest. At present Load More adds the new content below that point. 
It means that one has to try to remember what was below that point and scroll down through all the newly-added posts to get back to the insertion point. 
The requested option would add the newly-downloaded posts above the Load More point, leaving the post below that still visible. 

* * * *
- Tusky Version:19.0
- Android Version:7.0
- Android Device:Acer P027
- Mastodon instance (if applicable): mastodon.green

- [y ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Requested timeline behavior changes are being gathered in #2788

**Comment by Clfh47** [comment]
Thanks. Have added my Thumb-up to the best-fitting request in that list.
