### ISSUE TITLE
Keep Toot on screen while replying

### ISSUE THREAD

**Issue by robsonsobral** [tuskyapp/Tusky#2931]
As mastodon allows longer posts, to have them on screen while you write your reply would be useful.

Thank you!

**Comment by Tak** [comment]
Tap the "Replying to" line in the compose view to expand it

<img width="353" alt="Screen Shot 2022-11-25 at 08 45 44" src="https://user-images.githubusercontent.com/142250/203927968-71c9d9a3-ea1d-488e-b9b3-0e71483d670c.png">

**Comment by robsonsobral** [comment]
😯
