### ISSUE TITLE
Notifications about new reports show up empty 

### ISSUE THREAD

**Issue by rixx** [tuskyapp/Tusky#2933]
Tusky doesn't seem to know about the notification type about new reports, so I can't hide those notifications, and they show up as an empty line. 
![Screenshot_20221125-091615](https://user-images.githubusercontent.com/2657547/203933496-b05d4072-b728-4e37-8907-7edee42831d8.png)

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Pixel 4a
- Mastodon instance (if applicable): chaos.social (4.0.2)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2887

**Comment by rixx** [comment]
Oops, sorry, only searched in issues, not in PRs
