### ISSUE TITLE
Retrying can lead to duplicated posts

### ISSUE THREAD

**Issue by lambda** [tuskyapp/Tusky#2951]
[hachyderm.io](https://hachyderm.io/) is an instance that has run into some scaling problems with the recent Twitter migration, and posts are sometimes taking so long that a 504 Gateway Timeout results, while the post was actually successfully made. When posting from the web app, it will show the timeout in the UI, and users sometimes re-try a couple of times, before reloading and realizing that they've posted multiple times.

When using Tusky, it looks like Tusky does automatic retries. This means that when load is really bad, Tusky can sometimes re-try many times; I had 11 duplicate posts at one point today. So while this can happen when people retry manually on the web app, it happens automatically and much more often with Tusky.

Here's an example thread, where one user complains about it happening, and you see it happening again in the replies: https://hachyderm.io/@Tali/109423815926051158

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Pixel 4 XL
- Mastodon instance (if applicable): [hachyderm.io
](https://hachyderm.io/)
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Tusky sends an "Idempotency-Key" header to avoid this exact problem. If the server fails to respect that, it is the servers problem.
