### ISSUE TITLE
Does the HTTP Proxy feature even work?

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#2952]
There is an "HTTP proxy" feature at the bottom of the Tusky preferences.

I ran on my PC the https://deelay.me/ proxy, enabled "Enable HTTP proxy" and set "HTTP prox server" to "http://192.168.[redacted]:4567/10000". I did not set the port. I expected this to route all mastodon traffic through the deelay proxy, delaying every API call by 10 seconds.

Instead I was able to browse mastodon normally and nothing unusual happened. I did not see on the deelay proxy window notifications it was getting http requests (which I did when I tested with a PC). I did not get any errors. I did not notice anything in a casual view of the logcat. It continued working even after I shut down the deelay server, implying it was never even trying to contact deelay in the first place.

I tried restarting Tusky and did not get any different results.

Maybe deelay is not a compliant proxy server or the proxy server expects a hostname not a url (deelay does require a url because the delay length is part of the url). But I would expect some sort of error to be reported instead of Tusky just going ahead and contacting the normal Internet (the originally stated use case for the http proxy feature was privacy protection, so you really wouldn't want it to bypass the privacy protection on a failure).

* * * *
- Tusky Version: 20.0, [3d63596](https://github.com/tuskyapp/Tusky/pull/2947/commits/3d63596b0cf9bac82fc0323ca8c6f20fff790606)
- Android Version: 12
- Android Device: Sony XPeria 5 III
- Mastodon instance (if applicable): mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
we need better error handling but port should be between 0 and 65535

https://github.com/tuskyapp/Tusky/blob/8437fbd60513ec5279502e59ff0a02e3c5605611/app/src/main/java/com/keylesspalace/tusky/di/NetworkModule.kt#L90

**Comment by kylegoetz** [comment]
Should the provider instead return `OkHttpClient?`? I normally write in a functional paradigm, so my approach would be totally different, but in a non-FP style, the closest I can think of is this. Alternatively, throw an exception (always makes me tense up, afraid I'll forget to wrap them in try/catch blocks!).

**Comment by charlag** [comment]
We should probably change how we allow user to set it to not have invalid values

**Comment by kylegoetz** [comment]
Is there a preferred notification when this is invalid? It doesn't look like I can add a validator directly to the `editTextPreference` DSL to display an error message or disable the "positive button," so best I can do is clear out the setting if the user has put an invalid value for port number and accepted the (invalid) value.

It would be nice to put up a message, but didn't know if this project prefers Toast or something. Not sure if the Tusky Notification concept would be preferable since it seems you can disable these notifications, which I don't think we'd want here. Would `Toast.makeText` be OK?

**Comment by connyduck** [comment]
We also use a different OkHttpClient for image loading so proxy does not work for images. They should use the same client.

**Comment by kylegoetz** [comment]
@connyduck are you talking about the `MediaUploadApi` and that it would better be merge this with `MastodonApi`?

**Comment by kylegoetz** [comment]
Digging around a little more in this, the proxy settings are fetched in the Singleton provider, so if you launch the app and then use the API, the singleton provider executes, and if you change proxy settings after that, the singleton provider never re-initializes the API, so the API does not have the new proxy settings.

I just tested this by logging in without a proxy, adding a proxy in settings, and tooting a status, and the proxy settings were not used, and `NetworkModule` `providesHttpClient` did not re-execute. I'm going to open a ticket about this.
