### ISSUE TITLE
Feature request: click to copy username

### ISSUE THREAD

**Issue by gjvnq** [tuskyapp/Tusky#2955]
Basically when I open a profile, I wish that clicking on the username would copy it (including the server, so always as `@account@example.com` never just `@account`) to the clipboard.

My main reason for wanting this is to help with list management and with sharing profilea with other people.

This is similar to a previous issue #2744 but I decided to make a new one as that one was closed without much discussion.

Given how simple this feature seems to implement, I think I can write the code myself.

What should I know or discuss before putting my hands at the code?

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: Samsung Note 20
- Mastodon instance (if applicable): 

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mcclure** [comment]
This (longpress to copy @@ name, plus a share menu for profiles) was implemented in PR #3120, you should be able to get it in Tusky Nightly and I think this can be closed.
