### ISSUE TITLE
Discussion re: feature request: by default, "response posts" to self are marked unlisted instead of public

### ISSUE THREAD

**Issue by kylegoetz** [tuskyapp/Tusky#2960]
It seems that general advice from experienced Mastonauts is that if you're going to make a status thread, your first should be public but subsequent ones should be unlisted. Would it be desired default behavior to detect and do this automatically? It would help enforce an emerging (already emerged?) community standard and improve user experience for people who know that's what you are "supposed" to do.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

See, e.g., https://mastodon.social/@Johann_v_d_Bron/109338137320183624 for an example of people advising this. It's in German, but crucially step 1 is to mark the first status public and step 2 is subsequent ones unlisted.

It's certainly an improvement on how Twitter gunks up your timeline with fifteen related tweets by the same user in a two minute timespan.

**Edit** I'm interested in what people think. I could implement this if the head honchos of this project like the idea.

**Comment by Tak** [comment]
This is in progress in #2826

**Comment by kylegoetz** [comment]
Gotcha!
