### ISSUE TITLE
No notification on Android 13

### ISSUE THREAD

**Issue by akamizi** [tuskyapp/Tusky#2962]
First time installed today from play store. No notification appears, while with Megalodon yes.

* * * *
- Tusky Version: 20.0
- Android Version: 13
- Android Device: Pixel 4a
- Mastodon instance (if applicable): mastodon.uno

**Comment by akamizi** [comment]
Now work

**Comment by akamizi** [comment]
Reopen because  because they arrive discontinuously

**Comment by connyduck** [comment]
Do you mean notifications in Android or in the Tusky interface?

**Comment by akamizi** [comment]
Android notifications

Thanks!

**Comment by connyduck** [comment]
Ok, so do you have a [UnifiedPush](https://unifiedpush.org/) provider installed? Tusky uses UnifiedPush for live notifications, otherwise it falls back to regular polling, and then the delay is expected.

**Comment by akamizi** [comment]
No, I didn't have UnifiedPush installed, I didn't know it was needed. Since megalodon works without anything else, I assumed it was the same for Tusky.
Thank you
