### ISSUE TITLE
Get rid of swiping between tabs entirely

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#2964]
pros: 
- we can remove the setting for disabling swiping (simpler code is always nice, we have too many preferences anyway)
- we can have swiping between all & mentions in the notification tab in the future without having to worry about nested swiping
- no more problems with swipe sensitivity

cons:
- if one is used to swiping, its probably annoying at first

**Comment by nikclayton** [comment]
I was going to suggest going further, and ditching tabs.

The top (or bottom) bar would be

- hamburger menu to open the side bar (to resolve the multiple reported issues where people can't open it)
- account indicator / switcher on the right
- search icon
- maybe other icons if space?

Then move notifications, local, federated, and mentions to the nav drawer.

E.g., a bit like the nav in Google Calendar.

This would be consistent with the ux guidelines for nav drawers which say they should have an affordance to open them, and that you shouldn't mix and match navigation metaphors within the app (ie, don't mix a nav drawer and tabs)

I think mocking that up to see how it would work would be worthwhile, and I expect the mockup would show other ways to improve on the above.

**Comment by Gryzor** [comment]
> I was going to suggest going further, and ditching tabs.
> 
> The top (or bottom) bar would be
> 
> - hamburger menu to open the side bar

I respectfully disagree.

Personally I loathe drawers. 

I also believe  they are terrible for discoverability, and tapping a hamburger menu is a chore as it's mostly out of reach (since it sits at the top) and the alternative of "drag to open" interferes with gestures more often than not. :)

**Comment by nikclayton** [comment]
Personal preference is not a great reason to abandon platform norms.

https://m3.material.io/components/navigation-drawer/guidelines#c66c1db1-9239-4825-aafc-32a0ef7d6355

> Navigation drawers are recommended for:
> * Apps with 5 or more top-level destinations
> * [...]

which Tusky comfortably exceeds.

* Home timeline
* Notifications
* Local timeline
* Federated timeline
* Direct messages
* Bookmarks
* Favourites
* Lists
* Drafts

And

> *Caution*: Avoid using a navigation drawer with other primary navigation components, such as a navigation bar. Instead, choose a single navigation component based on product requirements and device size: Navigation bars for small screens, navigation rails for tablet screens, and standard navigation drawers for desktop screens.

On larger screens they can be permanently open, aiding with discoverability.

Requiring swipe-to-open as the only means to open them is also covered in the guidelines:

https://m3.material.io/components/navigation-drawer/guidelines#1f351b6f-f177-4ea1-83eb-fcb36dd40245

> Modal navigation drawers are always opened by an action outside of the drawer, such as clicking a navigation menu icon in a navigation rail.

It doesn't have to be a navigation menu icon, but there should be an accessible / discoverable mechanism to do this. There are multiple reported issues where accessibility around that UI was / is a problem, including:

- https://github.com/tuskyapp/Tusky/issues/2799
- https://github.com/tuskyapp/Tusky/issues/2783
- https://github.com/tuskyapp/Tusky/issues/2749
- https://github.com/tuskyapp/Tusky/issues/2473
- https://github.com/tuskyapp/Tusky/issues/2368
- https://github.com/tuskyapp/Tusky/issues/1426
- https://github.com/tuskyapp/Tusky/issues/465

Re the placement of the bar, that can be handled the same way it currently is, exposed as the "Main navigation position" preference.

**Comment by evant** [comment]
I've been using swiping heavily mainly because my phone is too large to reach the tabs at the top. Looks like there is a setting to move the bar to the bottom though. Would recommend making that the default (at least on larger screens) if swiping is removed.

**Comment by maxfragg** [comment]
Agree with @evant but tbh, as a user, I would hate to see swiping removed and it probably will make me change the client, I consider this a basic navigation paradigm, that I expect from such a social media app.

**Comment by DiegoARL38** [comment]
I, as a user, haven't got any problem with this staying as is. Most of the issues listed above should be fixed, though. I, personally, don't follow (nor care, really) changes on UX paradigms or so-called ‘good practices’. I prefer and value consistency.

**Comment by quicoto** [comment]
Swiping should stay, it's very convenient!
