### ISSUE TITLE
Increasing the app font size does not increase menu font size

### ISSUE THREAD

**Issue by magicalskye** [tuskyapp/Tusky#2982]
The text of the menu is still too small to read and increasing app font size does not affect it at all 

* * * *
- Tusky Version: 20.0
- Android Version: 12
- Android Device: Galaxy Tab A8
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Which menu do you mean?

**Comment by Lakoja** [comment]
Can confirm: Any context menu (app, conversation) and the side menu keep the same font.
Only the conversation / status text and account name is increased.

**Comment by connyduck** [comment]
The setting in Tusky was originally introduced because the system settings did not make the text big enough for some people
