### ISSUE TITLE
Blocking shows only the blocked person's toots

### ISSUE THREAD

**Issue by webhat** [tuskyapp/Tusky#2986]
I upgraded to 20.0 yesterday and noticed that the behaviour changed when blocking a user. Before, 19.0, blocking removed the user from the conversation, now, 20.0, I only see the user's toots and don't see the rest conversation

* * * *
- Tusky Version: 20.0
- Android Version: 
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
"Behavior change" is a nice way to say we messed up the logic completely. Thanks for reporting, will fix!

**Comment by webhat** [comment]
Thank you
