### ISSUE TITLE
Add ability to change the icon in the app

### ISSUE THREAD

**Issue by benjaminwolkchen** [tuskyapp/Tusky#2998]
There are people who liked the old logo design better and it would be cool if one could change the icon from within the app.
As for implementation details: Fedilab has a similar feature where you can choose the icon.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by PatHightree** [comment]
I'm also a fan of the old logo

**Comment by connyduck** [comment]
I'm against this, we cannot add settings for everything, especially if it is some design thing that does not impact usability in the slightest. Tusky has "lightweight" in its description and not "super customizable".

Also, there are launchers that allow you to customize icons of apps.

**Comment by stpierrevincents** [comment]
Hi all,

I quite like the new logo. 

- It feels fresh, familiar and inviting. It is also, as ConnyDuck highlights, lightweight.
- While I am mourning the elongated tusks that was the previous icon, it was very difficult to view as a smaller icon and had several accessibility issues in its own design.

Anyways, those are my thoughts as a junior, amateur designer.

Vincent

**Comment by PatHightree** [comment]
The old logo had a sophisticated arab glyph quality to it.
But I can understand that it would have downsides in certain situations.
