### ISSUE TITLE
Support new features for 1.4

### ISSUE THREAD

**Issue by Pangoraw** [tuskyapp/Tusky#301]
As [1.4](https://discourse.joinmastodon.org/t/mastodon-v1-4-1/261) has just been released, I think Tusky should support most of the key features of this release :

- [ ] Users can mute instances
- [x] Media gallery view on profile

**Comment by daycode** [comment]
You can add language filter too maybe ? 🤔

**Comment by Pangoraw** [comment]
For sure ! 😅

**Comment by moshpirit** [comment]
Really? muting an entire instance? isn't it too much?

**Comment by charlag** [comment]
@Pangoraw so, what do you think we should do about muting instances/filtering languages? Add settings for it? Because AFAIK filtering is done on the server.

**Comment by charlag** [comment]
We can check the second box now!

**Comment by charlag** [comment]
Updated: languages filter is not available via API. Domain blocks viewing editing is.

**Comment by connyduck** [comment]
Lets track the domain blocking with this issue https://github.com/tuskyapp/Tusky/issues/1143
