### ISSUE TITLE
[Feature Request] Automatic scroll to the last message of the conversation

### ISSUE THREAD

**Issue by moshpirit** [tuskyapp/Tusky#302]
When a conversation is too long it gets kind of annoying keep scrolling to answer. I know it's not a big deal, Tusky is a great app as it is and I love it, but I think this could make it even better.

I thought also about inverting the sort of the messages so instead of: A→B→C→D it would be D→C→B→A, but it would go against the design on the website so I think the automatic scroll would fit better for being more intuitive. 

Thanks a lot for your time!

**Comment by charlag** [comment]
@moshpirit  I'm not sure we should scroll to the last post. I kinda like the idea of scrolling to the post which was used to open the thread (it almost always works like that now).

**Comment by rixx** [comment]
I'd agree that the current behaviour of scrolling to the selected status is correct and good, scrolling to the latest one would be confusing and surprising. I'd vote for closing this issue.
