### ISSUE TITLE
"load more" jumps to wrong position

### ISSUE THREAD

**Issue by macidev** [tuskyapp/Tusky#3025]
Hi, 

if I tab on load more I always scroll to the top and have to scroll down and search for the last read entry. 

* * * *
- Tusky Version: 20.0
- Android Version: 13 
- Android Device: Google Pixel 4a
- Mastodon instance (if applicable): mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
We're gathering improvements for timeline behavior in #2788
