### ISSUE TITLE
Make status text selectable on a timeline

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3030]
Status text in conversation view is selectable, if it's using the item_status_detailed layout.

Text in statuses elsewhere isn't.

This adds an extra speedbump if I want to copy the text (e.g., to share it to a translation app).

This looks to be fixable with `android:textIsSelectable="true"` to the relevant `TextView` elements. Any reason not to do that?

* * * *
- Tusky Version: 20

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Text that is both clickable and selectable is horrible UX imho. If you are not 100% precise with your taps you end up doing the wrong thing.

**Comment by nikclayton** [comment]
We have text that is clickable and selectable already, in the "large" status in the thread view

Related:

- https://github.com/tuskyapp/Tusky/issues/2379
- https://github.com/tuskyapp/Tusky/issues/2051

Note to self: this isn't as straightforward as using `textIsSelectable="true"` on a `TextView` if the textview is clickable (as the ones on a timeline are -- the click loads the thread/detailed view.

If it's clickable and selectable the first click is ignored (this seems to be an Android bug).
