### ISSUE TITLE
Discuss: Changes to the "scheduling statuses" UX

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3037]
# Notes on scheduled status flow

I've been looking at the user flow for scheduling a status to be posted, and have written some recommendations here.

These are separate to the existing issues:

- https://github.com/tuskyapp/Tusky/issues/2705
- https://github.com/tuskyapp/Tusky/issues/2704
- https://github.com/tuskyapp/Tusky/issues/2260

Posting this here since the individual points are comingled (i.e., each para / bullet point would not correspond to a separate PR), so it makes discussion easier. Once there's consensus on which (if any) changes to make they can be broken out in to separate issues and PRs written.

## Creating a scheduled post

When a new status is being written and has been scheduled (i.e., the user has clicked the clock icon to schedule it, but is still editing it), the "Toot" button button should change to "Schedule". This makes it clear that it's going to be scheduled and not posted (but see also https://github.com/tuskyapp/Tusky/issues/2704)

It's possible to schedule a post for a time in the past (select today's date on the calendar, then select some time earlier in the day in the clock).
  - This is caught when you subsequently try and post the scheduled status     (error: "Mastodon has a minimum scheduled interval of 5 minutes"),     but it would be better to catch this as soon as the user selects the    invalid time.
  - Sadly, TimePicker does not allow you to catch this problem until the user    has dismissed the dialog.
  - Should this error message allow the user to post the status immediately,    or schedule it for ASAP (i.e., now + 5 minutes?)?
    - Probably not. The UI space in a snackbar is small, and it would be      easy for a user to misclick, and inadvertently post something now when      their mistake was to schedule it for today rather than tomorrow. It's      better to be conservative with decisions that make user data public. 

There's no user notification after scheduling a status, you're dropped back to the timeline. A toast to confirm that it's happened, or a snackbar with options (Open the scheduled status? Go to the list of scheduled statuses? Undo it? Go back to editing it?) would be helpful.

## Viewing scheduled posts

Opening the navigation drawer, the "Scheduled posts" menu item should show how many posts are currently scheduled (possibly as a badge on the icon).
  - Maybe it should also show, to the right of the menu text, the date/time     of the next scheduled status (or a countdown to when it goes live,    controlled by the existing preference for time/date display)?

## Managing scheduled posts

Title of the screen is "Scheduled posts". The UI uses "Toots" or "Toot" elsewhere. So either change this to "Scheduled toots", or change "toot" and variations to "post" elsewhere in the app.
 
The statuses in the list don't look like actual statuses (no avatar, username, content warning if it's set, etc). Arguably some of that is
redundant (it'll always be the account's username and avatar), but this would make this list of statuses look like the other lists in the app.

The icon to delete a scheduled post is a diagonal cross. It should probably be the trash can icon.

You have to tap the icon to edit the status. Probably tapping the whole row (except the delete icon) should open the status for editing. This would then be consistent with all the other places you can interact with a status by tapping it.
  - If this is done then the "delete" trashcan icon can go at the bottom    right of the status, in the row that's normally reserved for boost,    favourite, bookmark, etc (obviously, those icons won't be present on    a scheduled status)

There's no indication when the status will be posted. Suggest either:
1. The bottom of each status includes the scheduled date and time for the  post, or
2. The list of statuses is grouped by day, with a heading in the list for  each day. Then the statuses show what time that day they will be posted,  sorted by scheduled time.
- Either way, the list of statuses should be sorted by posting time, soonest  to post first.
    

* * * *
- Tusky Version: 20

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
> Title of the screen is "Scheduled posts". The UI uses "Toots" or "Toot" elsewhere. So either change this to "Scheduled toots", or change "toot" and variations to "post" elsewhere in the app.

actually it should be post everywhere? 🤔 https://github.com/tuskyapp/Tusky/pull/2396

> Either way, the list of statuses should be sorted by posting time, soonest to post first.

Yes, but it is paginated so in order to sort it clientside we would need to load all pages first.

> The bottom of each status includes the scheduled date and time for the post

I would put it on the top, but either way is good at least as it is shown.

> Opening the navigation drawer, the "Scheduled posts" menu item should show how many posts are currently scheduled (possibly as a badge on the icon).

I don't think that is possible as it is not exposed through the api, we would need to load all pages first and that is a bad idea for performance just to display a number.

> "Toot" button button should change to "Schedule"

Yes, but there is VERY limited space and I am sure there will be languages where the text will overflow the button

> You have to tap the icon to edit the status. Probably tapping the whole row (except the delete icon) should open the status for editing. This would then be consistent with all the other places you can interact with a status by tapping it.

yes

**Comment by nikclayton** [comment]
I'm working on this over in https://github.com/nikclayton/Tusky/tree/scheduled-show-time. I'll prep a PR when done, but if you want to look at the individual commits:

- [x] Show a confirmation toast when a post is scheduled or sent, https://github.com/tuskyapp/Tusky/commit/40ddcd376156610dd526aa03f61ccefc401dde9e
- [x] Change TOOT on send button to SCHEDULE if appropriate, https://github.com/tuskyapp/Tusky/commit/db0c476d9cc437bb99a14112c815d0ebe5585342
  - I'm not concerned about this for other languages, because if they are too long they can continue to use the current text for the new string resources.
- [ ] Tap the row to edit a scheduled status
- [ ] Show scheduled statuses like other statuses, move delete icon, show scheduled time
- [ ] Fix https://github.com/tuskyapp/Tusky/issues/2705 (I've seen this in my testing)
- [ ] ...

**Comment by nikclayton** [comment]
Note to self: There's a lot of overlap between the UX for managing drafts and the UX for managing scheduled posts. Suspect there's an opportunity to consolidate code and views to simplify things.

**Comment by da2x** [comment]
Hi. I don’t have any problems with using the post scheduling interface. However, I struggle too keep track of what is going live when from the Scheduled posts page/view.

I’d love to see the scheduled publication time displayed above each post on this page. The list of posts should also be sorted by the scheduled publication time. Whichever post is going live first should always be displayed at the top, followed by the next one to go live, and so on. Currently, the most-recently created post is displayed first, followed by the second-most-recently, and so on.

_Thank you for your time and for the great app!_
