### ISSUE TITLE
Converting Java to Kotlin

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3043]
Tracking issue for the work to convert Java source files to Kotlin.

Files (paths relative to `app/src/main/java/com/keylesspalace/tusky`):

- [x] `adapter/AccountViewHolder.java`, https://github.com/tuskyapp/Tusky/pull/3044
- [x] `adapter/NotificationsAdapter.java`, https://github.com/tuskyapp/Tusky/pull/3159
- [ ] `adapter/StatusBaseViewHolder.java`
- [ ] `adapter/StatusDetailedViewHolder.java`
- [ ] `adapter/StatusViewHolder.java`
- [x] `components/compose/view/ComposeScheduleView.java`, https://github.com/tuskyapp/Tusky/pull/3147
- [x] `components/compose/view/ProgressImageView.java`, https://github.com/tuskyapp/Tusky/pull/3147
- [ ] `components/conversation/ConversationViewHolder.java`
- [ ] `components/notifications/NotificationHelper.java`
- [ ] `db/AppDatabase.java`
- [x] `fragment/NotificationsFragment.java`, https://github.com/tuskyapp/Tusky/pull/3159
- [ ] `interfaces/AccountActionListener.java`
- [ ] `interfaces/ActionButtonActivity.java`
- [ ] `interfaces/PermissionRequestor.java`
- [ ] `interfaces/StatusActionListener.java`
- [ ] `network/ProgressRequestBody.java`
- [x] `util/HttpHeaderLink.java`, https://github.com/tuskyapp/Tusky/pull/3046
- [x] `util/PairedList.java`, https://github.com/tuskyapp/Tusky/pull/3046
- [x] `util/ThemeUtils.java`, https://github.com/tuskyapp/Tusky/pull/3046
- [x] `util/TimestampUtils.java`, https://github.com/tuskyapp/Tusky/pull/3046
- [x] `view/BezelImageView.java`, https://github.com/tuskyapp/Tusky/pull/3147
- [x] `view/EndlessOnScrollListener.java`, https://github.com/tuskyapp/Tusky/pull/3147
- [x] `viewdata/NotificationViewData.java`, https://github.com/tuskyapp/Tusky/pull/3159
- [ ] `BaseActivity.java`

**Comment by connyduck** [comment]
For the record, I think converting to Kotlin just for the sake of it is a waste of time, a conversion should come at least with better architecture/performance/readability etc.

`EndlessOnScrollListener` would go away anyway once everything is AndroidX paging.
`ActionButtonActivity` would go away when we remove the "Hide compose button when scrolling" setting, see https://github.com/tuskyapp/Tusky/issues/2504
`PairedList` goes away with the Notifications refactor.

**Comment by nikclayton** [comment]
> For the record, I think converting to Kotlin just for the sake of it is a waste of time, a conversion should come at least with better architecture/performance/readability etc.

I can appreciate that view, but I disagree with some of it, for a couple of reasons.

1. If I've understood the rxjava usage properly, getting this done is a blocker for moving away from rxjava. Moving off rxjava unblocks other architectural / readability improvements, so I'm interested in expediting that so I can move on to those.
2. The mix of languages and architecture idioms is a barrier to entry for new contributors to the project.
3. I would like these PRs to be as easy as possible to review. I think that's easier if the conversion is as straightforward as possible, so that it's as easy as possible for the reviewer to be comfortable that the change doesn't break existing functionality.

That's also why I've written tests in this PR (and verified those tests work before/after the conversion).

This does have a drawback -- it means more, smaller PRs to review. That's more work for me to create them, and more code reviews to be carried out. But on balance, I think it will lead to code reviews that are easier to complete, and easier for people to slot in to the free time they have to do reviews.

I do agree that (limited) changes that improve readability or safety as part of the conversion makes sense. That's why https://github.com/tuskyapp/Tusky/pull/3044/files fixes a layering violation and brings in view binding to improve safety, https://github.com/tuskyapp/Tusky/pull/3046/files uses a data class and property method to be more consistent.

If you have suggestions for other specific changes in these PRs that would improve readability in the Kotlin code I'm happy to make them (and repeat them in the other conversions)
