### ISSUE TITLE
[Feature Request] one click Boost

### ISSUE THREAD

**Issue by alzakex** [tuskyapp/Tusky#3045]
Your app is very good. I wish I could boost posts without a confirmation screen. Two clicks is too many. 

* * * *
- Tusky Version: 20.0
- Android Version: 13
- Android Device: Pixel 5a
- Mastodon instance (if applicable): im-in.space 

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by evant** [comment]
There's an option in preferences for this

**Comment by charlag** [comment]
Yes, preferences -> show confirmation dialog before boosting

**Comment by alzakex** [comment]
I am a blind fool. Thank you!
