### ISSUE TITLE
Help needed getting instrumentation tests working

### ISSUE THREAD

**Issue by kylegoetz** [tuskyapp/Tusky#3050]
I'm trying to get instrumentation tests (of which there are currently none) working in Android Studio so I can write them for all the classes that needed updating pursuant to fix for #2969, which required minor overhaul of dependency injection for API and Proxy management. Essentially now we have a singleton `ConnectionManager` that provides an up-to-date connection and API that reflects a desired domain name and proxy. Previously, there was an injected `MastodonApi`, which was a singleton and thus any change to proxy required restarting the application, and any change to domain required an OkHttp interceptor to get around the same singleton issue.

However, I cannot seem to get instrumentation tests working and would appreciate some help. I started with the LoginActivity, but the test hangs on the first attempt to interact with the UI, and after about four hours of trying everything, I'd hate for the proxy fix (and a unicode domain name fix improvement) to never be filed as a PR because I can't get the instrumentation tests working.

Any volunteers? I can push my code to my forked copy if there's someone willing to help: https://github.com/kylegoetz/Tusky/tree/2969/mutated_injected_dependency

* * * *
- Tusky Version: dev branch
- Android Version: API 32
- Android Device: Pixel XL 4a (emulated)

- [s] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kylegoetz** [comment]
I have more code that I need to commit to have the branch up to date with my latest code but I wanted to at least push something out there and get the issue posted before I go do my regular life stuff

**Comment by nikclayton** [comment]
What sort of problem are you having? I can take a look if you push a branch somewhere.

**Comment by kylegoetz** [comment]
I don't need the help anymore. Turns out the Espresso dependency (3.4.0) causes the test to hang silently (until eventual timeout) when you do work on a UI thread in a way it doesn't like, but updating to 3.5 crashes the test and specifies the issue. Then I fixed the issue and tests work great now.
