### ISSUE TITLE
Add Belarusian language

### ISSUE THREAD

**Issue by xzfantom** [tuskyapp/Tusky#3051]
I scanned weblate site and found no Belarusian translation there. I didn't find how to send request for new language there, so if this is right place, please add support for Belarusian language, if not - send me to the right place.
Thank you.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Hi. Translations are carried out by volunteers. Are you able to volunteer? It's a very effective way to get involved and improve things for many people.

If you can volunteer, translations are done through https://weblate.tusky.app/projects/tusky/tusky/

You can register for an account there (there's documentation about registering at https://docs.weblate.org/en/latest/user/profile.html).

There is no Belarusian translation at the moment, so would click the "Start new translation" button at the bottom of the screen, and start translating.

Your translations will be reviewed, and submitted as changes to the project.

**Comment by xzfantom** [comment]
Hello! Yes, I'm volunteer. I took part in translating mastodon, now I want to translate Tusky to use it on my phone.
I've already registered on [https://weblate.tusky.app/](https://weblate.tusky.app/projects/tusky/tusky/), but I can't press "Start new translation" button - it says that I don't have enough rights.

**Comment by connyduck** [comment]
New language added https://weblate.tusky.app/projects/tusky/tusky/be/

**Comment by xzfantom** [comment]
Thank you very much!
