### ISSUE TITLE
Very alarming 

### ISSUE THREAD

**Issue by MahaskaVillage** [tuskyapp/Tusky#3061]
I use NordVPN to protect myself. With it running, Tusky and Twitterdumb doesn't work. Why is that??? I didn't expect it from Tusky where I do from the corporate controllers like Fakebook and Twitterdumb.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Are you sure it's the VPN?

I ask because I looked at another report of network issues, and it was a problem with the phone, not Tusky (https://fosstodon.org/@jefmes/109519850746643196).
