### ISSUE TITLE
Respect "Hide with a warning" option for filters

### ISSUE THREAD

**Issue by YZirkind** [tuskyapp/Tusky#3064]
I have my filters set to hide filtered posts behind a content warning, which works as expected on the web app, but in Tusky those posts are hidden completely (the other option for filters). I want to still have the ability to see these posts even if I have them hidden, and that seems to be impossible currently with Tusky.

* * * *
- Tusky Version: 20.0
- Android Version: 12 (LineageOS 19.1)
- Android Device: Google Pixel 4a 5G
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Tusky 22 (in beta now) implements this.
