### ISSUE TITLE
Minor bug: Accounts which have moved show new name not old

### ISSUE THREAD

**Issue by rbairwell** [tuskyapp/Tusky#3071]
When viewing a profile of an (not followed) remote user:

If that user has moved instances, Tusky shows the name of their new account as "(new name) has moved to...(new name)" instead of "(name displayed) has moved to...(new name)" as displayed by the web UI (Fedilab just shows the full old and new Mastodon handle)

![Screenshot_20221219-123308](https://user-images.githubusercontent.com/775269/208427410-0db3f24e-5c69-41a2-a3b8-20425fa551f4.png)

* * * *
- Tusky Version: 20.0
- Android Version: 12
- Android Device: Pixel 3
- Mastodon instance (if applicable):

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/3015
