### ISSUE TITLE
[Feature Request] Placeholder in feeds

### ISSUE THREAD

**Issue by ratcatcher** [tuskyapp/Tusky#3072]
It would be good to have an option in timelines to take up where you left off.  Sometimes tabs do open at this point but in other cases the feed defaults to the latest toot.

For example, let's assume I have been reading through the home feed in chronological order.  I come to a point where it says "LOAD MORE".  I click on this and am taken to the latest toot.  I then have to scroll back down to find where I left off.  I may have to repeat this several times to load intervening toots.

What I would like is for "LOAD MORE" to load new stuff above, rather than below, my current position, so I remain at the point of the last toot I read.

* * * *
- Tusky Version: 20.0-6aed1c68
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Hi, thanks for the input! We're gathering feedback for timeline improvements in #2788
