### ISSUE TITLE
[Feature Request] Case sensitivity of hashtag search

### ISSUE THREAD

**Issue by ratcatcher** [tuskyapp/Tusky#3074]
At present when you type # and start to type the hashtag, a list of suggestions appears, which is not case-sensitive.  Would it be possible either to make it case-sensitive or, alternatively, to render the version with a leading cap first?

People who use screen readers need this so the hashtags are read out as actual words rather than spelled out letter by letter.

* * * *
- Tusky Version:  20.0-6aed1c68
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This needs to be fixed on Mastodons side

**Comment by ratcatcher** [comment]
An elegant alternative might be to provide a feature for people to save 
a custom list of frequently used hashtags.

This could be invoked when composing a post.  Checkboxes would allow the 
user to choose which hashtags to paste into the post.

Regards

Nick
