### ISSUE TITLE
Show warning or pop up when enabling 'Hide the title of the top toolbar'

### ISSUE THREAD

**Issue by robertvanhoesel** [tuskyapp/Tusky#3078]
I.e. after or while toggling, show a popup that explains the alternative UX that users opt in too:
"When you hide the top toolbar, you can only access the sidebar by long pressing and swiping from the left side of the screen

[ Cancel | Ok ]"

It took me a reinstall and finding multiple people making posting the same "issue" here before learning about it. For a 'destructive' setting like this a better UX is desirable.

**Comment by Tak** [comment]
Fixed by #2973
