### ISSUE TITLE
[Feature Request] Show More upward option.

### ISSUE THREAD

**Issue by KS-HTK** [tuskyapp/Tusky#3079]
It would be great if you could toggle the "show more" option of the timeline to load upward. Sticking at the post below instead of always loading downward so I have to scroll down to then read my timeline in chronological order.

* * * *
- Tusky Version: 20.0
- Android Version: 8.0.0
- Android Device: Huawei P10 Lite

- [~] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (More or Less, did not read every issue.)

**Comment by Tak** [comment]
Thanks for your input! We're collecting feedback on improvements to timeline behavior in #2788
