### ISSUE TITLE
"Hide follow button while scrolling" text (under Preferences > Appearance) gets cut off

### ISSUE THREAD

**Issue by GnUfTw** [tuskyapp/Tusky#308]
**Environment**
- HTC Desire 610
- Android 4.4.2
- API 19
- Display: 4.7 inches, 540 x 960 pixels
- Tusky version: 1.1.4-beta.3

**Reproduction steps** 
1. Open Tusky application
2. Open _Preferences_ from options menu
3. Under the _Appearance_ section, one will see the string _Hide follow button while scrolling_ gets displayed but only shows the word _scrolling_ partially (i.e. _Hide follow button while sc_).

**Comment by connyduck** [comment]
I noticed the same when doing the german translation, so in german the label is only "Hide button while scrolling" (no "follow"). Maybe change it in English as well?

**Comment by GnUfTw** [comment]
The **CheckBoxPreference** in consideration gets its label from the **pref_title_hide_follow_button** string value defined in the given translations _string.xml_ file found under app > java > res > values. In the German translation this button is titled "Verstecke Button bei Bildlauf" which translates to "Hide button or picture" in English. This issue you mention @connyduck is slightly different from the op issue. My issue is that I would expect the **title** of the **CheckBoxPreference** element to wrap if it doesn't fit inside the containing element.

**Comment by connyduck** [comment]
fixed by #1045
