### ISSUE TITLE
Load more button should have option to load above or below current point

### ISSUE THREAD

**Issue by gamefreak613** [tuskyapp/Tusky#3081]
Users would like to be able to have the "load more" button load new posts above the current point in the timeline rather than below.

Currently, when scrolling up (reading posts from the past to most recent) if a "load more" is encountered and pressed, posts are loaded and the user is put at the top of the newly loaded posts. This means users that want to see every new post would have to scroll down until they find the post they remembered being on before pressing load more, and then progressing from there. 

Loading posts so that the user stays with the older posts rather than being at the top of the newer loaded ones (or making it an option to do so) would resolve this frustration. 

* * * *
- Tusky Version: 20.0
- Android Version: 13
- Android Device: 4a5G
- Mastodon instance (if applicable):

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- I searched but didn't find an issue with just this one suggestion (there was one I found that sounded a bit like it, but was lumped in with a bunch of other requests). Sorry if this causes unnecessary clutter.

**Comment by Tak** [comment]
Thanks for your input! We're gathering feedback about improvements to the timeline in #2788
