### ISSUE TITLE
Pasting styled text into Tusky causes spurious styles

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#3082]
![kjNBSyrwhcHVzffPFBncribg](https://user-images.githubusercontent.com/277318/208718884-598203a5-ccf3-4c8c-8937-b1d3f51e7608.png)

Select styled text in a Chrome window. Copy it and paste it into Tusky compose. It retains its style in the Tusky compose. But Tusky doesn't do anything with the styles.

Taki on Element says

> in the screenshot, I'm pretty sure android is just applying a styled span that then disappears when we extract the text to post

Expected behavior: The styled text should be stripped when pasting into the compose box.

Once this is resolved, we should file a second long-term issue for the advanced technique of keeping the styled text but then "doing something" with it (EG on markdown instances)

* * * *
- Tusky Version: 20.0
- Android Version: 12
- Android Device: Sony XPeria 5 III
- Mastodon instance (if applicable): not applicable, but m.s

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
I'll take a look at this.
