### ISSUE TITLE
Date and time on scheduled posts

### ISSUE THREAD

**Issue by lianergoist** [tuskyapp/Tusky#3088]
It would be nice if there were time and date on the scheduled posts. As it is now, we have to open the post to see it.

* * * *
- Tusky Version: 20
- Android Version: 12
- Android Device: Lenovo tablet
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/3037
