### ISSUE TITLE
"load more" direction is wrong 

### ISSUE THREAD

**Issue by perler** [tuskyapp/Tusky#3089]
[Issue text goes here].

* * * *
- Tusky Version: 20.0
- Android Version: all
- Android Device: all

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

The "load more" fill direction is wrong. 

You scroll _up_ from oldest to newest. 
When you come back and meanwhile there has been a lot of activity you need to tap "load more" to see new entries. These entries are filled _down_, and you must scroll back to find where you have been.

Video: https://user-images.githubusercontent.com/623092/209070370-682b7ee8-8268-4a05-9ac2-fefa8b459e3c.mp4

**Comment by Tak** [comment]
Thanks for your input! We're collecting feedback for timeline improvements in #2788
