### ISSUE TITLE
Embedded link card does not lead to "#scrollHere" URL

### ISSUE THREAD

**Issue by beholdnec** [tuskyapp/Tusky#3094]
If I paste a URL containing a "#scrollHere" marker, the embedded link card omits the scroll portion. Clicking on the card leads to the top of the page. Clicking the link itself (not the card) still leads to the expected location.

This issue occurs in this toot: 
https://mas.to/@beholdnec/109561260469265602

* * * *
- Tusky Version: 20.0
- Android Version: 13
- Android Device: Google Pixel 5
- Mastodon instance (if applicable): mas.to

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This is a bug in Mastodon, see https://github.com/mastodon/mastodon/issues/19538
