### ISSUE TITLE
Load More should open above, not below

### ISSUE THREAD

**Issue by msbellows** [tuskyapp/Tusky#3099]
Hi! I love your app, but have one gripe: when I load more toots by clicking "Load More," it loads the new toots BELOW that place in the timeline, and I have to scroll down and guess where I left off. If the new toots appeared ABOVE the "Load More" line, navigation would be much easier. Thanks!

* * * *
- Tusky Version:
- Android Version:
- Android Device: Samsung S22+
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
Linking this to https://github.com/tuskyapp/Tusky/issues/2938 (and especially its PR).

**Comment by Tak** [comment]
Thanks for the input! We're collecting feedback on timeline improvements in #2788
