### ISSUE TITLE
Show alt text for images that are still loading

### ISSUE THREAD

**Issue by lucaswerkmeister** [tuskyapp/Tusky#3117]
Tusky only shows a blurred version of an image while the image hasn’t loaded yet. It should display the alt text as well, like e.g. Mastodon Web does. (Though that presentation isn’t perfect either – notice how the eye icon hides the beginning of the first alt text.)

Tusky:
![post by jiska@chaos.social: “The #HIP22 decorations are really great. The event feels a bit like an Easterhegg.” There are two images, which are only visible as blueish-purple-green blurs.](https://user-images.githubusercontent.com/2346599/209858771-a6e299cb-319b-49ce-844e-f471b0a5571d.png)
Mastodon Web:
![the same post; on top of the images, Mastodon shows the alt text: “Rocket with UV light” and “Super Mario UV light”](https://user-images.githubusercontent.com/2346599/209858781-6a4c5cc8-75fa-4b76-9427-bc009be8e446.png)
([link to post](https://chaos.social/@jiska/109591454844265336))

* * * *
- Tusky Version: 20.0
- Android Version: 12
- Android Device: moto g52
- Mastodon instance (if applicable): N/A

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
This is just how browser works, I don't think we should do it, you can already hold it to get a description

**Comment by lucaswerkmeister** [comment]
> This is just how browser works

Of course it is, because it’s the purpose of the alt text: to be shown as an alternative to the image. Browsers show the alt text because it’s a useful thing to do. I don’t understand how this means that Tusky shouldn’t do it?

> you can already hold it to get a description

Sure, but why make the user do that extra work? So they can admire the pretty color gradients instead? The alt text is surely more important than the blurry preview.
