### ISSUE TITLE
Mark older posts

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#3125]
In the spirit of the social aspect of Social media I prefer to interact with recent posts on a personal level.

I. e. it is normally a bit awkward to reply to a Sunday's post "What are you planning today?" on Monday.

Therefore I always have to check very ardently the age of a status.

*Desired feature*
It could be useful to indicate older posts. Maybe even with two colors for "hours old" and "days or years old".

![edit_time_highlight](https://user-images.githubusercontent.com/1618905/210166579-57579b06-fa7f-41ab-89ce-4f2edf6146a5.png)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
I've been using this for some days now. And I like it more than I thought. :-)

So here is the respective PR.

**Comment by connyduck** [comment]
I'm against adding this
- no new information, it says right there on the timestamp how old the status is
- It adds more clutter to the already very loaded interface
- It is unclear what the color means, I'd assume it means unread or something

If it is useful for you keep it in your fork?
