### ISSUE TITLE
Long descriptions of videos are cut-off/layered behind the video

### ISSUE THREAD

**Issue by eliasp** [tuskyapp/Tusky#3133]
Long descriptions of videos might get cut-off, since they're placed behind the video.
I've seen it happen with this post: https://mastodon.social/@ryanhoulihan/109626290103381298
Screenshot of this post:
![image](https://user-images.githubusercontent.com/48491/210422704-a9b43fee-a02c-42be-a438-3f79d751005f.png)

* * * *
- Tusky Version: 20.0-8c0f02cf (Tusky Test)
- Android Version: 11
- Android Device: Oneplus Nord (AC2003)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/3133
