### ISSUE TITLE
Timeout for long video captions should be longer

### ISSUE THREAD

**Issue by jsoref** [tuskyapp/Tusky#3141]
I can't read this caption in the time alloted. It takes me ~3 attempts
https://social.coop/@jonny/109634444943205237

https://user-images.githubusercontent.com/2119212/210813357-c7a95b1a-7249-4c4c-8e61-965d85447bad.mp4

* * * *
- Tusky Version: Tusky Test 20.0-0328c4e8
- Android Version: 12
- Android Device: Pixel 3A
- Mastodon instance (if applicable): social.coop

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
fixed by #3857
