### ISSUE TITLE
Prefer /api/v2/instance

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3146]
`/api/v1/instance` is deprecated, and returns a `V1::Instance` (https://docs.joinmastodon.org/methods/instance/#v1).

`/api/v2/instance` is not deprecated, and also returns a `V1::Instance` (https://docs.joinmastodon.org/methods/instance/#v2).

The `getInstance()` API method should probably be split in to a v1 and v2 versions, and `getInstance()` should call the v2 method first, falling back to the v1 method if the v2 one fails.

Not all instances support both v2 and v1. For example:

- https://post.lurk.org/api/v2/instance (works)
- https://post.lurk.org/api/v1/instance (returns a non-JSON error page)

* * * *
- Tusky Version: 20
- Mastodon instance (if applicable): post.lurk.org

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by aaaaargZombies** [comment]
Thanks for your help making this issue, I showed it to the admins of the instance. Two of them are using tusky 20 and not experiencing this issue, see thread:

https://post.lurk.org/@az/109647424624580477

very strange

**Comment by nikclayton** [comment]
When the API call succeeds, Tusky caches the result.

If the API call fails, *and* it previously succeeded, *and* the result was cached, the old result was used.

So it sounds like the cache on your device doesn't contain the information. Then Tusky falls back to the 500 character default.
