### ISSUE TITLE
Feature request: Scheduled boosts

### ISSUE THREAD

**Issue by dvinothkumar** [tuskyapp/Tusky#3156]
Feature request to do scheduled boosts. Tusky already supports scheduled posts. Being able to do scheduled boosts will also be nice. 

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/2863#issuecomment-1320893236
