### ISSUE TITLE
Insight into Home timeline ordering

### ISSUE THREAD

**Issue by andrewgodwin** [tuskyapp/Tusky#3157]
I'm developing a non-Mastodon Fediverse server that implements its client API in a "compatible" fashion (https://github.com/jointakahe/takahe/), and I'm seeing some odd timeline behaviour against our APIs with Tusky and wanted to see if you could offer any insight.

The key problem: All Boosts appear at the top of the timeline above all normal posts/toots.

Now, the big difference we have versus Mastodon is that our posts have IDs like `1234` and our boosts have IDs like `interaction-1234`. The behaviour I'm seeing looks quite like what would happen if the timeline were ordered by reverse sort on the lexographic IDs, which I imagine would work with Mastodon and its snowflake-style IDs.

So my question is - is this how the Home timeline is ordered? If not, are there any hints as to how you order the results that you could provide to help me improve compatibility?

I appreciate it's asking extra work from you outside of the already-hard mission of making Tusky work for Mastodon, but you're in a unique place to help me understand how client apps use their API and how to emulate it best! Thanks!

* * * *
- Tusky Version: 20.0
- Android Version: 13
- Android Device: Pixel 7
- Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
> So my question is - is this how the Home timeline is ordered?

Yes. There's more info in the thread that starts at https://github.com/tuskyapp/Tusky/issues/2938#issuecomment-1328898189

**Comment by nikclayton** [comment]
https://docs.joinmastodon.org/api/guidelines/#id from that thread is the most official guidance, I think, on how to sort Mastodon IDs.

**Comment by andrewgodwin** [comment]
Got it, thanks - I figured it was something like that. I can work with "must be sortable by size and then lexically".

Appreciate your help!
