### ISSUE TITLE
App crashing when opening tabs settings

### ISSUE THREAD

**Issue by LuisMayo** [tuskyapp/Tusky#3161]
In settings, while trying to open the "tabs" setting in the "filter" category the app crashes to the timeline

* * * *
- Tusky Version: Tusky Test/Nightly 20.0 c650ca93
- Android Version: MIUI 13.2.2 (Android 13 TP1A.220624.014)
- Android Device: Xiaomi Poco X4 GT
- Mastodon instance (if applicable): N/A

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thanks for reporting!
It is a regression from #3090 
Fragment names are hardcoded but obfuscated for release builds, referenced fragments can't be found anymore -> 💥 
cc @nikclayton can you fix this please?

**Comment by nikclayton** [comment]
Looking...
