### ISSUE TITLE
Not showing sensitive content or content with warnings despite options being set

### ISSUE THREAD

**Issue by SteveDinn** [tuskyapp/Tusky#3163]
Despite having the appropriate options turned on, my Tusky Test is not showing sensitive content or pasta with content warnings by default.

The current released build is showing this content correctly (Tusky 20.0).

![Screenshot_20230110-181002](https://user-images.githubusercontent.com/3911507/211673359-c2ef79b5-c766-4d60-abf6-5adc10ac4d9d.png)

* * * *
- Tusky Version: Tusky Test 20.0-561eda84
- Android Version: 12
- Android Device: LG Velvet
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Where is it not shown correctly? In thread view? Timelines (which ones)? Profiles? Notifications? Everywhere?

**Comment by SteveDinn** [comment]
I only noticed it in my timeline and thread view. It might also happen in the other places, but I haven't seen that yet.  Sorry for not mentioning this detail in the original bug.

**Comment by connyduck** [comment]
Can not reproduce with Tusky 20.0-f28252bf

**Comment by SteveDinn** [comment]
I am still seeing it in 20.0-7d444d1f, that's the latest version I can get from Google Play. I can reproduce it by searching as well, like this post, for example:

https://mastodon.social/@atomicpoet/109678564669721876

**Comment by Lakoja** [comment]
Do you use multiple accounts, @SteveDinn ?

**Comment by Lakoja** [comment]
Preliminary research result / questions: You might be able to workaround this by deactivating and activating that option in the settings.
Note that it only affects newly loaded content. So things you've already seen will probably keep their visibility setting.

**Comment by SteveDinn** [comment]
It looks like unsetting and resetting these options worked. Thanks!

Also, no, I don't have multiple accounts in Tusky.

**Comment by Lakoja** [comment]
Did you log off (or do it often) from Tusky?

**Comment by SteveDinn** [comment]
No. I've been logged on to Tusky Test since I installed it. I've never logged out.

**Comment by SteveDinn** [comment]
This sounds like a completely different issue to my original one.
