### ISSUE TITLE
Add option to define sensitive area for swiping right to Switch tabs

### ISSUE THREAD

**Issue by maikgreubel** [tuskyapp/Tusky#3177]
I use my left hand to scroll down in timeline. If I swipe not accuratly from top to down but a little bit from right to left, the timeline switches to next tab.

It would bei helpful, to define an area, where swipe from right to left to switch timelines could bei defined.

* * * *
- Tusky Version: 20.0
- Android Version: 10
- Android Device: Cupot X30
- Mastodon instance (if applicable): Ui issued but if it Matters really social.tchncs.de

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Maybe resolved by #3148 ?

**Comment by maikgreubel** [comment]
Thank you for pointing it for me. I'll give it a try.
