### ISSUE TITLE
Drop tabs, use spinner-like menu on the main app bar

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3191]
Megalodon has made a UI change we should shamelessly steal.

Instead of tabs at the top of the screen to navigate between different timelines, it's a spinner-like menu (i.e., there's text with the name of the timeline you're looking at, and a downward-pointing triangle immediately next to that to indicate it's clickable).

This solves multiple problems that users are complaining about.

- It's easy to add more timelines without the user having to swipe endlessly left / right (which is why the limit is currently 5)
- It removes the tab bar, freeing up screen real estate
- We can then remove the "Hide app bar" preference, it's not necessary, which means...
- ... there's always somewhere to show the overflow menu (e.g., for "Refresh", or "Apply filter" for notifications, etc)
- Timelines can be shown in the list by name, instead of occasionally cryptic icons. This is especially important for users who want to manage multiple lists

and probably more.

Would fix or moderate:

- https://github.com/tuskyapp/Tusky/issues/2512
- https://github.com/tuskyapp/Tusky/pull/3097
- https://github.com/tuskyapp/Tusky/issues/2964

* * * *
- Tusky Version: 20

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Yeah, I think swiping to move between them can be preserved.

**Comment by Lakoja** [comment]
It might then also get rid of this problem: https://github.com/tuskyapp/Tusky/issues/2857
(which i have seen once outside of debugging)

On the other hand it might decrease discoverability (which is not high at the moment): https://github.com/tuskyapp/Tusky/discussions/3144

**Comment by DavidEdwards** [comment]
https://user-images.githubusercontent.com/1585923/213868296-d7ee9ab9-3ea7-48dd-8dae-414dbb7b6bce.mp4

Example video of the feature.

**Comment by maxfragg** [comment]
I strongly agree with @Tak - this would break with a UX paradim established for Twitter clients more than 10 years ago and force everyone to do one more touch, if they don't use swiping.
Especially it would be terrible for accessibility, as you would force people with coordination issues to use a dropdown, which always is harder to use.

**Comment by sl1txdvd** [comment]
I use tabs on the bottom and have disabled swiping. The proposed change would completely break my Tusky usage. If this is going to be implemented please make it optional. I absolutely dislike it.

**Comment by nikclayton** [comment]
Obsoleted by https://github.com/tuskyapp/Tusky/issues/3331
