### ISSUE TITLE
[Feature Request] Allow viewing message you are responding to, while drafting a response

### ISSUE THREAD

**Issue by hexylena** [tuskyapp/Tusky#3194]
when I am responding to someone, I often find myself wishing I could see what they said while I write and edit my response. My current workflow often involves saving it as a draft, viewing their message again, and then opening the draft. Or copying their message into another app before responding.

I would love to either 

- be able to scroll up from the composition view and see their message 
- or maybe pull down a shade with their message
- or tap a button to see their message

* * * *
- Tusky Version: 20
- Android Version: 13
- Android Device: pixel 6 pro
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
You can tap where it says "Replying to user 🔽" to show the message to which you're replying

![Screenshot_20230119-174212](https://user-images.githubusercontent.com/142250/213503767-9465c278-fe5d-4fed-b62a-f4819613880b.png)

**Comment by hexylena** [comment]
oh wow, I did not realise that was something I could interact with. thanks! guess this is already done!
