### ISSUE TITLE
Profile settings display is sometimes incorrect

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#3204]
Noticed in https://github.com/tuskyapp/Tusky/issues/3163

All account based settings ("profile settings") might not correspond to their displayed value in the settings screen.

For example when logging out and in the "new" account will get the default settings. However there might already be a duplicate set of "shared preferences" which are used in the settings screen instead.

They will get in sync after the first change to these settings.

*So to reproduce*

- Change the "Always show sensitive content" to on
- Logout and in
- Open the profile settings screen again
Then this settings will be shown as "on" when in fact the actual account setting used is off.

* * * *
- Tusky Version: Any - at least since 2020

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
Technical explanation (of the bug):

All preferences use by default the "shared preferences" as the data storage.
`AccountPreferencesFragment would like to use the account db object instead and `tries to initialize the (displayed) settings' value with `isChecked`.
This would actually also set the value in the shared preferences. However during construction the preference manager is not yet set and thus nothing is done there.
There is then afterwards the attaching of the preference manager which triggers `TwoStatePreference#onSetInitialValue` which loads and sets the value from the shared preferences.

**Comment by connyduck** [comment]
Nice find. Also, your solution seems like a good idea.
