### ISSUE TITLE
Swipe to left/right is to sensitive

### ISSUE THREAD

**Issue by NCC1701M** [tuskyapp/Tusky#3208]
To swipe to left or right to switch between the tabs (Home, Notifications, ...) is a good and default feature.

But the swipe detection oft Tusky is to sensitive. If you scroll down your timeline using your thumb the thumb performs a small curve. If you make a long down swipe, lhis little curve is - very often - misinterpreted as a swipe to left or right and Tusky switches to the next/previous tab.

The dectetion of the left and right swipes shouldn't be that sensitive.

**Comment by Tak** [comment]
Duplicate of #2112
