### ISSUE TITLE
expand buttons area

### ISSUE THREAD

**Issue by okingfisher** [tuskyapp/Tusky#3209]
Clicking boost, reply, bookmark, fav often results to focusing the toot. Possibly, the active area covers barely the icon, therefore hitting slightly offset does not result in the intended consequence (boosting, etc.).
I believe this is the only app with this kind of behavior. The button row (the one with reply, boost, etc.) should not result in anything else than performing these actions (saving the left/rightmost space).
I get the unwanted outcome (going to the toot) half of the times I try to boost/like.
Great work!

* * * *
- Tusky Version: 20.0
- Android Version: 12
- Android Device: Samsung 10S
- Mastodon instance (if applicable):

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2872
