### ISSUE TITLE
accountSubscribeButton is visible on user's own profile

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3214]
accountSubscribeButton (the one with the notification bell) is visible when I go and look at my own profile.

I think that's a UI regression.

* * * *
- Tusky Version: 20

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Can't reproduce on Tusky 20, but in current `develop`, it is a regression from https://github.com/tuskyapp/Tusky/pull/3067
