### ISSUE TITLE
Sometimes the tab title is really tiny

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#3217]
Left: Normal
Right: Sometimes it does this and I don't know why
Have seen in both Home and Notifications tabs

[<img width=250 src="https://user-images.githubusercontent.com/277318/214759191-740004fc-9788-485d-9ff2-8e4453cc8f14.png">](https://user-images.githubusercontent.com/277318/214759191-740004fc-9788-485d-9ff2-8e4453cc8f14.png) [<img width=250 src="https://user-images.githubusercontent.com/277318/214759264-1f96f635-199d-42ce-984d-43a93f25cc47.png">](https://user-images.githubusercontent.com/277318/214759264-1f96f635-199d-42ce-984d-43a93f25cc47.png)

* * * *
- Tusky Version: 21.0. I am logged in on 2 accounts but I have the "don't show account name" option selected
- Android Version: 12
- Android Device: Sony XPeria 5 III
- Mastodon instance (if applicable): mastodon dot social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That is because Android makes it smaller when you start the Activity in landscape mode. We don't recreate Activities on rotation so it stays this way when switching to portrait (and vice versa). The solution is to use a ViewModel that holds the state and recreate the MainActivity on rotation. Forcing it  to be the same size is probably also possible but I guess there is a reason it is smaller in landscape.

**Comment by nikclayton** [comment]
Note to self: This is:

```
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|screenSize|keyboardHidden|screenLayout|smallestScreenSize"
            android:exported="true">
```

and similar in AndroidManifest.xml.

## MainActivity

TabData.kt defines the kinds of tabs that are supported and the Fragments they host:

They are `TimelineFragment`, `NotificationsFragment`, and `ConversationsFragment`.

Of those, only `NotificationsFragment` doesn't have a view model. But I'm fixing that in https://github.com/tuskyapp/Tusky/pull/3159. When that's merged this will be fixed.

## ViewThreadActivity

`ViewThreadFragment` has a view model. The activity doesn't have any additional UI.

## ViewMediaActivity

Does not host a fragment, and does not have a view model.

## AccountActivity

Has a view model.

---

So I think only `ViewMediaActivity` has to be converted.

**Comment by mcclure** [comment]
Okay. This bug is pretty minor so it's probably not worth major work, but if we're already doing the rewrite then that's not a problem…

**Comment by connyduck** [comment]
This was fixed in https://github.com/tuskyapp/Tusky/pull/4637
