### ISSUE TITLE
Don't display interaction buttons on timelines by default

### ISSUE THREAD

**Issue by pwd-github** [tuskyapp/Tusky#3218]
Consider only displaying the buttons under each toot only when a user actually wants to interact with said toot. 

* * * *
- Tusky Version: 20
- Android Version: 13
- Android Device: Pixel 6 Pro and Pixel 4XL
- Mastodon instance (if applicable):

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Having checked, I think this is a dupe of https://github.com/tuskyapp/Tusky/issues/1163

**Comment by Lakoja** [comment]
Yes.

While #1163 could probably closed as well (normally posts are larger than only a few lines, so this feature doesn't make much space saving).
