### ISSUE TITLE
Accurate stats on timeline + translate button.

### ISSUE THREAD

**Issue by KyKyDesign** [tuskyapp/Tusky#3225]
This is my proposal to add new features:

- To show the exact number of comments, likes, etc. next to the interaction buttons on the timeline.

- Adding a button to translate the post next to the interaction buttons on the post.

And my question is are there any plans to add this at all?

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/issues/2486
https://github.com/tuskyapp/Tusky/issues/2823 https://github.com/tuskyapp/Tusky/issues/2188 https://github.com/tuskyapp/Tusky/issues/134
