### ISSUE TITLE
Accessing global server settings from within the app

### ISSUE THREAD

**Issue by mapperfr** [tuskyapp/Tusky#3232]
Not sure if it's even possible but it would come really handy to be able to the global settings from Tusky, especially for admin and moderation related tasks like validating or rejecting new accounts requests.

* * * *
- Tusky Version: 20.0
- Android Version: 9
- Android Device: Samsung Galaxy S8
- Mastodon instance (if applicable): https://mapstodon.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Admin features are out of our scope for now, sorry.
