### ISSUE TITLE
Possibility to doesn't add 'Tusky' mark to toots

### ISSUE THREAD

**Issue by serrq** [tuskyapp/Tusky#3233]
I would like an option in order to remove the 'Tusky' mark from my toots.

![36837](https://user-images.githubusercontent.com/113377431/215257731-fc3c27b2-8ef4-4b83-a79c-2c7ddfa0654c.jpg)

**Comment by connyduck** [comment]
You can do so in the options of the Web interface.
Preferences -> Other -> Disclose application used to send posts
Note that you yourself will always see the Application, that is a security feature - in case an app starts spamming you know which one it is. For the same reason it cannot be disabled on Tuskys side.
