### ISSUE TITLE
Feature request: "Add to list" option within an account's options menu

### ISSUE THREAD

**Issue by rsHalford** [tuskyapp/Tusky#3260]
Add an option within the 3-dotted menu of an account. Prompting to select which list to add the account to.

Currently I have to go to the lists view with the account's name remembered, just so that I can add it. I think it would be useful to have this option available when browsing the timeline, without losing position history, as the action would take place nested nested within an account view.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This feature is available in Tusky 21.
