### ISSUE TITLE
v21 regression: Black screen when playing audio 

### ISSUE THREAD

**Issue by viviicat** [tuskyapp/Tusky#3261]
- Open an audio attachment such as the one on this post: https://solarpunk.moe/@vv/109562659215759090
- Note that the screen appears black except for the header, which disappears after a second.
- Tapping the screen does *not* cause the controls to reappear.
- Audio plays but no controls are visible
- Back button can be used to close the page.
- if you go to another app and return sometimes the controls become visible but are not correctly set up.

I had previously written some code to improve audio playback (keep the timeline visible for audio) but it seems to have stopped functioning properly.

![Screenshot_20230204-083439_Tusky](https://user-images.githubusercontent.com/287339/216778792-69900b44-3e08-457d-aef1-f3752b763769.png)
![Screenshot_20230204-083224_Tusky](https://user-images.githubusercontent.com/287339/216778762-1142d136-e021-4156-95d4-7998f8cd77ae.png)
![Screenshot_20230204-083309_Tusky](https://user-images.githubusercontent.com/287339/216778770-304364ae-ff27-4fd0-9537-0ec78f3649c4.png)

* * * *
- Tusky Version: 21.0
- Android Version: Android 12 (lineage OS)
- Android Device: Pixel 2
- Mastodon instance (if applicable): any

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by viviicat** [comment]
Updated - this is still present on the 21 release.

**Comment by Lakoja** [comment]
Can confirm this.

Audio (e. g. mp3) behaves in this way in Tusky (while video works fine).
