### ISSUE TITLE
Can't edit caption during "delete and re-draft" anymore

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#3273]
- Make a post, attach an image, do not add a caption
- "Delete and re-draft"
- **In the delete and re-draft pane you will not be given the option to edit caption, edit focus, or edit image**. The only menu item will be "Delete".

According to Maloki this worked before 21 (I'm 90% certain I remember it working before). Maloki thinks when we (correctly) set the edit pane to not allow caption edit, we (accidentally) removed it from delete+redraft as well.

Interestingly if at this point you save your re-draft to drafts, then re-open it, you will be able to edit captions again.

Practical impact is we should make sure to re-test this use case when #3215 merges

* * * *
- Tusky Version: 21.0 (plus a couple manually applied patches, not relevant)
- Android Version: 12
- Android Device: Xperia 5 III
- Mastodon instance (if applicable): mastodon dot social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Verified that #3215 fixes this
I can make a separate PR with the `MediaPreviewAdapter` change if we want to make a bugfix release before shipping v22

**Comment by mcclure** [comment]
Fixed by #3215
