### ISSUE TITLE
a11y: Increase touch targets for clickable items in statuses

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3282]
Touch targets for clickable items (usernames, hashtags, links) are currently determined by `ClickableSpan`.

They're very small -- to quickly see this, edit `NoUnderlineUrlSpan.kt` and change `updateDrawState` to:

```kotlin
    override fun updateDrawState(ds: TextPaint) {
        super.updateDrawState(ds)
        ds.bgColor = Color.RED
        ds.isUnderlineText = false
    }
```

You'll see that the touch targets are just the bare width/height of the text, and very far from the 48dp that Android guidelines recommend as the minimum size for a touch target.

`ClickableSpan` doesn't provide a mechanism to change the size of the touch target.

I suspect that the way to fix this is to move the touch handling to the `TextView`. That can figure out larger touch targets for each span, figure out if the touch is in one of the targets, and dispatch it accordingly.

If touch targets overlap, the span with the closest edge to the touch wins.

This probably also solves some of https://github.com/tuskyapp/Tusky/issues/1567

* * * *
- Tusky Version: 21

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Here's an example showing the actual touch target sizes highlighted in red.

<img src="https://user-images.githubusercontent.com/773100/217281190-f06e2037-dcf1-4ad9-97b9-49bed68383b0.png" width="45%">

**Comment by ichier** [comment]
yes! while highlighted area is looking good, they're actually way too small for touch-devices. 9 out of 10 times i click on a link i end up in the post.

**Comment by nikclayton** [comment]
I'm starting to work on this. I expect the fix will also address https://github.com/tuskyapp/Tusky/issues/1567

**Comment by nikclayton** [comment]
Screenshot showing the the new bounds:

<img src="https://user-images.githubusercontent.com/773100/220939841-b88e24f2-ec8f-4e81-8ffd-ba6c50324ac3.png" width="80%">

The behaviour on clicking one of those areas (highlighted in cyan) is:

- If the click is directly over a clickable span then forward to that span (current behaviour)
- If the click is over the expanded touchable area, and only one span extends in to that area (e.g., the left portion of the area above the "#AmWriting" hashtag in that screenshot) then forward to that span
- If the click is over an area covered by two or more spans (e.g., the overlap between "#AmWriting" and "#SFF" in that screenshot), forward the click to whichever span's center has the closest manhattan distance to the click.

I might reconsider that last one based on user feedback, as I'm not sure that's the most intuitive of the possible behaviours.

The extended touchable area in whitespace to the right of the "This Week in Rust" status in that screenshot is not a bug. Or at least, it's not a regression; clicking in that area without the changes I'm making will open the URL.
