### ISSUE TITLE
Content behind a content warning shows mentioned user names

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3283]
Not sure if this is a bug or WAI

Content behind a content warning, where the initial text of the hidden content is an @-mention of someone, shows the person's usename when the content is hidden.

To reproduce, write a post with a content warning (e.g., "A content warning"), and @-mention (e.g., @nikclayton) someone as the first part of the content that's behind the content warning.

Expectation: The status in the timline should look like this (with content warning collapsed):

```
A content warning
[   Show more   ]
```

What happens:

```
A content warning
[   Show more   ]
@nikclayton
```

* * * *
- Tusky Version: 21

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
This is mirroring the behavior of the web UI

![Screenshot_20230207-170144](https://user-images.githubusercontent.com/142250/217297423-ad17e41f-dc46-4ff3-888a-897f079e4ebc.png)

**Comment by nikclayton** [comment]
Huh, missed that when I searched. Cheers, I'll take this over there.
