### ISSUE TITLE
Image thumbnails for audio attachments

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#3291]
Consider this status

https://mastodon.social/@mcc/109836577896256495

It has an audio attachment, and the audio attachment has an image thumbnail, which I guess mastodon.social supports now (4.0 feature?). So viewed on mastodon.social this looks like

![image](https://user-images.githubusercontent.com/277318/217927417-2817b79a-7eff-490b-86df-fd29b0ace7b7.png)

Feature seems worth supporting.

* * * *
- Tusky Version: 21.0 (+ trivial patches)
- Android Version: 12
- Android Device: Xperia 5 III
- Mastodon instance (if applicable): mastodon dot social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
Slightly related: #3261 which says that controls do not work at all for audio.

**Comment by charlag** [comment]
fixed by #3857
