### ISSUE TITLE
Feature Request: Option to always "show more"

### ISSUE THREAD

**Issue by DevilsDescendant** [tuskyapp/Tusky#3292]
Would it be possible to offer an option to have Tusky load more posts automatically?
Currently there is a "show more" button between posts, which can not only be overlooked but also is just an extra effort. Keep the option to skip through posts and show the button, or give the user the opportunity to see every post of their timeline by en- or disabling said option in the preferences.

**Comment by Tak** [comment]
Hi, thanks for your feedback! We're collecting input on timeline improvements in #2788
