### ISSUE TITLE
Local feed has to be refreshed (again) after viewing a toot

### ISSUE THREAD

**Issue by 6b6279** [tuskyapp/Tusky#3317]
When I press on a toot in the "Local" tab to view it full-screen, and then return to the "Local" tab by pressing the Back button, all the loaded toots disappear and I get an empty feed with "There is nothing here." and the confused Tusky mascot.
* * * *
- Tusky Version: 21.0
- Android Version: Android 11
- Android Device: Samsung M30s
- Mastodon instance (if applicable): tilde.zone (running glitch-soc)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
Does that always happen?

It doesn't for me at the moment.

However I _sometimes_ see a problem like this _somewhere_ (any timeline) where content should be loaded/present but instead "There is nothing" is shown.

**Comment by 6b6279** [comment]
I can confirm that the problem is not limited to the local feed. For me, it happens every single time on the local feed and on profiles.

**Comment by Lakoja** [comment]
But it does work on your personal (home) timeline or the federated one?

**Comment by 6b6279** [comment]
Same issue in the federated timeline. Doesn’t occur in my personal timeline, though.

**Comment by 6b6279** [comment]
This somehow got fixed going forward, closing.
