### ISSUE TITLE
Ogg videos display broken

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#3329]
Got hold of a .ogg video file:

https://mastodon.social/@mcc_test_tusky/109882851902777246

mastodon.social web can't play the video at all in Chrome

Interestingly, Tusky 21 *can* play it, with an unusual problem: The video is displayed 1 pixel high. It animates and everything, it's just only 1 vertical pixel worth of content is shown.

[Exoplayer fork](https://github.com/mcclure/Tusky/tree/exoplayer) exhibits same problem, but displays exactly 1 frame of the full image.

* * * *
- Tusky Version: 21
- Android Version: 12
- Android Device: Xperia X 5 III
- Mastodon instance (if applicable): m.s

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
The post with that video doesn't seem to be available any more. Do you have another one?

**Comment by mcclure** [comment]
> The post with that video doesn't seem to be available any more. Do you have another one?

Looks like I accidentally posted it as "followers only". I have spotty internet access this weekend and it isn't letting me change the visibility level in an edit. If you follow mcc_test_tusky does it show you the post?

**Comment by nikclayton** [comment]
I've sent a follow request from the Tusky account

**Comment by mcclure** [comment]
follow accepted. sorry about that

**Comment by nikclayton** [comment]
That works to see the post. Doesn't work in your fork or mine (https://github.com/tuskyapp/Tusky/pull/3857). I'll try with the Exoplayer demo app and see if that fails as well.
