### ISSUE TITLE
Revamping timelines, tabs, and the navigation drawer

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3331]
I've been looking at the different open issues around navigation and tabs. This is a single, consistent proposal to fix all of them. Feedback requested.

## Problem

The current split between what's in the navigation drawer and what's in tabs is causing problems for users.

- It's unclear what goes where
- The limit of five tabs is confusing (https://github.com/tuskyapp/Tusky/issues/2512)
- There are artificial restrictions on what can be a tab and what can be in the navigation drawer. E.g.,
  - There's no "Bookmarks" tab
  - If you remove "Notifications" from the tab list it doesn't appear in the navigation drawer. Ditto for e.g., "Direct Messages"
- Users are complaining about this and proposing fixes (e.g., https://github.com/tuskyapp/Tusky/issues/3010, https://github.com/tuskyapp/Tusky/issues/2939)

### Elevator pitch

The navigation drawer becomes the canonical location for all the timelines that the user can access.

Tabs become completely user-controlled shortcuts to those timelines. A user may choose to have zero tabs. Or many tabs. Entirely up to them.

### Details

Model it as follows:

1. The user has access to many "timelines"
2. A timeline is one of:
    - Home
    - Notifications
    - Local timeline of the user's instance
    - Local timeline of another instance (https://github.com/tuskyapp/Tusky/issues/874)
    - "Customised" timelines (e.g., posts with media only, see https://github.com/tuskyapp/Tusky/issues/1332)
    - Federated timeline
    - DMs
    - Follow requests (subset of notifications)
    - Mentions (subset of notifications, https://github.com/tuskyapp/Tusky/issues/2735, https://github.com/tuskyapp/Tusky/issues/2378)
    - Scheduled posts
    - Drafts
    - Bookmarks
    - Favourites
    - Trending (the various trending types are different timelines)
    - Announcements
    - 0-N user defined lists of accounts (currently called "Lists")
    - 0-N user defined lists of hashtags (currently the "Hashtags" tabs)
3. Every timeline that the user has appears on the navigation drawer, and is directly selectable
4. Tabs are for "quick access"
    - The user may have 0-N tabs
    - If they have 0 tabs the tab bar does not appear, and all navigation is done through the drawer
    - Otherwise, the user may add as many of their timelines to the tabs as they want
    - The user can specify the "default" tab (the tab they return to after pressing "Back", which may not be the home timeline, https://github.com/tuskyapp/Tusky/issues/1838)
    - Tabs will need labels (possibly this is a user setting), otherwise the user can create multiple tabs with the same icon

This:

- Gives control to the user
- Removes any developer decisions about where a timeline should appear
- Ensures that removing a timeline from the default set of tabs does not make it invisible to the user, because it's still in the navigation drawer (i.e., if we did this, we can remove the "Where is the Federated timeline?" FAQ entry)

## What does this look like to the user?

The number of entries in the navigation drawer will grow as they add more timelines. I think that's fine, as other apps do that with no problems (GMail doesn't limit the number of labels you can create, GCal doesn't limit the number of calendars you can create, Feedly doesn't restrict the number of feeds you can subscribe to, etc).

They have a new "Account preferences > Timelines" entry which will:

- Allow the user to add new timelines
  - Create a new timeline from a list of accounts
  - Create a new timeline from a list of hashtags
  - Subscribe to the local timeline of another instance

- Allow the user to control the configuration of a timeline by tapping on its entry in the list.
  - E.g., the current preference "Preferences > Tabs" (the one that controls the visibility of boosts/replies) could be per-timeline
  - Selectively override the global "Wellbeing" settings for that timeline
  - Modify list settings (the accounts, hashtags, media-only settings, etc)

- The user may have multiple timelines of the same type / source, but with different options.   - The "Mentions" timeline is the "Notifications" timeline filtered to just mentions. They could have a "Home" timeline, and a "Home" timeline with the "filter replies" option enabled. It's up to the user. If they create two identical timelines (same source, config, and title) Tusky can warn them about this, but not forbid it.

- Mark one timeline tab as the "default" timeline. If not set it's the "Home" timeline tab. If that's not set it's the first tab.

- Optional: Allow the user to drag/drop the order of the timelines to control the order of them in the navigation drawer

- Optional: Control whether the timeline appears in the navigation drawer (e.g., if the user really wanted to turn off the Federated timeline and never see it in the UI they could do so here by tapping a switch)

For "Account preferences > Tabs":

- Show all the user's timelines, drag/sortable, with a switch that controls whether or not it is visible on a tab

This makes adding or removing a timeline from a tab a one-tap operation on this screen.

## What happens when the user clicks on a drawer item?

> This needs some consideration because Tusky currently tries to sidestep this; if an item is assigned to a tab then it is not present in the navigation drawer, and vice-versa. As noted in the introduction, Tusky's behaviour is inconsistent about this.

The item the user clicked on is either (a) also assigned to a tab, or (b) not assigned to a tab.

If it is assigned to a tab then the tabs are displayed, and the tab that contains the clicked item is selected. If the user then clicks "Back" they are taken back to the "default" tab.

If it is *not* assigned to a tab then item is shown without tabs. If the user then clicks "Back" the user is returned to their most recently selected tab.

This is consistent with how other Android apps I've surveyed that use navigation drawers and tabs behave (e.g., the BBC News app).

## Suggested default order of items in the navigation drawer

> `* Title: ...` is a section title, `---` is a section divider

```
* Title: Personal
Home
Bookmarks
Favourites
Direct messages
Drafts
Scheduled
---
* Title: Notifications
All
Mentions
Follow requests
---
* Title: Fediverse
Local timeline
Federated timeline
Trending hashtags
Announcements
---
* Private lists
Custom timeline #1
Custom timeline #2
Custom timeline #3
...
---
Account preferences
Preferences
About
Logout
```

- Each "Custom timeline" is a list (of accounts or hashtags)
- "Edit profile" is removed, it's available on the user's profile page

## Out of scope for this

https://github.com/tuskyapp/Tusky/issues/2965, which proposes the option to merge timelines from multiple accounts in to a single timeline.

It's a solid idea, and this proposal doesn't negate it, but it's orthogonal to the set of improvements here.

## What about the UX guideline 5 tabs limit?

There is no UX guideline of a maximum of 5 tabs.

There *is* one for navigation bars (https://m3.material.io/components/navigation-bar/guidelines#fe9927f5-5aa4-4954-b1d8-3506325a89d8, "Don’t use more than five destinations."), but tabs are not the navigation bar, and this proposal does not treat them like a navigation bar.

**Comment by charlag** [comment]
Quick feedback:
 * I feel good about a lot of these ideas and the general direction
 * After looking at material: we absolutely should lift the restriction on tab number
   * but then when tabs are in the bottom I would leave them that: tabs
 * I really like the idea that tabs are accessible at least in the side menu but I am also unsure if we need it if we will have unlimited tabs. Need to think about this a bit
 * I have a fear that all of this can be overwhelming and confusing. see Subway Tooter
   * We could use labels instead of icons as in material spec but idk if it works in all translations/languages
   * Maybe same icon is not a problem anyway unless you have *lots* of tabs
 * I disagree on what "timeline" is a bit. Announcements, drafts, scheduled posts are not timelines because they either show not posts or do show posts differently. I think having them in side menu is more than enough.

**Comment by nikclayton** [comment]
Thanks for the initial feedback.

> We could use labels instead of icons as in material spec but idk if it works in all translations/languages

For the "standard" timelines (home, notifications, etc) we already have translations.

For user defined timelines (i.e., lists) users already need to give them a name. So they'll use whatever feels familiar to them.

> Maybe same icon is not a problem anyway unless you have lots of tabs

It's a problem as soon as you have two lists under the current system because they have identical icons.

Or consider someone following the local feed from two different instances (we can't do that at the moment, but it's a user request, other apps support it, and it's functionality unlocked by this proposal). How would the user distinguish them, without allowing them to label them in some way?

And we do this already elsewhere in the app -- the different tabs shown when viewing a profile are labelled.

> I disagree on what "timeline" is a bit. Announcements, drafts, scheduled posts are not timelines because they either show not posts or do show posts differently. I think having them in side menu is more than enough.

I disagree with your disagreement :-)

For example, consider someone who's a social media manager and wants quick access to all of the account's scheduled posts. Or someone who writes a lot of drafts (or keeps forgetting that they've written them).

So I would err on the side of **not** putting arbitrary restrictions on which timelines can go where.
