### ISSUE TITLE
Domain in mentions shouldn't be included in character limit

### ISSUE THREAD

**Issue by cam-rod** [tuskyapp/Tusky#3339]
Mastodon set all links as 23 characters regardless of their length ([source](https://docs.joinmastodon.org/user/posting/#links)). It would be nice to have the post composer recognize links (`http` and `https`), and correctly adjust the character limit.

**Comment by connyduck** [comment]
Tusky does exactly that.

**Comment by cam-rod** [comment]
Hey, on closer look I think the issue was actually with domains in mentions. Attached some details below (sorry, should've included this in the initial report):

When I attempt to edit [this message](https://techhub.social/@camrod/109894193978357166) from the Mastodon website, it records as being 22 characters under the instance's 1000-character limit (978). Pasting the raw text into an external site like [wordcounter.net](https://wordcounter.net/character-count) matched after considering:

- links are automatically set to 23 characters ([source](https://docs.joinmastodon.org/user/posting/#links))
- user mentions don't include the domain ([source](https://docs.joinmastodon.org/user/posting/#mentions), seems to even apply for fake domains like \@twitter.com)
- wordcounter.net seemingly doesn't register newlines as a character, so adding 2 characters for each double line break in the post

Editing the same post in Tusky recorded as 2 characters above the limit (1002), a difference of 24 characters. It looks like it was counting the (fake) domains of the Twitter usernames like `@Racer_77@twitter.com`, while the Mastodon website doesn't. This also seems to apply for real users; `@camrod@pleroma.envs.net` counted for 7 characters on the website and 24 characters in Tusky.

Relevant details:

- _Device_
  - Model: Google Pixel 6
  - OS version: Android 13, February 2023 security patch
  - _Tusky app version:_ 21.0
- _Instance_
  - Host: https://techhub.social
  - Mastodon server version: v4.0.2
  - Character limit: 1000

**Comment by nikclayton** [comment]
Looking...
