### ISSUE TITLE
Editing a reply in thread view duplicates that reply

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#3366]
Reported by a user via email, reproduces both in current nightly and Tusky 21.0.

Steps to reproduce:
- Open a post you replied to in thread view.
- Edit the reply
- The reply is now shown twice, once with the old unedited content, and once with the new content

![Screenshot_20230221-200553](https://user-images.githubusercontent.com/10157047/220436541-10eef3d2-0d00-4300-96fb-5474617dafff.png)

**Comment by Tak** [comment]
🤔 What's the correct fix here? Should we force a refresh when returning from the compose view? Or is there something smarter we can do?

**Comment by nikclayton** [comment]
`ComposeActivity` is launched by `SFragment.editStatus()` (via `ViewThreadFragment.onMore()`) using `startActivity`.

Maybe use https://developer.android.com/training/basics/intents/result to get a result back from `ComposeActivity` indicating whether or not the status was edited.

If it was, use the `notify*` APIs to get the adapter to rebind.

This is probably quite handy outside of `ViewThreadFragment` too, as there are a few places where `ComposeActivity` is started (editing drafts, editing scheduled statuses) where it would be handy to know whether the status was edited or not.
