### ISSUE TITLE
Add search/filter to follows/followers views

### ISSUE THREAD

**Issue by jsoref** [tuskyapp/Tusky#3379]
It's true I might want to browse through a full follows/followers list, but right now I'm pretty sure I follow a certain account and just want to search for it in my follows list. 

Here's what follows/followers looks like (not necessarily from my account):

![Screenshot_20230223-172221](https://user-images.githubusercontent.com/2119212/221044242-86e8738e-de36-42d8-83c6-4fb2907a4cdd.png)
![Screenshot_20230223-172312](https://user-images.githubusercontent.com/2119212/221044252-91e5983b-7a36-4c62-8c46-d75db387b638.png)

An extra row at the top (or just a button in the top row) to enable filter/search would be great. 

* * * *
- Tusky Version: Tusky 21.0
- Android Version: 12
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Not possible unless Mastodon adds an Api for this

**Comment by jsoref** [comment]
😦 
If you're rendering a page, surely you could perform a client side filter...
