### ISSUE TITLE
Activities should not handle config changes

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3398]
Note to self: This is:

```
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|screenSize|keyboardHidden|screenLayout|smallestScreenSize"
            android:exported="true">
```

and similar in AndroidManifest.xml.

## MainActivity

TabData.kt defines the kinds of tabs that are supported and the Fragments they host:

They are `TimelineFragment`, `NotificationsFragment`, and `ConversationsFragment`.

Of those, only `NotificationsFragment` doesn't have a view model. But I'm fixing that in https://github.com/tuskyapp/Tusky/pull/3159. When that's merged this will be fixed.

## ViewThreadActivity

`ViewThreadFragment` has a view model. The activity doesn't have any additional UI.

## ViewMediaActivity

Does not host a fragment, and does not have a view model. Will need one.

## AccountActivity

Has a view model.

---

So I think only `ViewMediaActivity` has to be converted.

Edit to add: None of them override `onConfigurationChanged()`, so editing the manifest should be all the change that's needed.

Although... need to check whether the UI state is actually properly saved in those viewmodels. A quick experiment just now showed that `MainActivity` will fetch `verify_credentials` and `announcements` on each restart, so they're probably not cached.

_Originally posted by @nikclayton in https://github.com/tuskyapp/Tusky/issues/3217#issuecomment-1404957530_

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/4689
