### ISSUE TITLE
Emoji not shown in previews of links to profiles in statuses

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3420]
Here's a screenshot showing the problem (the relevant status is https://hachyderm.io/@tedivm/109978463964039402)

<img src="https://user-images.githubusercontent.com/773100/223398523-61417cbc-d213-4e9a-ae0c-effee627fec5.png" width="60%">

As you can see, the emoji shows in the author info line at the top of the status, but appears as just `:verified_bi:` in the preview card shown for his profile.

* * * *
- Tusky Version: 21

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Its the title of the website. We cannot know that it is a Mastodon profile containing custom emojis. Browsers also don't render it.
