### ISSUE TITLE
Opening notifications crashes the app

### ISSUE THREAD

**Issue by GeorgeWL** [tuskyapp/Tusky#3454]
Screen recording attached

It seems to happen on all my profiles 

 https://user-images.githubusercontent.com/5931248/225012970-b6b33a58-82ac-43ff-a559-4094a8c55c22.mp4

Edit: app version 21.0-test-3bb92d51

**Comment by nikclayton** [comment]
That's suboptimal.

- What do your notifications look like on the web? Do you have active notifications?
- Does it work in regular Tusky (i.e., not Tusky Test)?

**Comment by GeorgeWL** [comment]
1. On the web it's showing as 21 notifications
2. I'll try on none test and edit in the result

**Comment by GeorgeWL** [comment]
I've not seen it since, so I think it's fixed 👍

**Comment by nikclayton** [comment]
Thanks for letting us know.
