### ISSUE TITLE
Missing toots

### ISSUE THREAD

**Issue by Sisterratched** [tuskyapp/Tusky#3470]
There are several toots per day missing from my Tusky timeline. They are all on the official Masto app. Seems completely random and includes mine and those of a random selection of people I follow. Why???

* * * *
- Tusky Version:
- Android Version:
- Android Device: samsung phone
- Mastodon instance (if applicable): toot.community

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Duplicate of #3320
