### ISSUE TITLE
Links show too little contrast in dark mode

### ISSUE THREAD

**Issue by guerda** [tuskyapp/Tusky#3477]
I am using Tusky daily and I really like this app. What I see as an issue is the dark theme (night theme) in combination with links (hashtags, URLs) etc, as these have too little contrast to be readable in a night time setting.

I tried to figure it out and it seems that the link color is `tusky_blue` according to https://github.com/tuskyapp/Tusky/blob/8c519af611b27b4d99c7e5ee32c28f0111b7f413/app/src/main/res/values/colors.xml#L3, which translates to #2b90d9 
As far as I can see, the background in posts is #282c37 (`tusky_grey_20`). 

According to [WebAIM](https://webaim.org/resources/contrastchecker/), those two colors have a contrast of 4.04:1 and fails WCAG AAA in both normal and large text.

<img width="744" alt="Bildschirm­foto 2023-03-22 um 09 43 42" src="https://user-images.githubusercontent.com/230782/226848367-1a3b0ba0-8852-4622-a864-2bab73c3f0ba.png">

I propose to adapt the link color or the background color, to increase the contrast. For example, the link color #83BEF1 would pass all four checks with WebAIM.

* * * *
- Tusky Version: 21.0
- Android Version: 13
- Android Device: Pixel 7

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
(Slightly related: #3178)

**Comment by Lakoja** [comment]
(Just for reference: the two blue tints with 4.6 contrast each would be 217aba (for light) and 3c9add (for dark).)

**Comment by guerda** [comment]
Any update on this? I assume it's a question of consideration, not feasibility.

**Comment by visualstuart** [comment]
Chiming in, this is an accessibility issue for me. As I understand it, people with cataracts lose some of their ability to perceive blue.

**Comment by joergi** [comment]
It's really hard to reading in the app at night in the bedroom.
It would be super helpful, if we can choose the color ourself
