### ISSUE TITLE
Profile page: Work with lists

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#3488]
Followup of #3416 

When working with lists of a profile page (Add/remove from lists in the context menu) the respective dialog lets some to be desired:

- There should be a loading progress
- There should be a button for managing (adding) lists

**Comment by nikclayton** [comment]
First, lets look at the current UX flow and identify problems with it.

## Current flow

### If you have no lists

#### Creating a list and adding people to it

1. Open Nav > Lists (i.e., from the left-hand navigation menu)
	- "Nothing here" message
	- FAB
2. Click FAB
	- Dialog to name and create list
	- Do that, presented with the list page, showing the new list
3. Adding people to the list is non-intuitive
	- Opening the list doesn't show you the people that are on the list
		- This part of the UI is trying to mix "managing" lists with "viewing" content of people that are on lists, which leads to this confusion
	- Choosing "Edit" from the list's "..." menu allows you to search for people you are following
		- "Edit" as a verb did not put me in mind of "This will let me add people to the list"
	- There's no metadata shown in the list of lists.
		- In particular, there's no count of the number of accounts that are on that list.
		
**Problems and suggestions for fixes**

1. Opening Nav > Lists when no lists exist should automatically prompt the user to create one
2. Creating a new list should immediately prompt the user to add people to it.
	- The "Create list" dialog currently only prompts for list name.
	- It should show a list of people being followed, with Add/Remove UI controls, and a "search" feature (the current "add account to list" functionality only has search)
		- So a screen with three "fields"
			- One (text) for the new list name
			- One (text) for the search query
			- One (list) for the list of accounts this account is following
				- Each entry in the list should have an "Add" button (which switches to "Remove" if they're marked as being added)
				- Or this is two lists, one which is a list of accounts that can be added, and a second list which shows the accounts that will be added, and the user can move accounts between the two lists.
		- This UX suggests that this should be full screen, not a dialog.
	- Creating an empty list should still be possible.
3. Nav > Lists doesn't show any list metadata except the name. Useful information to include would be:
	- The "replies" policy for that list
	- The number of accounts on that list
		- Possibly flagging lists that have 0 accounts
		- Note that getting the number of accounts in the list is difficult with the Mastodon API at the moment ([lists API methods - Mastodon documentation](https://docs.joinmastodon.org/methods/lists/#accounts)). However, it is possible to distinguish between "This list contains 1 or more accounts" and "This list contains 0 accounts"

#### Adding to a list from an account profile

1. Click on a profile of an account you are following, open profile menu, choose "Add to list"
2. Big dialog, "You don't have any lists", DONE button

**Problems and suggestions for fixes**

- If the user has no lists the menu option should be "Create list with this account", not "Add or remove from list"

- If the user is not following this account they can't be added to the list
	- So change the menu option to "Follow and add to list" (or "Follow and create list" if the user has no lists)

---

### If you have a list

#### Adding someone from Nav > Lists

That's discussed in the previous section.

#### Adding someone from their profile

1. Click on someone's profile that you are following, open profile menu
2. Click "Add or remove from list" menu option
3. Shows all lists 
	- Click "+" button to add them
	- Click "x" button to remove them

**Problems**

- If the user has no lists containing this account the menu option should be "Add to lists", not "Add or remove from list "

## Rethinking this

What's the functionality that's needed?

- List existing lists, user can't edit (for picking a list to use in a tab)
- List existing lists, user can edit (e.g., the Nav > Lists case)
	- Create new list
	- Rename existing list
	- Delete existing list
- Create a new list
- Create a new list and add account X
- Rename a list
- Delete a list
- See list membership, modify it
- Add account X to list (from the account profile screen)
- Remove account X from list (from the account profile screen)

What classes do we need?

- `ShowListsFragment` (and associated view model)
	- Shows the lists the user has defined
	- Includes the list's replies policy, and whether the list has any members
	- Used when
		- Listing lists so one of them can be added to a tab
		- Listing lists from Nav > Lists
		- Listing lists from Profile > Add/remove from list
	- Input parameters:
		- (bool) Is the list of lists editable? True if launched from Nav > Lists, false if launched from Account preferences > Tabs. If true there should be UI to:
			- Add a new list
			- Delete an existing list
			- Rename a list
			- Manage the membership of a list (launches `ManageListFragment`, see next section)
		- (enum) Sort type. How the list should be sorted
			- Default -- the order they are returned by the Mastodon API
			- ContainingAccountFirst -- enum contains an account ID, these lists should be shown first (using [accounts API methods - Mastodon documentation](https://docs.joinmastodon.org/methods/accounts/#lists))
				- This is so that, when coming to the lists via a profile page, the lists that that account is on are shown first, so it's easy for the user to remove them from that list.

- `ManageListFragment` (and associated view model)
	- Shows metadata and membership for a single list, allows the user to edit it
		- I.e., this is form with fields for "List name", "filter followers", and lists of followers to add/remove from the list.
	- Input parameters:
         
	```kotlin
	@Parcelable
	data class ManageListFragment.ActionManageList(
	    val list: MastoList? = null,
	    val toAdd: List<TimelineAccount>? = null,
	    val toRemove: List<TimelineAccount>? = null
	)
	```

	- if `list` is null then a new list is being created, otherwise an existing list is being modified
	- If `toAdd` is not null and not empty then the UI should pre-add those accounts to the "to be added to the list" part of the UI.
	- If `toRemove` is not null and not empty then the UI should pre-add those accounts to the "to be removed from the list" part of the UI
		- They are **not** automatically committed to the list, just shown in the UI. The user can still choose to add or remove more accounts, including adding or removing accounts that were initially part of `toAdd` or `toRemove`. The changes to the list only occur when the user explicitly commits them.

- `ListsRepository`
	- Manages access to lists
	- Functionality to:
		- Get the current lists
		- Create a list
		- Create a list populated with a list of accounts
		- Rename a list
		- Delete a list
		- Add an account to a list
		- Remove an account from a list
		- Get lists containing an account ([accounts API methods - Mastodon documentation](https://docs.joinmastodon.org/methods/accounts/#lists))

- `FollowingRepository`
	- Manages followings for an account
	- Functionality to:
		- Return a list of following accounts (i.e., accounts that this account is following)
			- [accounts API methods - Mastodon documentation](https://docs.joinmastodon.org/methods/accounts/#following)
			- Provides a paginated list
		- Search through the list of following accounts
			- [search API methods - Mastodon documentation](https://docs.joinmastodon.org/methods/search/)
			- Supports only searching through accounts this account is following

### Checking the above proposal solves the problems

> Opening Nav > Lists when no lists exist should automatically prompt the user to create one

1. Launch `ShowListsFragment` (via `ListsActivity`)
	1. It gets the list of current lists (through `ListsRepository`)
2. If the list-of-lists is empty, launch `ManageListFragment` with a null `listId`
	1. `ManageListFragment` shows the UX to create the list
	2. Creates the list (through `ListsRepository`)

> Creating a new list should immediately prompt the user to add people to it.

This is achieved by having `ManageListFragment` also show the UI to add/remove people.

> Nav > Lists doesn't show any list metadata except the name.

This is handled in `ShowListsFragment`.

> (on the account profile menu):  If the user has no lists the menu option should be "Create list with this account", not "Add or remove from list"
> ...
> (on the account profile menu): If the user has no lists containing this account the menu option should be "Add to lists", not "Add or remove from list "

The account profile fragment can use the `ListRepository` to determine if the user has any lists, or lists that contain this account, and choose the correct menu option.

With additional "Follow and..." language if the user is not already following the account.
