### ISSUE TITLE
Changing orientation during video playback causes stretched image

### ISSUE THREAD

**Issue by NeatNit** [tuskyapp/Tusky#3508]
When tapping a video to watch it, the orientation remains in portrait. Then, to switch to landscape for a bigger picture, I rotate the device. At this point, the video gets stretched horizontally to fill the entire screen, showing the wrong aspect ratio.

Tap video:
![VideoCapture_20230403-234638](https://user-images.githubusercontent.com/2400026/229624442-9405067a-afbd-426b-8803-7f59af847912.jpg)

Rotate to landscape:
![VideoCapture_20230403-234644](https://user-images.githubusercontent.com/2400026/229624414-aeb4f150-ac44-431c-9697-4e5f4652229e.jpg)

The same can happen in reverse - switching from landscape to portrait mid-playback will stretch the video vertically.

Browse in landscape, tap video:
![VideoCapture_20230403-234653](https://user-images.githubusercontent.com/2400026/229624412-0a5aa7c3-b100-4fc6-ac0c-90dd16766678.jpg)

Rotate to portrait:
![VideoCapture_20230403-234655](https://user-images.githubusercontent.com/2400026/229624403-5b549b31-e60b-4c60-b343-3ae0fc60704c.jpg)

* * * *
- Tusky Version: 21.0
- Android Version: 13
- Android Device: Samsung Galaxy S22+
- Mastodon instance (if applicable): Videos I tried watching came from birdsite mirror profile: https://bird.makeup/users/kann_news

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by NeatNit** [comment]
You can watch the demo that those screen-grabs were taken from [here (youtube)](https://youtu.be/NeKXxEioL3Q), but it can be disorienting (ha) with the way orientation changes were encoded into the recording. I wish I had another camera to record externally, it would have made it clearer.

**Comment by Reonu** [comment]
Same on Pixel 6 with Android 13

**Comment by charlag** [comment]
fixed by #3857
