### ISSUE TITLE
View own posts

### ISSUE THREAD

**Issue by darkdragon-001** [tuskyapp/Tusky#3518]
How can I view my own posts? I couldn't find anything in the menu... 

* * * *
- Tusky Version: 21.0
- Android Version: 9
- Android Device: Xiaomi Mi A1
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Clicking on your avatar in the side menu will bring you to your own profile.
