### ISSUE TITLE
Search: search text is lost when switching tabs (before search)

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#3527]
The search view has 3 tabs (Posts, Accounts, Hashtags) for which you can search.
The search field above is emptied when you switch between these.
Or more precisely: it always shows the last search in all fields (also empty before the first search).

Why do we have three types (the web ui doesn't have it?)?
It's unusual to burden the user with this choice - at least before the search.

If there have to be three types it is not helpful to have three different search fields (or the one being emptied?).

 At least I normally decide on the type after I entered my search text...
(Especially as these tabs are below the field.)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
The web UI *does* have it, that's where this UI came from.

Mastodon <4 had Posts/Account/Hashtags (glitch still has this)
Mastodon 4+ has Posts/Hashtags/News(?)/For You

**Comment by Lakoja** [comment]
> The web UI _does_ have it, that's where this UI came from.

Not for me.

![grafik](https://user-images.githubusercontent.com/1618905/231878845-8addcab8-1caf-4a99-8732-648e299baf53.png)

Simple searching here gives me 3 sections with different results from the 3 areas.

**Comment by Tak** [comment]
Mine:
stock mastodon (mastodon.gamedev.place)
<img width="671" alt="Screenshot 2023-04-14 at 09 13 22" src="https://user-images.githubusercontent.com/142250/231970989-5efdb690-6348-4809-bd9c-9df97bbf3c74.png">

glitch social (glitch.taks.garden)
<img width="671" alt="Screenshot 2023-04-14 at 09 13 50" src="https://user-images.githubusercontent.com/142250/231971054-023a14f0-f1ed-4ab2-8330-f13e3b7bac21.png">

**Comment by Lakoja** [comment]
Correction: The search already behaves half as expected:

Once one search is performed all three tabs are filled with their respective results.
The searched term will then stay in the input field also when switching between tabs.
(Overriding all changes to the search field you may make after the search.)
