### ISSUE TITLE
Feature: Hide self-boosts

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3534]
Some Mastodon posters, otherwise reasonable people, have a profoundly annoying habit of boosting their own posts some time after they've posted them.

I've seen it once, I don't need to see the thing again.

For example, https://federate.social/@mattblaze/110198915334716075

Add an additional option to the "Filters > Tabs" preference to show these self-boosts (default: on)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
This is meaningful and partly encouraged ("because there is no algorithm to do that for you").
I do it myself from time to time.

If any this would be the Mastodon bug that this "group boosts period" is not configurable (it's fixed 40 posts, I believe).

**Comment by nikclayton** [comment]
Yes, but we provide mechanisms to clean up the timeline in Tusky that are also not part of stock Mastodon (e.g., removing all replies, or all boosts). This would be no different.
