### ISSUE TITLE
Change name of Preferences > Filters > Tabs

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3536]
Open Preferences and there's a section with the heading "Filters", and the single entry "Tabs".

This is confusing, and I've just figured out why.

1. These aren't filters in the normal Mastodon sense of the word. 
2. These aren't really "tab" options, they're timeline options.

Proposed concrete change:

1. Change the section title from "Filters" to "Per-timeline preferences"
2. Since the current "Tabs" entry is only for the Home timeline, change that to "Home timeline".

In the future, if other per-timeline options are needed (for example a "Show unread direct message count") then entries for those timelines can be added as additional sub-preference screens under here.

* * * *
- Tusky Version: 21

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
These options should also move to Account Preferences, a lot of users want to have different settings for different accounts.

**Comment by Tak** [comment]
That would be great!

**Comment by connyduck** [comment]
@sanao1006 I think it would involve adding two more columns to the `AccountEntity` table to save the settings, then adding the interface to the `AccountPreferencesFragment` (probably at the bottom in timelines?), removing the old interface, and finally switching all places where the settings are used from shared preferences to `AccountEntity`.

And of course database migrations ( in `app/src/main/java/com/keylesspalace/tusky/db/AppDatabase.java`) as well as a shared preference migration (in `app/src/main/java/com/keylesspalace/tusky/TuskyApplication.kt`) would be needed.

**Comment by sanao1006** [comment]
Okay. Thanks for the info.

 I may ask questions if I don't understand something.  I'll do my best.
