### ISSUE TITLE
nonlooping gifs loop infinitely

### ISSUE THREAD

**Issue by bodonkerhoderos** [tuskyapp/Tusky#3538]
i have a custom emoji gif that is set to play once and not loop again. when displayed on tusky, it loops infinitely regardless. in the web client using firefox it plays once as expected.

a public toot as an example (this is a gotosocial instance but i have observed the same behaviour when uploaded to mastodon v4.1.2+glitch):

https://demon.princess.pet/@lyds/statuses/01GY3KS9JJSKV9PWCK0S15ZG6D

* * * *
- Tusky Version: 21.0
- Android Version: 11
- Android Device: moto g power
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
(Technical research)

It looks as if that loop count is not read/supported
(in class com.github.penfeizhou.animation.gif.GifDrawable)?

One could set the loop count in EmojiSpan#getTarget 
`if (resource is GifDrawable) resource.setLoopLimit(1)`

But I don't see how I easily can find out the actual loop limit.
