### ISSUE TITLE
Feature request: Edit picture description

### ISSUE THREAD

**Issue by FlippoFlip** [tuskyapp/Tusky#3555]
After tooting a picture, I remembered I should add a picture desctiption for better acessibility. In my Tusky app on my android phone, I wasn't able to do it. The 'add alt-text' feature seems to only be available in the create toot interface.

Use Case: Editing alt-text in toots

Desired result: Easier editing of alt text

Notes:

- Maybe add a feature where others can suggest a description for my media? e.g. i get a notification like: "someone has suggest a media description for your picture: [Toot] Would you like to accept/edit/deny it?
- Another idea would be that if you post media without description for the first time, you are notified about alt-texts and why they are good. Maybe even ask if you would like to get future warnings about this as in https://github.com/tuskyapp/Tusky/issues/1049

* * * *
- Tusky Version: 21.0
- Android Version: 12
- Android Device:
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. Didn't find excactly this.

**Comment by Lakoja** [comment]
What happens when you tap the image when editing the status?

For me this behaves like with the initial creation: A popup opens (with "Add description" in it).
