### ISSUE TITLE
Option to filter posting language.

### ISSUE THREAD

**Issue by meyverick** [tuskyapp/Tusky#3564]
I would like an option to only show selected posting language.

I imagine the option as a list of all available languages where, when posting a message, it shows every language if none is selected in the option or only shows selected language in the option.

* * * *
- Tusky Version: 21.0
- Android Version: 12
- Android Device: RMX3363

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
This is a server-side setting

**Comment by meyverick** [comment]
Available languages are server-side but it's possible to hide the one you don't need.
