### ISSUE TITLE
22 beta: Loading notifications slow in Friendica?

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#3578]
Compared to the latest stable version, 22 beta and nightly are considerably slower when fetching timelines on Friendica, especially notifications. Known problem? Any way to debug this?

**Comment by connyduck** [comment]
There have been changes to the notification view, so this is definitely possible 🤔 
Since you specified Friendica, does that mean other servers are fine?

**Comment by nikclayton** [comment]
It's probably because the number of notifications loaded to populate the initial list has increased. I'll tune this down before the next beta release.

**Comment by kr428** [comment]
Seems quite a bit faster on a Mastodon instance. Not sure how that makes a difference though.

**Comment by nikclayton** [comment]
> Seems quite a bit faster on a Mastodon instance. Not sure how that makes a difference though.

Tusky makes the same API calls in both cases, so one or both of:

1. The Mastodon instance is running on faster hardware or has a faster network connection, so can respond faster.
2. The Mastodon code for computing the API response and returning it is faster than the Friendica equivalent

I'm not very familiar with either of those codebases, so I don't know which one of those is correct.

**Comment by kr428** [comment]
Hmmm that's odd then, because on earlier versions (tusky 21), difference between the two systems (same instances for both Mastodon and Friendica) weren't that noticeable. Friendica's always a tad slower for my account it seems, but so far it never bothered. But another thing I noticed: For some things (like, having new followers), I see the 22 beta displaying more details on for the user account / profile. Could this cause issues too? Does that make additional requests?

**Comment by nikclayton** [comment]
> Hmmm that's odd then, because on earlier versions (tusky 21), difference between the two systems (same instances for both Mastodon and Friendica) weren't that noticeable. Friendica's always a tad slower for my account it seems, but so far it never bothered. But another thing I noticed: For some things (like, having new followers), I see the 22 beta displaying more details on for the user account / profile. Could this cause issues too? Does that make additional requests?

That feature doesn't make any new requests. Tusky always received the information in the past, the difference is that now it displays it as well.

I've just compared the previous notifications code and the new code again.

In both cases the old and the new code requested 30 or more notifications. 30 is the limit imposed by the Mastodon API (see the description of the `limit` parameter at https://docs.joinmastodon.org/methods/notifications/#query-parameters), so the server shouldn't be having to do any more work per-request.

The new code does also fetch a page of notifications immediately before your reading position and immediately after your reading position -- so it's making three notifications requests where the previous code made one.

But only the request that loads the initial page of notifications at your reading position needs to complete in order for the UI to update.

Are you able to directly compare the old and new versions?

For example, install the current Tusky release (21) and the Tusky nightly release, and take a screen recording (https://support.google.com/android/answer/9075928?hl=en) showing the two versions refreshing notifications, so I can get a real understanding of the timing difference?

**Comment by nikclayton** [comment]
Thanks.

Hmm. I wonder if Mastodon is doing something stupid, like fetching more than 30 notifications if requested, but truncating the list back to 30 before returning it to the client.

I've just tried a similar experiment, and see differences in how long mastodon.social takes to return notifications, even though it's always returning no more than 30. I'll do some more investigating.

**Comment by nikclayton** [comment]
No, it's simpler than that.

Mastodon (at least, mastodon.social) is ignoring the documented limit, and returning how ever many notifications you ask for. So if Tusky requests more expecting Mastodon to clamp to the limit it doesn't.

https://github.com/tuskyapp/Tusky/pull/3579 will fix this.

I've reported this at https://github.com/mastodon/mastodon/issues/24684

**Comment by kr428** [comment]
Just to be sure: It's not Mastodon, it's Friendica I am talking to here...

**Comment by nikclayton** [comment]
Yeah, but I think Friendica has the same problem. I've taken a quick look at the code. If I'm reading it correctly then https://github.com/friendica/friendica/blob/develop/src/Module/Api/Mastodon/Notifications.php#L62 sets a default limit of 20 if one isn't specified, but I didn't see anything that imposes a hard maximum.

So Friendica has two bugs:

1. It claims to be compatible with the Mastodon API in this respect, but it does not set the same default value if the parameter is missing.
2. It doesn't respect the Mastodon API's documented limit.

**Comment by kr428** [comment]
@heluecht Are these bugs from your perspective? Should we file Friendica issues for this?

**Comment by annando** [comment]
I just had a quick glance at this thread. if you think that there is a bug in that endpoint, please file an issue so that we can fix it.

**Comment by nikclayton** [comment]
> I just had a quick glance at this thread. if you think that there is a bug in that endpoint, please file an issue so that we can fix it.

https://github.com/friendica/friendica/issues/13052

**Comment by kr428** [comment]
Is this in current nighties already? Seems faster now with my Friendica instance but my admins also upgraded server hardware this weekend so unsure which is more "relevant" here. Problem is gone, nevertheless.... 🙈

**Comment by nikclayton** [comment]
> Is this in current nighties already? Seems faster now with my Friendica instance but my admins also upgraded server hardware this weekend so unsure which is more "relevant" here. Problem is gone, nevertheless.... 🙈

Yep, nightly should contain any fixes from the previous day. Thanks for the feedback.
