### ISSUE TITLE
22 beta: Notification error in pixelfed

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#3580]
When connecting current 22 beta release (or nightly) to pixelfed.social, notifications timeline will display notifications for a moment and then switch to an error screen. Reloading will again make notifications disappear for a moment and then trigger the same behaviour. Related to #3578 ?

**Comment by kr428** [comment]
Any way to provide debug info on what's happening there...? Logs?

**Comment by nikclayton** [comment]
The builds on Play / F-Droid don't include logs unfortunately.

Are you able to build and test from the source code locally? That would provide logs.

**Comment by nikclayton** [comment]
OK. It's handy you can build from source, since you can reproduce the problem.

## Initial setting

The value of `max_id` is initially set in `NotificationsViewModel`, around line 460. Check the logs for a line like

```
Restoring at ...
```

The value at the end of that line should be the ID of the notification you were at the last time you used the app. The default value is 0, which gets converted to a null.

So if you see a null or a long string of digits on that log line things are OK. What would not be OK is if this is the empty string.

## Passing to NotificationsRepository

Still in `NotificationsViewModel`, `lastNotificationId` is passed to `getNotifications()` as the `initialKey` parameter.

From there it is passed to `repository.getNotificationsStream()`, which sets it as the `initialKey` for the `Pager`.

## Use in `NotificationsPagingSource`.

The `Pager` makes calls to `NotificationsPagingSource.load()` when it needs data. The first time it does this it passes in the `initialKey` value in the `LoadParams` type (`key` property).

Which is then used in `getInitialPage()`.

## Best guess

My best guess is that the `val lastNotificationId = when ...` code in `NotificationsViewModel` is getting a key that is unexpectedly empty (i.e., the empty string, **not** null).

Can you check that? If it is then the fix is straightforward, although I also need to figure out how that can happen.

**Comment by kr428** [comment]
Hmmm. I'm unsure. Added a breakpoint to see whether / how the lastNotificationId is set - and this seemed to happen just once, and in this case it seemed to have a meaningful value. Switching to the notification tab after that - displays notifications. See the "Prepend for key: 141...". This seems to work, and this is apparently what's being used in the request url for min_id:

```
D/NotificationsPagingSource: load() with Prepend for key: 14186984
I/okhttp.OkHttpClient: --> GET https://pixelfed.social/api/v1/notifications?min_id=14186984&limit=30&exclude_types%5B%5D=follow_request
I/okhttp.OkHttpClient: <-- 200 https://pixelfed.social/api/v1/notifications?min_id=14186984&limit=30&exclude_types%5B%5D=follow_request (421ms, unknown-length body)
I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
V/LinkTextView: Overlap: https://pixelfed.social/discover/tags/powergrid?src=hash https://pixelfed.social/discover/tags/fediphoto365?src=hash
V/LinkTextView: first: RectF(481.73047, 80.5, 705.3203, 212.5) second: RectF(267.0547, 23.0, 555.1094, 155.0) click: 484.97314 115.94763
V/LinkTextView: top/bottom overlap
D/LinkTextView: firstDiff: 30.552368 secondDiff: 26.947632
V/LinkTextView: padding click: https://pixelfed.social/discover/tags/fediphoto365?src=hash
D/NotificationF: Submitting data to adapter
``` 

Refreshing will cause the error described. In this case: "Refresh for key:" (without an actual value / empty string behind). This seems to indeed be in NotificationPagingSource.load() and param.key being empty just as you described:

``` 
D/NotificationsPagingSource: load() with Refresh for key: 
I/okhttp.OkHttpClient: --> GET https://pixelfed.social/api/v1/notifications/
I/okhttp.OkHttpClient: --> GET https://pixelfed.social/api/v1/notifications?max_id=&limit=90&exclude_types%5B%5D=follow_request
I/okhttp.OkHttpClient: <-- 200 https://pixelfed.social/api/v1/notifications/ (484ms, unknown-length body)
I/okhttp.OkHttpClient: <-- HTTP FAILED: java.io.IOException: Canceled
``` 

So for the "second part" you seem right but apparently it happens only in that Refresh, and in this case (as far as I could tell) the lastNotificationId isn't at least being reset in the ViewModel class? Also, what's the difference between Prepend and Refresh at this point...?

**Comment by nikclayton** [comment]
The `lastNotificationId` is saved with the chain of code:

`NotificationsFragment.onPause()`:

```
    override fun onPause() {
        super.onPause()

        // Save the ID of the first notification visible in the list
        val position = layoutManager.findFirstVisibleItemPosition()
        if (position >= 0) {
            adapter.snapshot()[position]?.id?.let { id ->
                viewModel.accept(InfallibleUiAction.SaveVisibleId(visibleId = id))
            }
        }
    }
```

That sends an action to `NotificationsViewModel`, which is handled with:

```
        // Save the visible notification ID
        viewModelScope.launch {
            uiAction
                .filterIsInstance<InfallibleUiAction.SaveVisibleId>()
                .distinctUntilChanged()
                .collectLatest { action ->
                    Log.d(TAG, "Saving visible ID: ${action.visibleId}")
                    accountManager.activeAccount?.let { account ->
                        account.lastNotificationId = action.visibleId
                        accountManager.saveAccount(account)
                    }
                }
        }
```

If the ViewModel is restarted it will then continue from that saved ID with the code:

```
        // The database stores "0" as the last notification ID if notifications have not been
        // fetched. Convert to null to ensure a full fetch in this case
        val lastNotificationId = when (val id = accountManager.activeAccount?.lastNotificationId) {
            "0" -> null
            else -> id
        }
        Log.d(TAG, "Restoring at $lastNotificationId")

        pagingData = notificationFilter
            .flatMapLatest { action ->
                getNotifications(filters = action.filter, initialKey = lastNotificationId)
            }
            .cachedIn(viewModelScope)
```

So when you navigate away from the notifications tab (e.g., by swiping to a different tab, or by opening preferences, or by switching from Tusky to another app) you should see a `Saving visible ID: ...` message from the view model.

Do you see that message?

Separately, can you set a breakpoint on the block

```
        val lastNotificationId = when (val id = accountManager.activeAccount?.lastNotificationId) {
            "0" -> null
            else -> id
        }
```

and confirm that value `lastNotificationId` actually has? And if it's the empty string, does adding a case for `"" -> null` to that `when` block resolve the crash?

It doesn't answer the question "Why is it the empty string?", but it's a step closer.

**Comment by kr428** [comment]
Ah ok.... been travelling halfway through that the last hour already, it gets a bit clearer. So, looking at this:

* The "Saving visible ID: ..." message appears correctly, whenever switching tabs or to another app, and (brief look at pixelfed) it seems to save valid data.
* Adding `"" -> null` doesn't change anything in the behaviour.
* Surprisingly (at least to me), the app will only run into that "val lastNotificationId ..." breakpoint once when starting the application? Is this intended?

What's a bit surprising too, at the moment (at least in the emulator): When starting the application and switching to Notifications for the first time, I see notifications, but right now it seems "some" notifications are loaded / added twice. Not sure this is related:

![2023-04-27_15-59](https://user-images.githubusercontent.com/685879/234885287-e0118db6-e30d-4300-907e-8eac568a4a6d.png)

**Comment by connyduck** [comment]
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
		at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
		at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
		at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
		at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
		at java.lang.Thread.run(Thread.java:1012)
	Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
		at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
```

Looks like `GET https://pixelfed.social/api/v1/notifications/{id}` is called with an empty id, which causes Pixelfed to return a list of notifications instead of a single one

**Comment by kr428** [comment]
> Looks like `GET https://pixelfed.social/api/v1/notifications/{id}` is called with an empty id, which causes Pixelfed to return a list of notifications instead of a single one

Just out of curiosity: How did you manage to extract that stacktrace?

**Comment by connyduck** [comment]
> Just out of curiosity: How did you manage to extract that stacktrace? 
 
I added a log statement for the exception [where it is handled](https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationsFragment.kt#L401)

**Comment by nikclayton** [comment]
@kr428 I'm "@nikclayton" on pixelfed.social, so if you could do something that will generate a notification to that account that'll help me debug. Cheers.

**Comment by kr428** [comment]
Done. Thanks. 🙂

**Comment by nikclayton** [comment]
That was enough to let me figure out the problem.

Paging @dansup to the issue for feedback.

There's one definite problem, and one problem lurking in the wings.

The definite problem is that Pixelfed's implementation of the Matsodon API is different from Mastodon's, specifically in how (at least) the `min_id` parameter is handled.

Per https://docs.joinmastodon.org/methods/notifications/#query-parameters, `min_id` is:

> String. Return results immediately newer than this ID

This means that the results returned from an `/api/v1/notifications?min_id=1234` call **must not** include the notification with ID `1234`. The call is requesting "Notifications newer than this ID", not "Notifications with this ID or newer".

Pixelfed doesn't do this. I've just verified this with my account.  If I make the following request:

**Comment by kr428** [comment]
Yes... the latter has been an issue then and now. Would be great if it worked (the way it did in the past), but as this API unfortunately is still too closely tied to a particular platform, seems that's where the Fediverse hits limits.😔
