### ISSUE TITLE
[regression] Missing 0/1/1+ reply indicator with "Show post statistics in timeline" disabled

### ISSUE THREAD

**Issue by digitalcircuit** [tuskyapp/Tusky#3588]
## In brief
* Tusky v22 should show `0`/`1`/`1+` reply count indicators with `Show post statistics in timeline` **unchecked**
   * Regression from [adding the feature to show post statistics inline](https://github.com/tuskyapp/Tusky/pull/3413 )
   * Matches Tusky v21 behavior and upstream Mastodon
   * Allows seeing if there are replies without requiring revealing all post statistics

### Steps
1.  Connect Tusky v22.0-beta.1 to an account with various posts on the home timeline
2.  Browse the timeline until you find a toot with replies
3.  Ensure that `Show post statistics in timeline` is **unchecked**
4.  Observe the reply icon

### Expected
Tusky shows a `0`/`1`/`1+` indicator depending on how many replies exist - none/one/more than one.

![Screenshot of Mastodon showing the loose reply count indicator](https://zorro.casa/sync/Hosting/Utilities/Development/Tusky/issues/timeline-missing-loose-reply-count/Timeline%20post%20with%20replies%20-%20Mastodon.png?v1)

### Actual
Tusky won't show any indication of whether a post has replies (not an exact count, just `0`/`1`/`1+`) until you expand it and wait for the thread to load.

![Screenshot of Tusky not showing any indicator next to the reply icon](https://zorro.casa/sync/Hosting/Utilities/Development/Tusky/issues/timeline-missing-loose-reply-count/Timeline%20post%20with%20replies%20-%20Tusky.png?v2)

* * * *
- Tusky Version: `v22.0-beta.1`
- Android Version: `13` (`TQ2A.230405.003.E1`)
- Android Device: Pixel 4 XL
- Mastodon instance (if applicable): N/A

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
I've looked at the changes and the number fields in the timeline were only added with them (not changed). At least the ones for boost and favorite.
Also the original issue #2486 says so: "_add_ stats in home timeline"

Taking the wording literally it could be argued that it is correct/consistent at the moment: the opposite of "Show post statistics in timeline" would be "do not show".

Having said that: The reply count was present and it was set to 0/1/1+.
That is now consistent with the other two: Either not showing or showing the actual number.

**Comment by nikclayton** [comment]
> I've looked at the changes and the number fields in the timeline were only added with them (not changed). At least the ones for boost and favorite. Also the original issue #2486 says so: "_add_ stats in home timeline"
> 
> Taking the wording literally it could be argued that it is correct/consistent at the moment: the opposite of "Show post statistics in timeline" would be "do not show".
> 
> Having said that: The reply count was present and it was set to 0/1/1+. That is now consistent with the other two: Either not showing or showing the actual number.

Yes, but (a) it's still a regression, and (b) the previous functionality for replies was useful, because it told you whether or not the status had one or more replies, so whether or not you should tap through the status to read the replies.

I'm throwing a fix together.

**Comment by Lakoja** [comment]
b) at least seems a bit twitter-ish: Click here to see the buzz.
In the Fediverse we much more value the intention of the initial post and author.

**Comment by digitalcircuit** [comment]
@Lakoja
> b) at least seems a bit twitter-ish: Click here to see the buzz. In the Fediverse we much more value the intention of the initial post and author.

It might be possible to add some complexity and make the setting a tri-state option, with e.g. "Show nothing", "Show if there are replies", and "Show all stats."

I personally use the 0/1/1+ just to know if it's worthwhile tapping to expand a post, as sometimes my Internet and/or instance can be slow requiring waiting a few seconds.  Distinguishing between "1" and "1+" lets me know if someone else replied in the middle of a thread.

(I do yearn for the way Google+ handled comments and how Cohost handles them now, gathering them under a single cohesive post instead of scattered through the timeline, but that's a much larger discussion and change.)

**Comment by Lakoja** [comment]
> @Lakoja
> I personally use the 0/1/1+ just to know if it's worthwhile tapping to expand a post, as sometimes my Internet and/or instance can be slow requiring waiting a few seconds. Distinguishing between "1" and "1+" lets me know if someone else replied in the middle of a thread.

As that makes you three and me one that is probably the correct way to go. :-)
I was merely observing anyway.
