### ISSUE TITLE
22 beta: Wrong Links Opening When Clicking on Post

### ISSUE THREAD

**Issue by bama35453** [tuskyapp/Tusky#3596]
After using the 22 beta for a while, I noticed a strange behavior:

Sometimes when clicking on a post (e.g. to open the corresponding thread and read other replies), Tusky doesn't show the post/thread, but opens a web link to a completely different post that has nothing to do with the current post at all.
This behavior is not really reproducible and only occurs every now and then.
When this happens, it is impossible to open the correct post until the timeline is reloaded. After reloading the timeline, everything works fine for a while.

I think I was able to narrow down the problem a bit:
It seems to be related to the position in the timeline when Tusky is launched. As far as I can tell from what is happening on my devices, it looks like Tusky remembers the web link contained in the very first post that is displayed when it starts. Now when I scroll down the timeline and click on another post, Tusky still opens the link from that very first post that was displayed at startup.
That would also explain why it doesn't happen every time. If, after launching Tusky, the first post displayed in the timeline happens to contain no links, Tusky works as expected.

The described behavior can be observed on various devices.

* * * *
- Tusky Version: 22 beta
- Android Version: 13 / Samsung OneUI 5.1
- Android Device: Samsung Galaxy S22 Ultra / Samsung Galaxy Tab S7
- Mastodon instance (if applicable): mastodontech.de

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
With "opens the web link" you actually mean it leaves Tusky and opens the browser?

(There have been some (2) reports in the chat that Tusky sometimes opens the wrong status (conversation) when tapping one.
Scrolling up and down a bit helps in this case.
That sounds at least a bit similar.)

**Comment by bama35453** [comment]
Yes, the browser opens displaying the page linked to the very first post after starting up.

And no, scrolling up and down does not help..

**Comment by tarper24** [comment]
I can add that I've had it happen after tapping "load more" occasionally. I just had that happen now.

It seems like Tusky isn't updating the "tap zones" properly when the UI is updated.

I've encountered both wrong status opening and web link opening, depending on what was there before the UI updated

**Comment by nikclayton** [comment]
@bama35453 

Which timelines does this happen on? E.g., is it only the Home timeline, or do you see this same behaviour in Notifications, Local, Federated, etc timelines?

**Comment by bama35453** [comment]
I mainly use my home timeline. So I experienced the issue there.
I did not see this behavior in the other timelines so far. Nevertheless this does not necessarily mean that it does not happen there at all since it's hard to reproduce.
So I have to admit I cannot tell for sure.

**Comment by nikclayton** [comment]
Just seen this on Pixel 4a running 22 beta 1 on mastodon.social, so it's not device dependent.  I've deployed a debug build to see if I can get more data.

**Comment by nikclayton** [comment]
Here's an example on the Federated timeline. The purple shading indicates where Tusky thinks there's a link, and indicates the clickable area for that link. The second full status (from Matt H) shows two shaded areas where there is no link.

<img src="https://user-images.githubusercontent.com/773100/235346543-71758572-1a78-4183-b8c3-1c0fa865bc10.png" width="45%">

This is going to be somewhere in `ClickableSpanTextView`, or code that uses it. I'll keep looking.

**Comment by nikclayton** [comment]
More digging turns up some weirdness. I've got a timeline that reliably reproduces this on one post, here's a screenshot:

<img src="https://user-images.githubusercontent.com/773100/235350088-0b5f224c-a518-41f3-bcb4-345a58126aac.png" width="45%">

The middle post from mjg59 is wrong, it's using a clickable rect from an earlier post.

I modified the code to dump up to the first 40 characters of each post in `ClickableSpanTextView.measureSpans()`. Here's what I see when I get to that point in the timeline:

```
12:59:10.094 ClickableSpanTextView           D  @mjg59 Was anyone else thinking, when Twi
12:59:10.743 ClickableSpanTextView           D  @mmasnick done by far the best job of chr
```

That's the first post in the screenshot, and the last post, but not the middle one. That explains why the clickable area is wrong, it's not being re-calculated when the contents of the view change. I don't know why that is yet, but investigation continues...

**Comment by nikclayton** [comment]
The post that contained the original span, and the post that contains the bogus area (i.e., the middle one in the screenshot above) are the same length. That feels suspicious. Does TextView optimise and avoid relayouts if the text is the same length or number of lines...?

**Comment by nikclayton** [comment]
Smoking gun in `TextView.java`...

```
    /**
     * Check whether entirely new text requires a new view layout
     * or merely a new text layout.
     */
    @UnsupportedAppUsage
    private void checkForRelayout() {
        // If we have a fixed width, we can just swap in a new text layout
        // if the text height stays the same or if the view height is fixed.
        ...
```
