### ISSUE TITLE
Turkish translations of relative dates and Use Chrome Custom Tabs menu item are partly wrong

### ISSUE THREAD

**Issue by gribaykus** [tuskyapp/Tusky#3605]
Hi!

I recently started using Tusky and immediatly noticed a couple of translations are faulty but not completly wrong. As it effects the first immersion, you may be want to fix them before the next release. I have already sent fixes via Weblate but as I don't use that software, I don't know if I made mistakes :) If you don't have dedicated Turkish translation here are the problems and fixes:

- Relative dates: Current translation contains English abbreviation for dates + Turkish tranlations. I removed English abbrevation. Also there were correct but unnecessary words. English text only shows abbreviation, so I updated accordingly.
- Use Chrome Custom Tabs: Proper Turkish translation should be: Chrome Özel Sekmelerini Kullan. It was just a typo. "ş" instead of "s"
- I didn't find where is used but translations of "in %d" looks wrong to me as translation means "before %d" in Turkish. I changed them too.

Best regards.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Thanks for the report, and for taking the time to make the fixes.

https://github.com/tuskyapp/Tusky/commit/e4f766d44761566e2f6b05d6e02e8d5a673c6104 was committed from Weblate a few days ago, and based on your description I think it includes your fixes.

So they'll be in v22 when it's released.

Thanks again
