### ISSUE TITLE
Duplicate push notifications in Tusky 22 beta

### ISSUE THREAD

**Issue by yuvalne** [tuskyapp/Tusky#3616]
I've been getting push notifications for interactions I've already been notified about since updating to the beta. It happen consistently so I don't know how to reproduce, but in the latest occurrence it was for two mentions, one of which I already liked, about 16 minutes after the original notification. I've also noticed that it's always notifying for more than one interaction in the duplicate push notification.
The push notification appears as normal and clicking on it brings you to the relevant notification in the notification tab as normal. and the in-app notifications tab doesn't show the same interaction twice. It's just the push that happens twice within some time interval.

* * * *
- Tusky Version: 22.0 beta 1
- Android Version: 12
- Android Device: Galaxy A12
- Mastodon instance (if applicable): multiple

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nehemiagurl** [comment]
Finally managed to capture this. I got a mention and a like, yet neither of them appeared in the push notification. Instead, these 8, all of which are duplicate, were pushed.
![Screenshot_20230506-102749](https://user-images.githubusercontent.com/109424320/236610079-95c73764-2185-4c4a-9861-836da778f9bb.jpg)

**Comment by nikclayton** [comment]
This should be fixed as of v22 beta 4.

**Comment by yuvalne** [comment]
Seems to indeed be fixed!
