### ISSUE TITLE
Missing linebreaks in polls make larger text unreadable

### ISSUE THREAD

**Issue by BDGreyson** [tuskyapp/Tusky#3618]
I'm using a Huawei Phone with OS text size set to "large" as well as using the largest text size in Tusky.
This works perfectly fine for Toots, all text is correctly readable and line-broken.

For polls, though, I have to use landscape mode to read longer texts, and it would be awesome if long text would just be broken to the next line instead of being shortened with "...".

Here some screenshots:

Poll in Tusky in portrait mode:

![grafik](https://user-images.githubusercontent.com/50461895/236141763-45105661-68a2-4a5d-9d3a-0816cfe2d86f.png)

As you see, the complete options are not readable.

Now, here's the landscape mode:

![grafik](https://user-images.githubusercontent.com/50461895/236141906-a3476215-694c-42c2-80e0-a51e44c20e64.png)

In that one it's readable, but it's not very convenient for me as I auto-rotate disabled usually.

Now, to compare, here's the Mastodon webview in a browser in portrait mode:

![grafik](https://user-images.githubusercontent.com/50461895/236142077-933e87af-7faa-4e1d-a281-a7978e78e4b3.png)

The text here is also correctly broken to the next line, making it fully readable, and it would be great if it would also work like that in Tusky.

I couldn't find an option in it, but feel free to let me know if I'm missing anything.

* * * *
- Tusky Version: 21.0
- Android Version: Android 10 (Huawei EMUI 12.0)
- Android Device: Huawei P 30 Pro
- Mastodon instance (if applicable): social.tchncs.de

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/3608

**Comment by nikclayton** [comment]
@BDGreyson -- thanks for the report. We have this fixed in v22, which is in beta now and should be released next week.
