### ISSUE TITLE
Still seeing duplicate notifications w/ v22 beta 3

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3658]
Something weird is going on with notification marker fetching, resulting in users seeing duplicate notifications.

I see this on some accounts, but not others.

Symptoms on a working account (nikclayton@mastodon.social in my case):

When new notifications are fetched it should fetch the notifications marker from the server, and fetch notifications that are newer than that (ignoring, for the moment, that beta 3 doesn't have the fix in https://github.com/tuskyapp/Tusky/pull/3657).

For my account I see the following logged:

```
I  --> GET https://mastodon.social/api/v1/markers?timeline%5B%5D=notifications
I  <-- 200 https://mastodon.social/api/v1/markers?timeline%5B%5D=notifications (47ms, 100-byte body)
D  Fetched marker: Marker(lastReadId=149606100, version=161, updatedAt=Mon May 15 17:09:38 GMT+02:00 2023)
D  getting Notifications for @nikclayton@mastodon.social, min_id: 149606100
I  --> GET https://mastodon.social/api/v1/notifications?min_id=149606100
I  <-- 200 https://mastodon.social/api/v1/notifications?min_id=149606100 (58ms, 2-byte body)
```

- Lines 1-2 are the request/response for fetching the marker
- Line 3 is a dump of the marker data, which looks good
- Lines 4-6 are confirming that it's fetching notifications newer than the marker.

Here's the same thing for the tusky@mastodon.social account:

```
I  --> GET https://mastodon.social/api/v1/markers?timeline%5B%5D=notifications
I  <-- 200 https://mastodon.social/api/v1/markers?timeline%5B%5D=notifications (98ms, 93-byte body)
D  Fetched marker: Marker(lastReadId=1, version=1301, updatedAt=Mon May 15 23:38:38 GMT+02:00 2023)
D  getting Notifications for @Tusky@mastodon.social, min_id: 149681638
I  --> GET https://mastodon.social/api/v1/notifications?min_id=149681638
I  <-- 200 https://mastodon.social/api/v1/notifications?min_id=149681638 (251ms, 118340-byte body)
```

Line numbers have the same meaning as above. The question is, why, on line 3, is the returned `lastReadId` == `1`?

If I make the same request outside Tusky I get back:

```
{
    "notifications": {
        "last_read_id": "149696886",
        "version": 1302,
        "updated_at": "2023-05-15T21:42:01.799Z"
    }
}
```

So the API is returning the correct data at this point.

Why is Tusky seeing the `lastReadId` as 1...?

* * * *
- Tusky Version: 22 beta 3

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by asjmcguire** [comment]
Couldn't you just set the lastReadId to the most recent notification id if the marker evaluates to 1, as a workaround?

**Comment by nikclayton** [comment]
> Couldn't you just set the lastReadId to the most recent notification id if the marker evaluates to 1, as a workaround?

That would result in missing notifications (and repeatedly showing the most recent notification).

**Comment by nikclayton** [comment]
It's reproducing again, and I've got an API response from mastodon.social that looks like:

```
{
    "notifications": {
        "last_read_id": "1",
        "version": 1364,
        "updated_at": "2023-05-16T09:32:05.163Z"
    }
}
```

So it is data coming from the server.

Working theory -- is the `POST` to update the marker sending garbage data, and the Mastodon server is resetting it to `1`? Possibly the `POST` is sending data of the wrong type?

**Comment by asjmcguire** [comment]
One thing that I did notice looking through the code last night, that I thought I would question, because it might just be that you had not posted the relevant log line - there is a line that logs that it is setting the marker on the server, are you seeing those entries in your log?

**Comment by nikclayton** [comment]
Debugging notes:

- 2 accounts on the emulator, both @mastodon.social
- The nikclayton account has a bearer token that starts `R`
- The Tusky account has a bearer token that starts `P`

Those tokens are going to be relevant.

I'm looking at a full log now (`NetworkModule.kt`, set `level = HttpLoggingInterceptor.Level.BODY` to get a dump of everything that's going on).

I see the following:

1. Get the notification marker for the Tusky account:

```
D  getting notification marker for @Tusky@mastodon.social
I  --> GET https://mastodon.social/api/v1/markers?timeline%5B%5D=notifications
I  Authorization: Bearer P...
...
I  {"notifications":{"last_read_id":"94313197","version":1378,"updated_at":"2023-05-16T09:52:07.358Z"}}
...
D  Fetched marker: Marker(lastReadId=94313197, version=1378, updatedAt=Tue May 16 11:52:07 GMT+02:00 2023)
```

That looks correct. It's a very old notification ID, but that's probably because of the underlying bug.

The bearer token is correct.

Pay attention to the `version=1378`, that's going to be important later.

2. Then it fetches new notifications. The marker is less than than the last read notification in the Notifications tab (149800636) so it uses 149800636 as the notification ID to fetch from.

```
D  getting Notifications for @Tusky@mastodon.social, min_id: 149800636
I  Authorization: Bearer P...
I  --> GET https://mastodon.social/api/v1/notifications?min_id=149800636
```

That's also correct.

3. That returns JSON with one new notification, with ID = `"149805723"`.

```
I  <-- 200 https://mastodon.social/api/v1/notifications?min_id=149800636 (291ms)
I  [{"id":"149805723", ... }]
```

That notification is displayed correctly (and it is the most recent notification).

4. The marker is set to `149805723` as the newest fetched notification.

```
D  updating notification marker for @Tusky@mastodon.social to: 149805723
I  --> POST https://mastodon.social/api/v1/markers
...
I  Authorization: Bearer R...
I  notifications%5Blast_read_id%5D=149805723
I  --> END POST (41-byte body)
```

That's **wrong**, it's using the bearer token for the other account (i.e., it starts with an `R`, **not** a `P`), *not* the @tusky@mastodon.social account.


6. `mastodon.social` returns a 200, with a JSON response confirming the new marker.

```
I <-- 200 https://mastodon.social/api/v1/markers (102ms)
...
I  {"notifications":{"last_read_id":"149805723","version":169,"updated_at":"2023-05-16T09:59:21.403Z"}}
I  <-- END HTTP (100-byte body)
```

Although the `last_read_id` is correct, the `version` is wrong. This should be `1379`, one higher than the `version` shown in the fetch at step 1.

The markers for my primary account do have a version in the 160s, so this confirms that Tusky is writing the marker to the wrong account because the wrong bearer token is being used at this step.

That's what's happening. Now to dig in to why it's happening.

**Comment by nikclayton** [comment]
`InstanceSwitchAuthInterceptor.kt` looks relevant...

**Comment by nikclayton** [comment]
If you're on the Tusky beta and affected by this, first of all, sorry. I get that it's super annoying.

Options that I can think of that will minimise the annoyance for the next day or two would be:

1. "Account preferences > Notifications" and disable all Tusky notifications. This won't prevent them from showing up in your Notifications tab, it just stops the Android notifications.
2. This problem only occurs if you have multiple accounts signed in to Tusky. Remove all but one account temporarily and the problem should not appear.
3. Some Android variants support installing multiple copies of the same app, and sandboxing them. You might be able to use this to install multiple versions of Tusky, and sign in to exactly one account on each of them (e.g., see https://www.makeuseof.com/run-two-copies-of-app-android/)
4. Temporarily un-enroll yourself from the beta program at either Google Play or F-Droid, depending on where you're getting Tusky from.
