### ISSUE TITLE
Tusky displays very old notifications with no way to quickly reach current ones

### ISSUE THREAD

**Issue by noiob** [tuskyapp/Tusky#3659]
Tusky beta 2 stattestarted showing me very old notifications, in some cases 4 years old, on multiple accounts. There is no easy/obvious way to view any current notifications, as scrolling up simply loads the next batch.

(workaround: filter everything but a category with very little activity like polls or follow requests if you're unlocked, then scroll all the way up)

* * * *
- Tusky Version: 22.0 beta 2
- Android Version: 13
- Android Device: Google Pixel 4a 5G
- Mastodon instance (if applicable): any

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Dupe of https://github.com/tuskyapp/Tusky/issues/3658
