### ISSUE TITLE
Possible duplicate notifications on servers that don't support the marker API

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3671]
I think we might need a beta 5 to prevent another possible source of duplicate notifications.

At the moment, each account has a `lastNotificationId` property.

---

v21 set `lastNotificationId` as the ID of the newest notification received, irrespective of the user's reading position in the Notifications tab.

This meant that if you came back to the Notifications tab you would always be sent to the newest notification because your reading position was not saved (assuming that Android had freed up the tab).

It also used `lastNotificationId` as a backup value if the server did not support the marker API. That's why it worked with GoToSocial.

---

v22 uses `lastNotificationId` as the user's reading position in the Notifications tab. So if you go to the Notifications tab, scroll down a bit, leave the tab and go and do something else, then come back, your reading position is restored. Critically, `lastNotificationId` is **not** the ID of the newest notification any more.

Tusky now *relies* on the marker API to save/restore the ID of the most recent notification shown as an **Android** notification (falling back to the `lastNotificationId` if it's missing, if e.g., the user hasn't received any notifications before).

This **will** result in users getting duplicate Android notifications if their server doesn't support the marker API **and** they've scrolled down in the Notifications tab.

Not all servers support the API. At least GoToSocial, as I've just discovered.

---

This could be fixed with a PR that introduces a new account-level property that stores the same value as the marker.

When fetching Mastodon Notifications to display as Android Notifications the code would look something like (`NotificationFetcher.kt:fetchNewNotifications()`).

```
val serverMarkerId = fetchMarker(authHeader, account)?.lastReadId
val localMarkerId = account.notificationMarker  // <-- new property
val markerId = if (serverMarkerId?.isLessThan(localMarkerId)) localMarkerId else serverMarkerId

val minId = when (markerId) {
    null -> account.lastNotificationId.takeIf { it != "0" }
    else -> if (account.lastNotificationId.isLessThan(markerId)) markerId else account.lastNotificationId
}
```

Then save `account.notificationMarker` in the same block that tries to update the marker on the server.

This would be beta 5 (could do that tomorrow), and pushes the release to probably Monday.

* * * *
- Tusky Version: 22 beta 4
- Mastodon instance (if applicable): GoToSocial, maybe more

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by sandzwerg** [comment]
I have a account on a gotosocial instance and I still get notifications for that Account even though there are no new notifications since two days. That is with beta 5, is that the same issue or something else? To me it feels like it might be the same.

**Comment by sandzwerg** [comment]
https://social.gulas.ch/ its an closed instance for an invite so registration is not open. I can ask if it's possible to get you an account

**Comment by nikclayton** [comment]
> https://social.gulas.ch/ its an closed instance for an invite so registration is not open. I can ask if it's possible to get you an account

Yes please. Thanks.

**Comment by sandzwerg** [comment]
I've sent an mail with instructions to the address in your profile. Ping me if you have any questions.
