### ISSUE TITLE
Tusky 22.0 beta 6  I can't install, error for APK

### ISSUE THREAD

**Issue by franco27** [tuskyapp/Tusky#3694]
Hello

I download the APK file to Github.

When I try to install there is an error message for the APK file.
APK Corrupt or invalid

**Comment by zer0fl0w** [comment]
confirmed / +1

parsing error.

**Comment by nikclayton** [comment]
Huh, weird. The attached file is slightly bigger than the file I downloaded from the Play store console. I'll try that again (and mark the release as draft again until it's fixed).

**Comment by nikclayton** [comment]
Fixed. The content type for the upload was part of the file contents for some reason. I've verified that the uploaded APK on the release now is byte-for-byte identical with the one on the Play store.

**Comment by franco27** [comment]
I confirm, it's repaired. Thank you
