### ISSUE TITLE
Compile fails for Tusky 22.0

### ISSUE THREAD

**Issue by johanw666** [tuskyapp/Tusky#3727]
When I try to build Tusky 22.0 in Android Studio I get the following build error:
```
Execution failed for task ':app:kaptBlueReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

* * * *
- Tusky Version: 22.0
- Android Version: NA
- Android Device: NA
- Mastodon instance (if applicable): NA

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Can you please give us detailed steps of what you are doing?

**Comment by johanw666** [comment]
- Download source code zipfile
- Unzip in a local folder
- edit app/build.gradle line 110 to remove gitSha
- Open the project in Androi Studio Flamingo | 2022.2.1 Patch 1
- Open menu Build - Generate Signed bundle or apk - check apk - select my key - select blueRelease
- Press create
- Get the error message.

**Comment by connyduck** [comment]
Sounds like a problem with either the wrong Android Studio version (Flamingo should work) or Java version (you need to run the build with Java 11 Settings -> Build, Execution, Deployment -> Build tools -> Gradle -> Gradle JDK)

**Comment by johanw666** [comment]
I downloaded a JDK 11 in Android Studio in that screen and that worked, thanks. Somehow Android Studio selected Java a 17 JDK with Android 11 settings but that didn't work.
