### ISSUE TITLE
emoji problem

### ISSUE THREAD

**Issue by usnbtv** [tuskyapp/Tusky#3730]
emoji problem ⁉️

1 - profil ⟩ name emoji 🧑‍💻❓
and 
2 - profil ⟩ edit ⟩ emoji 🧑‍💻❓

**Comment by connyduck** [comment]
I have no idea what you are talking about. If you want us to investigate a bug you need to provide us more information.

**Comment by usnbtv** [comment]
![1](https://github.com/tuskyapp/Tusky/assets/26837921/545cd711-c170-4651-a0a7-3e29b9c1c7ec)
![2](https://github.com/tuskyapp/Tusky/assets/26837921/581effff-1c90-4639-a738-6daea5db8e37)

**Comment by connyduck** [comment]
Those are not custom emojis, right? Maybe same problem as https://github.com/tuskyapp/Tusky/issues/3638?

**Comment by usnbtv** [comment]
no. it's not a special emoji. system emoji.

**Comment by usnbtv** [comment]
no. it's not a special emoji. system emoji. 
problem ' noto emoji ' sourced . i just realized:(
