### ISSUE TITLE
[Crash] nightly build crashes to homescreen instantly

### ISSUE THREAD

**Issue by Sirs0ri** [tuskyapp/Tusky#3740]
Hi, since this morning Tusky nightly crashes right back to my homescreen when I want to open the app. I see a short blue-gray splashscreen for a few hundred ms, and then the app crashes.

My phone then shows me a warning "An error occurred with Tusky" that prompts me to clear the cache (which doesn't help), and then to wait for an update that has a fix.

If there's any specific logs that could help you track this down, please lmk what exactly you need and I'll supply those!

* * * *
- Tusky Version: 22.0-ac49222d
- Android Version: 12
- Android Device: Galaxy s10e
- Mastodon instance (if applicable): corteximplant.com, not sure it's related.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Sirs0ri** [comment]
sure thing, here you go @nikclayton, lookks like it's indeed the notificationworker:

[crash_tusky_test.log](https://github.com/tuskyapp/Tusky/files/11724981/crash_tusky_test.log)

**Comment by nikclayton** [comment]
That's a 0 byte file...

**Comment by codl** [comment]
I'm having the same issue, here's my logcat log

https://f.codl.fr/2306/tusky_test_crash.txt?v=eba37e

**Comment by nikclayton** [comment]
@codl Thanks, that helps.

Hmm.

```
java.lang.ClassNotFoundException: com.keylesspalace.tusky.components.notifications.NotificationWorker
```

That's weird -- it's not called that in the newer code, it's `com.keylesspalace.tusky.worker.NotificationWorker`.

Is this a bug that's only trigged through an upgrade...?

**Comment by Sirs0ri** [comment]
whoops, looks like something went wrong with the upload, the log definitely wasn't empty on my pc - let's try that again: 
[crash_tusky_test.log](https://github.com/tuskyapp/Tusky/files/11728254/crash_tusky_test.log)
