### ISSUE TITLE
App crashes due to Troet favour Interaction 

### ISSUE THREAD

**Issue by Sam4000der2** [tuskyapp/Tusky#3748]
App crashes due to Troet favour Interaction. Only Tusky is affected. The message was addressed to a potential troll. I can't even open my interaction page in Tusky anymore without the app crashing. Even if the message is closed in the Android message centre via the favourites interaction, it always opens again.

* * * *
- Tusky Version: 22.0
- Android Version: Android 13 - TQ2A.230505.002.A1
PixelOS_alioth-13.0-20230512-0549 
- Android Device: POCO F3
- Mastodon instance (if applicable): Pixelfed de

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

time: 1686723664235
msg: java.lang.IllegalStateException: The same value, , was passed as the nextKey in two
 sequential Pages loaded from a PagingSource. Re-using load keys in
 PagingSource is often an error, and must be explicitly enabled by
 overriding PagingSource.keyReuseSupported.
stacktrace: java.lang.IllegalStateException: The same value, , was passed as the nextKey in two
 sequential Pages loaded from a PagingSource. Re-using load keys in
 PagingSource is often an error, and must be explicitly enabled by
 overriding PagingSource.keyReuseSupported.
	at k1.e3.b(SourceFile:995)
	at k1.o2.o(Unknown Source:12)
	at la.a.h(SourceFile:6)
	at kotlinx.coroutines.l0.run(SourceFile:113)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	Suppressed: kotlinx.coroutines.j0: [p1{Cancelling}@daba79c, Dispatchers.Main.immediate]
New Snippet 

 Memochō

**Comment by nikclayton** [comment]
Is this only happening with a Pixelfed account?

If so, this sounds like this is this bug in Pixelfed: https://github.com/pixelfed/pixelfed/issues/4461

**Comment by Sam4000der2** [comment]
> Is this only happening with a Pixelfed account?
> 
> If so, this sounds like this is this bug in Pixelfed: [pixelfed/pixelfed#4461](https://github.com/pixelfed/pixelfed/issues/4461)

Yes, only in combination mit Pixelfed.

**Comment by nikclayton** [comment]
OK. This is a Pixelfed issue, and needs to be fixed there unfortunately.
