### ISSUE TITLE
some posts video media aren't shown

### ISSUE THREAD

**Issue by demonspanther** [tuskyapp/Tusky#3753]
Hello , i would like to report that sometimes an account post a video and the message display " no description " but if i open the message link on browser i can see the full video.

* * * *
- Tusky Version: 22
- Android Version: 12

- Mastodon instance pettingzoo.co

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Please can you send some links to posts that have this problem so we can investigate.

**Comment by demonspanther** [comment]
Hello, the issues it's solved now.
Changing istance let it work.
Maybe was a limit of the old istance.
