### ISSUE TITLE
Possible "pull" notification regression

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3754]
With this (?) I get a regression for the notification worker (pull requests):

```
java.lang.IllegalStateException: Expedited WorkRequests require a Worker to provide an implementation for `getForegroundInfo()`
```

This is only visible in Logcat but prohibits notifications.

At the moment I cannot easily fix it (either by disabling the OneTimeWorkRequest or trying to move the NotificationWorker to a CoroutineWorker).

_Originally posted by @Lakoja in https://github.com/tuskyapp/Tusky/issues/3649#issuecomment-1594285314_

**Comment by nikclayton** [comment]
@Lakoja I can't immediately reproduce this.

On an emulator running `develop` from yesterday I've:

1. Installed F-Droid
2. Installed ntfy.sh from F-Droid (and disabled battery optimization for it)
3. Launched Tusky Nightly
4. Confirmed that ntfy.sh shows the subscriptions (I see two, both assigned to "com.keylesspalace.tusky.test"), and there's an ntfy notification showing that it's listening and subscribed to two topics.
5. Confirmed that Tusky is using Unified Push, the logs show:

```
2023-06-16 10:28:14.723 UnifiedPush                       D  Found distributor with package name io.heckel.ntfy
2023-06-16 10:28:14.725 NotificationHelper                D  NotificationsEnabled
2023-06-16 10:28:14.725 UnifiedPush                       D  Found distributor with package name io.heckel.ntfy
[...]
2023-06-16 10:28:14.772 PushNotificationHelper            D  UnifiedPush subscription updated for account 1
[...]
2023-06-16 10:28:14.879 PushNotificationHelper            D  UnifiedPush subscription updated for account 2
```

6. Sent myself a DM from one account to another

The notification for the DM arrives almost immediately, and there are no exceptions logged.

**Comment by Lakoja** [comment]
It's pull notifications (not push). So if you have a push distributor installed this won't happen.

**Comment by nikclayton** [comment]
OK, even weirder, as I don't normally have ntfy installed on the emulators when I'm testing, so I've been using the new code for the last month or so and haven't seen this problem.

**Comment by Lakoja** [comment]
This happens for Android 11 and lower.
See for example https://stackoverflow.com/questions/69627330/expedited-workrequests-require-a-listenableworker-to-provide-an-implementation-f

**Comment by nikclayton** [comment]
Thanks, that's the info I needed. https://github.com/tuskyapp/Tusky/pull/3760 fixes this, verified in an emulator running Android 11 (API 30).
