### ISSUE TITLE
comment icon

### ISSUE THREAD

**Issue by uslmz** [tuskyapp/Tusky#3757]
Tusky 
🗨️ how about if you change the ' comment iconc' ?![tusky_1comment.jpg](https://github.com/tuskyapp/Tusky/assets/26837921/6b40503a-742f-4679-a09d-aee868828c36)

**Comment by connyduck** [comment]
How about you explain why that would be better than the current one?

**Comment by usnbtv** [comment]
it was a humble suggestion 🤗

**Comment by foss-** [comment]
> it was a humble suggestion 🤗

Suggestions are great. But without context and explanation as to why the current icon is not good and which icon you prefer and why, this issue is not actionable and thus not very useful.
