### ISSUE TITLE
Follow request page incorrectly shows "your account is not locked"

### ISSUE THREAD

**Issue by WesleyAC** [tuskyapp/Tusky#3773]
The "Follow requests" page incorrectly shows the text stating your account is not locked, even when it is locked. See screenshot.

![signal-2023-06-23-15-09-23-995](https://github.com/tuskyapp/Tusky/assets/5001092/4a34987d-7c36-4fe0-9bc0-0c84c4698e0e)
![signal-2023-06-23-15-09-23-995-1](https://github.com/tuskyapp/Tusky/assets/5001092/a02330d6-d173-4ec9-bd68-0f085d820724)

* * * *
- Tusky Version: 22.0
- Android Version: 12
- Android Device: Pixel 6
- Mastodon instance (if applicable): interlace.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
How did you get there? Through the main menu? Or via another place like notifications?

**Comment by connyduck** [comment]
Ah yes absolutely. Thx for reporting, I think this can be fixed by falling back to the cached value when the request fails.
