### ISSUE TITLE
Animation to hide the "new toot button"

### ISSUE THREAD

**Issue by IamHaddad** [tuskyapp/Tusky#3774]
When scrolling down on the main page, the new toot button appears on top of the toots texts, making it difficult to read them. It would be helpful if the button could disappear as the user scrolls down to allow for uninterrupted reading of the toots.

* * * *
- Tusky Version: 22.0
- Android Version: 13
- Android Device: Poco F3
- Mastodon instance (if applicable): androiddev.social

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
Go in to "Preferences", and set the "Hide compose button while scrolling" option.
