### ISSUE TITLE
Render of editted post doesn't wrap text

### ISSUE THREAD

**Issue by da5nsy** [tuskyapp/Tusky#3814]
When viewing the details of an edit, text is not wrapped as it should be.

Post:
![Screenshot_20230707-111809](https://github.com/tuskyapp/Tusky/assets/3739866/3c346422-14c1-43ab-bf91-6df7b097f1a0)
Edit info:
![Screenshot_20230707-111757](https://github.com/tuskyapp/Tusky/assets/3739866/80b02a20-e932-448e-abd7-db1a1e4a7da1)

* * * *

- Tusky Version: 22.0
- Android Version: 11
- Android Device: Fairphone 3

- Mastodon instance (if applicable): post on peoplemaking.games, viewed via social.coop

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I believe this is fixed in version 23 (currently in beta), can you please confirm that?

**Comment by da5nsy** [comment]
@connyduck - I just signed up for beta, but I think that means I get the _next_ beta, but not the current one, so: no, I cannot confirm (hopefully someone else can).

**Comment by da5nsy** [comment]
👏 thank you!
