### ISSUE TITLE
Selecting a list for a tab shows unformatted IDs

### ISSUE THREAD

**Issue by kvibber** [tuskyapp/Tusky#3819]
In Tusky 23 beta 1 and 2, when going to the account preferences and choosing which tabs to show, adding a list tab brings up the lists...but instead of showing the title, it shows each list as something like  `MastoList(id=123, title=Tech Projects)`

They're still functional, they just look awful.

Confirmed with current Mastodon and the latest GoToSocial RC

**Comment by kvibber** [comment]
![Screenshot_20230707-174201.png](https://github.com/tuskyapp/Tusky/assets/6667023/75a9bdf2-d9dd-4a8a-b493-36bbc6cc59f0)

**Comment by Lakoja** [comment]
Introduced with (a simplification in) #3131.
(ListSelectionAdapter was removed.)

**Comment by connyduck** [comment]
Yes we need ListSelectionAdapter back. Can you take that over @Lakoja?
