### ISSUE TITLE
Feature: search for the toots I've seen

### ISSUE THREAD

**Issue by epragalakis** [tuskyapp/Tusky#3846]
Searching things on mastodon is impossible (outside of hashtags)
I think it would be amazing if we can had a searchable history of all the toots I've seen (think of a browser history but for mastodon).

**Comment by connyduck** [comment]
Posts not being searchable is a feature.

**Comment by epragalakis** [comment]
@connyduck 

I agree it is a feature and part of mastodon's design but this is not what I'm proposing to change here.

The searchable history will be local only and the data will live on the user's device.

Secure scuttlebut is doing something like that and the app works offline as good as it does online.

**Comment by connyduck** [comment]
Yes I understood your proposal, I still think it has to much abuse potential. One could follow a bunch of accounts, then load up the timeline and search for keywords to harass people for. Not in Tusky, sorry.
