### ISSUE TITLE
Filtering hashtags filters too much, not helping

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#3891]
![grafik](https://github.com/tuskyapp/Tusky/assets/1618905/9700a973-052a-4821-a994-36077a8b7f40)

There is a mute button on a hashtag timeline. I noticed several problems there:

1. The added filter also filters the word without being a hashtag; so muting "#X" will mute "X"
2. The buttons here give no feedback what they are doing
3. The added filter only hides but does not remove completely
4. The home timeline is not re-rendered after a change

(2) There should be at least a dialog that for example "Hashtag X was followed". But furthermore the next steps are not obvious: You can see and especially tweak the "mute filter" under Account settings > Filters. I guess no one will find that easily.

(3) Can be discussed what the default here is.
But this actually got me started on this problem when reading a complaint that muting a hashtag still shows it; albeit as "hidden; do you want to see it?".

(4) It can be workarounded by refreshing the view yourself. But I fear many will not know this.

* * * *
- Tusky Version: v22+
(Code introduced with #3188)

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment]
(1) should be a reasonably straightforward fix, tag muting/unmuting is in https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt. Do you want to prep a PR for that? If not, I'm happy to.

(2) ditto. They already show a snackbar if muting fails, so showing a snackbar (**not** a dialog) if muting / unmuting succeeds should be trivial. The snackbar could include an action that opens the filter preferences. Message could be something like "#foo filtered with a warning  [Open filters]"

(3) yes, the behaviour is to warn (https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt#L227). This feature has been present for 8 months (https://github.com/tuskyapp/Tusky/commit/424326f99fca6492e8923499b67189222ea5d373), this is the first time I recall someone suggesting the default should change.

(4) is https://github.com/tuskyapp/Tusky/issues/3546

**Comment by Lakoja** [comment]
> (1) should be a reasonably straightforward fix, tag muting/unmuting is in https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/StatusListActivity.kt. Do you want to prep a PR for that? If not, I'm happy to.
> 
> (2) ditto. They already show a snackbar if muting fails, so showing a snackbar (**not** a dialog) if muting / unmuting succeeds should be trivial. The snackbar could include an action that opens the filter preferences. Message could be something like "#foo filtered with a warning [Open filters]"
> 


Done (MR). Using a snackbar action is a good idea.
