### ISSUE TITLE
[Feature Request] Support for Firefish's concept of a "Social Timeline"

### ISSUE THREAD

**Issue by Sirs0ri** [tuskyapp/Tusky#3907]
I recently started exploring Firefish (Formerly known as Calckey), and one of the features about it I really like is the "social feed", a combination of the local feed and all my followed accounts ("Home timeline") in one single timeline, that exists next to the "Home", "Local", and "Federated" timelines that we know from Mastodon and most of the other Fedi platforms.

Since the Social Feed is just a merge of two already existing other timelines, I hope it could be added to Tusky for all the platforms the app supports, not just for FF and thus be a feature that potentially a lot of users could benefit from.

I'd hope to see the new timeline as one of the options for the tab bar.

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
More or less a duplicate of #3438.

Both want to combine different sources in one timeline.

**Comment by Sirs0ri** [comment]
You're right, my request would be a part of that, I must have missed that when looking for similar issues!
