### ISSUE TITLE
URLs(?) count differently against character limit in Tusky and web (Reprise)

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#3909]
Tusky 23.0 (tested with stock) on Mastodon.social, Android 12, Sony Xperia 5 III.

In #3849 I found a post which was at character max on web Mastodon but -4 in Tusky 21. It was pointed out this was fixed with v22. I can confirm the string in #3849 works with v23.

However, now I have found a string which in v23 is is at -3, not postable, but on web mastodon is postable with one character to spare. I cannot begin to explain this.

```
What I'm listening to today: "Blue Skies", maleficent hardware

A "modular study" wherein cross-wired modules self-generate an ambient composition made of distant howls and shimmers and occasional interruptions from a corrupt harpsicord. A hand occasionally snakes in to nudge the machine's momentum in whatever mysterious direction, but less often than I'd have expected given the complexity of the piece. Uses that one pedal that makes everything sound like old cassettes.

https://www.youtube.com/watch?v=ON5_5fm9RPk
```

**Comment by mcclure** [comment]
It gets worse!!

Say I take the above text. I copy it out of Simpletext, the original source on my android phone. I paste it into Tusky. -3, illegal.

Say I copy it out of *this GitHub issue*. The text in the GitHub issue was copypasted from Simpletext and posted on Android. I paste it into Tusky. +1, legal.

It seems like something invisible is coming along for the ride when the content is sourced from SimpleNote, but a pass through GitHub cleans it out??

**Comment by nikclayton** [comment]
If you've still got a copy of the original text in Simpletext (or Simplenote?), try pasting it in https://www.fontspace.com/unicode/analyzer and see what that reports. It should find hidden glyphs, unexpected whitespace, and so on.

**Comment by Lakoja** [comment]
Just an idea: You can (or present in the file in Simpletext?) add spaces before arbitrary line endings. They would probably be removed here in Github (in Html).

**Comment by connyduck** [comment]
I think this is fixed? @mcclure

**Comment by mcclure** [comment]
I'll test this tomorrow. I think I caught it not working as expected this afternoon but it wasn't a rigorous test

**Comment by mcclure** [comment]
The bug in *this post* is fixed. But I have a new one.

https://github.com/tuskyapp/Tusky/issues/4641
