### ISSUE TITLE
Profile link detection is case-sensitive in Tusky 23

### ISSUE THREAD

**Issue by bremensaki** [tuskyapp/Tusky#3929]
I just got tripped up by the change in https://github.com/tuskyapp/Tusky/pull/3341 when checking some of my stuff against v23.

I've always presented some of my support accounts with camel case names in links, like @ChinwagNews - but these links no longer go to profiles in Tusky because this check is case-sensitive.

Is there really any reason for this not to be case-insensitive? If the URLs it's trying to check are not sensitive, shouldn't the test ideally be as well?

**Comment by nikclayton** [comment]
@Lakoja Do you want to prep the PR to fix this?

I think it's just changing `accounts.firstOrNull { it.url == url }?.let` in the original PR to something like:

```kotlin
 accounts.firstOrNull { it.url.equals(url, ignoreCase = true) }?.let
```

**Comment by bremensaki** [comment]
I tested that solution on my own build and yep, seems to work as intended for my purposes!

**Comment by nikclayton** [comment]
Great, thanks.

On the off-chance you're looking for other contribution opportunities, https://github.com/tuskyapp/Tusky/contribute is a list of open issues you might want to check out.A

**Comment by bremensaki** [comment]
Thanks Nik! I do scan through it occasionally, but my actual coding skills are pretty limited. I will jump in anywhere if I can though!

**Comment by nikclayton** [comment]
Thanks. If you do feel like trying any of them and you have questions please do ask, either on the issue (feel free to @ mention me directly) or in https://riot.im/app/#/room/#Tusky:matrix.org.
