### ISSUE TITLE
Show notification fetching mechanism on the About screen

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3950]
The "About" screen now shows useful information when debugging user reports (logged in account, remote server info, device and SDK info, etc).

It would be helpful if it also displayed the method that Tusky was using to fetch notifications. This is either:

- "Pull", because ntfy.sh or similar is not installed and/or Tusky has not registered with it, or
- "Push", probably with some extra information about how Tusky has registered

* * * *
- Tusky Version: 23.0

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
https://github.com/tuskyapp/Tusky/pull/3642 shows the current push distributor - at the moment as "setting".
