### ISSUE TITLE
No longer receiving notifications on app.

### ISSUE THREAD

**Issue by Andre601** [tuskyapp/Tusky#3953]
For unknown reasons do I no longer receive any notifications on my Smartphone, be it follows, favourites, reblogs, etc.

I use ntfy for faster notification receival.

Note that I am using the web-version of the instance too, but I still don't get notifs even while the PC is off/in sleep mode. Coming back to the web version shows me notifications I have not received on my phone.

* * * *
- Tusky Version: 23.0
- Android Version: 10
- Android Device: Samsung Galaxy S9
- Mastodon instance (if applicable): blobfox.coffee

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
maybe related: #3935

**Comment by Andre601** [comment]
Seems like it. Will close this and reply on that issue.
