### ISSUE TITLE
Cannot play any video in Tusky

### ISSUE THREAD

**Issue by frenksisco** [tuskyapp/Tusky#3962]
Any video I try to play in Tusky does not start and reports: "Can't play this video".
Same videos play without any problems on official mastondon site and Fedilab app.

Example of non-reproducible vodeo:
https://mastodon.social/@inkican/110792446056251371

* * * *
- Tusky 23.0
- Android 9
- Moto G6 Plus

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. But I haven't found a solution

**Comment by nikclayton** [comment]
Would you be able to try this in Tusky Nightly, https://github.com/tuskyapp/faq#where-can-i-get-tusky ?

That contains updates to the video player (which will be in the next release). I just tried that video using that code and it worked OK for me.

**Comment by frenksisco** [comment]
With Tusky Nightly the video works perfectly
