### ISSUE TITLE
Home timeline doesn't update and the latest post is from a person I'm following with another account 

### ISSUE THREAD

**Issue by Hund** [tuskyapp/Tusky#3979]
My timeline haven't been updating for a few days now. The last post is from a user that I'm following from my other account (that's added to Tusky as well).

I assume I could reinstall the application to (temporally?) solve this issue as well, but I really don't want to.

* * * *
- Tusky Version: 23.0 (F-Droid)
- Android Version: 13
- Android Device: Google Pixel 7 
- Mastodon instance (if applicable): Fosstodon.org

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I think you will have to reinstall (or clear app data) anyway, once the database is corrupted there is not much else to do. This will probably only get fixed in a way so that it can't happen again, but not that it recovers already corrupted databases.

**Comment by Hund** [comment]
I was able to solve it by removing the account and adding it back again. I don't know why it happened though.

**Comment by connyduck** [comment]
If you have steps to reproduce the bug, please share them, that info could help a lot to fix it.

**Comment by Lakoja** [comment]
I'm closing this then.
If there are more informations, please comment here or add another one.
