### ISSUE TITLE
Support for the custom emoji

### ISSUE THREAD

**Issue by charlag** [tuskyapp/Tusky#398]
Mastodon custom emoji seems to be completed by now and it makes sense to implement them.
There are actually two parts: showing them in timeline and writing them.
I think we should start with showing them in timeline. I think it can be done with `ImageSpan`.
 I may try to do this if I have time but I just want to track it by now. If anyone's going to implement it - please, post it here.

- [x] Show custom emoji in posts
- [x] Add ability to use custom emoji
- [ ] Autocomplete custom emoji

**Comment by Luraktinus** [comment]
need !!!

**Comment by connyduck** [comment]
Emojikeyboard coming in Tusky 1.6!
