### ISSUE TITLE
Posts never show stats

### ISSUE THREAD

**Issue by mattvenn** [tuskyapp/Tusky#3994]
I have hide stats in wellbeing settings turned off, but I never see stats on posts untill I expand them. Then I see number of boosts etc.

* * * *
- Tusky Version: 23.0
- Android Version: 12
- Android Device: pixel4a
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
This was added in #3413 , and will be available in the next release (or you can try it in a [nightly build](https://github.com/tuskyapp/faq/blob/main/README.md#what-tusky-release-should-i-use))
