### ISSUE TITLE
Add support for new features in Mastodon v 4.2.0

### ISSUE THREAD

**Issue by jahway603** [tuskyapp/Tusky#4030]
Add support for new features in Mastodon v 4.2.0.

Currently if a user is using Tusky 23.0 with a Mastodon instance running the latest v 4.2.0, then the federated timeline will not appear in the Tusky application.

* * * *
- Tusky Version: 23.0
- Android Version: 13
- Android Device: Pixel phone
- Mastodon instance (if applicable): Any instance that has upgraded to the latested Mastodon to v 4.2.0

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I don't think federated timeline is a Mastodon 4.2 feature.

Could you please be more specific what "not appear" means? Is it showing an error screen? No post?

**Comment by jahway603** [comment]
I will better explain.

* In Tusky 23.0, when I'm using a Mastodon account on a server not running the latest version 4.2.0, but instead running an older version, I see 4 icons on the top of the Tusky app screen - which are Home, Notifications, Local, and Federated.

* In Tusky 23.0, when I'm using a Mastodon account on a server which IS running the latest Mastodon version 4.2.0, I still see 4 icons on the top of the app's screen, but one of them is different now. They are Home, Notifications, Local, and Direct messages.

If Tusky 23.0 is used with a Mastodon server running the latest version 4.2.0, then the Federated icon (and the Federated feed) is not offered to the user anymore & is instead replaced with a "Direct message" section in the UI.

**Comment by connyduck** [comment]
Ok thanks for clarifying! I think you just don't know about the possibility to customize tabs in Tusky. Go to Account Preferences -> Tabs and there you can set the tabs up however you want.

**Comment by jahway603** [comment]
Thanks for that info @connyduck, as I was not aware of that functionality. This issue was written as the Federated icon at the top in Tusky changed to "Direct messages" after a server upgraded to Mastodon 4.2.0 -- i.e. Tusky's UI changed without user input or awareness.

**Comment by jahway603** [comment]
Closing. Upgrading a Mastodon server to pre-v4.2.0 to post-v4.2.0 will change headings in Tusky, but these are configurable as per the instructions above from @connyduck.
