### ISSUE TITLE
Feature Request: Code blocks

### ISSUE THREAD

**Issue by marek22k** [tuskyapp/Tusky#4033]
Hello,

sometimes I like to reply to toots with code. To format it correctly (e. g. with monospace) you often use '`' (or three '`' for multi-line code). This can be done in Markdown and Telegram for example. I would like Tusky to recognize such code blocks and display them with monospace for example.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Duplicate of #1840

**Comment by marek22k** [comment]
My feature request is only for Code Blocks and not for Markdown. Therefore this is not a duplicate.
