### ISSUE TITLE
Android notifications posted while in bedtime mode (dark theme) are unreadable in daytime mode (light theme)

### ISSUE THREAD

**Issue by brad2014** [tuskyapp/Tusky#4046]
Apologies if this is covered by #3477, PR #3921.  This issue is specifically about illegible Android notifications (outside the App).

To reproduce: Receive a Tusky notification while in dark theme (e.g. bedtime mode), then view that notification while not in dark mode (e.g. next day).

Expected:  Text is light on dark.
Actual: Text is dark on dark, illegible.

Workaround:  enable dark mode to read the notification.

* * * *
- Tusky Version: 23.0
- Android Version: 13
- Android Device: Pixel 4 XL
- Mastodon instance (if applicable):

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
And this only happens with Tusky notifications? That would be very weird because Tusky does not set any colors on Android notifications. I don't think it is even possible to do so. Sounds like a bug on your device tbh.

**Comment by brad2014** [comment]
I'd assumed it was related to the constant setColor in  

https://github.com/tuskyapp/Tusky/blob/9412ffba0f90f99d849a3de25578b096371d9004/app/src/main/java/com/keylesspalace/tusky/components/notifications/NotificationHelper.java#L338

But I'm having trouble reproducing this.  Let me see if I can get a reproducible case.

**Comment by connyduck** [comment]
That is the accent color (Tusky's blue) not the text color

**Comment by brad2014** [comment]
Yep.  My bad.  This is not a tusky-specific issue.
