### ISSUE TITLE
Show in active apps list

### ISSUE THREAD

**Issue by julianfairfax** [tuskyapp/Tusky#4049]
Feature request: show the app in Android's active apps list. This would indicate to the user that the app is running in the background. This is applicable when the app uses polling for notifications.

* * * *
- Tusky Version: 23.0
- Android Version: 13 (GrapheneOS)
- Android Device: Google Pixel 6a
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
1) What is the active app list?
2) Notification polling in Tusky is not done by permanently running in the background, but by asking the system to periodically wake Tusky up so it can check for notifications.

**Comment by julianfairfax** [comment]
> 1. What is the active app list?
> 
>     2. Notification polling in Tusky is not done by permanently running in the background, but by asking the system to periodically wake Tusky up so it can check for notifications.

1. The active apps list is a list of all apps running in the background on an Android device. It's available on stock Android starting from version 13. You can see what it looks like [in the Android documentation](https://developer.android.com/guide/components/foreground-services#handle-user-initiated-stop).
2. It may not be always running in the background, but it will run periodically in the background. The user should be made aware of that through this list, in my opinion.

**Comment by connyduck** [comment]
I see, learned something new. Looks like this list is for foreground services, Tusky is not using a foreground service to check for notifications. Changing this s a rather large undertaking and I don't think it is worth it.

Tusky is currently using WorkManager for checking notifications, which is the recommended API for these kind of background syncs: https://developer.android.com/guide/background/persistent
