### ISSUE TITLE
Refresh doesn't work

### ISSUE THREAD

**Issue by Vavassor** [tuskyapp/Tusky#405]
> It doesn't do anything visible when I swipe down. Home and Federated seem up update every couple minutes, Local and Notifications are completely stuck.
>
>My profile page shows toots from an hour ago.
>
>here's some logcat, doesnt look like anything useful though https://gist.github.com/MightyPork/4c43dac9da4bb7562d00270f367491b3
>
>—`@MightyPork@dev.glitch.social` ([original post here](https://dev.glitch.social/@MightyPork/98874480282331615))

They also noted that clearing app data and cache doesn't affect the issue. And it's been present for "a few months", so it's not new to version 1.2.0.

This is the only report of this I've heard but worth dropping it here.

**Comment by connyduck** [comment]
@MightyPork is this still an issue?

**Comment by MightyPork** [comment]
no i think it's been long fixed, I switched back from twidere in something like February
