### ISSUE TITLE
Feature request: load media directly from media-blocked instances

### ISSUE THREAD

**Issue by mDuo13** [tuskyapp/Tusky#4054]
## Summary
Sometimes an instance has to media-block a remote instance because of a difference in moderation policies. A convenient workaround would be to allow users to load media directly from the remote instance instead of using the home Mastodon instance's media cache.

## Problem Statement
It's inconvenient to view media when your local instance media-blocks the remote instance. The media shows up with an attachment (paperclip) icon and the description, if there is one, but if it's an image, it doesn't load, and clicking the description takes you to a 404 page for the local instance's media cache.

Typically if you follow a remote user, you know they aren't in the habit of posting content you don't want to see, but this makes it much less convenient to get the view you want of your Following timeline, especially if you follow users from across the Fediverse.

## Example

The instance icosahedron.website media-blocks misskey.io because misskey allows (loli/shota) illustrations that, while legal under Japanese law, are illegal to possess under German law, where Icosahedron's servers are hosted. Even though most users are mainly uploading sfw artworks and photos, and Misskey pretty consistently enforces the use of the NSFW tag for media, there is enough  possibility that illegal content may be cached in Icosahedron's servers makes it a necessary precaution. This poses an inconvenience to users who want to follow Japanese artists, many of whom are on Misskey.io.

## Workarounds

Currently, you can usually see the media by opening the individual post, clicking the top (vertical) ... menu and selecting "Open in browser" to load the post on its original website.

The admin of Icosahedron has [shared a user script workaround](https://icosahedron.website/deck/@halcy/110203661552963470) to load remote media directly from the remote instance in these cases, when using the Mastodon web client.

## Proposed Solution

It would be great to have Tusky pull thumbnails and full-media from the remote instance in cases where it's media-blocked. This could be either by default or as a setting that can be turned on.

Even though this adds some additional load to remote instances (only the media-blocked ones, preferably), it's probably not worse than users clicking through to load the entire remote page to view the same posts.

## Related Screenshots

(Post used for these screenshots: [on icosa](https://icosahedron.website/@swev_r_tk@misskey.io/111197734043532031) | [on misskey](https://misskey.io/notes/9kkl5bzb26) )

[Post with media, as seen on Tusky](https://github.com/tuskyapp/Tusky/assets/7515597/93beaa32-4b79-412f-9c89-cc4d5cec601a)
[Same post with ... menu including "Open in browser" shown](https://github.com/tuskyapp/Tusky/assets/7515597/b990cf8c-e76d-4518-8bc1-d88b47557667)
[Post with media as viewed on Misskey, after clicking through "Open in browser"](https://github.com/tuskyapp/Tusky/assets/7515597/48f8fb44-63ac-46b0-ae98-3b5c97868b4f)
[Post as seen on Mastodon web view with the workaround user script installed](https://github.com/tuskyapp/Tusky/assets/7515597/8113d054-305c-464e-811a-250838d2dc9c)

* * * *
- Tusky Version: 23.0 (and earlier versions)
- Android Version: 13 (but probably any)
- Android Device: Nokia XR-20 (but probably any)
- Mastodon instance (if applicable): as an example, https://icosahedron.website/

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
Tusky isn't adding features that:
- directly/automatically interact with remote instances without user interaction
- circumvent your instance's moderation policies

If you don't agree with your instance's moderation policies, please consider joining a different instance instead of applying workarounds in your clients.
