### ISSUE TITLE
Type a search term, then switch search tabs, the search terms is deleted

### ISSUE THREAD

**Issue by scmbradley** [tuskyapp/Tusky#4059]
Tap search, type in a search term, then tap Accounts or Hashtags, and your search term will disappear. I would prefer the search term to persist across those search tabs. (This isn't specific to the Posts tab, whichever tab you're on, moving to a different tab wipes out your search term).

* * * *
- Tusky Version: 23.0
- Android Version: 13
- Android Device: Fairphone 5
- Mastodon instance (if applicable): mathstodon.xyz

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
fixed by https://github.com/tuskyapp/Tusky/pull/3540
