### ISSUE TITLE
Import TBS 

### ISSUE THREAD

**Issue by SoniEx2** [tuskyapp/Tusky#4067]
You already have blocklists why not import more blocklists?

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by xfix** [comment]
I don't think it would be a good idea. TBS blocklist is, let's say, controversial, there are plenty of issues with it, many of them are documented on https://thegoodspace.neocities.org/.
