### ISSUE TITLE
Opening the trending tab immediately crashes Tusky

### ISSUE THREAD

**Issue by fin-w** [tuskyapp/Tusky#4070]
Depending on the instance I use, when I click on the trending tab, Tusky will either display the trending tabs perfectly, or else display nothing and crash immediately.

The issue occurs on an up-to-date Hometown instance.

I'm happy to do testing if necessary.

* * * *
- Tusky Version: 23.0
- Android Version: 13
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Could it be that there are no trends on the instance where it crashes? Than this is a duplicate of https://github.com/tuskyapp/Tusky/issues/3852 / fixed by https://github.com/tuskyapp/Tusky/pull/3853.

**Comment by fin-w** [comment]
Ah sorry, looks like #3853 was after v23.0 came out, I had assumed it was beforehand! My bad.
