### ISSUE TITLE
Blur image eye button too small/easy to miss-press 

### ISSUE THREAD

**Issue by Fluhzar** [tuskyapp/Tusky#4110]
Roughly a third to half of the times when I want to hit the eye button to blur an image I will instead tap on the image itself, maximizing it. The eye icon is fairly small on my device so it can be pretty easy to miss-press, not sure if that's a function of the resolution/dpi of my device or otherwise, but having the image maximized instead of hidden (basically the opposite behavior than I intended) so often is not great.

Here's a screenshot of an image showing the size of the eye button on my device:
![Screenshot_20231113_102102_Tusky](https://github.com/tuskyapp/Tusky/assets/51805745/0b7a22ee-e8b6-4719-b916-8877064c59e0)

* * * *
- Tusky Version: 23.0
- Android Version: 13 (OneUI 5.1.1)
- Android Device: Samsung Z Flip3
- Mastodon instance (if applicable): N/A

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
The button will look differently with the next release, could you please have a look at a [nightly build](https://github.com/tuskyapp/faq#where-can-i-get-tusky) if that improves the situation?

**Comment by Fluhzar** [comment]
@connyduck that is a big improvement, particularly the border around the eye helps visibility of the button a lot. Obviously I haven't used the nightly build much as I've only just installed it so I know this is highly nitpicking, but I wouldn't mind if the button were a bit larger still, maybe 5% or so. If it stays the same as the current nightky I'll be happy enough though! I'll close this issue as is.
