### ISSUE TITLE
[Feature Request] Share link to own account

### ISSUE THREAD

**Issue by strk** [tuskyapp/Tusky#4120]
This is similar to  #3093 but it is for your own account. I could not find a way to share that one with friends (but neither I find the new menu added by #3120 so maybe I'm just using an old release)

It could go in the top-right menu which currently has a single item in it ("Refresh")

* * * *
- Tusky Version: 23.0
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
You have to go to your own profile (you can do so by clicking your profile image in the menu drawer) and then open the three dot menu there.

**Comment by strk** [comment]
Thanks, it works! I didn't realize clicking on the currently active account would do anything, I thought it was just for switching accounts
