### ISSUE TITLE
Make it possible to correctly translate certain abbreviations in Welsh

### ISSUE THREAD

**Issue by fin-w** [tuskyapp/Tusky#4145]
Some strings that come after numbers don't change in English but do in Welsh. The English source string is a type `string` in the file `strings.xml` so it can't be translated as having more than one form (i.e. plurals) in Weblate for Welsh.

I can see an unrelated source element of type `plurals` that has a single child element, `item quantity="other"`, which can be translated in various ways as a plural in Weblate, so I figure that's how to do the below strings too?

These strings in the source correspond with the Welsh strings that should change depending on the preceding number: 
```
abbreviated_in_years
abbreviated_in_days
abbreviated_in_minutes
abbreviated_years_ago
abbreviated_days_ago
abbreviated_minutes_ago
```

* * * *
- Tusky Version: 24.0

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
> One issue with this proposed change is that after mutation, some words might be confused with each other. Some abbreviations for 'year" would look the same as for "minute", for example. Without mutations it's easier to differentiate the durations, though technically not correct.

@fin-w Ok so do you want this now or not? I openend a PR but it adds quite some code

**Comment by fin-w** [comment]
Thank you for working on this! I believe it should be implemented because it's accurate. Mutations like these are common and understood and expected in Welsh.

**Comment by fin-w** [comment]
I'm really sorry, but I'm having serious doubts about this change, after trying to translate everything in Weblate. While it would be possible to get all mutations accurate, for some durations (years) you would have to expose 5,7,8,9,10 for translation as well, and if we're being very exact, for all numbers above 10 the strings get a bit too long and ugly and start to deviate from the English formatting even more (`11 o f. yn ôl` instead of the current `11b yn ôl` for the English `11y ago`, for example).

It would be possible to translate everything with the further changes to the code outlined above, but at this point the increased code complexity and string lengths is all making this far more involved than it's worth for such a minor change.

Welsh numbers are unfortunately quite complicated and awkward, and here I think it's probably better just to revert your changes and accept that the Welsh translation of Tusky formats these strings in a regular and clear way that is slightly inaccurate.

I'm very sorry for wasting your time!
