### ISSUE TITLE
App force-closes when opening notifications

### ISSUE THREAD

**Issue by Karmalakas** [tuskyapp/Tusky#4158]
I've added a second account, which is on Metapixl (Pixelfed) and when I switch to that account and try to open the notifications tab, the app just closes. 

Android 14 (Pixel 6a)

**Comment by connyduck** [comment]
Sounds like a bad notification. Any chance you can have a look at the json response of the `GET /api/v1/notifications` andpoint?

**Comment by Karmalakas** [comment]
Don't know how to see it on a phone, but on a PC on Metapixl itself for `https://metapixl.com/api/pixelfed/v1/notifications?pg=true` it's:
![image](https://github.com/tuskyapp/Tusky/assets/3602819/923b2f1f-c766-4aae-a0bf-8badc23bde59)

I collapsed some objects to hide identifiable info. If you need it, I can blur out some parts

**Comment by connyduck** [comment]
Ok good. Now we need to find which attribute does not conform to what Tusky expects.
The first weird thing is that `"type":"share"` is not a type used by the Mastodon Api, it seems to be Pixelfed specific. Tusky should just ignore it, but I'll double check.

**Comment by Karmalakas** [comment]
Maybe not ignore, but treat it as a boost?

**Comment by connyduck** [comment]
Ok, no `/api/pixelfed/v1/notifications?pg=true` seems to be a Pixelfed Web specific api. We really need "/api/v1/notifications" which is what apps use.

**Comment by Karmalakas** [comment]
How would I check that?

**Comment by connyduck** [comment]
With an api client like [bruno](https://www.usebruno.com/). You'd have to obtain a bearer token and then make the request. Not sure if I can explain it if you never done something like that.

The crash log from Tusky could also be helpful. You should be able to obtain it [like this](https://support.mozilla.org/en-US/kb/retrieving-a-pocket-crash-log-on-android).

**Comment by Karmalakas** [comment]
I just tried to reproduce a bug and couldn't. Notifications opened as expected. Now I'm thinking, that it's a completely new account and it didn't have any notifications at the time when the app was crashing while trying to open the tab 🤔 Could it be the case, that it crashes if there are no notifications at all?

**Comment by Karmalakas** [comment]
Oh, but wait... There were notifications before too. But now app doesn't show me the oldest ones. It shows only the latest, which are 4 hours or newer 😕

**Comment by Karmalakas** [comment]
OK, I opened filters and there was one checkbox unchecked - "Follow requests". Checked that, tapped "Apply" and only then it loaded all the older notifications (none of which were actual follow requests). Something's really weird happening with notifications 😕

**Comment by Karmalakas** [comment]
Not sure how related this is, since I managed to open that notifications tab for the second account and managed to get a list of all of them after applying the filter, I got all of them as push notifications at once. But... As soon as I clear the notification on the phone, in a few seconds I get again a push for the exact same notification. And this happens over and over. I think I'll have to remove the second account, because currently it's a mess 😞 Will try to remove and add again a bit later and see if that maybe helps

**Comment by Karmalakas** [comment]
Logged out from that second Metapixl account and logged back in. Immediately got a push notification again for the notification, which was read days ago. And again trying to open the notifications tab on the app force-closes it.

Any advice on how to get a bearer token? I know how to make requests

**Comment by connyduck** [comment]
Will be fixed on Pixelfed side

**Comment by Karmalakas** [comment]
Is there an issue I could follow?
