### ISSUE TITLE
disability to use player buttons if media alt text is long

### ISSUE THREAD

**Issue by mokazemi** [tuskyapp/Tusky#4165]
If media alt text (for example an audio and its lyrics) is long, it can cover media player controllers, so it's not possible to use them.

![Screenshot_20231212_083219_Tusky](https://github.com/tuskyapp/Tusky/assets/18334056/bb4ba143-3c2b-4ef7-928c-f0b3e9218b6e)

* * * *
- Tusky Version: 24.0
- Android Version: 13

**Comment by fdmarcin** [comment]
Also present in Tusky 26.1

Device:
- Google Pixel 8
- Android version: 14
- SDK version: 34

Account:
- Version: 4.2.10
