### ISSUE TITLE
there is a problem with rendering characters correctly

### ISSUE THREAD

**Issue by mittwerk** [tuskyapp/Tusky#4175]
![photo_2023-12-15_19-36-37](https://github.com/tuskyapp/Tusky/assets/135833222/4543d3e5-dbde-4d65-818b-724f12c66352)

it would be nice to fix

* * * *
- Tusky Version: 4.2.1 develop
- Android Version: 10
- Android Device: STK-LX1

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Where is that screenshot from?

**Comment by mittwerk** [comment]
from my phone

**Comment by connyduck** [comment]
Ok and where did you click for it to show that? Can you provide a link to a status that reproduces the problem? Or at least the full screenshot?

**Comment by mittwerk** [comment]
Ah, sure
![photo_2023-12-16_10-02-14](https://github.com/tuskyapp/Tusky/assets/135833222/f7259b1e-3ca6-4b8c-b375-caecec85ffe0)
![photo_2023-12-16_10-02-12](https://github.com/tuskyapp/Tusky/assets/135833222/f20e4672-b419-4215-89ce-a6a67ebaddbb)

**Comment by connyduck** [comment]
There is no Tusky version "4.2.1 develop". Do you mean a custom build from current develop or what?

Can reproduce on an Android 10 emulator, will try to fix.

**Comment by mittwerk** [comment]
problem persist

**Comment by mittwerk** [comment]
problem fixed
