### ISSUE TITLE
add copyright notices  in source file headers

### ISSUE THREAD

**Issue by strk** [tuskyapp/Tusky#4188]
The sole presence of a LICENSE file doesn't clarify which license applies to the source code. The recommended way to specify that is via comments in each source file, which is also where you specify if you can also apply a "later version"

**Comment by connyduck** [comment]
We usually do that, did we miss a file?

**Comment by strk** [comment]
I've opened a random one and the header wasn't there: https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt

**Comment by mxmlkzdh** [comment]
I took the liberty of creating a PR for this issue: https://github.com/tuskyapp/Tusky/pull/4190
