### ISSUE TITLE
Can't translate a string, it doesn't even seem to exist in the repository

### ISSUE THREAD

**Issue by fin-w** [tuskyapp/Tusky#4193]
There is an error screen that appears when you delete a post and then click to view the post. The error text is not available to translate on Weblate and does not seem to be in the repo either? It's not in `strings.xml` and doesn't show up when running `grep -r 'Record not found'` on the full repository either.

The error screen appears when a post is deleted on the server, but still exists locally. I can delete the post from Tusky but Tusky doesn't seem to update its database immediately, so even though the post doesn't exist on the server any more, I am still able to click on it within Tusky (until refreshing the view). This is occurring when I delete posts from the search view, it may happen in other places too. When the post is deleted and I try to view it, the image of an elephant with a broken wire, the text "Record not found" and a Try Again button are shown, so I know the text must exist somewhere, and should be translated. However as I have said, I can't find it in the repository and Weblate doesn't have it, which is odd.

Can it be added / made available somehow, to be translated?

* * * *
- Tusky Version: 24.1 beta 1-004659a5
- Android Version: 13

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
That is not a string in the Tusky source code, that is an error message the server sends.
