### ISSUE TITLE
Notifications do not take you to the corresponding account notification tab

### ISSUE THREAD

**Issue by strk** [tuskyapp/Tusky#4203]
Tapping on a notification takes you to the notification tab of an account which is not always the one to which the notification belongs. Having multiple accounts this is very frustrating as you basically loose the notification, not finding it after it is cleared due to tapping on it.

**Comment by strk** [comment]
Frustration rant (not really useful here but I thought I'd mention): https://mapstodon.space/@strk/111681079672835798

**Comment by strk** [comment]
My experience was with Tusky 24.0 on Android version: 11 with SDK version: 30

**Comment by connyduck** [comment]
Can not reproduce. Tried with 4 accounts and multiple notifications, I always end up at the right notifications tab. 
How often would you say this bug occurs? Almost always? Or more like every tenth time?
Is it maybe a special type of notification where the bug occurs?
Have you changed the order of tabs in some accounts?
Anything else that could be special about your setup?

**Comment by strk** [comment]
I've just tried again, with Tusky 24.1 and things seem to work fine. Must have been fixed. Thanks !
