### ISSUE TITLE
Tusky fails to update via Google Play

### ISSUE THREAD

**Issue by bt90** [tuskyapp/Tusky#4206]
![grafik](https://github.com/tuskyapp/Tusky/assets/1926175/603bd20d-7c54-4a33-9213-b0593fa6a11d)

The issue is most likely caused by drawables which are larger than 200×200 or which contain vector paths with over 800 characters.

Related:

* https://github.com/syncthing/syncthing-android/issues/2026
* https://github.com/uazo/cromite/issues/595
* https://discuss.grapheneos.org/d/9645-javalangruntimeexception-could-not-copy-bitmap-to-parcel-blob

* * * *
- Tusky Version: latest
- Android Version: 14 (Stock Android, no custom firmware etc)
- Android Device: Pixel 4a 5G

**Comment by bt90** [comment]
I was a little too quick with my assumption. It seems to be just a conflict between Google Play and F-Droid. Version 24.1 is installed correctly and, according to Droidi-fy, is up to date.

**Comment by licaon-kter** [comment]
:-1: https://forum.f-droid.org/t/google-play-store-tries-to-update-my-f-droid-apps/24621
