### ISSUE TITLE
Tablet optimization

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#421]
Thats a huge Tasks. But I think it should be done eventually so Tusky is really awesome on all devices.

**Comment by connyduck** [comment]
I now have a tablet, and Tusky already is already really awesome, but some improvements can definitely be made.

**Comment by trwnh** [comment]
Easiest approach would be to use 2 columns in portrait and 3 columns in landscape -- this is a common pattern for columned apps and works well in e.g. Twidere or Plume for Twitter.

Toot compose window can be made into a popup like Twidere / Plume as well, with an account selector.

Those are the two most obvious improvements to me
