### ISSUE TITLE
Integrated password code

### ISSUE THREAD

**Issue by issueseverywhere** [tuskyapp/Tusky#423]
I really like Tusky but the whole process of having to disconnect and then reconnect to the instance takes some time, if you just want to leave your phone somewhere for a moment (or hand it to a friend so he can use it for a moment, to read his emails, use a game on your phone or see some pictures you took).

Signal has an integrated password/lock code that is very easy to use, from the notification bar and inside the app.

Is it possible to integrate such a password lock in Tusky (even if it is inside the app interface, without the notification bar option)?

**Comment by kyrias** [comment]
This is the type of things that the Android Guest Mode is meant for, which switches to a completely new user with none of your regular user data available.
