### ISSUE TITLE
Custom Emoji sometimes invisible in profile view

### ISSUE THREAD

**Issue by dantescanline** [tuskyapp/Tusky#4231]
When viewing my profile often the custom emoji do not show up in the bio on first load. Reloading the view often makes them come back, but it's inconsistent. I haven't noticed other problems with displaying these custom emoji elsewhere in the app.

Example video: I go to my profile and reload it several times by pulling down. Each time it's reloaded it has a chance to show custom emoji in the bio. The only custom emoji that is always present is one that's also in my display name.
https://github.com/tuskyapp/Tusky/assets/100843019/ad6c3487-5359-4e15-8c36-8c7254087297

* * * *
Tusky 24.1

Device:
OnePlus DN2103
Android version: 13
SDK version: 33

Account:
@dantescanline@autonomous.zone
Version: 4.2.3

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Seems similar to https://github.com/tuskyapp/Tusky/issues/3330

**Comment by dantescanline** [comment]
Ahh good call. For reference autonomous.zone is currently running Mastodon v4.2.3 on managed hosting.
