### ISSUE TITLE
App crashes when sending Toot

### ISSUE THREAD

**Issue by jeyemwey** [tuskyapp/Tusky#4288]
### Detailed description

Whenever I want to send out a toot, after hitting "TOOT!", the app crashes. Android shows the "Your app has been stopped repeatedly" dialog.

The issue happens on various accounts on chaos.social (I have not tried with any other instance), both on Original Toots and on Replies. It is not necessary to post any additional media such as CN or attachments.

I'm using Tusky Test:

```
Tusky Test 24.1-166e5ac2

Device:

Google Pixel 4a (5G)
Android version: 14
SDK version: 34

Account:

@jannik@chaos.social
Version: 4.2.8
```

### Steps to reproduce the problem

1. Open Tusky.
2. Compose a toot.
3. Hit Send button.
4. Find yourself on the homescreen.

### Debug information

Tusky Test 24.1-166e5ac2, Android version: 14, SDK version: 34, Mastodon Instance Version: 4.2.8

**Comment by connyduck** [comment]
fixed by https://github.com/tuskyapp/Tusky/pull/4274
