### ISSUE TITLE
Posts that have gif & plain images attached are rendered wrong

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#429]
example https://mastodon.at/@ConnyDuck/98916936658539530

![screenshot_20171030-094316](https://user-images.githubusercontent.com/10157047/32161909-8027486c-bd57-11e7-970b-0349a9f723c6.png)

apparently tusky does not account for the case where one status has attachments of multiple types

Also ViewMediaActivity & ViewVideoActivity should be merged into one that can handle media items of any kind

**Comment by charlag** [comment]
Should I get crazy and make an ImageView which can draw this play symbol on top or we will just use nested views for that? That's a timeline so the latter can be quite expensive

**Comment by Miklostibi** [comment]
@charlag coudn't we just create a shape or layer list with constant width-height and set it as foreground? ImageView already has that attribute and as I've seen media/video preview height is constant anyways

**Comment by charlag** [comment]
@Miklostibi oh, that's nice idea! Does it work on all versions of Android? I hope it does with AppCompat.

**Comment by charlag** [comment]
@Miklostibi actually it may not be constant in the future. AFAIK there are some plans to not cut previews if there is only one of them, at least in the web (or I am mistaken and that's just what ppl from mastodon.art wanted)

**Comment by Miklostibi** [comment]
@charlag doing a quick check now and if we end up modifying the constant size of the image then we'll have to implement a custom ImageView witch would handle the placement of the icon pre and post displaying of the image, or we could add it to the clauses of Picasso Target() wich has onBitmapLoaded(..), onBitmapFailed(..), onPrepareLoad(..)
altough we have to be careful with these because of memory management of the bitmaps...

**Comment by charlag** [comment]
@Miklostibi we cannot control vector size on old API versions, right? I had a similar problem when background vector which was centered on some versions was stretched on others.
Probably custom ImageView is the cheapest, generating more bitmaps is very undesirable.

**Comment by connyduck** [comment]
Partly fixed in #445 - timeline now handles the mixed attachments correctly, still need to improve what happens after openening attachments

**Comment by connyduck** [comment]
fixed in #866
