### ISSUE TITLE
Image visibility resets when refreshing timeline 

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#4317]
### Detailed description

Reported here https://chaos.social/@Arona1984@dresden.network/112052893511152666

### Steps to reproduce the problem

1. Have a post with image attachment in the first few posts on your timeline.
2. Change the image visibility
3. Refresh the timeline
4. Notice how the image visibility changed back

### Debug information

Tusky Test 24.1-fbb22799, mastodon.social

**Comment by charlag** [comment]
probably translation changes?

is this part stored in db?

**Comment by connyduck** [comment]
No, can't be translation chnges because it was reported before we merged that.
Yes it is stored in the database, but updated incorrectly when refreshing.
