### ISSUE TITLE
Side Menu in app slow when rendering

### ISSUE THREAD

**Issue by mitchellurgero** [tuskyapp/Tusky#433]
As the title suggests on some phones when attempting to render the side menu, it causes the app to slow to a crawl. I have no way to debug it right now, but just wanted to document it.

**Comment by charlag** [comment]
Thanks for reporting.
It hink side menu is rendered at all times, it is just offscreen. If it's the launch then I experience some lag when profile pic, profile background and toots are all appear at the same time but everything is fine afterwards.

**Comment by charlag** [comment]
Now I'm not sure I experience it at all. There's some sluggishness in the first second or so but it's mot about the menu - it is the whole app loading.
I am not sure what to do about it now so I would close it if there are no suggestions.

**Comment by mitchellurgero** [comment]
I just removed my background image in my Mastodon profile and the loading issue is no longer a problem, so big background images in the profile cause rendering to lag heavily.

**Comment by charlag** [comment]
@mitchellurgero  A-ha, that's something, I knew it was something with images/Picasso.
Can you give me a hint about background size please? And phone model could be nice too.

**Comment by mitchellurgero** [comment]
The image I had before was something like 8000x6000 (or something like that?) but the file size was ~8MB.

**Comment by charlag** [comment]
@mitchellurgero thanks, I will try to reproduce it
