### ISSUE TITLE
Crash when selecting Akkoma account

### ISSUE THREAD

**Issue by kvibber** [tuskyapp/Tusky#4393]
I added my Akkomane.social account to Tusky a few days ago and was able to interact with it fine, at least in terms of basic features. But today I tried to switch to it and the app crashed immediately. Relaunching the app crashed immediately as well. Clearing the cache and restarting the app hasn't made a difference.

I was able to switch to another account by Long-pressing the Tusky icon.

I don't remember exactly when I successfully added the crashing account, but it was probably before the phone updated to the beta.

Tusky 25.0 beta 1

Device:

Google Pixel 5
Android version: 14
SDK version: 34

**Comment by connyduck** [comment]
I can't reproduce a hard crash, but on my akkoma account all timelines show an error 🤔

**Comment by connyduck** [comment]
Oh when I log in with 24.1 and then upgrade to 25.0-beta1 it crashes. Will fix, thanks for reporting!
