### ISSUE TITLE
Scheduled post spam

### ISSUE THREAD

**Issue by mymsy** [tuskyapp/Tusky#4405]
### Detailed description

Scheduled a post for while I was asleep, woke up to find it had posted repeatedly (approx. 20 times) until getting cut off by the server rate limiting me ("upload failed" message) 

### Steps to reproduce the problem

Did not attempt to reproduce, would be rude to my followers

### Debug information

Tusky 25.0 beta 1

Device:

samsung SM-G973U
Android version: 12
SDK version: 31

Account:

@mym@toot.cat
Version: 4.3.0-alpha.3+glitch

**Comment by mymsy** [comment]
Screenshot courtesy of a follower
![e028bcbd79ad3897](https://github.com/tuskyapp/Tusky/assets/7102990/1b90ead4-870c-476b-aec1-c5e47b8f3154)

**Comment by connyduck** [comment]
fixed by https://github.com/tuskyapp/Tusky/pull/4392
