### ISSUE TITLE
Improve UX by adding more feedback for the user

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#442]
I see three areas where we can easily improve user experience:

- remove empty callbacks ( for example in SFragment). Blocking Users and similar actions should result in an success or error displayed in a snackbar. Ideally the snackbar contains a button to undo or retry the action. Just removing toots from timelines and ignoring the api call is really bad.

- never display empty fragments or activities. All should have a ProgressBar or other activity indicator. If nothing was loaded display a nice message to the user. Improve the current "no content" messages with more specific information. AccountMediaFragment currently shows no progress on first load and no message when empty.

- when a timelime fails to load, display a retry button and not just keep ProgressBars running. Users should know if there was an error or if the timeline is still loading.

**Comment by connyduck** [comment]
Also, all touchable areas should have some sort of visible feedback when touched, e.g. a ripple background.

I am adding this issue to the next milestone, because it will not be completely done for this one (it probably never will, but lets always have an eye on it)

**Comment by flyingrub** [comment]
One little thing too : When there is no network (for exemple in airplane mode) we should perhaps display a message that tusky need an internet connection to work ?

**Comment by connyduck** [comment]
Yes I plan to implement an error view that displays an message like "An error occured, please check your internet connection" & a retry button. Pretty much how the twitter app does it. For now it would be enough if we have it for TimelineFragment and NotificationFragment, but the goal is to implement it for every fragment. 
If you want you can do this :)

**Comment by charlag** [comment]
Related #1000
