### ISSUE TITLE
Add the ability to pin/unpin statuses, show pinned statuses in profiles

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#443]

**Comment by charlag** [comment]
I've checked and API sends pinned toots first anyway. Good to know.

**Comment by charlag** [comment]
I want to show pinned statuses pretty badly but I think we should wait for #562 to be merged because it makes some changes to the timeline.
Heck, this pinned statuses thing can add quite a lot of complexity.

**Comment by wxl** [comment]
It looks like pin/unpin is now an option; what about viewing the pins?

**Comment by charlag** [comment]
We somehow have support for pinned statuses thanks to #994 so I think this should be closed?
We should improve it in the future and remove that tab but it can be another issue.
