### ISSUE TITLE
Can only delete draft on reopening

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#4434]
### Detailed description

1. Compose toot
2. Close and save as draft
3. Open the draft
4. Close that again

A dialog appears which only allows to "Continue editing" and "Delete". So you can either leave and delete or send the toot.

**Expected**: Without a change to the toot content there should be no dialog on quitting.
With a change the dialog should be "Discard changes" or "Update draft".

### Debug information

...

**Comment by texttheater** [comment]
+1. I cannot comprehend what could possibly have prompted anyone to implement this change. It was working perfectly before. Now we get the same broken behavior that Twitter used to have.
