### ISSUE TITLE
Tusky has two app bars, one of them overlapping the side drawer

### ISSUE THREAD

**Issue by Sirs0ri** [tuskyapp/Tusky#4446]
### Detailed description

Since the latest test version, Tusky has gotten an extra header bar that just says "Tusky test", and which even overlaps the side drawer. It shows up in addition to the usual to bar that has my account info, what feed I'm on, the search button, etc.

It only shows up on the "main page" of the app, and stays visible when navigating through the different timelines through the bottom navigation. It does not show up when navigating away from the main page through the side drawer.

Screenshots: 

![Screenshot_20240513_123433_Tusky Test](https://github.com/tuskyapp/Tusky/assets/6765536/43fa1c41-395d-4c9e-8a15-365f3049316c)
![Screenshot_20240513_123425_Tusky Test](https://github.com/tuskyapp/Tusky/assets/6765536/f68e0d48-1e80-4dbf-9461-4a4ed0e9a3e8)

### Steps to reproduce the problem

1. Open the app

### Debug information

Tusky Test 25.2-45d36a6a

Device:

samsung SM-G970F 
Android-Version: 12 
SDK-Version: 31

Account:

@Sirs0ri@corteximplant.com 
Version: 4.3.0-alpha.3+glitch.cortex

@Sirs0ri@nightcity.bar 
Version: 4.2.1 (compatible; Iceshrimp 2023.12.7)

**Comment by connyduck** [comment]
Seems like this is still an issue @cbeyls.
I tested this change with a sdk 29 emulator where this happened as well, after upgrading the splashscreen to 1.2.0-alpha01 it was fine. It is also fine with my sdk 33 Fairphone, but I can now reproduce it on an sdk 31 emulator even with 1.2.0-alpha01.

**Comment by cbeyls** [comment]
Ouch, I'll try to find a workaround, otherwise I'll have to disable the splash screen library.

**Comment by Sirs0ri** [comment]
can confirm that with the latest beta everything's back to normal, thanks for the quick fix! <3
