### ISSUE TITLE
Updating List members show all users as bots

### ISSUE THREAD

**Issue by aurorasmiles** [tuskyapp/Tusky#4455]
### Detailed description

When viewing or updating members of a list all accounts are shown as having the bot badge, even though they don't have it.
![grafik](https://github.com/tuskyapp/Tusky/assets/21148213/f1591ea6-4f1f-4505-a3c3-bad376de30fe)
![grafik](https://github.com/tuskyapp/Tusky/assets/21148213/18e65a46-d338-4e84-9c1c-37f1229b987c)

### Steps to reproduce the problem

1. Create a list
2. Add members

### Debug information

Tusky 25.2

Device:

samsung SM-G975F
Android version: 12
SDK version: 31

Account:

@aurora@toot.queer-lexikon.net
Version: 4.2.8

**Comment by Tak** [comment]
👀
