### ISSUE TITLE
Followed Hashtags UI needs an UX overhaul

### ISSUE THREAD

**Issue by igalic** [tuskyapp/Tusky#4459]
### Detailed description

Right now this UI only offers only two things:

- delete a followed hashtag (with an unintuitive looking button that looks like  this: ×👤)
- add a new one

Things i would expect from this UI:

- click on a hashtag to view the current stream
- long press on a hashtag to copy it

### Debug information

Tusky 25.2

Device:

OnePlus IV2201
Android version: 13
SDK version: 33

Account:

@meena@glitch.social
Version: 4.3.0-alpha.3

**Comment by Tak** [comment]
This was completed in https://github.com/tuskyapp/Tusky/pull/4475
