### ISSUE TITLE
Webfinger @demo@seppo.social not found

### ISSUE THREAD

**Issue by mro** [tuskyapp/Tusky#4488]
### Detailed description

when searching @demo@seppo.social no results are given despite being a valid webfinger and activitypub actor.

### Steps to reproduce the problem

1. enter @demo@seppo.social  in the search

### Debug information

not known as it is a 3rd party report to https://seppo.social/issues/14

**Comment by mro** [comment]
I guess you require the mastodon API - what parts do you need? Are the conformance levels?

**Comment by connyduck** [comment]
From where are you searching?

From a Mastodon server -> Most probably not a Tusky bug, that profile just doesn't federate, the server is blocked, etc...

From some other server -> We don't support those, especially if they are experimental like this seppo.social seems to be


> I guess you require the mastodon API - what parts do you need? Are the conformance levels?

Yes, Tusky only works with servers that support the Mastodon Api. Almost all of it, or parts of the app won't work. The list of endpoints we use is [here](https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt).

**Comment by mro** [comment]
thanks for the endpoint list, that's a bunch of URLs. Today none are implemented by the backend, so let's close this issue.

Thanks @connyduck!
