### ISSUE TITLE
The transition from "view post in thread" to "view error message about post edits not being found" has no background colour (?)

### ISSUE THREAD

**Issue by fin-w** [tuskyapp/Tusky#4489]
### Detailed description

Clicking to view the edits on a post, when the edits are not found on the server, causes an error message to be displayed. Something along the lines of "your server knows this post was edited but doesn't have a copy of the edits, this is a mastodon issue".

The transition from "view post" to "view error message about edits" shows this briefly before the "view post" text disappears, it appears like the transition phase has no background colour (idk how Android apps work or if that's what's really going on, that's just what I see). After showing the below during the transition, the screen looks normal again.

It seems the issue also appears when viewing the edits on a post (the new profile info doesn't properly get replaced / draws over the original profile info). The error message has a far more obvious issue but both transitions seem problematic.
![Screenshot_20240603-171121_Tusky Test](https://github.com/tuskyapp/Tusky/assets/41450706/42d288cb-7f54-40ef-a361-163992517d39)

### Steps to reproduce the problem

1. Find a post with edits where the edits are not cached on your server (for me it was https://en.osm.town/@openstreetmap/111998377064974485)
2. Open the post / thread
3. Try to view the edits and observe the app's transition

### Debug information

Tusky Test 25.2-8aaca3bb

Device:
motorola moto g(7) power 
Fersiwn Android: 14 
Fersiwn SDK: 34

**Comment by connyduck** [comment]
Ok that one is lowkey hilarious. Thanks for reporting!
