### ISSUE TITLE
filters do not work for gotosocial

### ISSUE THREAD

**Issue by nikkicoon** [tuskyapp/Tusky#4499]
### Detailed description

Gotosocial merged support for filters in March: https://github.com/superseriousbusiness/gotosocial/issues/1472
Using tusky in the latest available version in the playstore and in f-droid, the "filter" function fails to load at all.

If I could provide any more information (on Android), instruct me how to do so.

### Debug information

Tusky 25.2
Android 11 SDK 30
Xiaomi Redmi Note 8T
raum.klang.is gotosocial 0.15.0+git-15733cd

**Comment by connyduck** [comment]
On my goblin.technology account it seems fine 🤔 
GoToSocial 0.15.1-SNAPSHOT+git-b371c2d / Tusky Test 25.2-c6f8588d

What is "fails to load at all"? Do you see an error screen? Or loading forever? Which filters do you have set?

**Comment by nikkicoon** [comment]
so when I go to "profile settings" (I assume that's what it translates to, the GUI is in German here), click "Filter", I get:

"Ein Fehler ist aufgetreten"

I'll follow-up with what I find on the server itself

**Comment by nikkicoon** [comment]
```
redacted - - [06/Jun/2024:21:30:08 +0200] "GET /api/v2/filters HTTP/2.0" 404 21 "-" "Tusky/25.2 Android/11 OkHttp/4.12.0"
redacted - - [06/Jun/2024:21:30:08 +0200] "GET /api/v1/filters HTTP/2.0" 200 26 "-" "Tusky/25.2 Android/11 OkHttp/4.12.0"
```

**Comment by connyduck** [comment]
Thank you, this is helpful!

So GTS 15.0 supports only filters v1, while the upcoming GTS will also support v2. 
Now Tusky should try v2 first and fall back to v1 if that returns 404, but apparently that is buggy. Thanks for reporting, will fix.

**Comment by nikkicoon** [comment]
Thanks!

None at all, since I've only notice now that this landed in gotosocial and use no other client.
