### ISSUE TITLE
Sharing image to Tusky seems to leave behind residual broken post composition area?

### ISSUE THREAD

**Issue by fin-w** [tuskyapp/Tusky#4517]
### Detailed description

After sending a post with an image that has been shared to Tusky from another app, Tusky exits and returns you to the app that shared the image. Tusky retains some kind of existence in the recent apps view in Android though: I'm not sure if this is Android behaviour or whether Tusky isn't exiting cleanly, but I thought it was worth pointing out. There's still an entry in the recent apps for Tusky but you can't click it to open Tusky.

I seem to remember that some time ago, clicking this entry would re-upload the shared image and start a new post if you'd already sent the first post with a shared image? Perhaps this part of the code was changed since then? The current behaviour is odd / unexpected, regardless.

### Steps to reproduce the problem

1. Open e.g. the photo gallery on your phone
2. Share a photo from there to Tusky. Tusky opens the post composition area and the image is uploaded
3. Send the post. For me, Tusky exits and I am returned to the gallery
4. View currently open apps in Android. The Tusky post composition area remains open in the app previews, but clicking on it opens nothing and Android says "app not available"

### Debug information

Tusky Test 25.2-125483db (but this has been happening for a while)

**Comment by connyduck** [comment]
For me it restarts the sharing process, weird indeed. I think I can fix that.
Which Android are you on?

**Comment by fin-w** [comment]
I use Android 14 and Lawnchair as the launcher. I'm not sure what handles the recent apps view but I do remember on Android 12, I think (assuming no changes to Tusky's behaviour regarding this, in the last couple of years), the image share would restart like you say?

**Comment by fin-w** [comment]
checking the latest version of tusky nightly (25.2-f5ad3994), when the app is not open and then an image is shared to it, for me the app still exists in recent apps and says "not available" when clicked like i described before. if the app is already open and then something is shared to it, clicking it in recents after uploading opens the app as though it was fully restarted, and opens the timelines i.e. not the post creation view

**Comment by connyduck** [comment]
>  when the app is not open and then an image is shared to it, for me the app still exists in recent apps and says "not available" when clicked like i described before

this should be fixed by  #4521 

> clicking it in recents after uploading opens the app as though it was fully restarted

I think this is accepteable behavior
