### ISSUE TITLE
Home tab: Mute then unmute a conversation -> blank timeline

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#4523]
### Detailed description

Open up Tusky. Scroll to the top of the Home tab. Make a post, so that the top post on your Home tab is a post by you. Tap ⋯ on this top post. Tap "Mute conversation". Tap "⋯" again. Tap "unmute conversation".

You will see this:

![Screenshot_20240619-125828](https://github.com/tuskyapp/Tusky/assets/277318/605484d1-fe26-4d19-a1b6-ad43df715bda)

The timeline will just be gone. Dragging down to refresh will make it come back.

### Steps to reproduce the problem

I discovered this by accident. Note that in my testing this ONLY happens on the Home tab, it ONLY happens for the top post, and it ONLY happens if the top post is "mute conversation"able (IE by you or a reply to you).

### Debug information

I tested this with a self-built ae12ba4d84f0 (color_improvements branch)
I have not tested with a shipping Tusky.

**Comment by connyduck** [comment]
Can partially reproduce on current nightly: For me it flickers for a second and then the timeline comes back by itself.

**Comment by mcclure** [comment]
> Can partially reproduce on current nightly: For me it flickers for a second and then the timeline comes back by itself.

Earlier, I reproduced this several times in a row.

I am now testing it and finding that on [i]each[/i] mute/unmute operation (whether it is the first "mute" or the following "unmute"), I get one of the following four, seemingly at random:

1. Flickers for a split second, timeline comes back (fine; could be improved, but arguably not a bug)
2. Flickers for a half second, elephant is briefly visible, timeline comes back (could be improved, but arguably not a bug)
3. Timeline goes to elephant, stays there until I pull down to reload.
4. Flickers for a split second, timeline comes back *but the first "page" of results is missing*, and stays missing until I pull down to reload.

I now usually get [1] or [2], but if I repeat the test enough times I eventually get [3] or [4].

I *think* (?????) I get [3] more often on my main account where the timeline moves quickly than on my test account where I can only get [4].
