### ISSUE TITLE
Notifications tab: "Mute conversation" doesn't act "modal"

### ISSUE THREAD

**Issue by mcclure** [tuskyapp/Tusky#4524]
### Detailed description

Go into the notifications tab. Go to the first mention/reply. Tap ⋯. Tap "Mute conversation". Tap ⋯ again.

Expected behavior: After tapping "Mute conversation", the menu item should change to "Unmute conversation", to indicate that the conversation is now muted and the next act will unmute it. 

Observed behavior: The menu item still says "Mute conversation". If you somehow cause the tab to refresh (for example, tap the toot, then tap "back") then the menu item will correctly change to "Unmute conversation", but this will not occur automatically.

(The reverse also applies: If you tap "unmute conversation", the menu will not change to indicate the updated state.)

### Steps to reproduce the problem

-

### Debug information

I tested this with a self-built ae12ba4d84f0 (color_improvements branch)
I have not tested with a shipping Tusky.

**Comment by connyduck** [comment]
Nice find, can reproduce on current nightly
