### ISSUE TITLE
26 Beta 1 crashes when attempting to load notifications

### ISSUE THREAD

**Issue by AutumnRivers** [tuskyapp/Tusky#4548]
### Detailed description

Tusky 26.0 Beta 1 consistently crashes when attempting to load notifications on my wetdry.world account. This also prevents me from viewing the live feed or my direct messages, as Tusky goes over the notification tab to get to these. The app does not crash on my mozilla.social account. My guess is that Tusky is *now* having trouble with unsupported notifications, such as reactions, to the point where it crashes.

### Steps to reproduce the problem

1. Log onto an account on an instance where reactions are supported
2. Have someone react to your post
3. Attempting to load the notifications tab will crash the app

### Debug information

Tusky 26.0 beta 1

Device:

Google Pixel 7
Android version: 14
SDK version: 34

Account:

@ohanamatsumae@wetdry.world
Version: 4.3.0-alpha.5+chuckya

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/4546
