### ISSUE TITLE
Tusky on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [tuskyapp/Tusky#4552]
Hey,

I'm running a repo for Android open source apps at https://www.openapk.net and I would like to have Tusky listed in the repo. Please review the listing at https://www.openapk.net/tusky/com.keylesspalace.tusky/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by connyduck** [comment]
Sure, we don't mind Tusky being available from other sources but I don't think we want to actively link to OpenAPK
