### ISSUE TITLE
Old posts from other account shown on timeline, before posts from correct account.

### ISSUE THREAD

**Issue by NoraCodes** [tuskyapp/Tusky#4554]
### Detailed description

I have several accounts (let's call them A, B, C ... F) in Tusky on Android. Several of these are on Mastodon servers, and others are on GoToSocial servers. One of those GoToSocial servers, constellation.home.nora.codes, has extremely limited federation; the posts on that instance should exist on 2 other servers, exclusively (mutual federation, but none of us federate anywhere else). Let's call that account F.

However, sometimes when I add accounts to Tusky, some other accounts - say, B and D - show 30 - 32 old (May of this year) posts from that instance in their home timeline. Refreshing and clearing cache do nothing; logging out of F does nothing; logging out of B and D and back in *sometimes* fixes the issue. Reinstalling the app sometimes fixes the issue. Scrolling down shows posts from B or D's timeline below the 30 errant posts.

There is no way the instances for accounts B and D have any knowledge of posts from constellation.home.nora.codes, so I think this is purely a client issue.

### Debug information

Google Pixel 6a
Android version: 13
SDK version: 33
Tusky 25.2 (but has been happening since months ago)
constellation.home.nora.codes (GoToSocial) and types.pl (Mastodon)

**Comment by NoraCodes** [comment]
Possibly related to https://github.com/tuskyapp/Tusky/issues/4402 but somewhat different symptoms

**Comment by NoraCodes** [comment]
I'm excited to see a PR fixing this! Thank you so much. 

In the meantime,  is there any workaround so I can continue using Tusky without this issue? It's started happening on notifications, too, which makes them pretty hard to use'l.

**Comment by connyduck** [comment]
> In the meantime, is there any workaround so I can continue using Tusky without this issue? It's started happening on notifications, too, which makes them pretty hard to use.

For notifications, it helps to change the filters. For the timeline you need to log out and in again, I think.
