### ISSUE TITLE
Reply privacy setting always defaults to "Unlisted"

### ISSUE THREAD

**Issue by bremensaki** [tuskyapp/Tusky#4555]
### Detailed description

In #4496 a new client-side setting for reply privacy, defaulting to "unlisted" was added. This is a bad default for a new option that has not existed before. People with post privacy set to a more restrictive default have made visible replies and not known why, and had to go digging for a new option in Account settings.

The default for this preference should be "Use post privacy settings". Not to copy the setting on first use, but to always track it - unless the user seeks out this new (and non-standard for Mastodon and derivatives) setting, knowing that they want this behaviour.

### Steps to reproduce the problem

To reproduce, have a post privacy setting of "Followers Only" in Mastodon, update to Tusky 26 and reply to a public post.

### Debug information

Tusky 26.0 beta 1

**Comment by Archenoth** [comment]
Oh yeah! I also ran into this, since I mainly only look at post visibility to limit it; not broaden it

It took me trying to debug why my replies to bridged accounts were methodically being forwarded into a black hole to realize that it was because they were unlisted
