### ISSUE TITLE
I cannot enter  pixelfed.uno

### ISSUE THREAD

**Issue by lichingyun** [tuskyapp/Tusky#4557]
### Detailed description

I cannot enter in pixelfed.uno (the italian instance of Pixelfed)
From the "choice instance" page of Tusky I go to the login page of pixelfed.uno, I fill the form with my data and Tusky go back to the " choice instance" with the message " The login page could not be loaded" (in the picture is write in italian". . With Tusky I can login to different Pixelfed instances without problems ( e.g. pixelfed.eu, pixelfed.social)

![Screenshot_2024-07-10-08-57-30-51_c38dddb2ed334becc5defa8615851593](https://github.com/tuskyapp/Tusky/assets/79099214/7dc832bf-bd89-4b18-938d-bd8264908248)

### Steps to reproduce the problem

1.open Tusky
2.write the name of the instance (pixelfed.uno) in the "choice instance name" page
3.write my username and password in the pixelfed.uno login page
4. Tusky go back to the "choice instance name" with an error message ( The login page could not be loaded)
5. With Tusky I can login to different Pixelfed instances without problems ( e.g. pixelfed.eu, pixelfed.social)

### Debug information

Tusky 26.0

Device:

OnePlus DN2103 
Versione Android: 13 
Versione SDK: 33

Account:

@lichingyun@mastodon.uno 
Versione: 4.2.10

**Comment by Tak** [comment]
Hi, have you also tried the "Login with Browser" option from the three-dots menu?

**Comment by lichingyun** [comment]
no, I try now, thanks for the tips 🙏

**Comment by lichingyun** [comment]
using Firefox for Android I can enter in pixelfed.uno
![Screenshot_2024-07-10-11-02-30-91_3aea4af51f236e4932235fdada7d1643](https://github.com/tuskyapp/Tusky/assets/79099214/a9bce6dc-ccfd-4829-bfcb-0431c0033239)

**Comment by lichingyun** [comment]
Sorry, I forget to close this issue.
The problem to login in pixelfed.uno is because the server provider don't work well. The admin change server provider and now all is ok 🙏

**Comment by maninthemiddle01** [comment]
I have the same issue with the instance [polylux.xyz](https://polylux.xyz). Also logging on with browser brings me back to the screen, where I can select the server (with out without the error message)

**Comment by connyduck** [comment]
Ok I can reproduce. polylux.xyz sends HTML as an API response (on the `api/v1/accounts/verify_credentials` endpoint), preventing the login. Could be a general Pixelfed problem or something specific to polylux.xyz, but definitely not a Tusky problem.

**Comment by maninthemiddle01** [comment]
Ok, then I can ask there to shed some light on the subject ;)
