### ISSUE TITLE
Tusky 26: Repeated force-close in notifications view (Friendica)

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#4563]
### Detailed description

Unsure how to completely reproduce or describe this: Been using Tusky with Friendica quite reliably for white a while now, but with the 26 (Google Play) release this has turned pretty unstable. Observations:

- Notifications don't seem to appear or be loaded anymore at all.
- Opening the notification tab does display "something" but this doesn't seem to be up-to-date most of the time.
- Trying to refresh notifications will make the app crash / force-close.

What other information can I provide to track this down...?

### Debug information

Tusky 26 (Google Play build)
Android 12
loma.ml instance (Friendica 2024.06rc)

**Comment by connyduck** [comment]
What kind of notifications do you have? Any that are very unusual / friendica specific? I tried reproducing this on my opensocial.at account with a bunch of mentions and likes and it works just fine.

**Comment by kr428** [comment]
To be honest: I'm not sure. Just the "usual stuff" I guess. Some comments, some likes. Nothing I'd see as specific or surprising. Any way to debug what's going on here...?

**Comment by connyduck** [comment]
Can you have a look at the logcat output during the crash or take a bug report?

**Comment by kr428** [comment]
> Can you have a look at the logcat output during the crash or take a bug report?

Still being unable to capture a crash report, I _think_ I found a trace here. In Friendica, I subscribed to the Friendica Helpers group ...

https://forum.friendi.ca/profile/helpers

... and set that to "notifications on new posts" which will make those appear in my notification window. A couple of times, now, I noticed crashes of tusky whenever such notifications appeared there, and the app reproducibly stopped crashing the very moment I used some other client to remove this particular notification. Not sure what could cause that, though.

**Comment by connyduck** [comment]
Ok I subscribed to that group, let's see what happens on the next notification

**Comment by connyduck** [comment]
It is because the posts in notifications have reblogs, which never happens for other servers. But I guess it makes sense in this context, I'll fix it.

**Comment by kr428** [comment]
Seems fixed. Thanks very much.
