### ISSUE TITLE
Tusky 26 showing notifications tab from wrong account

### ISSUE THREAD

**Issue by haverholm** [tuskyapp/Tusky#4567]
### Detailed description

I'm using Tusky with three different Mastodon accounts (all different instances). Since the update to v26 (F-droid), the notifications tab for account_A@imaginair.es shows notifications for the latest other account to be opened.

I have tried to solve the issue by force stopping Tusky and clearing the app cache, same result. Checked imaginair.es which can sometimes be bottlenecked, it's up so shouldn't be the issue.

I imagine this has to do with the new notifications cache?

### Steps to reproduce the problem

1. Use Tusky v26 with multiple accounts
2. Switch between accounts
3. Open notifications tab

Expected: see notifications for the current account.
Issue: notifications for the latest used account shown instead.

### Debug information

Tusky 26.0

Device:

OnePlus ONEPLUS A6003
Android version: 10
SDK version: 29

Account:

@REDACTED@imaginair.es
Version: 4.3.0-alpha.3+glitch

**Comment by charlag** [comment]
Thank you so much for the info, we are investigating!

related: #4554 #4402

**Comment by haverholm** [comment]
Just wanted to verify, on closer inspection this is exactly the same issue as #4402 — the amount of notifications that are added above the relevant ones merely drown those out. So currently my notification tab for account_A@imaginair.es consists of

* a year's worth of notifications from account_C@vis.social
* a corresponding period's notifications from account_B@helvede.net
* account_A@imaginair.es notifications, even up to current

The order notifications from the accounts are shown in the account_A tab correspond with that in which they were opened after the latest update.

**Comment by maste9** [comment]
I like to add that in my case it's not only the notifications that are affected. 

My account_A's timeline doesn't work any longer at all:
 * it doesn't update and 
 * TL shows parts (frozen to the state when I installed the update 5d ago) of the TL of account_B AND some of account_C. 
 * Some of the notifications - also frozen to state of 5d ago - belong to account_D 
 * while the private messages are those of account_A as it should be.

Accounts B, C, D, E and F work fine afai noticed, but A is completely unusable atm.

**Comment by lapete** [comment]
I have the same issue. Account A is the first account in Tusky and the one selected when newly opening the app.
In A's notifications tab, the first 30 entries are notifications from account B, after that it's notifications from account A. Newly incoming notifications also join the list, but after the 30 entries from B.
Account B as well als 3 other accounts seem to be workig properly.

**Comment by haverholm** [comment]
KISS solution to this (I'm embarrassed I only thought of this now)

1. Open the notifications tab of the affected account
2. Open the Filter menu
3. Uncheck all options and apply
4. Your notifcations are now empty.
5. Open the Filter menu and re-check the options you want
6. The app now only shows notifications from the relevant account

Hopefully this works for others as well!

**Comment by Oblomov** [comment]
I was recently affected by this issue and can confirm that @haverholm's  proposed workaround works.

**Comment by maste9** [comment]
> KISS solution to this (I'm embarrassed I only thought of it now)
> 
>     1. Open the notifications tab of the affected account
> 
>     2. Open the Filter menu
> 
>     3. Uncheck all options and apply
> 
>     4. Your notifcations are now empty.
> 
>     5. Open the Filter menu and re-check the options you want
> 
>     6. The app now only shows notifications from the relevant account
> 
> 
> Hopefully this works for others as well!

It worked for the notifications  but my start  timeline stayed frozen to the corrupted state of 21 days ago. 
I tried to remove the tabs and re-add them.  But even if I removed the start tab it stayed and appeared instead of the notifications content.

So I decided to try to **remove the affected account and re-added it** after that. 

Et voilá! The Account seems to work well again in the end. So that's my workaround I guess. And I can happily  switch back to my absolute favourite Fediverse app! :purple_heart:
