### ISSUE TITLE
Browser-based login does not work

### ISSUE THREAD

**Issue by puckipedia** [tuskyapp/Tusky#4592]
### Detailed description

When I return from browser-based OAuth, the `domain`, `clientId`, and `clientSecret` variables are all blank (never persisted to storage), and authentication fails with "An unidentified authorization error occurred.".

### Debug information

Tusky Test 26.0-0f3dd64c
Google Pixel 6
Android version: 14
SDK version: 34

The account is on my own server software, which implements the right API contract for returning an OAuth code to Tusky (verified with a debugger).

**Comment by Tak** [comment]
Hi, have you also tried the "Login with Browser" item from the three-dots menu on the login screen?

**Comment by puckipedia** [comment]
Yes, that's what I meant with "Browser-based OAuth".

**Comment by Tak** [comment]
Ok, but then it *does* work with the default embedded webview?

**Comment by puckipedia** [comment]
No; using the embedded webview on my server shows the following (which is correct, it requires Basic auth and, sometimes, webauthn):
![Screenshot_20240805-150941](https://github.com/user-attachments/assets/1169b5a4-c019-4cf8-925a-d607c28c28f9)

And using the browser lets me log in, but returns "An unidentified authorisation error has occurred", which, after running Tusky in a debugger, is caused by the issue I specified in the issue.

**Comment by puckipedia** [comment]
In fact, testing with the most recent version of Tusky available in F-Droid (26.0), I cannot even log in to mastodon.social using the browser based flow.

**Comment by charlag** [comment]
just tried m.s. with tusky 26 from f-droid and it works. probably the only difference between your setup and mine is WebView

**Comment by charlag** [comment]
oh sorry you meant browser-flow, missed that

**Comment by charlag** [comment]
can confirm, browser-based login didn't work for me with m.s.

![Screenshot_20240805-155121](https://github.com/user-attachments/assets/d85392ac-450a-4adb-9ba4-e5e40b8744d7)

**Comment by tiptoptom** [comment]
Could this be the problem? 
https://github.com/zacharee/MastodonRedirect/issues/25

**Comment by edwardp3** [comment]
Having same issue with browser-based login. Same error as per @charlag above. Android 10, version 26.0 of Tusky app.

**Comment by ma3s7r0** [comment]
Same problem here, pixel 8, latest os, tusky 26.1, can’t login to chaos.social.

**Comment by jamagin** [comment]
Any chance this is going to be released in the Google play store soon? At least in the beta channel?

I can't use Tusky until that happens
