### ISSUE TITLE
Avatars and other media not showing

### ISSUE THREAD

**Issue by hyperreal64** [tuskyapp/Tusky#4593]
### Detailed description

When I connect my instance to Tusky and the other app Husky, avatars and other media do not show. I noticed this became a problem when I began using S3 object storage on my instance. The media loads fine when I'm using a web browser, though.

Given that it's not specific to Tusky, I wonder if it's maybe a configuration issue on my end? Are there special reverse proxy directives I need to use for compatibility with Tusky/Husky?

### Steps to reproduce the problem

1. Connect Tusky or Husky to my Mastodon instance.
2. Notice that avatars and other media do not show.

### Debug information

Tusky 26.0
Android version: 14
Google Pixel 6
Mastodon instance: https://fedi.hyperreal.coffee (using Mastodon version 4.2.10)

**Comment by connyduck** [comment]
Avatars and headers are also not loading when I visit your instance on the web, so it is definitely a configuration problem on your end

<img width="595" alt="Screenshot 2024-08-01 at 21 45 05" src="https://github.com/user-attachments/assets/2975115a-79f9-4bd0-a135-51079c0f358d">
