### ISSUE TITLE
Feature: Reduce accidental boosts/favorites, either by hiding or requiring confirmation

### ISSUE THREAD

**Issue by fardog** [tuskyapp/Tusky#460]
In Tusky, it's easy to accidentally favorite/boost toots that you did not intend to during the normal act of scrolling.

To editorialize somewhat: this is one of the things that always bothered me about the official Twitter client: it feels more like a feature that's meant to "drive engagement" rather than one that's meant to help the user. A user that wants to boost/favorite likely knows that this action can be performed, so it can be tucked away somewhere where it's not done accidentally.

I've got a few thoughts on how this could be improved:

# Add an option to require confirmation before boost/favorite

This wouldn't change the existing design, and could be done as a preference for users that wish to control the behavior. Adding options (one for boost, one for favorite) that would add a confirmation step. 

Example workflow:

* User navigates to preferences, enables "Require confirmation before boost" preference
* User navigates to timeline, taps "boost" on a toot
* _App prompts user: "Are you sure you would like to boost this toot?"_
    * User selects "yes": toot is boosted
    * User selects "no": toot is not boosted

What's possibly neat about this is the UX for actually gaining the confirmation could be handled in clever ways, like the first tap on the "boost" button changes the button to a confirm icon, and the second tap actually boosts it. Could be handled in a plain-old dialog or some sort of pop-over, however.

# Hide the boost/favorite buttons behind some user interaction

This could possibly clean up the reading experience some, but is less discoverable: Hiding the favorite/reply/boost buttons behind some interaction, such as a long-press on the toot, or requiring a tap through to the toot to the detail view, where the buttons could be shown.

Again, the UX could be more pleasant, say: the buttons are not shown, but a long-press on the toot "expands" the buttons on the bottom of it.

---

Those are just some suggestions, but in general I think it'd be ideal to add confirmation to anything which could either alter your own timeline or notify another user in some way, and accidental favorite/boost is one that's really easy to do from the timeline.

**Comment by connyduck** [comment]
I personally never accidentally boostet or favourited and I would find an additional step annoying.
But apparently this seems to be a problem for some people, so we should do something about it :)
I think we can add a confirmation dialog that can be activated in the settings.

**Comment by C1710** [comment]
Another idea would be add a short period where an 'undo boost' snackbar is shown. Sending the boost to the server would be delayed which shouldn't be a major problem.
