### ISSUE TITLE
Can’t reach some instances

### ISSUE THREAD

**Issue by Sylvhem** [tuskyapp/Tusky#4607]
### Detailed description

I have several Mastodon and Pleroma accounts logged in on Tusky. Starting recently, all of those accounts bare one stopped being refreshed. I can’t access their federated timelines, don’t get new notifications, the home tab is not being updated and I can’t send any message using those accounts.

I tried to log off and log in again with one of the affected accounts, hoping it would solve the problem. Sadly, Tusky fail to log in to that instance altogether now (see the steps to reproduce below).

I strongly suspect this is not a bug with Tusky itself, but rather a compatibility issue with my antiquated Android phone. I would like to be sure.

Affected instances are eldritch.cafe, mastodon.art and social.wxcafe.net among others.

### Steps to reproduce the problem

1. Click on “Add Account”
2. Enter an instance domain name (e.g. “social.example”) in the “Which instance?” textbox
3. Click on “Login with Tusky”
4. Following error message is displayed: “Failed authenticating with that instance. If this persists, try Login in Browser from the menu.”

### Debug information

Tusky 26.0 (same problem on Tusky 25.2)
Android 7.0
Android SDK 24
Wileyfox Spark +

**Comment by connyduck** [comment]
Ah yes certificate validation problems with newer Let's encrypt certificates, should have seen that coming https://letsencrypt.org/2023/07/10/cross-sign-expiration.html
