### ISSUE TITLE
publish hashes of signing keys

### ISSUE THREAD

**Issue by grrrrr** [tuskyapp/Tusky#4612]
### Pitch

On Android,  you can use [AppVerifier](https://github.com/soupslurpr/AppVerifier) to confirm if an apk was signed by the owners or an untrusted key (as well as other methods).   This can be combined with [Obtanium](https://github.com/ImranR98/Obtainium)  to check at install time.

The hashes could be published in a number of places for additional trust.  e.g

- blog post
- gpg signed download
- mastodon / twitter /...
- Github

### Motivation

Allows for an additional layer of certainty being able to easily check that the apk is legitimately signed

**Comment by connyduck** [comment]
The key used for Tusky Nightly (`com.keylesspalace.tusky.test`) releases on Google Play has the hashes:
```
md5 7E:DE:A8:7D:98:6C:A4:BE:4B:62:78:90:D9:3D:17:14
sha1 5F:E5:C4:0A:87:3C:8F:AC:1B:70:90:61:C9:33:F9:7B:D6:D3:E4:90
sha256 92:09:AC:1C:10:EE:CF:3F:1C:DD:A4:7B:5A:31:FF:3D:3E:FB:E8:83:79:BD:86:C0:5D:0A:F6:2F:B0:1C:DE:55
```

The key used for Tusky (`com.keylesspalace.tusky`) releases on Google Play and GitHub has the hashes:

```
md5 60:2C:F9:6E:11:E0:E1:D7:7A:F6:06:DC:B1:EC:CC:29
sha1 A6:91:B3:8D:EA:D2:FA:2A:FE:E1:41:85:C2:AD:24:43:84:CF:90:3E
sha256 95:10:EA:DA:78:EA:6E:B0:00:7B:8A:11:88:8B:1F:CC:3B:67:A5:1D:31:BC:32:E9:1F:85:16:E3:EF:E1:2F:AE
```

Releases from F-Droid will be signed with different keys, which does not mean they can't be trusted.
