### ISSUE TITLE
Suport login for access to federated timeline

### ISSUE THREAD

**Issue by ne20002** [tuskyapp/Tusky#4613]
### Detailed description

Friendica added a new feature to restrict access to the federated/public timeline to logged in users (for improving privacy). However, it turned out that Tusky just shows an error on the federated timeline if the access is limited to logged in users in friendica.

### Steps to reproduce the problem

1. In friendica enable restriction of public timeline endpoint (see [#14355](https://github.com/friendica/friendica/pull/14355))
2. In Tusky look at the federated timeline, it's empty

### Debug information

Tusky 26.0 Android
Friendica 2024.06-rc

**Comment by connyduck** [comment]
Is there an instance that has this enabled where I can create an account to try this out?

**Comment by annando** [comment]
@connyduck it is possibly that there had been a problem with the change. I already created a fix for that in Friendica. Most likely this will fix this issue.

**Comment by ne20002** [comment]
I will update my instance and do some tests today.

**Comment by ne20002** [comment]
> Is there an instance that has this enabled where I can create an account to try this out?

Does (or shall) Tusky support login on the /api/v1/timelines/public?

**Comment by connyduck** [comment]
> Does (or shall) Tusky support login on the /api/v1/timelines/public?

Tusky has no concept of authorized/no-authorized endpoints, it always sends the Authorization header. That includes /api/v1/timelines/public.

**Comment by ne20002** [comment]
Thank you for the clarification. It seems obvious that the problem is with Friendica. So this issue is closed now.
