### ISSUE TITLE
Harmonise viewing of hashtags at the end of posts

### ISSUE THREAD

**Issue by bannisdale** [tuskyapp/Tusky#4616]
### Pitch

Some updates ago, Mastodon Web introduced that hashtags that are at the end of posts after two line breaks are presented differently:

![Screenshot_20240815_155544_Firefox](https://github.com/user-attachments/assets/5984fe88-a97e-4979-8ed9-4535e301b8e3)

This seems to have never made its way into Tusky, as these hashtags are still just part of the regular post body.

Would be nice if both behaved the same. :)

### Motivation

I think it's needed as it is the standard (and therefore expected) behaviour. Plus, it looks nicer and cleaner. Also, you can't be sure if your post is displayed as intended without opening it via URL afterwards.

I think all users would benefit from the change that view posts with "attached" hashtags. 😉

**Comment by Tak** [comment]
🤔 We could also display "out-of-band" hashtags here (hashtags that are attached to the post but aren't referenced via `#hashtag` in the post content)

**Comment by Tak** [comment]
This was implemented in https://github.com/tuskyapp/Tusky/pull/4761 and will be available in the next release (or it is now available in [nightly](https://tusky.app/faq/))

**Comment by bannisdale** [comment]
> This was implemented in #4761 and will be available in the next release (or it is now available in [nightly](https://tusky.app/faq/))

Yay, thank you! :)

**Comment by bannisdale** [comment]
In the current beta version, trailing hshtags only seem to apply for posts that have attached media, i.e. not for text posts. However, the standard behaviour also supports trailing hashtags for text posts.

Should I open a new issue? Doesn't seem like I can re-open this one.

**Comment by Tak** [comment]
Hi, it should apply the same way for text-only posts, e.g. https://tenforward.social/@AlsoPaisleyCat/113649567262447089

Note that the post needs to have a line at the end with only hashtags, or hashtags that are not contained in the post body (also in mastodon web).

If you have a specific example of a post where it isn't working correctly, please send it to us (either here, on an issue, or [via matrix](https://matrix.to/#/#Tusky-General:matrix.org)), and we'll take a look

**Comment by bannisdale** [comment]
First one I scrolled over:

![Screenshot_20241214_095557_Tusky](https://github.com/user-attachments/assets/ec6a9a59-df97-4bd2-93a8-6479f857b097)

In web:

![Screenshot_20241214_095613_Firefox](https://github.com/user-attachments/assets/f4b0b90e-81b2-4d6e-8fd9-8452f5f9dcc3)

Post: https://mas.to/@farbel/113617210579459684

**Comment by bannisdale** [comment]
Seems to work when viewing a single post, but not in the timeline. At least it's not very distinguishable. 😅

Timeline:

![Screenshot_20241214_100112_Tusky](https://github.com/user-attachments/assets/dda06fb6-3582-43c7-a829-c820ba6339cb)

Post view:

![Screenshot_20241214_095557_Tusky](https://github.com/user-attachments/assets/e6fd4d90-d69d-4b31-85ff-5a35a5fcc4d3)

Standard:

![Screenshot_20241214_095613_Firefox](https://github.com/user-attachments/assets/5db31620-0730-428e-af83-160aac46aed7)

URL: https://mas.to/@farbel/113617210579459684

**Comment by Tak** [comment]
I believe it's being applied, there's just not such a big difference in the look as in mastodon web - you can tell on posts with a *lot* of hashtags, because they get ellipsized in the timeline
