### ISSUE TITLE
Unboosting post from own profile broken

### ISSUE THREAD

**Issue by WebCoder49** [tuskyapp/Tusky#4625]
### Detailed description

When I tap the boost icon on a post I have boosted in my own profile's feed, the boost icon does not change appearance to demonstrate this. This post is unboosted, however, as tapping it demonstrates.

https://github.com/user-attachments/assets/0475b42c-1fab-4b49-97b6-aa73b67d39f2

The UI _does_ update properly when I do the same in my home feed. It also updates properly when I am boosting rather than unboosting my own post in my profile.

### Steps to reproduce the problem

1. Tap on my own profile image to get the navigation sidebar.
2. Tap on my own profile image in the sidebar to open my profile.
3. Tap on the boost icon of a post I have boosted and confirm the unboost.

### Debug information

Tusky 26.0

Device:

OPPO CPH2343
Android version: 13
SDK version: 33

Account:

@WebCoder49@floss.social
Version: 4.2.12

---
Thank you for this amazing app - it works very smoothly normally and has so many useful features for the Fedi!

**Comment by connyduck** [comment]
Please try version 26.1.
I'm pretty sure this is fixed by https://github.com/tuskyapp/Tusky/pull/4549.

**Comment by WebCoder49** [comment]
It works. Thank you for the reply, @connyduck !
