### ISSUE TITLE
Notifications attributed to incorrect account

### ISSUE THREAD

**Issue by Ragzouken** [tuskyapp/Tusky#4629]
### Detailed description

I have two accounts logged in tusky, each notification is attributed to the other account--clicking through opens the wrong account in tusky

### Steps to reproduce the problem

1. Two accounts linked in tusky
2. Get a like on post of account A
3. Like is attributed to account B and clicking it opens tusky in account B
...

### Debug information

Tusky 26.1, Android

**Comment by connyduck** [comment]
You are talking about system notifications and not the notifications tab in the app, right?

**Comment by Ragzouken** [comment]
Yes sorry, I mean the out-of-app notifications I receive, not the in-app notifications--they are fine.
