### ISSUE TITLE
Open links in new tab (web browser)

### ISSUE THREAD

**Issue by issueseverywhere** [tuskyapp/Tusky#463]
When i click on links in posts, i get a message that it has been opened in a new tab in firefox, but it actually loads the link on the same active tab.

If i scroll down the home feed, and click on two links one after the other, firefox will not open a new tab for the second link clicked, but load it in the first clicked link's tab.

**Comment by charlag** [comment]
Yeah, I feel you, but I think that's a problem with Firefox?

**Comment by connyduck** [comment]
No this happens because we set Browser.EXTRA_APPLICATION_ID on the ACTION_VIEW intent.
See https://developer.android.com/reference/android/provider/Browser.html#EXTRA_APPLICATION_ID

**Comment by charlag** [comment]
Wow, thanks, didn't know that.
Why do we do that?

**Comment by connyduck** [comment]
I guess it once was good practice to do so but actually it is just annoying? Feel free to remove it.

**Comment by charlag** [comment]
I am actually quite annoyed by this, maybe I will try to do a quick fix on the weekend

**Comment by connyduck** [comment]
fixed #603
