### ISSUE TITLE
Can't login with multiple accounts on same server/domain as of version 26

### ISSUE THREAD

**Issue by kouya** [tuskyapp/Tusky#4631]
### Detailed description

I have different accounts on the same server (personal and bots).

I can log in to the first one fine. If I log in to the second one, the first account will not be shown anymore as if I only had one account in Tusky. The timeline also doesn't change and will show the items from the first account. Sidebar will show the new one.

If I log in to the third one, the sidebar account will show that one but the timeline again does not change.

If I log out of the account, Tusky will revert to having no accounts configured.

I can't tell when it started sadly. I had the timeline/notification mixup in 26.0 and deleted and reinstalled 26.1 from F-Droid to start fresh. That version at least is affected.

Not sure if it matters, this is a gotosocial instance. It worked fine with 26.0 before reinstalling Tusky. I think I originally added all accounts with version 25 or 24.

### Steps to reproduce the problem

1. Add account 1 on a Domain A
2. Add another account 2 also on Domain A
3. Only account 2 will be shown added to Tusky, account 1 will be gone as if it was never added
4. Additionally, if you log out of account 2, no account will be configured, account 1 won't come back.

### Debug information

Tusky 26.1 F-Droid
Android 14
Fairphone 5

Update with additional info: I installed 25.2 from the F-Droid archive and it works correctly with that version.

**Comment by connyduck** [comment]
Can reproduce, and the fix that I'm working on for #4629 fixes this as well

Thanks for reporting & sorry for the inconvenience

**Comment by kouya** [comment]
Oh didn't realize that one is related. But thanks! <3

**Comment by connyduck** [comment]
Yeah the symptoms are different, but in the end what happens is that 2 accounts are collapsed into one
