### ISSUE TITLE
[feature] Custom columns

### ISSUE THREAD

**Issue by nailyk-fr** [tuskyapp/Tusky#465]
On the webUI there is a way to add custom columns, like tags. 
It will be great if we can do the same on Tusky. 
Adding 'tabs' will be the best (with ability to swipe left/right, like it is already possible with the four default columns) but guess having them under the menu should be good enough. 

Many thanks :)

**Comment by charlag** [comment]
I think it would be cool but it would require a lot of effort.
@connyduck what do you think, would we support such a thing in the future?

**Comment by Trav1sty** [comment]
Would this be something to consider with the upcoming changes to Tusky to support the DM functionality? Tootdon has a perfect implementation of creating a new column using a hashtag search as well as regular text for search criteria. It would fantastic if Tusky could include that as well.

**Comment by connyduck** [comment]
Tabs are already customizable, will add hashtag columns soon. Also a good idea would be local timelines of other instances and displaying lists in dedicated tabs.

**Comment by connyduck** [comment]
Hashtag columns are done! https://github.com/tuskyapp/Tusky/pull/1145
