### ISSUE TITLE
[issue] Time line jump after idling

### ISSUE THREAD

**Issue by nailyk-fr** [tuskyapp/Tusky#466]
**Step to reproduce**: 
1. Open Tusky, 
2. scroll the time line, 
3. push home button (android) -> app is in background, you receive notifications, 
4. go back to Tusky, main time line, 
5. scroll time line down (should be a fixed amount of toots, will try to find how many)
- There is a jump in the time line with missing toots (timeline at 3. state + fixed amount of new toots)

**Workaround**: press return button until Tusky get closed, then launch it again, timeline is now complete. 

Sorry if it is not clear enough. Please ask if you need more informations. 
Thanks for your time :)

**Comment by charlag** [comment]
@nailyk-fr does this still happen to you?

**Comment by nailyk-fr** [comment]
Didn't tried for a while. Will test again asap.

**Comment by nailyk-fr** [comment]
Looks like it is solved. 
Thanks for your support!
