### ISSUE TITLE
To much empty lines in post

### ISSUE THREAD

**Issue by Offerel** [tuskyapp/Tusky#4663]
### Detailed description

There seems to be to much space or empty lines in some posts, so that they look strange. Example post: https://pixelfed.social/p/nhoizey/739018826511637678

Expected look:
![Screenshot_20240910_103225](https://github.com/user-attachments/assets/3f5f614d-f5d8-44d0-a1b5-355e46a31b62)

in Tusky:
![Screenshot_20240910_103602_Tusky](https://github.com/user-attachments/assets/65ae5ee3-8404-4ce5-b896-1d123be3a4f1)

### Steps to reproduce the problem

1.
2.
3.
...

### Debug information

Tusky 26.1 F-Droid

**Comment by connyduck** [comment]
Oh no, this is a tricky one. 
The think is, Pixelfed seems to use both newlines and `<br/>`  tags, while Mastodon usually only has `<br/>` tags. 
Tusky displays both because there are other edge cases where this is necessary. Ignoring newlines would fix this issue, but cause problems elsewhere. 😕

**Comment by Offerel** [comment]
I assume tusky converts <br/> to newline or newline to be <br/>. If a double newline or <br/>is removed after this conversion or it detects a newline followed by <br/>, the extra newline should be ignored. 

In my opinion, it should be a rare case, that a newline followed by a <br/> is intentionally. But if you have multiple <br/>, this could be a wanted double newline. At least this is how I would handle that for example in my Primitivenotes Project. But that's PHP and a complete other story.

**Comment by connyduck** [comment]
@Offerel very good idea, thx
