### ISSUE TITLE
Filtering of boosts out of home panel not working all the time

### ISSUE THREAD

**Issue by KonomiKitten** [tuskyapp/Tusky#468]
Topic says it all but after a quick look at my home panel it looks like boosts from my own instance are filtered but boosts from other instances are not.

Tusky v1.3.1
LineageOS: 14.1

**Comment by charlag** [comment]
@KonomiKitten hi! Does this still happen?

**Comment by KonomiKitten** [comment]
@charlag I just tested and seems fixed as of 1.7.0 so closing.
