### ISSUE TITLE
"An error occurred" when opening profile with 2B followers / followees

### ISSUE THREAD

**Issue by progval** [tuskyapp/Tusky#4681]
### Steps to reproduce the problem

1. Search for `@puckipedia@puckipedia.com`
2. Open the profile

### Debug information

Tusky ~~4.2.12~~ 26.2
Android 14
Fairphone 3
oc.todon.fr

**Comment by connyduck** [comment]
We never released a Tusky verison 4.2.12. 
Tusky 4 is 6 years old.
It works with Tusky 26.2 on mastodon.social.

**Comment by progval** [comment]
Sorry, that was my Mastodon version. I just updated Tusky from 26.1 to 26.2, and it is still happening.

**Comment by connyduck** [comment]
I made an account on oc.todon.fr and tried with Tusky 26.2 on an Android 14 device and it works fine.

![Screenshot_20240914_201419](https://github.com/user-attachments/assets/14c38159-54cf-4557-9fcc-16393d8aeedd)

🤔 

So it must be something else. Is your network fine? Does it work on other apps / the web? Did you change any Tusky settings? What language is it set to?

**Comment by progval** [comment]
It's working now. Maybe a cached version of the profile, that I fetched while on 26.1.

Thanks
