### ISSUE TITLE
Draft message goes away when switching screens 

### ISSUE THREAD

**Issue by wesgeorge** [tuskyapp/Tusky#4693]
### Detailed description

When composing a post in Android, if you write something, then switch applications with the partial post still open in the compose window, after a minute or two the post is gone when you switch back to Tusky. Pressing the new post button does not take you back to the in progress post, it opens a new blank post, and the in progress post is also not saved in drafts.

Don't remember it doing this before, so I think this is a relatively recent bug. 
![Screenshot_20240920_094914_Tusky](https://github.com/user-attachments/assets/6544200a-5cbf-4b80-86b6-64b175103b6d)

### Steps to reproduce the problem

1. Tap Compose post
2. Write some text but do not: post, close compose window, or save post to drafts
3. Switch to another app
4. Wait 1-2 minutes
5. Switch back to Tusky
6. In process post is gone, timeline is displayed
...

### Debug information

Tusky 26.2

Device:

samsung SM-G981U
Android version: 13
SDK version: 33

Account:

@wesgeorge@mstdn.social
Version: 4.3.0-alpha.5

**Comment by Packbat** [comment]
Observing this on my phone as well - Tusky 26.2, samsung SM-A146U, Android version: 14, SDK version: 34.

**Comment by connyduck** [comment]
fixed in https://github.com/tuskyapp/Tusky/pull/4685
