### ISSUE TITLE
Schedule Toot button causes repeated duplicated posts on GoToSocial

### ISSUE THREAD

**Issue by rochacbruno** [tuskyapp/Tusky#4703]
### Detailed description

When trying to schedule a post on Tusky connected to a GoToSocial instance (which doesn't support scheduling), instead of erroring, Tusky will post the message repeated indefinitely until Android application is forced stop.

More Context: https://go.rocha.social/@bruno/statuses/01J95XX6VZ3FW5K6GRR7V4H94K 

### Steps to reproduce the problem

1. Using Tusky connect to a gotosocial instance (I can provide an account for testing)
2. Write a post
3. Click schedule button and set 3 hours ahead
4. Click post

Expected: Tusky would report "Error scheduling, post is saved as a draft"

What happens: Tusky will post and then indefinitelly repeat the same post, making the timeline to be spammed with multiple posts with the same content.

GTS issues:
https://github.com/superseriousbusiness/gotosocial/issues/1006 
https://github.com/superseriousbusiness/gotosocial/issues/2723
...

### Debug information

26.2 - Android 11 - From Google Play

**Comment by connyduck** [comment]
Meh its a Json parsing error because GtS replies with a `Status` object and not a `ScheduledStatus`.

**Comment by tsmethurst** [comment]
We don't yet support scheduled statuses, so we can partially fix this on our side by returning an error or something instead of just a normal Status.

**Comment by rochacbruno** [comment]
@tsmethurst I suggest rejecting posts with `scheduled_at` option until the feature is implemented, then the client can manage it by the HTTP 501 returned.
