### ISSUE TITLE
"Load more" in "system design black" mode uses the dark background instead of the black background

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#4708]
### Detailed description

![Screenshot_20241005-195025~2](https://github.com/user-attachments/assets/80810f2c-5e34-40f3-bdd4-086857b2462b)

### Debug information

Tusky Test 26.2-156d4ffa (based on current `develop`)

Device:

Fairphone FP5
Android version: 14
SDK version: 34

Account:

@Tak@glitch.taks.garden
Version: 4.3.0-trans_rights&blm&gaza+glitch

**Comment by connyduck** [comment]
That is intended to make it more visible https://github.com/tuskyapp/Tusky/issues/3311

**Comment by Tak** [comment]
Ah ok, it didn't register with me that this is the divider color
