### ISSUE TITLE
Performance difference Moshidon/Tusky

### ISSUE THREAD

**Issue by Offerel** [tuskyapp/Tusky#4709]
Currently I use both Moshidon and Tusky on my device. Due to #2807 more Moshidon, if not all the time. But what I always notice is the performance difference between the two clients. Tusky is many times faster, especially when displaying photos in the timeline. Is there really a reason for that? Since this is actually the opposite of a bug, but rather a question, this is somewhat out of place. Sorry for that.

**Comment by connyduck** [comment]
Thanks I guess? 
Without inspecting the Moshidon code I can't tell you what is going on, maybe ask them to check?
Here at Tusky we always try to write efficient code, sometimes we benchmark parts to check we are doing good, and bytecode minification is turned to the max. But nothing of this is special.

**Comment by Offerel** [comment]
Yes, I asked on purpose here because it works a lot better with Tusky. Since Moshidon is a fork of Mastodon, I should probably ask at Mastodon why their app is so inefficient compared to Tusky. But I doubt I'll get a usable answer there.

Anyway, I'll try my luck.

BTW: it would be really great if #2807 could be implemented as an option. This is pretty much the only thing that keeps me away from using Tusky exclusively.
