### ISSUE TITLE
Charakter Limit is not correct 

### ISSUE THREAD

**Issue by nyansen** [tuskyapp/Tusky#4710]
### Detailed description

My Server has a char limit of 1312 chars but the app always show me a limit of only 500 chars 

### Steps to reproduce the problem

1.
2.
3.
...

### Debug information

Tusky 26.2

Device:

Google Pixel 8a 
Android-Version: 15 
SDK-Version: 35

Account:

@nyansen@elbmatsch.de 
Version: 4.2.10

**Comment by connyduck** [comment]
https://elbmatsch.de/api/v2/instance says (amongst other things) `"statuses":{"max_characters":500}`. Looks like the server is not configured correctly, please talk to your admin.
