### ISSUE TITLE
toot lost when composing, switching away from tusky, then back again

### ISSUE THREAD

**Issue by onelson** [tuskyapp/Tusky#4714]
### Detailed description

While composing a toot, if interrupted the in-progress post can be lost. Switching away from Tusky and then returning will put me on the timeline view.

https://github.com/user-attachments/assets/70f7868b-97fd-4010-b971-9f03dda1d219

It would be great if either:
- resuming tusky put me back at the in-progress composition
- the in-progress composition was saved to drafts automatically

### Steps to reproduce the problem

1. compose a toot but don't post it
2. switch to some other app
3. switch back to tusky
...

### Debug information

- Tusky Version: 26.2
- Device: Pixel 9 Pro
- Android Version: 14
- SDK Version: 34
- Instance: mastodon.social

**Comment by mcclure** [comment]
Thank you. Duplicate however

**Comment by onelson** [comment]
🤦🏻

**Comment by onelson** [comment]
Oh dang it. I see https://github.com/tuskyapp/Tusky/issues/4693 and it was already closed.
