### ISSUE TITLE
Support custom emoji gifs

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#472]
For example https://cybre.space/@maunzikation/99094971933547861

**Comment by charlag** [comment]
It's really not easy to do and it will be quite laggy but it's desirable of course
https://stackoverflow.com/questions/8632801/how-to-add-animated-emoticon-in-textview-or-edittext-in-android

**Comment by M4lik** [comment]
Yeah, I know that this is low prio and maybe a little bit difficult, but just wanted to ask if there is any progress here? :sweat_smile:

**Comment by charlag** [comment]
Nope, not yet, sorry.

**Comment by aka-rin** [comment]
I don't know if I get it wrong, but custom emoji only supports png files that less than 50KB. So they are not gifs, but APNG. It seems that Line, the popular chatting application in Japan and Korea, released an APNG library for Android: https://github.com/line/apng-drawable .

Well, some users are asking if any client of Mastodon support animated emojis so I want to create a new issue but it seems duplicate ... If Tusky implement this feature it will be the first one though. 😂

**Comment by hynet-mel** [comment]
It seems Fedilab already implemented custom emojis, maybe I will look if I can make a patch for both Tusky and Husky (and my own fork of Husky)
https://github.com/stom79/Fedilab/commit/0dff65192a3ace68301c02cde331dc2215db89f6
