### ISSUE TITLE
Crash when toot contains quote toot by same author 

### ISSUE THREAD

**Issue by tomayac** [tuskyapp/Tusky#4725]
### Detailed description

Hard crash when reaching a toot with a quote toot of the same author. 

### Steps to reproduce the problem

- Follow https://hachyderm.io/@jyasskin.
- Open their profile and scroll until you see https://hachyderm.io/@jyasskin/113303505160169279 which contains a quoted toot pointing at https://hachyderm.io/@jyasskin/113303493113946716.
- Observe the crash on
   ```
   Tusky 26.2
   
   Device:

   Google Pixel 8 Pro
   Android version: 15
   SDK version: 35

   Account:

   @tomayac@toot.cafe
   Version: 4.2.13
   ```

### Debug information

Tusky 26.2

Device:

Google Pixel 8 Pro
Android version: 15
SDK version: 35

Account:

@tomayac@toot.cafe
Version: 4.2.13

**Comment by connyduck** [comment]
I can reproduce a crash here, but not because it is a self quote, rather because the link preview card has a very weird image attached.

@tomayac do you have the "show link previews in timelines" setting turned on?

**Comment by tomayac** [comment]
"Download media previews" is on, yes, if this is what you mean.

**Comment by tomayac** [comment]
Oh, wait. Found the "Show link previews in timelines" setting. It was on. If I turn it off, the crash doesn't occur anymore. So this is definitely the culprit. Let me know if or how I can help debug this.

**Comment by connyduck** [comment]
That confirms that the crash I can reproduce is the same as yours! Thanks for reporting, will fix.

**Comment by tomayac** [comment]
Thank _you_ for working on Tusky `<3`! So the problem is essentially [this 661 x 2 image](https://media.hachyderm.io/cache/preview_cards/images/026/123/930/original/c35b698b606557ec.png). 

![c35b698b606557ec](https://github.com/user-attachments/assets/c74cf68c-cbc7-4188-92a9-27db891d760b)

**Comment by connyduck** [comment]
Well strictly speaking the problem is that Tusky doesn't account for weird aspect ratios when loading the preview card image 😅
