### ISSUE TITLE
Tusky loses current activity when opening from the app drawer

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#4727]
### Detailed description

Tusky loses current activity when opening from the app drawer, and comes back to the main view, on the last column I was.

That means that if I was in my settings, on someone’s profile, in a thread, or composing a post, I lose where I was (what I was doing/writing).

### Steps to reproduce the problem

1. open Tusky
2. open settings
3. go to home screen
4. open Tusky from the app drawer

### Debug information

```
Tusky 26.2

Device:

Google Pixel 7 
Version Android : 14 
Version SDK : 34

Account:

@melunaka@eldritch.cafe 
Version : 4.3.0-beta.1+glitch
```

**Comment by connyduck** [comment]
This was fixed in https://github.com/tuskyapp/Tusky/pull/4685
