### ISSUE TITLE
Deprecating Android 4

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#476]
Android 4 causes more and more problems with Tusky development e.g I cannot use vector drawables and compound drawables the way I want. Mastodon instances drop support for TLS 1.1 and workarounds to enable TLS 1.2 an Android 4 do not seem to work.
This hinders development of new features for the 93% of users that have a newer Android version.

Here are the current installation numbers from Google Play:

Android 4.4 | 1,057 | 5.0% | -6.0%
Android 4.3 | 36 | 0.2% | -23.4%
Android 4.2 | 290 | 1.4% | -5.2%
Android 4.1 | 131 | 0.6% | -7.7%
Android 4.0.3 - 4.0.4 | 45 | 0.2% | -6.3%

So my suggestion is, we drop Support for Android 4.0.3 - 4.1 by the end of the year / with the next release, Android 4.2 - 4.3 in 4 month from now and 4.4 in 8 month the latest. Until then I will resolve all crashes on Android 4, but no display bugs or connection errors because that just takes to much time.

**Comment by MasterGroosha** [comment]
Just wondering: even web-client won't work for Android 4 with TLS 1.1 ?

**Comment by connyduck** [comment]
Definitely not with stock browser, Chrome probably ships its own TLS stack.

**Comment by MasterGroosha** [comment]
Well, since Chrome will work with Mastodon on Android 4, I personally think it's not a bad idea to drop support for this version, since it causes lots of troubles with compability

**Comment by charlag** [comment]
I would drop everything below API 16 at least or even below 19.
Drawables are almost never the problem if you assign them programmatically.

**Comment by stom79** [comment]
I know that TLS issue is probably not the main reason to stop the support for API < 19. But there is a way to solve connection issues with some instances for Google Play users.
It's what I use with Mastalab but I am not sure to be able to implement it quickly with Tusky. The easiest way would be to give you the pieces of code.

**Comment by connyduck** [comment]
Step 1 of the deprecation has been done. https://github.com/Vavassor/Tusky/commit/3c795c6eef4d8637ef67691053897a8e0fddab77

According to Google Play, this affects 2.1% of our users.

**Comment by connyduck** [comment]
Android 4 is now at 3.8% / 800 installs.

**Comment by Tagadda** [comment]
That's because Tusky doesn't work on Android 4 so nobody install it ?
I love Tusky, this is my favourite app for Mastodon. 
Unfortunately, I have to use Mastalab since most of my instances only support TLS1.2 and Tusky do not...

**Comment by charlag** [comment]
@Tagadda that's the main reason supporting Android 4 is such a PITA. We don't want to make an app 2x bigger for everyone because of the old Android versions. Mastalab already does this so Android 4 is covered by at least one good app so I don't see a reason in investing so much time in it.

**Comment by stom79** [comment]
@Tagadda 
Some stats from Mastalab (Google Play) that do confirm what was said by @connyduck  and @charlag 

Android 4.4: 2.6%
Android 4.3: 0.2%
Android 4.2: 0.6%
Android 4.1: 0.6%
Android 4.0.3 - 4.0.4: 0,2%

Mastalab might be one of the "most used app" for these Android versions due to the fact, few apps support up-to-date cipher suites for Android < 19 (only because the apk file will increase its size by several Mb). 

Also, maintaining a separated release of Tusky for Android <= 4.4, is not a simple matter, especially with some issues with vector icons. If it was only for the cipher suites issue, I would have suggested my help on it.

**Comment by connyduck** [comment]
Ok, so lets focus on creating a rock solid Tusky 3.x and the throw out 4.4 support in Tusky 4.

**Comment by connyduck** [comment]
#843

**Comment by kitkatloyalist** [comment]
the TLS 1.2 solution?

https://github.com/square/okhttp/issues/2372
