### ISSUE TITLE
Existing time limited filters can't be modified to indefinite filters

### ISSUE THREAD

**Issue by nondeterminischtick** [tuskyapp/Tusky#4760]
### Detailed description

If you create a new filter that lasts for a limited duration (any option other than indefinite).

If you open the filter to edit and change the duration from "(no change)" to "Indefinite". The save appears to work but the filter still shows the old duration. I.e. The duration stays on the previous value.

Changing between limited durations does work. Eg. Changing from 5 minutes to 7 days works fine.

### Steps to reproduce the problem

1. Create a filter with a 5 minute duration.
2. Open the filter and change the duration to indefinite and save the change
3. The filter duration has not changed

### Debug information

Tusky 26.2

Device:

Google Pixel 6
Android version: 14
SDK version: 34

Account:

@basil@sarcasm.stream
Version: 4.3.1

**Comment by nondeterminischtick** [comment]
After I created the 5 minutes filter.
I tried to change the duration to indefinite.
The filter still showed the time remaining. In this case 4 minutes. And the remaining time continued to count down.
After the duration had elapsed the time shown next to the filter starting counting up.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/4743
