### ISSUE TITLE
Share to other account leaves UI inbetween two accounts in tusky test

### ISSUE THREAD

**Issue by codl** [tuskyapp/Tusky#4766]
### Detailed description

In recent tusky test, sharing an image or text to an account that is not the currently active account leaves the ui in an inconsistent state where parts of the ui say that the previous account remains active but other parts of the ui load data and do actions from the new account

### Steps to reproduce the problem

1. Log into two different accounts in tusky, we'll call them A and B
2. Load up the home timeline on A
3. Share an image or a text snippet to tusky, and in the dialog asking which account to share with, choose B
4. Post the post, or dismiss the compose screen
5. Tusky now displays A's home timeline and shows A as the active account, but swiping to the other tabs shows B's notifications, B's local timeline, etc. Tapping the Compose button shows the compose screen for B. Faving or bookmarking posts in the home tab is done from A's account but tapping on a post loads it from B's account (which fails if A and B are on different instances) and any actions taken from the post view are done from B.
6. Closing and reopening tusky, or switching accounts, clears the issue.

### Debug information

Tusky Test 26.2-fa35648a

Device:
Fairphone FP4
Android version: 13
SDK version: 33

Accounts:
codl@chitter.xyz, codltest@chitter.xyz
Version: 4.2.10
codl@donphan.social
Version: 4.3.1+glitch.donphan.social
codl@reentry.codl.fr
Version: GoToSocial 0.17.1+git-8a93300

**Comment by connyduck** [comment]
oh no

**Comment by nehemiagurl** [comment]
this also happens in recent beta

**Comment by connyduck** [comment]
Yes I'm aware of the bug, the problem is that the easy fix restarts the app too often, causing #4789, which is even more annoying. At least an app restart helps, and we don't mix timelines permanently like we used to. It will take a while until I can figure out a fix for all these problems.
