### ISSUE TITLE
Email address advertised in the Google Play Store for Tusky Test bounces

### ISSUE THREAD

**Issue by jikamens** [tuskyapp/Tusky#4780]
### Detailed description

```
Final-Recipient: RFC822; contact@tusky.app
X-Actual-Recipient: rfc822; contact@tusky.app
Action: failed
Status: 5.7.1
Remote-MTA: DNS; mail.tutanota.de
Diagnostic-Code: SMTP; 550 5.7.1 <contact@tusky.app>: Recipient address rejected: Recipient not available
Last-Attempt-Date: Sun, 1 Dec 2024 10:10:28 -0500
```

### Steps to reproduce the problem

1. Open the app info for Tusky Test in the play store
2. Open the app support information
3. Try to send email to the address listed there
4. It bounces.

### Debug information

N/A

**Comment by Tak** [comment]
Hi, thanks for letting us know, our provider has resolved the problem ❤️
