### ISSUE TITLE
Tusky Test is hanging

### ISSUE THREAD

**Issue by jikamens** [tuskyapp/Tusky#4781]
### Detailed description

First Tusky Test hung when I was in the middle of using it. When I closed the app and tried to reopen it, it hung on startup and I can't get past that. What I am seeing is a mostly blank screen with the menu bar at the top (my avatar plus the feed buttons plus the menu button on the right), the compose button at the bottom, and what is supposed to be a spinny cursor in the middle but it isn't actually spinning.

### Steps to reproduce the problem

Launch Tusky Test.

### Debug information

Tusky Test version 26.2-555ff1ea
Pixel 9 unlocked from Google running up-to-date stock Android
federate.social

**Comment by connyduck** [comment]
probably https://github.com/tuskyapp/Tusky/pull/4779

**Comment by connyduck** [comment]
@jikamens The newest Test Version (26.2-af5d10cd) should fix this problem, can you confirm that?

**Comment by jikamens** [comment]
Yes, no longer hanging.
