### ISSUE TITLE
Wrong Umlauts + small letters in new hashtag bar (since v27)

### ISSUE THREAD

**Issue by Der-K-2000** [tuskyapp/Tusky#4810]
### Detailed description

I see at least two character issues with the **new hashtag bar** function below posts which will be introduced in [version 27](https://github.com/tuskyapp/Tusky/pull/4761):

1. Umlauts and other allowed characters are **converted incorrectly** (e. g. _Bäume_ → _baume_), although they should not be changed at all.
2. All characters are also shown in **lower case**, which is confusing for everyone, but especially problematic for accessibility reasons as soon as there are multiple words (like _#AnDiesemTag_).

Example:
https://ard.social/@tagesschau/113652054318347927

Web:
![grafik](https://github.com/user-attachments/assets/038b5999-eca1-4e49-afba-8e40b1d30098)

Tusky:
![grafik](https://github.com/user-attachments/assets/f3bafbbe-eb77-4787-9a65-bddc51b694eb)

### Steps to reproduce the problem

1. Write a post with a single hashtag line at the end.
2. Use Hashtags with Umlauts and in capital letters.

### Debug information

Tusky v27 beta 1

**Comment by connyduck** [comment]
Thanks, we already fixed this https://github.com/tuskyapp/Tusky/pull/4802

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/4845
