### ISSUE TITLE
Opening Tusky from notifications fails

### ISSUE THREAD

**Issue by Sirs0ri** [tuskyapp/Tusky#4820]
### Detailed description

When clicking an (Android) notification, Tusky opens for a brief moment, and then closes itself again

This has definitely happened for replies and notifications about reports so far, I haven't gotten other notifications recently.

Please let me know if there's specific logs I could provide to help narrow this down!

### Steps to reproduce the problem

1. (Get a notification)
2. Tap the notification

I'd expect to end up in tusky, on the notifications tab, but instead the app almost instantly closes and I'm back on my Homescreen.

### Debug information

Tusky Test 27.0 beta 1-3e6bfe87

Device:

samsung SM-G970F 
Android-Version: 12 
SDK-Version: 31

Account:

@Sirs0ri@corteximplant.com 
Version: 4.4.0-alpha.1+glitch.cortex

**Comment by connyduck** [comment]
Will be fixed by https://github.com/tuskyapp/Tusky/pull/4818
