### ISSUE TITLE
Add support for moved accounts

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#483]
New feature of Mastodon 2.1: https://github.com/tootsuite/mastodon/releases/tag/v2.1.0rc1

**Comment by charlag** [comment]
@connyduck it implies "moved here" accounts as well?

**Comment by connyduck** [comment]
Yes! I would have already implemented it, but I have not yet found a memorial accoun to test with. Tips welcome.
Moved account example: https://mastodon.social/@mastalab

**Comment by charlag** [comment]
Ah, I see, thx

**Comment by connyduck** [comment]
Ok, looks like the API does not expose memorial accounts, only moved accounts.
https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#account
Memorial account: https://glitch.social/@TipsyTentacle

**Comment by connyduck** [comment]
done https://github.com/tuskyapp/Tusky/pull/662
