### ISSUE TITLE
[Edge Case Bug] Useless "Show More" button with trailing hashtags

### ISSUE THREAD

**Issue by bannisdale** [tuskyapp/Tusky#4838]
### Detailed description

This is an edge case. :)

Take a long post that isn't collapsed:

![Screenshot_20241229_091603_Tusky](https://github.com/user-attachments/assets/ce8c11b0-14df-4d51-9e2a-2d29c2f1760e)

Now add (more) trailing hashtags:

![Screenshot_20241229_091620_Tusky](https://github.com/user-attachments/assets/677a5d73-ed29-418f-a635-1921e0aabdc7)

There's now a "show more" button, but the whole post is still visible. Clicking it just toggles it but doesn't change anything else:

![Screenshot_20241229_091630_Tusky](https://github.com/user-attachments/assets/853021d1-c255-4a85-be5e-24d961cf3a42)

Obviously only happens on posts with longer character count on the verge of being collapsed while also having trailing hashtags, probably because they count towards the post length.

### Steps to reproduce the problem

1. Take a long post
2. Add a few trailing hashtags
3. Post gets "collapsed" but is still fully visible, just with a useless button

### Debug information

Tusky v27

**Comment by connyduck** [comment]
Can you link me that post, please?

**Comment by connyduck** [comment]
Tests Post: https://akko.chir.rs/notice/ApY4G5teeg7WtFzkEy
Can reproduce the problem, thanks
