### ISSUE TITLE
Empty space added under some toots

### ISSUE THREAD

**Issue by averageunicorn** [tuskyapp/Tusky#485]
I've seen it a few times now, iirc always with short-ish toots. Today with one of my own, so I know that it wasn't due to any intentional weird stuff in it. The space wasn't there in detail view, and later disappeared in the home timeline as well.

Tusky 1.4.1 on Nougat.

![screenshot of home timeline with a toot with a bunch of empty space below the text](https://user-images.githubusercontent.com/10791840/33762522-047b1b56-dc0d-11e7-8790-54c0ccfcc540.png)

**Comment by charlag** [comment]
@averageunicorn as with another problem you reported (with CWs) I think this may happen because rows don't get recycled properly. I wonder what may be the cause.

**Comment by charlag** [comment]
@averageunicorn I would ask you about this one as well. Still happens?
