### ISSUE TITLE
[Feature Request] 24-hour format

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#486]
Right now Tusky shows timestamps with 12-hour time format (e.g. 1 AM, 9 PM).
Is it possible to respect phone settings and show time in "system" format? I don't know whether it's possible or not to get current time format though.

**Comment by connyduck** [comment]
It works on my devices?

![screenshot_20171216-081803_a](https://user-images.githubusercontent.com/10157047/34068797-02274e0c-e242-11e7-9b0b-760c14c77332.png)
![screenshot_20171216-081803_b](https://user-images.githubusercontent.com/10157047/34068798-02401838-e242-11e7-8c46-c8e89eae4e46.png)

**Comment by MasterGroosha** [comment]
Hmm...now I see 24-hour format too. But I'm 100% sure I saw 12-hour format several times. Will try to catch and reproduce it

**Comment by MasterGroosha** [comment]
A small update: just opened the app after not using it for ~12-20 hours and I see "AM/PM" format.
Force closed the app, restarted it and now I see 24-hour format again.

So something is definitely bugged in Tusky, however I'm not sure what exactly :(

**Comment by charlag** [comment]
@MasterGroosha do you still encounter this bug? Sounds like a bug in the OS to me tbh

**Comment by MasterGroosha** [comment]
Oh, I forgot about this issue, sorry.
Haven't encoutered this bug again for now, but I'll watch it carefully
