### ISSUE TITLE
Notification settings: can't turn off vibration

### ISSUE THREAD

**Issue by averageunicorn** [tuskyapp/Tusky#488]
I unchecked "notify with vibration" a while ago, but it still vibrates.

Tusky 1.4.1, Android 7.1.2.

**Comment by charlag** [comment]
@averageunicorn thanks for reporting! Let's see if this got fixed in 1.5

**Comment by averageunicorn** [comment]
Ah, cool, I just checked and this seems to be working now! Thank you!
