### ISSUE TITLE
CWs in fav/boost notifications expanding only at second tap

### ISSUE THREAD

**Issue by averageunicorn** [tuskyapp/Tusky#491]
Sometimes (I haven't figured out the pattern), in notifications for favs or boosts of a toot with a CW, the CW is set to "show less" at first (without the CWed text visible). Tapping it sets it to "show more" (text still hidden), and tapping that opens it as expected.

Tusky 1.4.1, Android 7.1.2.

**Comment by charlag** [comment]
@averageunicorn hi! thanks for reporting. Did you figure out when it happens?

**Comment by averageunicorn** [comment]
No, I didn't figure it out. When it happens, it's (almost?) always in the newest/topmost one, but nothing more specific. And I think it happens less now than when I reported it, but still does now and then.

**Comment by charlag** [comment]
@averageunicorn can you check if it's happening in recent versions? Thanks
