### ISSUE TITLE
Image posting problem

### ISSUE THREAD

**Issue by averageunicorn** [tuskyapp/Tusky#492]
Sometimes, an image isn't posted right. It appears to upload and the URL appears. But in the actual toot, it's not visible, and clicking its link leads to a "The page you were looking for doesn't exist" page.

Example: https://cybre.space/@maunzikation/99223862895799969

Tusky 1.4.1, Android 7.1.2

I'm on cybre.space, but this has only happened for me when using Tusky.

I _think_ that this time I accidentally rotated the phone the first two times (a thing that caused some problems in earlier versions of Tusky iirc), when the image didn't post, and I didn't rotate it the last time. I'm not sure though and I don't remember what I did the other times this happened.

**Comment by charlag** [comment]
Oh, this could happen! Thanks for reporting.

**Comment by averageunicorn** [comment]
(Happened again for me yesterday, again I think I might have accidentally made my phone switch orientation, but I'm not sure if I remember that right. I'm on version 1.5.2 right now.)

**Comment by charlag** [comment]
This might be the case, the app is not really good with screen rotations atm (especially Compose screen)

**Comment by charlag** [comment]
There were a lot of improvements to the compose screen. Does the problem persist in 1.6-1.7? @averageunicorn
