### ISSUE TITLE
Bad assumption

### ISSUE THREAD

**Issue by puckipedia** [tuskyapp/Tusky#494]
https://github.com/Vavassor/Tusky/blob/73342d38cf3bcb41cdef4e05f5c50e05d0005e5d/app/src/main/java/com/keylesspalace/tusky/fragment/TimelineFragment.java#L582-L584

Mastodon says:
> Maximum number of statuses to get (Default 20, Max 40)

emphasis on `Maximum`!

if there's no more `Link` tags, then there are definitely no more posts.
I'm writing an implementation of the Mastodon API and due to the way I filter things, filtering is done *after* getting the posts. This means that sometimes you get less, or even no, posts.

**Comment by charlag** [comment]
Oh, this is a painful thing to write, we made and fixed a lot of mistakes. Can you please propose a correct version, at least in pseudo code or as an algorithm?

**Comment by puckipedia** [comment]
Like how to paginate follower lists etc, you could use the Link header, and as long as there's a rel=next Link header, you know there's probably more statuses.

**Comment by charlag** [comment]
@puckipedia well, unfortunately that doesn't cover the case when we're filling the hole in the middle of timeline.

**Comment by puckipedia** [comment]
I mean, you can still use the max_id and from_id, those work in Kroeg. But it can't guarantee you will get the maximum amount of items in one page. So if you want to know if there's more items, the Link header works, for other cases you can manually generate the url

**Comment by charlag** [comment]
I think we should ask @connyduck because I am bad with timelines

**Comment by puckipedia** [comment]
Tbh this is a super edge case that probably won't ever occur with plain Mastodon servers, but Tusky has been very resilient so far and I've used it to test my Mastodon API compat and I'm really pleased it works as well as it does, so congrats :)

**Comment by charlag** [comment]
@puckipedia thanks! As far as I know it works with Pleroma as well so maintaining compatibility would be nice

**Comment by charlag** [comment]
@puckipedia is this still relevant?
I would support a PR which fixes this (and doesn't break things) but I don't think it's a priority now.

**Comment by charlag** [comment]
I'm closing this for now, feel free to reopen
