### ISSUE TITLE
Feature request: ability to copy text from messages

### ISSUE THREAD

**Issue by moshpirit** [tuskyapp/Tusky#497]
Being able to select some test from any post can be very useful for quoting or just copying a code/phone number/nickname/link/etc.

**Comment by remi6397** [comment]
I did some funny experiments on tusky code and one of them is exactly what you wanted. And this patch adds… only one line! Here you go: https://github.com/remi6397/Tusky/commit/ea5525f10b8922b2f7ccfdc8c85a8a4ed0d40683

**Comment by charlag** [comment]
@connyduck do we want this? We could allow this only in expanded view

**Comment by connyduck** [comment]
We definitely want this. The question is if selectable test or an entry in the overflow menu would be better? 🤔

**Comment by novadeviator** [comment]
Yes please. Inability to select (and copy) text is a major drawback.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/commit/8bca651f536b8034bc113707e2b5535a76227810
