### ISSUE TITLE
Peertube Video Support

### ISSUE THREAD

**Issue by ghost** [tuskyapp/Tusky#503]
Hello,
Do you plan to support the integration of video from Peertube instances?
With kind regards

**Comment by charlag** [comment]
Hi!
Sorry for the late response!
I'm not sure if Peertube has an API already. Maybe you know?
Otherwise embedding things can be quite hard

**Comment by GotExx** [comment]
it seems to me, yes: https://github.com/Chocobozzz/PeerTube/tree/develop/support/doc/api

**Comment by connyduck** [comment]
I am not sure what exactly you want us to support? @GotExx 
Tusky will not become a Peertube client, the Api is completely different. We focus on being a really good Mastodon client.

**Comment by Angristan** [comment]
I don't see what there is to support 🤔

**Comment by lionirdeadman** [comment]
I think he wants support for Peertube embeds like the Webclient has. 

If this is the case, I think it's simply out of scope because it'd require Webtorrent support for it to work as wanted.

**Comment by Angristan** [comment]
I agree

**Comment by GotExx** [comment]
No, I was thinking more of playing a Peertube video directly from Tusky. Currently Tusky gets the title, description and thumbnail of the video.
Currently if we want to watch the video we are redirected to the Peertube instance.

**Comment by Angristan** [comment]
Yes, like YouTube videos right?

**Comment by GotExx** [comment]
Whether it is a Youtube video or Peertube both redirects to the video link.

![screenshot_tusky_20180522-150743](https://user-images.githubusercontent.com/16288145/40364346-62fa4200-5dd2-11e8-8bb0-c88b0f086e3d.png)

![screenshot_tusky_20180522-150818](https://user-images.githubusercontent.com/16288145/40364347-631a985c-5dd2-11e8-99e4-677cce723e85.png)

**Comment by Angristan** [comment]
We should keep it like that. Besides the technical issues associated, I don't even see how that would be an improvement.

**Comment by GotExx** [comment]
This would avoid opening an additional application and I think it brings a gain in the user experience.

**Comment by lionirdeadman** [comment]
Tusky is a mastodon client, it's not a Youtube or Peertube client, it doesn't need to do this. 

What's next? We should support every embed that ever exists because it's posted on Mastodon? 

No, this will only bring a worse experience because it's not the focus of Tusky. Another application would be way more suited for the job than Tusky. (I'd personally recommend NewPipe)

**Comment by FediVideos** [comment]
Can I just check, as it's been many years since this was closed as wontfix, is Tusky still not going to display embedded videos from PeerTube?

Is there a technical reason why the iOS Mastodon clients mostly support PeerTube embedding but Android Mastodon clients mostly don't?

**Comment by connyduck** [comment]
Yes, the reason is that the embedding mechanism is built with web technology, and embedding into apps requires a bunch of hacks like loading a whole browser just to show the embed so we rather don't.

**Comment by FediVideos** [comment]
Okay, fair enough, thanks! That's good to know as some people had been asking, and this helps explain it to them.
