### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by scroom** [tuskyapp/Tusky#506]
Hallo,

I've installed Tusky a few days ago using the Google Play Store and I'm Quote happy with the app (Version 1.4.1).

But I'm missing one thing I would like to use: emoticons. In my messenger apps I can just click on emoticons to insert them. Would be great to be able to do so in Tusky.

I'm using a Oneplus One with Lineage OS 14.1. and the standard keyboard.

**Comment by connyduck** [comment]
You can use standard Android keyboard to input emojis (usually you need to long press Enter), and mastodon custom emojis will have a dedicated input in Tusky 1.6 :)
