### ISSUE TITLE
Tusky crashes 

### ISSUE THREAD

**Issue by moshpirit** [tuskyapp/Tusky#507]
I don't know why, I'm just scrolling down and suddenly it crashes. [This is a screencast I recorded on my phone](https://imgur.com/a/bZ7yn) (velocity of scrolling is definitely not a variable and it always crashes at the same post).

[Picture of my timeline on my desktop](https://i.imgur.com/s1kRqcK.png) (there was no problem loading it)

- [Link to the toot by keel!!](https://mastodon.social/@cutewitchirl/99368536606871881)
- [Link to the post by Eric VA](https://mastodon.mit.edu/@ervanalb/99368058438691597)

**Comment by connyduck** [comment]
Thx for the detailed explanation! Did you use the Playstore version & did you report the bug so I can find the stacktrace? What device did you use?

**Comment by moshpirit** [comment]
No, I'm using F-Droid, so no Play Store.

It's a BQ Aquaris M5.

NewPipe has a feature that help us send a bug report ([see here](https://github.com/TeamNewPipe/NewPipe/pull/224)), maybe there's a way to implement this as well and send it manually by adding a section/button/younameit in the "About" tab

**Comment by charlag** [comment]
@moshpirit hi! Does this still happen to you on 1.5?
