### ISSUE TITLE
Server authentification problem for dtp-mstdn.jp

### ISSUE THREAD

**Issue by iamal** [tuskyapp/Tusky#512]
Server authentification fails. I'm not sure on which side the problem is:
* Authentification with mstdn.osaka works fine
* Authentification at dtp-mstdn.jp works fine with e.g. Mastalab

Version 1.4.1, installed from f-droid on a Fairphone 1 (Android 4.2.2)

Error message (German version): "Diese App konnte sich aud dem Server nicht authentifizieren."

**Comment by charlag** [comment]
That's weird, thanks for reporting!

**Comment by connyduck** [comment]
I guess its a TLS compatibility issue

**Comment by kpleines** [comment]
I seem to have an something similar issue using my nextcloud-Instnace.
Is it possible to enable some debug-logs to get the exact error?

**Comment by charlag** [comment]
It's already writing to the logs. You can either connect with ADB to fetch them or give some app like Matlog permission to read logs (using adb) and check it there.

**Comment by connyduck** [comment]
Nextcloud? I know they want to implement the Mastodon Api but I don't think they already finished that.

http://kpleines.spdns.de/ is not loading at all for me, you might want to look into this first.

**Comment by kpleines** [comment]
@connyduck 
Is it required to route http (Port 80) to my nextcloud? I prefere to only use https (443).

**Comment by charlag** [comment]
it's not but https://kpleines.spdns.de/ does not open either
