### ISSUE TITLE
[BUG] ipv6 drop problem

### ISSUE THREAD

**Issue by nailyk-fr** [tuskyapp/Tusky#514]
Hi, 

I have an issue with picture loading. Sometimes I get no more chance to have picture displayed on the UI, until I force close the app, then open it again. 

My theory is ipv6 related: it looks like there is a DNS cache into the app. 
At home I have full ipv6 support, not at work or in LTE mode. 
While at home, everything goes fine. Then am outside and load over LTE network, I have no pictures (PP or attachment), except the already displayed ones. If I goes at home again, everything load fine after some refresh. 

Only pictures are impacted, all the toots text looks fine. 

Sorry if it is not clear, am not good at English writing :)
Feels free to ask explanations.

**Comment by charlag** [comment]
Thanks for reporting! Good guess I would say. Could you specifiy you Android and Tusky versions ans phone model?

**Comment by nailyk-fr** [comment]
Sure. 
OmniRom 8.1.0-20180202-z3-nailyk
About Tusky am unsure. Probably built here https://github.com/Vavassor/Tusky/tree/2eaf727a1db49062e0f6b66c35259a1f7a8ad459

Will try to get a log while at home tonight.

**Comment by nailyk-fr** [comment]
Sorry, there is nothing into logs :s
I tried to set `public static final boolean DEBUG` to `true` into `app/build/generated/source/buildConfig/*/release/com/keylesspalace/tusky/BuildConfig.java` but nothing more into logs...

**Comment by connyduck** [comment]
To get logs you need to use the debug build type and probably enable picasso logging in app/src/main/java/com/keylesspalace/tusky/TuskyApplication.java (add the line `builder.loggingEnabled(true);`)

**Comment by nailyk-fr** [comment]
Thanks for the hints! 
FI: added the tusky debug with your 'patch' ( https://github.com/nailyk-fr/jenkins_scripts/blob/fdroid/k_tusky.sh ) on my fdroid repo:  / https://releases.nailyk.fr/repo/ . 
Gonna try this again while at home.

**Comment by nailyk-fr** [comment]
Here is the log:
[2018-02-08-19-40-04.txt](https://github.com/Vavassor/Tusky/files/1708373/2018-02-08-19-40-04.txt)
However it does seems to show an error. It looks like the opposite: report successful download of avatar or pictures but nothing was shown. 
Log is after switching from wifi to LTE, scroll a bit, notice missing avatar pictures, click on one picture (the 'window' is shown empty). 
wifi -> lte: 
![screenshot_tusky_20180208-194904](https://user-images.githubusercontent.com/16372405/35992139-b68884b4-0d09-11e8-8740-5d1c43acf035.png)

switching back to wifi: 
![screenshot_tusky_20180208-195046](https://user-images.githubusercontent.com/16372405/35992151-bfe797f2-0d09-11e8-8e9a-4473f443f2f8.png)

Am wondering if it is ipv6 related. At work there is no ipv6 and switching from work wifi to LTE produce the same (a bit less predictable however)

Feel free to ask more tests/logs.

**Comment by charlag** [comment]
@nailyk-fr hey! I would ask if it's still happening. I still have no idea how Tusky can have anything to do with it

**Comment by nailyk-fr** [comment]
Hello, 
Sorry but I am not able to help you more on this as I do not have mastodon account anymore...
You should be right and, as nobody seems to have connectivity issue, it should have been a false report. 

Sorry for the noise...

**Comment by charlag** [comment]
Hey
No problem
Sad to see you go
