### ISSUE TITLE
Possibility to competely disable background sync

### ISSUE THREAD

**Issue by nobse** [tuskyapp/Tusky#518]
Currently the background sync can only be configured between 15 minutes and 2 hours. It would be nice to have the possibility to completely disable background sync.

**Comment by connyduck** [comment]
If you are on Android < O you can disable notifications for all accounts and Tusky will not do any background syncing. But the behavior on O+ is different, I will fix this.

**Comment by connyduck** [comment]
It now works on all Android versions: If you have notifications disabled, no background sync is started.
