### ISSUE TITLE
Decrease the Font Size

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [tuskyapp/Tusky#520]
Please decrease the font size of datestamp, timestamp, and the name of the client that appear at the bottom of a toot. They make reading toots difficult.

**Comment by connyduck** [comment]
Does the font size setting in the preferences not work for you? Why not?

**Comment by iknownothingaboutcomputers** [comment]
@connyduck No, I wasn't talking about status text size. I meant reducing the size of the date, time and client name that show up below every toot b/c I feel they kinda take the focus away from the main body of a toot. The status text size should always be bigger than other less important info.

**Comment by connyduck** [comment]
We could increase the font size of the detailed toot, like the Twitter app does it 🤔

**Comment by connyduck** [comment]
Actually, we had a bigger font size on the detailed toot, but that got lost when we introduced the font size setting. I fixed that, it should now be better to read https://github.com/tuskyapp/Tusky/commit/14439c016c2f59c6d2f3efa3ca42da67f826490d
![screenshot_20180217-135343](https://user-images.githubusercontent.com/10157047/36341158-24adf744-13ea-11e8-8c13-8034a767114c.png)
