### ISSUE TITLE
Timeline Filtering in Profile TL

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [tuskyapp/Tusky#527]
Need the same Show/Hide Boosts/Replies option for Profile TL as well.

**Comment by iknownothingaboutcomputers** [comment]
Profile TL is a cluttered mess. Hope to see this feature in the near future.

**Comment by iknownothingaboutcomputers** [comment]
@connyduck Profile TL is a cluttered mess. Hope to see this feature in the near future.

**Comment by charlag** [comment]
@iknownothingaboutcomputers hi! Why do you think it's a mess? How do we improve it? Let's be constructive please

**Comment by Lionirdeadman** [comment]
I think they mean that it's messy because of the boosts and replies shown on the profile TL.

Mastodon also allows to this and therefore we should implement it.

I'm not sure which way would be more appropriate though.. Do we mimic Mastodon or do we put it in the settings? 

(I would opt for mimicking since it allows more flexibility and is more intuitive)

**Comment by iknownothingaboutcomputers** [comment]
@charlag I think it's a mess because of all the replies that show up on my Profile TL. There's no option to hide them, unlike Home TL.

When I was a Mastalab user, I could hide them by long-pressing on the 'Profile' tab in Profile TL and deselecting boosts, replies. It'd revert to its default state (of showing all the clutter) after exiting so it only worked partially. Don't know if it's been fixed.

How about making the options under 'Tabs' work their magic on Profile TL as well?

**Comment by charlag** [comment]
@iknownothingaboutcomputers there are two tabs in profile: with and without replies. I would say that this is enough because profile is not intended to be used as a primary means of checking toots but only as accidental one.
Feel free to reopen if you disagree.
