### ISSUE TITLE
Make attachment scrollable when composing toot

### ISSUE THREAD

**Issue by novadeviator** [tuskyapp/Tusky#530]
When attaching an image to a toot the area where the text is being written is extremely small. The position of attached image is fixed and always visible above the keyboard which leaves about 4 lines of text visible and scrollable which is not much. 

Perhaps this can be improved upon by fixing the attached image(s) to the bottom of the text so it's part of the scrollable buffer and becomes only visible when users scrolls to the end of the text.

**Comment by charlag** [comment]
Yeah, it's a problem, I agree. We probably should make whole content scrollable because the same thing happens when you expand toot you reply to.

**Comment by connyduck** [comment]
this is fixed in Tusky 1.6
