### ISSUE TITLE
Batch notification sounds

### ISSUE THREAD

**Issue by LogicalDash** [tuskyapp/Tusky#531]
Getting one notification chime per event isn't very useful when I'm only updating every 15 minutes. With every update, I get 10 or 20 chimes.

Please give me the option to get only one notification when I have new replies.

**Comment by charlag** [comment]
Hi
I think it works this way for me.

**Comment by LogicalDash** [comment]
I use OxygenOS 5.0.1, which is Android 8.0.0, on a OnePlus 3T, and installed Tusky through the Play Store. I get one notification chime per reply, though this doesn't always seem to result in anything showing up in the toaster -- which might be a different bug?

**Comment by LogicalDash** [comment]
Ok, I was confused -- it only shows the one notification in the toaster, but I get multiple chimes for some reason. This doesn't seem very useful.

**Comment by connyduck** [comment]
This should be fixed. Please try the next release and confirm. https://github.com/tuskyapp/Tusky/commit/550235d40b9eb3162ea707342d8afc001d02f37a

**Comment by LogicalDash** [comment]
It's fixed and I forgot all about this, sorry
