### ISSUE TITLE
Get default post privacy from the API

### ISSUE THREAD

**Issue by ashkitten** [tuskyapp/Tusky#534]
Instead of having to specify default post privacy in the settings, Tusky should instead fetch it from the API - https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#getting-the-current-user

**Comment by connyduck** [comment]
Yes, this would be super nice, but then we cannot set the default privacy in Tusky anymore.
There is already an open ticket for the mastodon api https://github.com/tootsuite/mastodon/issues/6553

**Comment by ashkitten** [comment]
We could remove that and add something in the preferences that just loads a webview with the mastodon preferences for now

**Comment by charlag** [comment]
@ashkitten seems like too much work (extremely hacky work) for such a minor thing

**Comment by connyduck** [comment]
There is an open PR on mastodon for this feature https://github.com/tootsuite/mastodon/pull/6789

**Comment by ariasuni** [comment]
Now that tootsuite/mastodon#6789 is merged, this should not be hard. However, since it is a setting that is tied to an account, there probably should be an account preference screen (which could be used for #670 too).
