### ISSUE TITLE
Group notifications, Android N style

### ISSUE THREAD

**Issue by ashkitten** [tuskyapp/Tusky#535]
Pretty self-explanatory - notifications should be separate but grouped if there are more than a couple. I'd offer help but I haven't worked with Android in over a year and have no idea how to work with the new APIs ¯\\\_(ツ)\_/¯

**Comment by charlag** [comment]
Hi, thanks for reporting! To be honest, I've got no idea either but @connyduck seems to be fluent with them.
I am not sure but I think they already pack?

**Comment by ashkitten** [comment]
The notifications just pack into one notification, but aren't expandable like notification groups

**Comment by RX14** [comment]
This is a feature I can't live without coming from tootdon.

Notifications pack away nicely:
![](https://my.mixtape.moe/mhhxcg.png)

But expand properly when you want detail:
![](https://my.mixtape.moe/kgrlgm.png)

Tusky's notifications have none of the useful information I want to see when triaging my notifications:
![](https://my.mixtape.moe/esxnpg.png)

This makes me sad :(

**Comment by RX14** [comment]
Tootdon's notifications are absolutely perfect, if tusky could copy them exactly I'd switch instantly. Without, i'm stuck on closed source software it's *that* important to me :(

**Comment by remi6397** [comment]
I'm interested in this feature too. It looks relatively easy to implement. I'll try to look into it. 😉
