### ISSUE TITLE
Account on Inaccessible Server prevents switching to other accounts

### ISSUE THREAD

**Issue by sanloublues** [tuskyapp/Tusky#536]
If you have multiple accounts and your active account is on a server that is temporarily down, you are unable to switch to other accounts unless you log out.  The profile icon area in the top of the left menu renders no content until the server comes back online or until you log out.

**Comment by charlag** [comment]
Hi! Thanks for reporting. I was bitten by it myself and it should totally be fixed! There's tons of work on multiaccount to be done.

**Comment by connyduck** [comment]
fixed it https://github.com/tuskyapp/Tusky/commit/86de51ede5020247d09b8b9031cfaa746d958f9b
