### ISSUE TITLE
[Feature request] Media tab: Add a way to get to the whole toot

### ISSUE THREAD

**Issue by averageunicorn** [tuskyapp/Tusky#545]
Right now, the media tab on profiles shows all the media, but there is no way to see the original toot that the media is from (to read any text that there might have been or to boost/fav). Having a way to do that would be great :)

**Comment by charlag** [comment]
Yes, totally, I am annoyed by this as well. We need to change some things about the gallery for this to work properly, unfortunately, but I want it too :)

**Comment by connyduck** [comment]
fixed https://github.com/tuskyapp/Tusky/pull/630
