### ISSUE TITLE
Errors occurs during thread view on Pleroma

### ISSUE THREAD

**Issue by lambadalambda** [tuskyapp/Tusky#546]
When viewing a conversation on Pleroma, the "an error occured" message pops up, even though the thread view loads and looks fine. I can't find any error in logcat.

**Comment by connyduck** [comment]
This is because Pleroma does not implement the `/api/v1/statuses/{id}/card` endpoint.
I added a workaround so Tusky fails silently when the card cannot be loaded. https://github.com/tuskyapp/Tusky/commit/44b79e31d4195b06bfbd279933c6281a45ee9fe4

**Comment by lambadalambda** [comment]
Thanks!
