### ISSUE TITLE
Thread/conversation not updating after replying

### ISSUE THREAD

**Issue by mbirth** [tuskyapp/Tusky#552]
After I've sent a reply, the thread doesn't update to show my reply. I have to refresh manually to make it show up.

* * * *
- Tusky Version: 1.5.2
- Android Version: 7.1.1
- Android Device: BlackBerry KEYone
- Mastodon instance (if applicable): mastodon.social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi,thanks for reporting!
You're right, it's not there yet, I want it myself.

**Comment by charlag** [comment]
It does update as for 1.7.0 but it refreshes whole thread, #562 will improve things
