### ISSUE TITLE
Silly scrolling issue

### ISSUE THREAD

**Issue by clarcharr** [tuskyapp/Tusky#553]
Flicking the timeline down and then pressing the home button jumps to the top of the timeline, without removing the existing momentum. The side effect is that it doesn't stop at the top, but keeps scrolling down.

* * * *
- Tusky Version: 1.5.2
- Android Version: 7.0
- Android Device: Galaxy S7

**Comment by connyduck** [comment]
Haha nice find. Fixed it https://github.com/tuskyapp/Tusky/commit/720f7c6a0cbc99acd6809663be551401dbd8db86
