### ISSUE TITLE
Feature request: add regular expression feed filtering as available in Mastodon web

### ISSUE THREAD

**Issue by forty8bits** [tuskyapp/Tusky#555]
The regular expression feed filtering in Mastodon web is really useful and something I miss sorely in Tusky. I recommend sharing a single regular expression filter throughout all feeds, [as I hope is implemented in Mastodon web](https://github.com/tootsuite/mastodon/issues/3848#issuecomment-377632216), both to reduce unnecessary complexity and to improve UX.

**Comment by charlag** [comment]
Hi, thanks for reporting!
I think that this is a valid case and it shouldn't even be too hard to implement but I'm not sure how it could fit into UI yet. I'm also not sure either of us have time on this now. Would you consider giving us a hand with this?

**Comment by forty8bits** [comment]
Sure, I can at least take a look at the code and see if I can make a contribution. It's been a few years since I've developed for Android and I've never used Kotlin though, so no guarantees.

**Comment by charlag** [comment]
Okay, cool! I think those timeline parts don't use Kotlin but if you have any problems feel free to poke me 😃
