### ISSUE TITLE
Long bios get cut off, username domains removed when editing

### ISSUE THREAD

**Issue by noiob** [tuskyapp/Tusky#561]
Awoo has longer-than standard bios (a lot of instances do) and whenever I edit it in Tusky (even if I just edit my username since it's all one form) it gets cut off and I have to retype the end of it.

Also I link to my alt accounts in my bio but Tusky seems to remove the domain parts.

I'm not sure if this needs to be adressed client-side but Glitch Social (the mastodon fork) has a [metadata function](https://glitch-soc.github.io/docs/features/profile-metadata/) and I think it also breaks somehow by editing the bio in Tusky. I know you don't need to support forks but if you wanna I'm sure the glitchsoc folks would be happy to give you info on it.

**Comment by noiob** [comment]
I think Tusky loads/ processes the bio in a way that turns @noiob@cybre.space into @noiob? It's the loading  part that screws up the usernames, anyways. Check my bio (how it should be) at [awoo.space/@noiob](https://awoo.space/@noiob)

I think the table markup gets processed whenever the bio text is saved, so this might be more complicated to fix. I haven't done extensive testing on that part. I could get someone an awoo.space account for testing (or just make one on dev.glitch.social, it's pretty much the same software)

**Comment by charlag** [comment]
If it's the loading part then I don't really understand... here's profile in the web, it is cut off too?

![screenshot from 2018-04-05 08-55-59](https://user-images.githubusercontent.com/3099142/38349335-35aa8438-38af-11e8-841f-9c42a4df44dc.png)

I don't think we do much processing on our side while loading. We receive HTML, all we do is look for mention/hashtag links and remove underlines, that's it, if I understand correctly.

I didn't investigate editing, though,

**Comment by noiob** [comment]
This is how it looks when I open it to edit in Tusky:

![grafik](https://user-images.githubusercontent.com/8197071/38349811-01e21162-38a9-11e8-9b7a-2d5c2e6a10fc.png)

Yes, that is the whole text, and it will save like that, so without the domains

**Comment by charlag** [comment]
I see now, thanks!

**Comment by connyduck** [comment]
I fixed the "usernames not resolving" part https://github.com/tuskyapp/Tusky/commit/21344866d3899aee07e229a27cf3829102522a78

Not sure what to do about the length of the text though. We could make the input field unlimited length and then show the error message the server returns (which is in the servers default language)?

**Comment by noiob** [comment]
Maybe the Mastodon API needs a way to report the length? Showing the error message is probably a good quick fix

**Comment by charlag** [comment]
- [x] Usernames resolved while editing
- [ ] Calculate length as server does / return error instead of counting chars

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/751 will remove the length validation on client side but will instead show the server error.
