### ISSUE TITLE
Inconsistencies in the German translation

### ISSUE THREAD

**Issue by jaller94** [tuskyapp/Tusky#566]
The following terms have inconsistent translations in the German translation:
https://github.com/tuskyapp/Tusky/blob/master/app/src/main/res/values-de/strings.xml

I would fix those myself, however, I haven't used an operating system in German within the last 10 years so my UI German is a bit outdated.

### `Toot` as "Toot" and "Tröt"
Whereas I like the Germanized Tröt better, I wonder if it is commonly used in the German community.

### `sensitive media` as "Heikle Inhalte" and "NSFW-Inhalte"
I dislike "NSFW-Inhalte" because it's an abbreviation of English words and only known in the Internet/tech-savy German community. Is "Heikle Inhalte" a commonly used term? Does Android have a term for sensitive media?

### `report` as "melden" and "berichten"
Only "melden" seems correct to me in the context of UI language.

### `follower` as "Follower" and "Folgende"
How does one deal with those term where the English word is used more often and more accurately than the German?

**Comment by charlag** [comment]
My German absolutely sucks but I guess we have enough German speakers here, so, figure it out, y'all!
(I think we can look up translations in the Mastodon)

**Comment by jaller94** [comment]
Good idea!

From the [Mastodon repository](https://github.com/tootsuite/mastodon/blob/master/config/locales/de.yml):
- Toot: der Beitrag
- (to) toot: teilen (rarely: posten)
- Sensitive media: Heikle Inhalte
- (to) report: melden
- Follower: die Folgenden
