### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by chloeboulez** [tuskyapp/Tusky#570]
To be able to see how many retoots and likes a post got (tracking)
To be able to "quote" a toot
To have recommended popular Tooters to follow and toots to see

* * * *
- Tusky Version: 1.5.2
- Android Version: 8.0.0
- Android Device: Note8
- Mastodon instance (if applicable): switter.at

**Comment by charlag** [comment]
Hi, thanks for reporting!
Let's break them one by one.

1. What do you mean by tracking? You would like to see numbers on posts? We're trying to follow mastodon.social here. I personally believe that after some time needed to adapt I look at content more and not just skip over everything without much favs. I think it's possible to add this as option but I am not sure about it.

2. We could consider this but again I would follow upstream here: quoting does more harm than gold most of the time.

3. I don't think we (the app) can do this, it needs to be done on server and it needs some algorithms and analyzing user behavior and I think that it goes against Mastodon values.

Sorry for being such a show-stopper but there are always drawbacks and we're trying to keep balance

**Comment by chloeboulez** [comment]
Hi Ivan,

I'm sorry maybe I misunderstand, are there a set off guiding principles
somewhere?

C

**Comment by charlag** [comment]
I'm not sure they're formalized somewhere, it's mostly from reading about Eugen's decisions I guess... but it would be cool to list them somewhere.
