### ISSUE TITLE
Updating translation

### ISSUE THREAD

**Issue by BoFFire** [tuskyapp/Tusky#577]
Hi,
New arabic translation, here values-ar :
https://gist.github.com/b4e856bf8a3199ef72f9b91e32140708

Pull Request failed. I'm noob on Github.
Have a nice day :)

**Comment by connyduck** [comment]
Did you use stringlate? Seems like it is handling some stuff incorrectly, we had the same problem with Russian today.
Thx so much anyway!

**Comment by BoFFire** [comment]
Yep done with stringlate.
