### ISSUE TITLE
I want to help with Dutch translations and other languages when needed

### ISSUE THREAD

**Issue by littlebelgianwriter** [tuskyapp/Tusky#579]
[How can I help you with Dutch translations? I also speak French and German. I can do the following language pairs: English to Dutch/ Dutch to English/ French to English/ German to English/ French to Dutch/ German to Dutch].

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This is very nice of you! The dutch translation is quite outdated.

You can either edit the translation file directly (here is the english one that has all strings https://github.com/tuskyapp/Tusky/blob/master/app/src/main/res/values/strings.xml , here the incomplete dutch one https://github.com/tuskyapp/Tusky/tree/master/app/src/main/res/values-nl ), or [use Stringlate](https://f-droid.org/en/packages/io.github.lonamiwebs.stringlate/).

When translating, try to use wordings similar to web mastodon, some strings can even be identical.

**Comment by littlebelgianwriter** [comment]
Thank you for the links! I am currently finishing another 'project'. Will likely start on your files tomorrow and keep you updated of course!

**Comment by littlebelgianwriter** [comment]
The translation is finished.
I hope that you can find it here: https://github.com/tuskyapp/Tusky/pull/586/files#diff-01dafb3fd0217441330103cfc8300094
