### ISSUE TITLE
Add media bar stays in middle of screen

### ISSUE THREAD

**Issue by sammy8806** [tuskyapp/Tusky#581]
If you need to grant the media permission the first time, accept it and simply go back without attaching media the menu is stuck on the screen (but works) and gets reset if you use it and attach something

For this to happen the on-screen keyboard must be active and visible.

Could be a timing thing where the bar couldn't get to the bottom before the Permission-UI comes and stopps the animation?

https://www.youtube.com/watch?v=p2gEzLAIU0E
![f6ea69caa12dc1f1](https://user-images.githubusercontent.com/1584070/38779933-a08981d2-40cf-11e8-98f3-fe76684d2366.png)
![914eefc719bb4228](https://user-images.githubusercontent.com/1584070/38779932-a0125b84-40cf-11e8-93a7-f69822406dba.png)

* * * *
- Tusky Version: 1.6.0-8acee3c (GPlay & Git)
- Android Version: 6.0.1, 7.1.2, 8.0.0
- Android Device: Samsung Note4 (Stock), Samsung Galaxy S5 (LinageOS 14.1), Android Emulator (8.0.0)
- Mastodon instance (if applicable): Layer8.Space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Thanks for reporting! Yeah, permission popup is actually another window, we should check that.

**Comment by mihudevcom** [comment]
@sammy8806 I've tried to reproduce it on Android 8 emulator and my device but it doesn't seem to happen anymore. Can you confirm that the latest version still has this issue?

**Comment by sammy8806** [comment]
@mihudevcom It's working *most of the time* now ... but I can still get it sometimes (for ex. after declining the permissions the first time)

![screenshot_20190222-164050_paket-installer](https://user-images.githubusercontent.com/1584070/53253317-36f31880-36c1-11e9-98c0-91d746c03aa7.png)
![screenshot_20190222-164058_tusky](https://user-images.githubusercontent.com/1584070/53253331-3d819000-36c1-11e9-823a-538983cbcefe.png)

---

Tusky Version: 5.0 (PlayStore Beta 21.02.19)
Android: 8.1.0 (LineageOS 15.1)
