### ISSUE TITLE
Problem Uploading Videos

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [tuskyapp/Tusky#582]
Getting an error while uploading .mp4 videos downloaded from Twitter. Also, Tusky won't upload videos > 4MB in size even though the max limit is 8MB on my instance.

* * * *
- Tusky Version: 1.5.2
- Android Version: 5.1
- Android Device:
- Mastodon instance (if applicable):

**Comment by connyduck** [comment]
Yes please update to 1.6 (will be available in a few days on all stores) and then try again.

**Comment by iknownothingaboutcomputers** [comment]
@charlag @connyduck Yes, new update has fixed this issue. Closing it.
