### ISSUE TITLE
Quick Settings tile "Compose Toot" should prompt to select account

### ISSUE THREAD

**Issue by remi6397** [tuskyapp/Tusky#584]
It can be resolved in several ways, for example:
- by having different QS tiles for each account (not a good idea IMO),
- by showing an account selection dialog, maybe even with optional default account selection,
- by making the avatar on ComposeActivity clickable to show a popup,
- by completely removing QS tile and moving Compose action to [App Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts.html), one shortcut for each account.

**Comment by charlag** [comment]
Hi!
It's planned!
#558
