### ISSUE TITLE
External apps from file picker

### ISSUE THREAD

**Issue by Eskuero** [tuskyapp/Tusky#588]
When I'm writting a new post and I want to add a picture to it I use the built-in button.
This inmediately pops the file picker, however it's quite hard to navigate between albums from there and gifs take a lot to preview so I usually just jump to my gallery app from there to select a picture.
However when opening the file picker from Tusky I cannot see any option to open a different app (only Termux shows up wtf).

Screenshot when file picker is opened from Tusky vs Twidere:
![screenshot_20180418-192943](https://user-images.githubusercontent.com/1757242/38951508-5f47c4c0-4338-11e8-9d74-29219018e7dc.png)![screenshot_20180418-192933](https://user-images.githubusercontent.com/1757242/38951517-65830246-4338-11e8-8ef9-c1c4b325f149.png)

* * * *

- Tusky Version: 1.6.0 (F-Droid)
- Android Version: 7.1.2 (LineageOS based)
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
That's weird, thanks for reporting! What is your gallery app?

**Comment by connyduck** [comment]
Thats because we fire the `"android.intent.action.OPEN_DOCUMENT"` intent to open files and it looks like the gallery app does only implement the older `"android.intent.action.GET_CONTENT"`.
We can't easily change that, because `"android.intent.action.OPEN_DOCUMENT"` is necessary for the `ContentProvider` stuff we do in `SaveTootHelper`.

**Comment by Eskuero** [comment]
It's the Simple Gallery avalaible on F-Droid, there's a whole suite of apps like that.
May it be possible to fix it on your side? @tibbi

**Comment by tibbi** [comment]
I created an issue for it, Ill take a look at it someday.

**Comment by Eskuero** [comment]
Fair enough, thank you all for your time and work!

**Comment by charlag** [comment]
I guess we cannot do much at this point? Feel free to reopen if you have any questions

**Comment by tibbi** [comment]
Well it looks like none app that I have installed handles the open_document intent. I dont really plan adding open_document handling either, apps just usually dont do that. It is handled by the system, like on the screenshot.
