### ISSUE TITLE
"Sending Toot..." notification hangs indefinitely

### ISSUE THREAD

**Issue by davgordo** [tuskyapp/Tusky#589]
Since a couple days ago, when I post a toot, it is sent successfully, but the Android notification hangs with the text "Sending Toot...". As far as I can tell, it hangs indefinitely (at least 30+ minutes), but then again, I have notification OCD, and I kill it by any means possible.

![tusky-notification-20180418](https://user-images.githubusercontent.com/14282991/38968195-618c7c74-4358-11e8-8ec3-0d8eb8923dbe.png)

* * * *
- Tusky Version: 1.6.1
- Android Version: 8.1.0
- Android Device: Pixel 2
- Mastodon instance (if applicable): toot.cafe

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi, thanks for reporting! I think @connyduck is already fixing it
https://mastodon.social/@ConnyDuck/99882348784791483
