### ISSUE TITLE
Confusing phrasing on leaving compose opened from drafts

### ISSUE THREAD

**Issue by charlag** [tuskyapp/Tusky#595]
When we open a toot from drafts and then leave the compose scrern, we're presented with two options: save draft or delete draft. If you press delete it won't actually delete the draft, it just won't save changes you've made.
I've been working on this dialog and it confused even me because I expected the draft to disappear from the list!
I don't think we should change how it works but we should probably change phrasing on a button to something like "don't save changes"

* * * *
- Tusky Version: -
- Android Version: -
- Android Device: -
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ariasuni** [comment]
«Cancel» would work: cancel writing the toot/updating the draft.

**Comment by TheOtherDoctor** [comment]
Has this been changed? I just re-checked (in tusky 10.0) the behavior when editing a previously created draft, adding some text and then exiting with "delete" - the respective draft is now entirely gone, the behavior being now like expected in the original post.

Thus it looks to me the "discard changes" option does not really exists (anymore)?
As I often mess up something during edit, I'd see this as a missing point.

If it could be changed to cover this option, I'd propose to change the text from "save draft?" to "save changes to draft?" - then the choices could be "discard" or "save". Wouldn't that be better?

**Comment by charlag** [comment]
It's a bug with compose screen currently I believe

**Comment by ariasuni** [comment]
Do you think adding a “Discard changes” along with the existing “Delete” and “Save”? If yes, that sounds like something I could do.

**Comment by ariasuni** [comment]
Any idea how to fix this? Do you have an opinion on my proposed solution in the comment above?

**Comment by TheOtherDoctor** [comment]
I'd think the proposal to add "discard changes" option would be an good improvement in usability for the compose dialog. Just checked to confirm: the behaviour in tusky 12 today is still as observed with tusky 10 in April.

**Comment by Tak** [comment]
#1744 might be relevant here

**Comment by ariasuni** [comment]
Maybe we should close this issue since #1744 has been merged? And maybe open a new one if the current behavior is still not considered as ideal.

**Comment by Lakoja** [comment]
"Delete" is gone from that dialog (by some other issue/PR).
