### ISSUE TITLE
"Sending toot..." doesn't always disappear when it should

### ISSUE THREAD

**Issue by clayote** [tuskyapp/Tusky#598]
Sometimes I'll compose a toot, send it, and get the "Sending toot..." notification. Then I'll refresh my timeline and see my toot there, but "Sending toot..." never goes away.

I thought this was related to spotty connectivity at first, but then it happened while I was on my home WiFi once. Only once, though. Not sure how to diagnose further.

* * * *
- Tusky Version: 1.6.1
- Android Version: 8.0.0
- Android Device: onePlus 3
- Mastodon instance (if applicable): cybre.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by LogicalDash** [comment]
ah, sorry! I left the is:open filter on by mistake
