### ISSUE TITLE
actions across accounts

### ISSUE THREAD

**Issue by novadeviator** [tuskyapp/Tusky#601]
Better incorporate cross-account actions, for example:

- when looking at a toot, 
  - an entry in the _toot's menu_ "open with account >" or similar
  - _long press_ on reply/boost/fave and choose from a menu with which account you want to perform this action.
- when looking at someone's profile, its menu should  offer "Open with >" or "Open with account >"

(if the idea is interesting, perhaps these should be split into separate tasks/issues?)

* * * *
- Tusky Version: 1.7.0

**Comment by novadeviator** [comment]
ok, looks like another idea ("follow with account >")  connected to these above was already expressed in #517

**Comment by charlag** [comment]
I've merged it into #517
