### ISSUE TITLE
[Feature] Block entire Mastodon instance

### ISSUE THREAD

**Issue by heyitswither** [tuskyapp/Tusky#602]
I'd rather not have to see toots from users of switter.at

**Comment by Lionirdeadman** [comment]
@heyitswither, You can do that in the WebUI in case you didn't know.

(While you wait for this feature in Tusky)

**Comment by heyitswither** [comment]
@Lionirdeadman how would I go about doing that?

**Comment by Lionirdeadman** [comment]
@heyitswither,

Go to someone's profile from that instance, click on menu where you'd find mute and block then select "Hide everything from switter.at".

**Comment by charlag** [comment]
So, it is controlled on the server side, right?

**Comment by Lionirdeadman** [comment]
Yeah, it's server-side. Just like the muting and blocking features. 

There may or may not be an API request to do this though.

**Comment by charlag** [comment]
I'm pretty sure there isn't (even if there is, it's not a priority). Thanks.

**Comment by Lionirdeadman** [comment]
Actually, looks like that API exists.. [here](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#blocking-a-domain) therefore it should indeed be reopened until it's done.

**Comment by heyitswither** [comment]
That is correct

**Comment by charlag** [comment]
It's a duplicate of (much older) #301 so I'm closing this in favor of that issue.

**Comment by LostCreed** [comment]
Hiding is not blocking.
