### ISSUE TITLE
Support Account-Fields

### ISSUE THREAD

**Issue by sammy8806** [tuskyapp/Tusky#604]
In the upcoming Mastodon release there is a feature for custom fields in account-profiles, which already exists in glitch for some time. https://github.com/tootsuite/mastodon/pull/6645

It would be nice if this could be shown in a somewhat elegant way and also be __edited__ again.

![profil](https://user-images.githubusercontent.com/1584070/39278300-ba7fc8a0-48f2-11e8-98cb-22040b840565.png)

---
### Some random additional information

* An additional key in the `Account` has been created: `fields`
* The number 4 is arbitrary and it's saved as a single field of json

`/api/v1/accounts/:id`
```json
{
  "id": "1",
  "username": "sammy8806",
  "url": "https://dev.layer8.space/@sammy8806",
  "...": "...",
  "fields": [
    {
      "name": "Main-Instance",
      "value": "<a href=\"https://layer8.space\" rel=\"me nofollow noopener\" target=\"_blank\"><span class=\"invisible\">https://</span><span class=\"\">layer8.space</span><span class=\"invisible\"></span></a>"
    },
    {
      "name": "Main-Account",
      "value": "<span class=\"h-card\"><a href=\"https://layer8.space/@Sammy8806\" class=\"u-url mention\">@<span>Sammy8806</span></a></span>"
    }
  ]
}
```

----------------------
- [ ] Displaying fields
- [ ] Editing fields

**Comment by connyduck** [comment]
read support for Account fields has been implemented in https://github.com/tuskyapp/Tusky/pull/662
to do: add support for setting account fields
