### ISSUE TITLE
Adding a per user "show sensitive content" option

### ISSUE THREAD

**Issue by phikal** [tuskyapp/Tusky#607]
Extending issue #385, I wanted to suggest an option, to automatically show "hidden content" (see for example [this account](https://high.cat/@archillect)), _but_ on a per-user basis, since there are certain accounts I know won't disturb me, but use this option on all their posts anyways, and others which most certainly do, which I would very much want to hide.

**Comment by charlag** [comment]
Hi! Thanks for reporting. We should consider that. I think this is a valid use-case but I think it's kinda low-priority (unless someone jumps in with implementation).
Thanks for understanding.

**Comment by connyduck** [comment]
Do you mean you want to set the option **per each account you are logged in with**? We can do that.
Or do you mean you want to have the option **for each other user you follow** in the fediverse? Because thats definitely out of scope for Tusky.

**Comment by mal0ki** [comment]
Can this be combined with clarifying the language of this setting? 

https://github.com/tuskyapp/Tusky/issues/814
