### ISSUE TITLE
Scrolling in profiles does not pull up the header (in current master build)

### ISSUE THREAD

**Issue by C1710** [tuskyapp/Tusky#612]
So I just found a bug that if you go to a user page and try to scroll through the user's toots without raising the finger, instead of pushing the header image, etc. up, you'll just scroll thorugh that small part in which the toots are shown.  
This is not the case in the 1.7 build.
Here's a screencast of it (sorry for the bad quality 😅):
https://drive.google.com/open?id=1LLD5HkDAAvhCA60-8xKdYgClP0G4rZgb

* * * *
- Tusky Version: Current Master build (3dfe43dfb2b7712ae9eceff18c07b534b9f63d65)
- Android Version: 7.1.2
- Android Device: Moto Z2 Play
- Mastodon instance (if applicable): mastodon.xyz

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi!
Thanks for reporting. We've already noticed it and we have a possible fix.
But I thought that it doesn't happen in release builds, only later 🤔

**Comment by C1710** [comment]
As I already stated, it's _not_ the release build which is affected 😅
