### ISSUE TITLE
Tusky logo design

### ISSUE THREAD

**Issue by harunbadilli** [tuskyapp/Tusky#614]
I designed a logo for the tusky app. I have made it more understandable by placing the initials of the simple and remarkable appearance and now you want the design is ready to be sent any size. Choose whichever you want to use.
![1](https://user-images.githubusercontent.com/34319922/39401137-052248a0-4b47-11e8-81fc-1316902eaa1b.png)
![2](https://user-images.githubusercontent.com/34319922/39401138-05588c26-4b47-11e8-8b91-eabfc2a78034.png)

**Comment by charlag** [comment]
Hi!
Thanks for your concepts.
I cannot tell if it will be used - we need a lot of input about this.
To me, personally, it looks a little bit defensive - like a shield. Also T resembles a sword. I'd rather see Tusky as a friendly thing. But again, it's my personal opinion.

**Comment by connyduck** [comment]
Thx that is very nice of you.
When I took over the project, I also wanted to introduce a new logo, but trust me, users love the current one.
