### ISSUE TITLE
Spacing incorrect in thread view depending on font size

### ISSUE THREAD

**Issue by beta-phenylethylamine** [tuskyapp/Tusky#615]
Depending on font size, the spacing between the highlighted post's profile picture and text can become smaller than I believe is intended or looks good. Example:

Small text size
![screenshot_20180428-183525](https://user-images.githubusercontent.com/36526063/39401490-20034666-4b14-11e8-955e-025acc453988.png)

Medium font size
![screenshot_20180428-183600](https://user-images.githubusercontent.com/36526063/39401492-2ae7bbb6-4b14-11e8-8e49-d9afb307a78a.png)

Large font size (taken later)
![screenshot_20180428-184524](https://user-images.githubusercontent.com/36526063/39401504-58b331e2-4b14-11e8-936f-d2c12d86a069.png)

* * * *
- Tusky Version: 1.7.0
- Android Version: 7.1.2
- Android Device: Nexus 5X

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Ouch! Thanks for reporting!

**Comment by connyduck** [comment]
thx
https://github.com/tuskyapp/Tusky/commit/d4425c619a2e867906e9c5d00d259d3cf7f16c1b
