### ISSUE TITLE
Going back from a video requires two taps on Back button

### ISSUE THREAD

**Issue by C1710** [tuskyapp/Tusky#620]
So there seems to be a small, yet annoying bug:  
When I click on a video, it opens up this video player and shows the video.  
But in order to go back to the timeline, I need to click on the Back button (the one in the Navigation Bar) twice.  
It looks like the first 'back' hides the video controls as it immediately brings me back when they're gone.

* * * *
- Tusky Version: 1.7 + current `master`
- Android Version: 7.1.1
- Android Device: Moto Z2 Play
- Mastodon instance (if applicable): mastodon.xyz

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Yes! Annoys me a lot. Thanks!

**Comment by viviicat** [comment]
This appears to have to do with the video controls--as long as they are open I'm unable to close the video.

**Comment by viviicat** [comment]
I wanted to mention that I found a solution to this issue and pushed it to my dev fork https://github.com/viviicat/Tusky . I plan to make a pull request as soon as I take some time to figure out how to actually do that the "right" way as I haven't done it before.
