### ISSUE TITLE
Design Issue in Profile Page of Other Language (Tamil) 

### ISSUE THREAD

**Issue by balogic** [tuskyapp/Tusky#624]
The details of following, followers and toots in profile page overlaps with one another. Please fix it. Attached the Screenshot below.

![](https://i.imgur.com/ftlaAlj.png)

**Comment by charlag** [comment]
Thanks for reporting! Sorry to see it being this way. We will try to fix that!

**Comment by connyduck** [comment]
fixed https://github.com/tuskyapp/Tusky/pull/662
