### ISSUE TITLE
AccountActivity redesign

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#625]
For Tusky 1.9 I am planning to do a bigger redesign of `AccountActivity` like I did with ComposeActivity for Tusky 1.6.
Things that need to be addressed: #624 #443 #604 #483
Also I will add a third tab so there will be "toots", "toots with replies", "media".
Onening this issue as a heads up to contributors and a reminder for myself to not forget anything. I am also open for any discussion or other ideas.

**Comment by connyduck** [comment]
Honestly, I would like to rewrite in Kotlin, but lets see how much time I will find.

**Comment by Lionirdeadman** [comment]
You may want to make NSFW pictures appear as such in the media tab too just like Mastodon does.

**Comment by charlag** [comment]
That should be a separate thing but yes, it needs a lot of improvement

**Comment by charlag** [comment]
I think we can have one badge for blt, moved and suspended?

**Comment by charlag** [comment]
Ah, you're right
