### ISSUE TITLE
Enable custom emojis in profiles (notes, field values, display names)

### ISSUE THREAD

**Issue by charlag** [tuskyapp/Tusky#631]
See https://github.com/tootsuite/mastodon/pull/7374

**Comment by connyduck** [comment]
Custom emoji support should now be complete, except for users own name in the Drawer. That one is tricky because it is not possible with the current Drawer api. I will look at it for the next release, maybe we need to subclass something or send a PR to the drawer library.

**Comment by connyduck** [comment]
I think we have to cache an accounts emojis in database in order to have them display correctly in the side drawer 🤔

**Comment by charlag** [comment]
You mean shortcode -> url?

**Comment by connyduck** [comment]
Yes. Or we could use the cache we use for the emoji keyboard. But that contains ALL emojis of an instance and that could make `CustomEmojiHelper.emojifyText` really slow 🤔
