### ISSUE TITLE
Custom emojis are forced to a square aspect ratio

### ISSUE THREAD

**Issue by ashkitten** [tuskyapp/Tusky#635]
Emojis like :oh_no: from dev.glitch.social are squished to a square aspect ratio, whereas the web client leaves them as is and only scales to a certain height.

![e76a15d45f7d8512](https://user-images.githubusercontent.com/9281956/39712700-02bebbdc-51f2-11e8-87fd-2a832803cd41.png) 

* * * *
- Tusky Version: 1.7.0
- Android Version: 8.1.0
- Android Device: Google Pixel XL
- Mastodon instance (if applicable): dev.glitch.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Thanks for reporting! Cannot say how hard it is to fix right now but I think it's possible

**Comment by connyduck** [comment]
The problem with this is, we cannot know the size of the emoji prior to loading it, so the text will reformat when the emoji does not have square aspect ratio with could cause the whole layout to jump. This could get really ugly and I would rather not support any other aspect ratio than having this.

**Comment by charlag** [comment]
Hmm, we can invalidating anyway after loading but as I remember intrinsic size was too small so I just hardcoded the size. It's totally possible to write a thing which will figure appropriate size but it's not really high priority

**Comment by Tak** [comment]
ref: https://snouts.online/@DanQGoo/101484458448518003

**Comment by ashkitten** [comment]
can we at least maintain aspect ratio and center them within the square?
