### ISSUE TITLE
[i18n] Language unavailable on Android

### ISSUE THREAD

**Issue by Quenty31** [tuskyapp/Tusky#644]
I'm opening this issue because for some language it's impossible to have the application translated as the application switches to the system language.
The problem is that for example, Android is not available in Occitan, so the application won't show in this language.
Could we add a menu in the setting to set the language one wants?

**Comment by charlag** [comment]
Hi! I understand your issue but I'm not sure how hard it is to add this. We use native instruments to switch languages so I'm not sure if it's possible at all. We'll try to look into this!

**Comment by ariasuni** [comment]
Silence (and I guess Signal) does this.

**Comment by ariasuni** [comment]
I’m working on it.
