### ISSUE TITLE
Migrate from RelativeLayout to ConstraintLayout

### ISSUE THREAD

**Issue by charlag** [tuskyapp/Tusky#645]
RelativeLayout is de-facto deprated. It is a very slow layout (which measures children *twice*) and it's kinda buggy and tied to platform.
ConstraintLayout is a modern and very powerful alternative. In most cases nesting layouts is a bug with ConstraintLayout.

The most obvious case is [item_status.xml](https://github.com/tuskyapp/Tusky/blob/master/app/src/main/res/layout/item_status.xml). Right now it has *two* `RelativeLayout`s, `ConstraintLayout` and `LinearLayout` which is clearly too much.
It's kinda tricky to not break anything but I believe that we can simplify layout a lot.

**Comment by rkerkour** [comment]
I would like to work on this issue how I assign it?

**Comment by connyduck** [comment]
Just write here that you started working on it and send us a pull request when you are finished!
