### ISSUE TITLE
Add a LicenseActivity

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#646]
Link it somewhere in the about screen, I don't think a dedicated entry in the side menu is needed.
Should show & link all libraries we use. Should look like this:

<img src="https://user-images.githubusercontent.com/10157047/39862591-8a67595a-5444-11e8-90c6-4a8e6f42b357.png" width="200px"/>

Maybe we can use a library like this one https://github.com/yshrsmz/LicenseAdapter

**Comment by charlag** [comment]
I don't remember if we decided to use something like the library you linked or Google's thingy. I don't care personally.
