### ISSUE TITLE
Support the focal point feature introduced in Mastodon 2.3

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#648]
https://github.com/tootsuite/mastodon/releases/tag/v2.3.0

- [ ] Set image previews correctly according to their focal points
- [ ] Support setting a focal point when uploading media

I think we should definitely implement the first point, not sure if we really need the second.

**Comment by iknownothingaboutcomputers** [comment]
@connyduck I think both are needed. It really helps.

**Comment by iknownothingaboutcomputers** [comment]
ETA?

**Comment by connyduck** [comment]
its not planned currently

**Comment by jfml** [comment]
I would really love to have this! Just went through the trouble of going to the desktop to repost a toot that had an image where the head was cut off in the preview +___+

**Comment by Tak** [comment]
Implemented in #899 and #2620
