### ISSUE TITLE
Notification sound is not grouped in 1.8

### ISSUE THREAD

**Issue by MightyPork** [tuskyapp/Tusky#650]
Tusky can now produce batches of 10 or more boops within a few seconds, whenever it happens to fetch updates, instead of doing it just once.

**Comment by charlag** [comment]
Thx for filling this in!

**Comment by connyduck** [comment]
The problem is, we are dealing with multiple notifications now, so `setOnlyAlertOnce` no longer works 🤔
I guess we have to manually set no sound&no vibration to all notifications but the first from a batch. I really hope this is even possible with notification channels on Oreo.

**Comment by charlag** [comment]
There's an article on this
 http://blog.danlew.net/2017/02/07/correctly-handling-bundled-android-notifications/

> Noisy Notifications
> 
> Notifications typically alert the user in some way, like making sound and/or vibrating.
> 
> Unfortunately, if you're adding multiple notifications at once, each still makes its own individual noise! This creates a cacophony if you create many notifications at once (which can easily happen if the user was offline for a bit).
> 
> Our solution was to examine all the notifications we're adding and only enable sounds for one of them. If there's only one notification, then the choice is easy. If there are multiple, then we set sounds on the group summary alone. This keeps the user from being overwhelmed by notification noises.

People are really annoyed because of this and we should solve this asap
