### ISSUE TITLE
Uploading any media files when creating a new toot doesn't work anymore

### ISSUE THREAD

**Issue by bonsaiheldin** [tuskyapp/Tusky#654]
Hello there. 👋

Uploading media files when creating a new toot doesn't work anymore at me. When it opens the app for selecting files, it just doesn't show any. It only shows folders, but lists them all as empty as if it ignores all file endings.

I think it already stopped working with Tusky 1.7. I just forgot to report it. ☺️

* https://user-images.githubusercontent.com/11500053/40025652-9f19ca54-57d2-11e8-9fc9-9df29c027679.png
* https://user-images.githubusercontent.com/11500053/40025653-9f38b644-57d2-11e8-91a6-41a582abd530.png

Uploading a photo by sponatenously making one using the app does work though.

* * * *
- Tusky Version: 1.8.0
- Android Version: 6.0.1
- Android Device: Xiaomi Redmi 3S
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This seems to be the same problem as https://github.com/tuskyapp/Tusky/issues/588 
There is no easy fix for this, either some Androids can't pick images, or saving toots with images will fail. The whole process needs to be refactored, but that may break saved toots from older versions. I will try to come up with a solution for the next release.
