### ISSUE TITLE
Loading media from "Media" tab should load the associated status.

### ISSUE THREAD

**Issue by trwnh** [tuskyapp/Tusky#656]
As the title says.

1) Go to user profile
2) open "Media" tab
3) tap on any thumbnail

Expected behavior: either the status loads, or there is a button linking to the status
Actual behavior: media loads directly with no way to reach the status

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! This is fixed in #630 and it's coming in the next version!
