### ISSUE TITLE
Add a "Smaller" and a "Larger" font size option

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#657]
These have both been requested quite often.

**Comment by charlag** [comment]
Should this affect posts content, everything in the posts or all labels in the app?

**Comment by charlag** [comment]
Wait we have this option, we need more values or?.. Like 17 and 19 sp?

**Comment by connyduck** [comment]
yes, we already have the option and we should extend it with two additional sizes

**Comment by charlag** [comment]
I've done this, let me push it.
I have no idea what to do with translations, fill missing options with English or delete them altogether so people can add them again?..

**Comment by charlag** [comment]
Ah, it also breaks default for some reason, fucc
