### ISSUE TITLE
Ability to remove accounts from Tusky

### ISSUE THREAD

**Issue by jhaye** [tuskyapp/Tusky#661]
Currently one can only add accounts to Tusky, however in order to remove accounts one has to reset the entire application.
An option for simply removing accounts from Tusky again would be great!
Thank you for your work on the multi account feature!

**Comment by connyduck** [comment]
To remove an account from Tusky, select that account and then logout (last entry in the sidemenu).

**Comment by jhaye** [comment]
Right, thanks for the answer.
I looked for 5 minutes and couldn't find that for some reason.

On 26 May 2018 20:36:48 CEST, Konrad Pozniak <notifications@github.com> wrote:
>To remove an account from Tusky, select that account and then logout
>(last entry in the sidemenu).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tuskyapp/Tusky/issues/661#issuecomment-392279811

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xnuk** [comment]
I tried:
- Long press the account in the account switcher
- Long press the account indicator at the top bar
- Go to account settings and scroll to bottom to check if there's a button like 'delete account'

And... I just found this issue, successfully removed my account. Never expected I can scroll the sidemenu to the bottom... Just sharing my little UI trip story.

**Comment by tullo-x86** [comment]
Reason #9318054 that scrollbars still matter!
