### ISSUE TITLE
Feature Request: Add title of the website when sharing it on Mastodon

### ISSUE THREAD

**Issue by moshpirit** [tuskyapp/Tusky#667]
A feature I really miss from Twidere is being able to share links with the title of the web. 

For example, if I share [this website](https://www.cnbc.com/2018/05/28/european-union-moves-to-ban-single-use-plastics.html) on Twidere, it automatially detects the title and add it, so it doesn't show me `https://www.cnbc.com/2018/05/28/european-union-moves-to-ban-single-use-plastics.html` but `European Union moves to ban single-use plastics - https://www.cnbc.com/2018/05/28/european-union-moves-to-ban-single-use-plastics.html`. This way it's much more comfortable to share interesting websites online.

* * * *
- Tusky Version: 1.8.0
- Android Version: 7.1.2
- Android Device: BQ M5
- Mastodon instance (if applicable): mastodon.social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Sorry, but no. 
- Tusky had this feature once, people were complaining that we auto inserted stuff they did not intend and leak data by resolving the url
- Tusky uses the mastodon card feature to show title and preview image of links in the detailed toot view, this is a way better approach

**Comment by moshpirit** [comment]
>Tusky had this feature once, people were complaining that we auto inserted stuff they did not intend and leak data by resolving the url

Is there any way to make it optional? I'm not a developer, so I don't know if this is too complicated. I mean, if this feature was already implemented, then it shouldn't be that difficult to include again, and we could have just a setting (maybe disabled by default) so we can just need to enable this option. Again, I am no developer, so you're the boss here.

>Tusky uses the mastodon card feature to show title and preview image of links in the detailed toot view, this is a way better approach

Only when the toot is opened. For example: https://social.heckin.tech/voxdotcombot shares links but I only can see them when I open the toots, so until then, I have no idea what this link really is about (except because this profile shares the title too).

**Comment by connyduck** [comment]
> Is there any way to make it optional?
Well yes we could, but it probably requires us to ship a fully blown HTML parser, which would add significant size to the apk. I really would like to keep Tusky lightweight and simple, so please understand that we will not add any features that are not really of value to most users
