### ISSUE TITLE
Feature request: open avatars to see them in bigger size

### ISSUE THREAD

**Issue by moshpirit** [tuskyapp/Tusky#669]
Right now we can see avatars and that's nice but if we go (on web UI) to a profile an copy the avatar's image URL we can see in another tab the avatar in a better resolution.

 It's a cool feature I miss from GNU social that would be nice to have on Mastodon (I'll check if this is also requested on Mastodon's web UI)

**Comment by charlag** [comment]
It's actually a pretty good idea, thanks!
