### ISSUE TITLE
forced UI theme bug in 8.1 Oreo

### ISSUE THREAD

**Issue by nadszeg** [tuskyapp/Tusky#671]
i started using the 8.1 Pixel Experience rom instead of MIUI 9 on my Xiaomi Redmi 4x phone, and before, i could toggle between the light and the dark UI from the app's settings. now the system's option overwrites Tusky's theme - i can change to dark or light UI from the Tusky settings, but nothing will happen, only when i change the overall theme in the Android settings. Screenshots: https://imgur.com/a/kW58g45

* * * *
- Tusky Version: 1.8.0
- Android Version: 8.1
- Android Device: Xiaomi Redmi 4X
- Mastodon instance (if applicable): mastodon.social

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! Thanks for the report. This is an interesting bug, we'll look into it!

**Comment by charlag** [comment]
We've discussed it and set priority "low" for now because it only occurs on specific versions and we cannot even really check it now. Thanks for understanding.

**Comment by nadszeg** [comment]
hi! thanks for the reply! i'm gonna wait! :)
