### ISSUE TITLE
oauth2 login broken, opens search briwser

### ISSUE THREAD

**Issue by kenrestivo** [tuskyapp/Tusky#682]
after successfully logging in via what looks like browser redirection, instead of tusky working I get redirected to a search engine browser searching for:

oauth2redirect://com.keylesspalacetusky/?code=NUHfIUCzI8P-VOhwnzBYVl5EiaArC=&state=

hub.spaz.org, lastet tusky from fdroid, lineage 14.1os

**Comment by connyduck** [comment]
That is a known issue with the default browser of lineage OS, can you try a different one please?
