### ISSUE TITLE
Make it easier to remember adding image descriptions for visually impaired people

### ISSUE THREAD

**Issue by aldonogueira** [tuskyapp/Tusky#683]
I have published countless images without a description for visually impaired people. I guess it would be easier to remember if a few modifications were done:
- right after the upload, Tusky would focus on a text field for description
- next to this text field there is an icon such as :question: or :information_source: that explains why this is important
- the user has to write a text and press Add or press Cancel

* * * *
- Tusky Version: 1.8.0 (downloaded from F-Droid)
- Android Version: 7.1.2 (LineageOS 14.1)
- Android Device: Moto G (falcon)
- Mastodon instance (if applicable): https://masto.donte.com.br

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! Thanks for reporting it. I fully agree with indicator I had plans for it. I don't remember us having an issue for this.
