### ISSUE TITLE
Weird notifications on Android Marshmallow

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tuskyapp/Tusky#690]
Notifications don't get displayed (but the clear-all-button is being shown) and the notification LED begins to blink when locking the phone (even when i triggered the clear-all-button). This behaviour only disappears when I go into the app and swipe to the notifications tab and appears when new notifications arrive.

* * * *
- Tusky Version: 1.8.0
- Android Version: 6.0
- Android Device: Wiko UFEEL LITE

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
hi! Sounds really weird. Not sure how to test it! Stupid question, but did you try clearing data/re-installing?

**Comment by koyuawsmbrtn** [comment]
I'll try that out and see if it helps

**Comment by koyuawsmbrtn** [comment]
The issue still persists after clearing data/re-installing the app

**Comment by connyduck** [comment]
I'm guessing this is because we issue the notifications and they get immediately cancelled once the notifications tab is shown. We probably need an additional check somewhere 🤔

**Comment by koyuawsmbrtn** [comment]
Anything new on that topic? The issue still persists in 2.1

**Comment by aadilayub** [comment]
Notifications have been weird for me as well. Some of them show up late, and some don't get sent at all. I'm using a Google Pixel, Android Oreo. I will report back if the problem persists.

**Comment by koyuawsmbrtn** [comment]
So I found out that this issue is only on this specific phone model so it doesn't need fixing if I'm the only one using the phone. This issue can be re-opened if more people used this phone.
