### ISSUE TITLE
Tusky crashes if a profile should be displayed

### ISSUE THREAD

**Issue by demisapiens** [tuskyapp/Tusky#699]
I just downloadet the new tusky beta version over google.playstore.

Every time I want to go to a user profile (mine or others) the whole app close itself.

There is no error code or message shown.

the app is still in the active apps tab, and can be startet normally.

a restart of my phone didn't help.

* * * *
- Tusky Version: 2.0 beta 1
- Android Version: Android 7.0 mit EMUI 5.0.1
- Android Device: honor 6x
- Mastodon instance (if applicable): pentacl.es

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thanks for reporting!
That is a known issue because pentacl.es is still on Mastodon 2.3, will be fixed in the next release!
https://github.com/tuskyapp/Tusky/commit/0930fab72bb984635d4a74af55793e472c9f4aab
