### ISSUE TITLE
Add support for "delete and redraft"

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#705]
new feature of Mastodon v2.4.1

**Comment by rubahness** [comment]
If the priority on this is low, could we conceivably get an enhancement for copying a toot to include the @server of tagged users' identifiers? Right now it only copies the username portion which breaks the tag if they're on a different instance.

**Comment by kyori19** [comment]
I made this feature on my repository.
https://github.com/kyori19/Tusky/commit/ae0b4b6fef208cbb4eee973eef0429d798081d1a

**Comment by charlag** [comment]
Could you send a PR?

**Comment by connyduck** [comment]
@kyori19: Your change does not account for posts with media attached

**Comment by smonff** [comment]
This is a useful feature for those who makes lots of typo and/or have difficulties when writing their thoughts: personally I think I use this feature on the web interface or on Mastalab something like more than 10% of the time and it is very handy, it save a copy-delete-paste set of action , plus, eventually the rewriting of CW and setting of the toot (visibility etc.)

**Comment by charlag** [comment]
We want it and it's useful no doubt, there are just technical difficulties associated with media. We'll solve it eventually. Thanks for the interest.

**Comment by smonff** [comment]
I am sure it involve some complex technical things, what I meant is that it is more like an ergonomy thing.
