### ISSUE TITLE
Crash on profile media load if minimized

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#709]
Steps to reproduce:

1. Go to user's profile
2. Tap on Media and minimize app instantly
3. App crashes. 

* * * *
- Tusky Version: 2.1
- Android Version: 8.1
- Android Device: Oneplus 5
- [ hope so ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thx for reporting!
This is already fixed and will be in the next release https://github.com/tuskyapp/Tusky/commit/4df93c49cb00f254a8c369a828912b110113dc63
