### ISSUE TITLE
"With replies" is too small

### ISSUE THREAD

**Issue by moshpirit** [tuskyapp/Tusky#713]
why leaving such huge space between "with replies" and the sides of the box? It leaves "with replies" too small. 

I'm asking from the ignorance. But I think leaving less space would be better. Maybe even using "+ replies" but probably that's too informal, right?

Anyway, it was just a thought.

(At least on Tusky 2.0 from F-droid)

**Comment by charlag** [comment]
hi!
Space is the same as with other tabs. I'm not sure that "+ replies" translates well or clear.

**Comment by connyduck** [comment]
We use the default Material design Widgets for the tabs. There is not much we can do, there will always be a device or a localization that does not look perfect.

**Comment by connyduck** [comment]
this has been fixed
