### ISSUE TITLE
Lists management enhacements

### ISSUE THREAD

**Issue by danicarril** [tuskyapp/Tusky#714]
I find lists very useful, everytime I follow an user I try to assign him/her to a list. It's a way to control the information overflow. But in Tusky list management tends to be poor: can't add a user directly from his/her profile to a list, can't edit them: describe, add, move or eliminate users, can't see if the users I've added to a list of mine are featured in other users' lists etc.

What are your thoughts about this?

Thanks a lot for reading me.

* * * *
- Tusky Version: 2.1
- Android Version: 8.1
- Android Device: OnePlus 5
- Mastodon instance (if applicable): @scholar.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi!
We agree, of course, that we want proper list management, it's not like we just don't want it, we're just kinda limited on resources now. Thanks for reporting anyway, I did not find an issue for that surprisingly.

**Comment by danicarril** [comment]
I truly understand the limited resources you have. I'm very grateful to you for your app. Thanks!

**Comment by Sushubh** [comment]
This is the first time I noticed when I started using lists on Tusky. Web UI seems to have the option to add user from profiles so that's nice.

**Comment by tdemin** [comment]
I undestand bumping issues isn't great, but having at least a button to add/remove a person to/from a list from their profile would greatly simplify the life of a list user.

By the way, this would ideally fit in a separate feature request issue.

**Comment by tacoturtle** [comment]
Bump. Please bump priority. This is painful

**Comment by connyduck** [comment]
Adding to list from profile is being added in https://github.com/tuskyapp/Tusky/pull/2818
