### ISSUE TITLE
Bookmarks / Saved toots

### ISSUE THREAD

**Issue by danicarril** [tuskyapp/Tusky#715]
This time I'l be brief: I miss the Twitter's bookmark feature. Is there any chance to implement this in the near-medium term?

Thanks a lot for reading me.

* * * *
- Tusky Version: 2.1
- Android Version: 8.1
- Android Device: OnePlus 5
- Mastodon instance (if applicable): @scholar.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi again!
Could you please describe, how this would work? Afaik Mastodon server does not have an api for this so they would be stored locally?

**Comment by danicarril** [comment]
In case of Mastodont's API absence I'd save locally, with an option to download them whenever it's due. If eventually a Mastodont API appears, just sync between them.

**Comment by contraexemplo** [comment]
I believe there's a Mastodon fork with this exact feature (glitch.social, maybe?).

**Comment by charlag** [comment]
I'd put it as a low-level feature, at least locally. @connyduck ?

**Comment by charlag** [comment]
Closed by 6bfe861
