### ISSUE TITLE
Introducing per-account settings

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#716]
Currently, only the notification settings can be applied per-account, all other settings have a global value.

In the next releases I want to introduce more settings like that
- always show sensitive content (see #607)
- default post privacy (will sync with mastodon web) (see #534)
- mark images as sensitive per default? (will sync with mastodon web)
- maybe an possibility to easier see which account is the currently logged in (see #670)

So the question is where should I put the settings? I see three possibilities:
A) Leave them in the settings. Will let to a lot of settings eventually. (vote with 👍)
B) Put them in the "Edit prodile" page. Page may get very long, it is still missing support for account fields. (vote with 😄)
C) Add a new entry in the sidemenu. Not sure if it will be used often enough to justify a new entry. (vote with 🎉)

<img src="https://user-images.githubusercontent.com/10157047/42833527-942bd7a0-89f4-11e8-8d2d-849b8ce85bbd.png" width="320" />

All possibilities will probably need some kind of explanation or visual indication, which setting will sync with mastodon web and which wont, otherwise that may confuse users a lot.

**Comment by noiob** [comment]
Please also allow for an easy way to apply settings to all accounts

**Comment by igalic** [comment]
i really like the way twidere handles this… although i cannot say for sure, that they're doing it correctly ;)

![screenshot_twidere_20180718-143837](https://user-images.githubusercontent.com/497249/42883344-a985460c-8a9b-11e8-90b3-cfc887f24f20.png)

![screenshot_twidere_20180718-143844](https://user-images.githubusercontent.com/497249/42883375-c346921c-8a9b-11e8-887e-48c580d2a02e.png)

![screenshot_twidere_20180718-143854](https://user-images.githubusercontent.com/497249/42883380-c88f7bda-8a9b-11e8-9759-067c627fcf92.png)

**Comment by connyduck** [comment]
Another thing to keep in mind is that we need to fit the new serverside filters somewhere, so I am really a fan of option C 🎉 because it gives us the most space.
