### ISSUE TITLE
Show (only?) CW in notifications for CW'd statuses

### ISSUE THREAD

**Issue by rixx** [tuskyapp/Tusky#717]
When receiving CW'd mentions, I'd prefer (and expect) Tusky to feature the CW in the notification prominently or exclusively, which doesn't happen (I see the non-CW text directly).

* * * *
- Tusky Version: 2.1
- Android Version: 7.0
- Android Device: moto g 5
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! I agree here. Thanks for reporting.

**Comment by connyduck** [comment]
fixed in #754
