### ISSUE TITLE
Crashing when uploading pic

### ISSUE THREAD

**Issue by Neur0dancer** [tuskyapp/Tusky#718]
[Issue text goes here].
App keeps crashing once in a while when i upload a pic. It happens once and then works perfectly well (but not to worry, it's not as if i uploaded tens of pics a day ;))
* * * *
- Tusky Version:Tusky 2.2-4d3a6a6
- Android Version:6.0
- Android Device:homtom HT 37 smartphonr
- Mastodon instance (if applicable):octodon.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I am pretty sure this will be fixed by #722

**Comment by Neur0dancer** [comment]
As far as i can see, it is now (but beware, i'm pretty shortsighted xD)

**Comment by connyduck** [comment]
Are you [@]CountZero on mastodon?
Please keep testing the nightly if it works in the next days I will release the fix for everybody.
Thank you for helping!
