### ISSUE TITLE
Media upload resets when switching to landscape and back to portrait

### ISSUE THREAD

**Issue by codl** [tuskyapp/Tusky#719]
When an image is being uploaded, if I rotate my phone to switch to landscape and back into portrait again, the progress indicator goes back to zero. If left to complete, the media will still upload correctly. It seems it just restarts the upload entirely.

**Comment by codl** [comment]
oops turns out fasthub doesn't respect issue templates so:

- Tusky Version: 2.2
- Android Version: 8.0.0
- Android Device: OnePlus 3T
- Mastodon instance (if applicable): chitter.xyz

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! I did not hear about this issue for some time. Does it happen every time?

**Comment by codl** [comment]
Yes, I can reproduce it every time

**Comment by connyduck** [comment]
this is fixed
