### ISSUE TITLE
Forced phone locking to place notifications

### ISSUE THREAD

**Issue by kikithegecko** [tuskyapp/Tusky#728]
When my phone is unlocked and Tusky is not in the foreground, I've experienced the following behaviour: The phone freezes for a couple of seconds with the display going dark, then my lock screen appears with a new notification from Tusky. It seems to me that the app somehow wants to place a notification on the lock screen and therefore locks the phone.

I'm not sure if this also happens with Tusky in the foreground, I didn't pay attention on that. Also not sure if this issue arises when a notification is already there but I think not. Sorry for the vague info!

* * * *
- Tusky Version: 2.2
- Android Version: 6.0.1
- Android Device: Fairphone 2
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! I don't think we do anything like that. Could it be that you have Ambient Display or something like that on and it dosesn't work properly?

**Comment by kikithegecko** [comment]
There's no Ambient Display setting in my display settings and I've not installed any such app. Also, Tusky is the only app which has this behaviour and I've been using this phone since its release with almost 900 hours of uptime.

**Comment by charlag** [comment]
It's super weird and I don't know why it may be happening. Not sure how to debug it either but we'll try looking into this.

**Comment by kikithegecko** [comment]
Thanks! Feel free to reach our if you need more info :)

**Comment by connyduck** [comment]
Getting more reports about this https://social.tchncs.de/@sumomi/100448010590162510 
🤔

**Comment by kikithegecko** [comment]
Short update: 
* This issue still occurs with Tusky 2.3
* When there is already a notification, additional notifications don't lead to this issue.

**Comment by charlag** [comment]
@Bugsbane sorry, did you mean "not on F-Droid"?
Besides versions available via F-Droid we publish releases here:
https://github.com/tuskyapp/Tusky/releases

**Comment by charlag** [comment]
@Bugsbane sorry, did you mean "not on F-Droid"?
Besides versions available via F-Droid we publish releases here:
https://github.com/tuskyapp/Tusky/releases

**Comment by rhonda** [comment]
It indeed seems to be an issue specific to Android 6.0.1, for which there aren't updates anymore for phones. It happens to me too, unfortunately I don't have any other device and there is no newer android available for my beloved nexus 5.
