### ISSUE TITLE
Swiping between mixed media types is inconsistent

### ISSUE THREAD

**Issue by logic** [tuskyapp/Tusky#730]
When you click on the first image of this toot:

https://mastodon.art/@eishiya/100442420158662448

It displays perfectly; if you swipe left to see the next picture, which is an animation, you only get a black screen. If you click on the animation first, you can't swipe right to see the first picture. (In the animation view, most swiping doesn't behave as you'd expect, but maybe that's better as a separate issue.)

Having some idea of how this works under the hood, I suspect it isn't an easy fix, but it was pretty weird the first time I came across it. :)

**Comment by connyduck** [comment]
Thx for reporting! This is related to https://github.com/tuskyapp/Tusky/issues/429

**Comment by connyduck** [comment]
fixed in #866
