### ISSUE TITLE
Profile image transparent areas get coloured black by crop screen.

### ISSUE THREAD

**Issue by puffinux** [tuskyapp/Tusky#732]
When uploading a new profile image, if the image is a PNG file and has areas that are transparent, the crop feature in Tusky (that appears after selecting the file to upload) changes all the transparent areas in the image to black after the user presses "Crop". The profile image is then uploaded in this modified form.

* * * *
- Tusky Version: 2.2
- Android Version: 7.1.2 (Lineage OS 14.1)
- Android Device: Moto G4 Play
- Mastodon instance (if applicable): fosstodon.org though this issue is very probably nothing to do with the instance.

- [+] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Thanks for reporting!

**Comment by puffinux** [comment]
If you're using picasso-transformations library then using "KuwaharaFilterTransformation" turns transparent areas black, open [the open issue](https://github.com/wasabeef/picasso-transformations/issues/35) for their code. They in turn depend on GPUImage which appears to supply "KuwaharaFilterTransformation" and there's an [identical issue](https://github.com/CyberAgent/android-gpuimage/issues/373) open there so the problem might not be with picasso, but with GPUImage.
