### ISSUE TITLE
[feature] Deletion confirmation

### ISSUE THREAD

**Issue by LogicalDash** [tuskyapp/Tusky#738]
Web Mastodon shows a confirmation dialog when I ask to delete a toot. This would actually be *more* useful in Tusky, because touchscreen input is less precise. I'm more likely to bounce my thumb wrong on the menu button.

* * * *
- Tusky Version: 2.3
- Android Version: 8.0.0
- Android Device: onePlus 3t
- Mastodon instance (if applicable): cybre.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! I think that's not bad idea, thanks for reporting

**Comment by connyduck** [comment]
closed by https://github.com/tuskyapp/Tusky/pull/865
