### ISSUE TITLE
AccountActivity enhancements

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#745]
Just some small things to improve the AccountActivity

- [ ] add pull to refresh to the header, remove it from tabs
- [ ] use the "follow" button as an "unblock" button on the profiles of blocked users
- [ ] add an icon to the profiles of muted users that can be clicked to unmute the user
- [ ] mark suspended profiles and profiles that have blocked the current user
- [x] improve the layout of the AccountFields
- [ ] dont remove the tabs from "moved" profiles

**Comment by pandasoft0** [comment]
@connyduck Does anybody work on this issue? I would prefer to start to work on this feature if nobody work on it.

**Comment by connyduck** [comment]
there has been some work done in #755, but no, nobody is working on it, feel free to pick it up

**Comment by pandasoft0** [comment]
@connyduck i have some questions about this task
1. "add pull to refresh to the header, remove it from tabs
Should app refresh a full content of the account page on swipe down (include all tabs) or just an account info?
2. "mark suspended profiles and profiles that have blocked the current user"
Any ideas how can i get "suspended" or "blocked by user" statuses? I didn't find this info at the API responses
3. "dont remove the tabs from "moved" profiles" 
Sorry, i am newbie at Mastodon. Could you please say me how to do the "moved" status for the profile?

**Comment by connyduck** [comment]
1. It should refresh everything including tabs, otherwise it won't make sense to move it
2. no but should be easy to try out, maybe with the help of an admin
3. My old account is a moved one, for example https://mastodon.social/@ConnyDuck
