### ISSUE TITLE
Escaped HTML in Notifications

### ISSUE THREAD

**Issue by lfuelling** [tuskyapp/Tusky#746]
Hi,
Notifications for likes show escaped HTML chars in the toot quote.

* * * *
- Tusky Version: 2.3
- Android Version: 9 (PPR1.180610.009)
- Android Device: Pixel 2
- <del>Mastodon instance (if applicable):</del>

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
    - Used keywords: `notification, escaped, html`

**Comment by connyduck** [comment]
Can't reproduce. Can you please show me a screenshot or link the status that caused the issue?

**Comment by nailyk-fr** [comment]
In the nick name IIRC. Like nicks with some specials characters.

**Comment by lfuelling** [comment]
Sorry, this is a false positive. It was a notification from the webapp. Sorry for wasting your time.
![screenshot_20180811-131056](https://user-images.githubusercontent.com/5144843/43991218-4ca1f216-9d68-11e8-8da7-5a52fe60ef36.png)
