### ISSUE TITLE
Auto collapse posts with more than 500 characters

### ISSUE THREAD

**Issue by Toromino** [tuskyapp/Tusky#748]
Other ActivityPub implementations (like Pleroma or GNU/Social) support more than 500 characters (Mastodon's recommended character length) in a status. Whichs results in long statuses appearing in their entire length on Tusky.  

I suggest the implementation of an auto-collapse feature, that only shows a preview of the status first (500 characters?), but can be expanded using a button. 

* * * *
- Tusky Version: 2.3-d29a123
- Android Version: 6.0.1
- Android Device: Meizu MX4
- Mastodon instance (if applicable):

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yeah thats a good idea! Somewhat related to https://github.com/tuskyapp/Tusky/issues/655
