### ISSUE TITLE
Provide option to maintain scroll position on timeline

### ISSUE THREAD

**Issue by iandees** [tuskyapp/Tusky#749]
When I open the app my timeline has moved to the top and I have to scroll down and try to remember where my last unread toot was.

Please give me an option to keep scroll position between app opens and show the number of unread toots above my read position. 

* * * *
- Tusky Version: 2.3
- Android Version: 9.0
- Android Device: Pixel 2 XL
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi!
This souls be a cool feature but it would require us to cache all toots on the disk. it's half-done in #663 but I did not figure out how to figure out that there's a gap in the cached toots.

From mobile I cannot find if we have an issue for that already

**Comment by connyduck** [comment]
Yes we already have an issue for that #89 
It has 14 upvotes, so really high priority, I guess

**Comment by iandees** [comment]
Sorry I didn't spot that one.
