### ISSUE TITLE
Black theme

### ISSUE THREAD

**Issue by jkcclemens** [tuskyapp/Tusky#750]
Hi! I like Tusky a lot so far, but I'm really missing the pure black theme from my last client. They're useful on OLED devices for battery saving.

Here's an example of a Reddit client using a pure black theme.

![boost pure black](https://i.imgur.com/AJdZx04.png)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
This is already implemented https://github.com/tuskyapp/Tusky/pull/726 and will be released soon. You can try [Tusky Nightly](https://play.google.com/store/apps/details?id=com.keylesspalace.tusky.test) if you want to have it now

**Comment by jkcclemens** [comment]
Oh, thanks! Didn't think to search PRs >_>
