### ISSUE TITLE
Feature Request: Clear Notifications

### ISSUE THREAD

**Issue by aadilayub** [tuskyapp/Tusky#762]
One of the features that makes Mastodon such a pleasant-to-use social network is the ability to clear all notifications. Reduces clutter and prevents information overload. It would be nice to have this toggle in the Tusky notifications panel.

* * * *
- Tusky Version: Tusky 3
- Android Version: Pie
- Android Device: Google Pixel
- Mastodon instance (if applicable): mastodon.social

- ✅ I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yeah I would like that feature too. I just have no idea where to put such a toggle 🤔

**Comment by aadilayub** [comment]
The most logical place would be somewhere in the notification panel. It could either replace the compose toot FAB or you could just implement it as a clickable row like in the web interface.

**Comment by charlag** [comment]
I am against FAB because:
1. It's a destructive action
2. Changing semantics of a FAB is rarely a good idea

**Comment by pandasoft0** [comment]
Hi @connyduck @charlag 
I would like to implement this feature along with the #764 but i don't know what is the best place to add UI elements for these features.

I see several ways:
1. Add them to the top level of the navigation drawer bellow Preferences or Account Preferences
2. Add them to the account settings. We have a filter section there. So, we can a "Notifications by type" row to this section and "Clear notifications" above it.
3. Implement the long click on the TabLayout icon. And show popup menu with some actions. But, there is no direct way to add long click listener to the tabs. There is hack way (add a long click listener for child views of the tablayout item). I like the solution but i don't like a method.
4. FAB - agree, don't like it.
5. Add a not scrollable item above the recycler view with options (clear notifications, filter by type)
6. Add an item like described at the p.5 but to the top of the RecyclerView adapter.

**Comment by charlag** [comment]
I would prefer 5 or 6. I don't think it belongs to settings.
Long click on tab is not discoverable and not accessible (ideally we need menu for each timeline to refresh it without gesture but that's another story)

**Comment by connyduck** [comment]
closed by #1168
