### ISSUE TITLE
Hashtag Completion

### ISSUE THREAD

**Issue by mailonator** [tuskyapp/Tusky#769]
A hashtag completion would be fine. Hashtags can be long and hard to remember.

- Tusky Version: 2.3
- Android Version: 6.0.1
- Android Device: Samsung S5 mini
- Mastodon instance (if applicable): chaos.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I agree!

**Comment by jooooop** [comment]
Can I suggest that when implemented it automatically selects a CamelCase version of the hashtag for accessibility reasons? Apparently they are better read by screenreaders.

**Comment by charlag** [comment]
@jooooop it is a nice idea but it's a little bit tricky
