### ISSUE TITLE
Error for API Limits

### ISSUE THREAD

**Issue by bernd289** [tuskyapp/Tusky#771]
Just hit an "429 Throttled" error. (Unfollowed a few accounts... :) )
Tusky didn't tell me, it just stopped loading anything - web client told me about that error.

-> please improve error messages like this.

* * * *
- Tusky Version: 2.3
- Android Version: 8
- Android Device:
- Mastodon instance (if applicable): chaos.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
hi! We should.
But maybe we should merge this issue into #813 ? @connyduck
