### ISSUE TITLE
Post visibility isn't preserved when saving draft

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#772]
Post visibility isn't preserved when saving a draft.

Steps to reproduce:
- Begin drafting a post
- Set the visibility to something other than your default
- Close the post and save it
- Begin editing the resulting draft again

Result: Post visibility is reset to the user default
Expected: Post visibility of the draft was preserved

* * * *
- Tusky Version: 3.0b1
- Android Version: 6.0.1
- Android Device: Yotaphone 2
- Mastodon instance (if applicable): cybre.space , probably not relevant

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
closed by #772
