### ISSUE TITLE
Compose activity should scroll to content warning field on selection

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#773]
When enabling the content warning option while composing a post, if the top of the text entry has scrolled off of the screen, the CW field gets the input focus but remains offscreen, so it's not clear to the user what's happening.

Steps to reproduce:
- Begin composing a post
- Enter enough text that the top of the compose entry scrolls off the screen
- Press the CW button

Result: The CW field gets input focus but remains offscreen
Expected result: The activity should scroll up to the CW field? Or maybe the CW field should float? Or?

* * * *
- Tusky Version: 3.0b1
- Android Version: 6.0.1
- Android Device: Yotaphone2
- Mastodon instance (if applicable): cybre.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I am not a fan of floating CW but maybe that's the most accessible option
