### ISSUE TITLE
Enhancement: Add ability to specify notification sound/buzz pattern in preferences

### ISSUE THREAD

**Issue by kenrestivo** [tuskyapp/Tusky#781]
Feature request: ability to choose a unique notification sound and vibrate pattern for Tusky compared to other apps.

* * * *
- Tusky Version: 2.3
- Android Version: 7.1.2
- Android Device: ether
- Mastodon instance (if applicable): All

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kenrestivo** [comment]
Supposedly (according to SO) it's as easy as adding this to the application's XML:

```xml
 <RingtonePreference android:showDefault="true"
     android:key="Audio" android:title="Alarm Noise"
     android:ringtoneType="notification" />
```

I may try it and see if that's an easy win.

**Comment by case** [comment]
:+1: -- just looked for this after getting an audio notification, would love for these to be visual-only, with audio silenced!

**Comment by connyduck** [comment]
Starting with Android 8, apps have to use notification channels. Users can change the sounds of a channel, so you could say this feature already is in Tusky. I don't think changing the vibration pattern is possible with channels.
I am no fan of investing time in adding additional options for older Android versions.

**Comment by kenrestivo** [comment]
As I use Free Software (LineageOS) and older/cheaper devices, it will likely be a long time before I have Android 8. Oh well.
