### ISSUE TITLE
Whitespace in toots not preserved

### ISSUE THREAD

**Issue by edent** [tuskyapp/Tusky#786]
Some toots use whitespace for formatting. Tusky trims / collapses the whitespace.

An example https://botsin.space/@emojidna/100583990127839913

## Tusky 
![screenshot_20180820-195852](https://user-images.githubusercontent.com/837136/44360756-c0782280-a4b3-11e8-9588-ba1ba2630b4a.jpg)

## Chrome for Android 
![screenshot_20180820-195911](https://user-images.githubusercontent.com/837136/44360760-c4a44000-a4b3-11e8-8b2b-3749dfe92415.jpg)

* * * *
- Tusky Version: 2.3
- Android Version: 7.1
- Android Device: OnePlus 5T
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lenchan139** [comment]
@charlag Hi, I just create a PR to Fedilab with the same issue:
https://gitlab.com/tom79/mastalab/merge_requests/2140

It might be tricky but I think it works :(

**Comment by lenchan139** [comment]
Hi, I submitted a PR to Fedilab for the same issue:
https://gitlab.com/tom79/mastalab/merge_requests/2140

...It might be a bit tricky but it hope it also works.
