### ISSUE TITLE
Allow disabling of relative timestamps 

### ISSUE THREAD

**Issue by spacekookie** [tuskyapp/Tusky#788]
I don't know if I'm the only person who prefers absolute dates when it comes to a long timeline but it would be really cool if it was configurable.

When I scroll through someone's feed (or even my own), I want to be able to see the date (even if its shorted like "April 2018" or something) they posted something, not how many days it was and then having to do maths in my head.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/766

**Comment by spacekookie** [comment]
Ah, that must have slipped through my search. Thanks :)
