### ISSUE TITLE
Unable to authorize in Android app (stable and beta) from Chromebook

### ISSUE THREAD

**Issue by sophware** [tuskyapp/Tusky#792]
"An unidentified authorization error occurred" and or "failed getting an authorization token"
* * * *
- Tusky Version: current stable and current beta
- Android Version: 7.1.1
- Android Device: Chromebook (Lenovo Chromebook 13 with Play Store Apps enabled)
- Mastodon instance (if applicable): mastodon.social and mastodon.technology

- [ yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (I searched for authorize, authenticate, chromeos, and chromebook; I found another "failed getting a login token," but it was closed)

NOTE - Android and ChromeOS are not on the same subnet, even though they are on the same device. The app does send you to a web page for auth and does switch to Chrome in ChromeOS to open the page. Choosing "Authorize" in the app does bring the user back to the Android Tusky app.

**Comment by connyduck** [comment]
I think thats this issue https://github.com/doorkeeper-gem/doorkeeper/issues/1137
if it still does not work after these instances updated to the latest Mastodon version its something else

**Comment by sophware** [comment]
Is mastodon.social updated? Problem still happens with that instance.

**Comment by randynose** [comment]
I'm have a  " failed getting login token " issue with my Chromebook also.  I just picked it up today.  I've tried to uninstall Tusky and I also cleared my browser cache.  No joy. 
I did get couple of (web?) 401 errors that pop up on the screen.  Something funky is going on. 

FWIW. Tusky works fine on my phone. 

![eea4cfd14c500871](https://user-images.githubusercontent.com/18078909/63656851-a24c9e80-c767-11e9-9a6d-b05133a059da.png)

![c728423c3e755860](https://user-images.githubusercontent.com/18078909/63656853-a5478f00-c767-11e9-94ca-4a1d5c79fbfd.png)

* * * *
- Tusky Version: 8.1 Current version on Google Play
- ChomeOS version 76.0.3809.102
- Acer Chromebook Spin 11 CP311-1H-C1FS 
- Mastodon instance (if applicable): Fosstodon.org

**Comment by connyduck** [comment]
I would love to fix this, I just have no idea how to debug it without having access to a chrome book :(

**Comment by BenLubar** [comment]
looks like there's an emulator: https://developer.android.com/topic/arc/emulator

**Comment by BenLubar** [comment]
Current hypothesis: Chrome OS allows the LoginActivity to stay open while the browser is requesting authorization, so the app never saves the token in shared storage.

**Comment by BenLubar** [comment]
Confirmed workaround: Close the Tusky app after entering the instance domain and being sent to the browser but before clicking the accept button.

**Comment by connyduck** [comment]
Ah yes, could reproduce it with the emulator! It did indeed not work because it saved the tokens at the wrong point. Thx very much!
