### ISSUE TITLE
Push notifications?

### ISSUE THREAD

**Issue by Lynnesbian** [tuskyapp/Tusky#793]
Currently, only fetch notifications are implemented, and the minimum frequency is 15 minutes. Would it be possible to implement push notifications?

* * * *
- Tusky Version: 2.3
- Android Version: 7.1
- Android Device: Xperia Z5
- Mastodon instance (if applicable): N/A

- [✔️] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Maybe nor real push notifications but I have a good option ob my mind which I implemented for another app. Should be very close.

**Comment by serenitylabs-sascha** [comment]
Posting toot for reference:

> One of the most frequent questions we get is: Why doesn't Tusky support push notifications?
> 
> Because pushing to devices would require us to use proprietary Google libraries and to run a relay server. But we want Tusky to be pure FOSS (free and open-source software) and don't want to send any data to Google so we decided not to implement push notifications at this time. We are researching other possibilities to make notifications faster though.

https://mastodon.social/@Tusky/100616577926425060

**Comment by serenitylabs-sascha** [comment]
Now, for opinion.

Either way to do push notifications should be available, and opt-in only.

* Polling works everywhere, but can drain battery (variable how much, but at any poll frequency)
* Google Cloud Messaging / Play Services introduces non-free code, but provides push notifications (or, at least, a way to wake up the device) for the entire device over one socket.

Arguments for the inclusion of GCM:

* People may not care about free software (enough) and already rely on Play Services everywhere.
* It can be a soft dependency; See how Signal handles this: https://github.com/WhisperSystems/Signal-Android/commit/1669731329bcc32c84e33035a67a2fc22444c24b
* Free software replacements for play services exist now, and are, as far as I can tell, functional enough to use push notifications.

As mentioned, using Play Services even if it is available should be strictly opt-in, and maybe not even suggested on first starting the app.

**Comment by charlag** [comment]
I am strictly against plat services:
- you must you plugins which can do anything to your code
- we will get antifeature on f-droid

I'd implement listening for SSE like we did for github.com/tutao/tutanota

**Comment by nipos** [comment]
I recommend adding an option to keep the streaming websocket permanently open.
That would need a bit more battery but it's 100% privacy friendly and doesn't rely on third parties.
Using Google shit in a open source app for a open source network is a absolute no go in my opinion.
And you shouldn't forget that it's not only the data of the Tusky user which goes to Google but also the data of the people they're discussing with.
I discuss with many Tusky users and I don't want that f***ng Google gets my data.
A permanent websocket (optional as alternative to polling) would be a much better solution.

**Comment by charlag** [comment]
Mastodon doesn't use WebSocket

**Comment by nipos** [comment]
It does,see API documentation here: https://github.com/tootsuite/documentation/blob/master/Using-the-API/Streaming-API.md
I'm the developer of Halcyon,the Twitter-like webclient and that's how I implemented real-time notifications without third-partys.
As it's a webapp that does work only as long as the page is opened here but Tusky as a native app could do it permanently in the background.

**Comment by charlag** [comment]
SSE != WebSocket

**Comment by serenitylabs-sascha** [comment]
A *bit more battery* is about a 50-70% increase in idle power draw to most phones (that don't run anything that might be datamining like Facebook, except for arguably Google Apps), even if you isolate the polling from the rest of your apps logic.

@nipos That's not websocket, websocket is framed TCP upgraded from an HTTP connection; this is just long polling. And please, can we have this discussion on a civilised level? Thank you.

@charlag With microG existing, is there no way to use play services without dragging in a big binary blob?

**Comment by charlag** [comment]
SSE is not long polling either. It does not mean 50-70% battery increase if you let the phone sleep at least sometimes, for me it is around 1-2%

**Comment by serenitylabs-sascha** [comment]
The main issue is that reliably keeping the connection open requires wakelocking the device, which will drastically increase idle power draw.

**Comment by charlag** [comment]
Here's how we did it: we use JobScheduler and try to stay awake as long as possible. For this to work reliably user has to give exception from battery optimizations. If they don't want to, it's fine - it's just a bigger delay/no notifications in doze

**Comment by jtracey** [comment]
Maybe microG has gotten better since I last used it (back when Signal needed it), but I would very much prefer to never have to let that mess touch my phone again.

**Comment by wryk** [comment]
It seems to me that WebSocket et SSE are both available for the streaming API.

(old repo with experiments on the streaming API : https://github.com/wryk/tusky-api/tree/master/experiments/listener)

**Comment by charlag** [comment]
Anything which is not FCM is technically the same as just connecting to Masto directly. I've experimented with this in #892

**Comment by charlag** [comment]
@ishitatsuyuki I'm not sure what you actually want to achieve with commenting/opening issues. Whip developers to work quicker? If everything is fine we'll try to merge that PR I mentioned above in one of the next releases

**Comment by ishitatsuyuki** [comment]
@charlag Oh actually I didn't notice you have already been working on this due to the negative comments at the top. It seems you implemented exactly what I mentioned - thanks and keep it going!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by feld** [comment]
Roma is going to be launching a highly scalable push notification server written in Elixir soon and integrating it in our Tusky fork. We'll be able to support multiple apps and would gladly donate the push services to Tusky if you want it to be an option. No fees for you, and our service will not require 3rd party like OneSignal to get the notifications to Apple/Google.

I'll circle back and check in with you once we have it running and tested thoroughly.

**Comment by PinyaColada** [comment]
When will notification in tusky will arrive?

**Comment by karmanyaahm** [comment]
<https://unifiedpush.org> is a project that allows user-hosted push notifications. Fedilab uses it so the basic resources for Mastodon with UnifiedPush should already work. <https://matrix.to/#/#unifiedpush:matrix.org> is where the discussion for UP is.

**Comment by genofire** [comment]
I would really like it, if Tusky support UnifiedPush.
Otherwise i have to switch to Fedilab.

**Comment by 6543** [comment]
+1 for UnifiedPush
