### ISSUE TITLE
Images not loading 

### ISSUE THREAD

**Issue by MirahImage** [tuskyapp/Tusky#794]
Images are not loading. They remain blank, even after clicking on the image and waiting. 

* * * *
- Tusky Version:2.3
- Android Version:8.0.0
- Android Device:oneplus 3t
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thats strange. 🤔
 On what instance? All images? Also Avatars? On what network connection?

**Comment by MirahImage** [comment]
This was on toot.cat, and avatars were loading fine, but images in toots were not loading, though also images for users on other instances. I would not be surprised if it turned out to be a traffic issue. I've checked today and images are now loading, so I'm going to go ahead and close the issue.
