### ISSUE TITLE
Long toots disappearing in the composition screen

### ISSUE THREAD

**Issue by contraexemplo** [tuskyapp/Tusky#795]
Long toots disappear at certain point in the composition screen. The only way to make it visible again is deleting some of the characters used. I've made a few tests and unfortunately that didn't give an exact answer on how many paragraphs and characters left are needed to make content exhibition malfunction (it generally happens when there's less than 100 left). Here's a GIF showing how it disappears:  

![Quick video of my phone screen while I type a toot. As I type delete, all text disappears.](https://user-images.githubusercontent.com/29989176/44550723-74b7ba00-a6fb-11e8-9be6-0a37c7d77061.gif)

This happens with all themes available.

* * * *
- Tusky Version: Tusky Nightly 3.0 beta 1-791a81e
- Android Version: 8.0.0 on July security patch
- Android Device: Samsung Galaxy S7
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mal0ki** [comment]
I've encountered this too. Once at least.

**Comment by connyduck** [comment]
@mal0ki are you on Android 8 too?

**Comment by mal0ki** [comment]
Yes 8.0.0 currently.

**Comment by bhtooefr** [comment]
FWIW, I'm experiencing this (when I reach circa 1400-1500 characters in a post) in Tusky 7.0 on Android 8.1.0 patch level April 5, 2019 on a BlackBerry BBF100-2 (Key2).

**Comment by mal0ki** [comment]
For me it doesn't seem to be character bound, but rather "pixel height bound" but I can be wrong. 

I.e if I use a lot of double line spaces (like above) i reach the bug a lot faster, than if I just write one long continuous text.

**Comment by connyduck** [comment]
For the record: This only happens on Android 8. Android 8 has a bug where some input can crash apps. The crash has been fixed in https://github.com/tuskyapp/Tusky/pull/731, but as a side effect long inputs are now disappearing.

**Comment by mal0ki** [comment]
I don't think this is an issue anymore, at least it's not anything I've heard anyone encountering recently
