### ISSUE TITLE
Possiblity to move the header to the bottom of the screen

### ISSUE THREAD

**Issue by aleksandar-todorovic** [tuskyapp/Tusky#796]
As someone with a 6" smartphone, it would be nice to have it as a setting to move the header bar to the bottom, like the official Twitter does it since recently.

I disagree with the Twitter's decision to simply move it for everyone by default, but it would still be nice to have it as an option within the settings.

The reasoning is simpler navigation using one hand.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by robsonsobral** [comment]
Despite being a tall guy, I can't reach all the screen of my phone with one hand. To allow bottom toolbar would also allow the creation of swipe actions, like reply or boost, like Telegram X, per example.
