### ISSUE TITLE
Enhancement: Remove redundant "Add data" button if all 4 metadata fields are used

### ISSUE THREAD

**Issue by arunsathiya** [tuskyapp/Tusky#798]
It would be a good idea to remove the `Add data` button that is shown on the `Edit your profile` view, when all 4 metadata fields are used.

It can be shown only when at least one metadata field is available for use.

* * * *
- Tusky Version: 3.0 beta 2
- Android Version: 8.1.0
- Android Device: OnePlus 5
- Mastodon instance (if applicable): mastodon.social (Mastodon instance used for testing)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Thanks for reporting!

**Comment by duggalsu** [comment]
Hi @charlag , shall I work on this?

**Comment by charlag** [comment]
@duggalsu if you like?

**Comment by kylegoetz** [comment]
Should this issue be closed? Looks like a PR for it was merged in a couple years ago.

**Comment by Tak** [comment]
Implemented in #1934
