### ISSUE TITLE
Videos don't have "open toot" button like photos do

### ISSUE THREAD

**Issue by trwnh** [tuskyapp/Tusky#799]
Go to any profile and load the media tab. A three-dot menu appears in the upper right corner on pictures, but disappears on videos. This makes it impossible to open the original toot that the video was attached to.

* * * *
- Tusky Version: 3.0beta2
- Android Version: 8.1
- Android Device: Xperia X Compact
- Mastodon instance (if applicable): mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Yes, we should merge video screen into screen with all other media

**Comment by connyduck** [comment]
fixed by #852
