### ISSUE TITLE
links starting with an uppercase letter aren't can't be opened 

### ISSUE THREAD

**Issue by Dostoi** [tuskyapp/Tusky#801]
Links that start with an uppercase letter can't be opened by tusky. There're recognised as link as there're displayed in blue but tapping on them doesn't do anything
The example I tested was Http://etsy.com 
* * * *
- Tusky Version: 2.3
- Android Version: 5.1.1
- Android Device: samsung galaxy j1

**Comment by connyduck** [comment]
Nice find. Apparently Android can't deal with such links 🤔
Not sure what we should do about that. Lowercasing the first 5 letters of a link before opening it?

**Comment by connyduck** [comment]
Ah `android.net.Uri` has an `normalizeScheme` method that does exactly what is needed here. Let's fix this.
