### ISSUE TITLE
Ability to crop Images

### ISSUE THREAD

**Issue by ChargingBulle** [tuskyapp/Tusky#804]
Please allow the user to crop images before uploading.

Usecase: I screenshot my phone but I only want to show a small part of the screen and/or remove my system bar.

Workaround: I always open my gallery after creating a screenshot. There I use the AOSP Tooling for cropping my image. The process takes about 20 seconds and takes way longer than with, say, WhatsApp. 

Being able to crop images before uploading has showed value (to me) via other apps (e. g. WhatsApp).

[![](https://i.imgur.com/X4wSHN0m.png)](https://i.imgur.com/X4wSHN0.png)
<sub>[image source](http://www.tomsguide.com/faq/id-2343060/instantly-crop-images-whatsapp.html)</sub>

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JonasDralle** [comment]
Perhaps [Android-Image-Cropper](https://github.com/ArthurHub/Android-Image-Cropper) is helpful to you

**Comment by charlag** [comment]
Thanks for reporting, I think @connyduck wanted to include this in Tusky 4?

**Comment by charlag** [comment]
I myself do not use that too much but I see how it may be convenient
