### ISSUE TITLE
Completely black theme

### ISSUE THREAD

**Issue by BNolet** [tuskyapp/Tusky#805]
possible to get a completely black theme? Great for OLED screens saving battery

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
But a completely black screen would make the app useless?¿?

**Comment by BNolet** [comment]
Didn't see closed issue

**Comment by KD0BPV** [comment]
I'm pretty sure he means like mastalab's black theme. On OLED screens, black pixels are literally off, not using any power, not emitting any light. That can save a lot of battery power.
https://cloud.kd0bpv.name/index.php/s/TBHnCnRGYkG2j8d (screenshot of Mastalab's black theme)

**Comment by BNolet** [comment]
@KD0BPV apparently the black theme was added already but I can't find it in the app (supposedly with the latest version)

**Comment by Bugsbane** [comment]
> But a completely black screen would make the app useless?¿?

Yes, but think of the power savings!!! :D

**Comment by JonasDralle** [comment]
Have you people considered, that black just looks super good and some people prefer _Black_ over _Dark_?


![image of black themed thunderbird](https://www.tiotrom.com/wp-content/uploads/2018/01/new-thunderbird.png)

**Comment by JonasDralle** [comment]
Where?
![](https://user-images.githubusercontent.com/6533815/44629313-9c05c580-a94d-11e8-8f08-259619336910.png)

**Comment by connyduck** [comment]
Tusky 3, please blame F-Droid for not updating faster

**Comment by BNolet** [comment]
Guys, this issue is fuckin' closed. Google Play has v3.0 at this point and FDroid is being slow AF. If you want the black theme without using Google Play, go [here](https://tuskyapp.github.io/) and click download apk at the bottom of the page.
