### ISSUE TITLE
(enhancement) Customize Notification Check interval

### ISSUE THREAD

**Issue by alexschnapper** [tuskyapp/Tusky#808]
Instead of providing a list of minutes for notification check interval why not give the user an option where he can enter a number of minutes, so the user could reduce the interval how the user wants to have? And then reduce the fixed minutes to 15, 30 minutes (leaving 1 and 2 hours in the list).

At the moment (Tusky Version 3.0) the app settings offers:

- 15 Minutes
- 20 Minutes
- 25 Minutes
- 30 Minutes
- 45 Minutes
- 1 Hour
- 2 Hours

![2018-08-26 14 12 20](https://user-images.githubusercontent.com/1958292/44628105-3956fe80-a93a-11e8-960f-ec3ca6a831cc.jpg)

Opened the issue due to a toot [https://chaos.social/@luzifer/100616322310832628]

* * * *
- Tusky Version: 3.0
- Android Version: 7.0
- Android Device: Honor 6.x
- Mastodon instance (if applicable): 

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
The Android platform does not allow background jobs to run more often for battery saving reasons.

**Comment by JonasDralle** [comment]
> the user an option where he can enter a number of minutes

as far as I see it, this issue is more about having an numeric EditText instead of a selector.
Maybe people want to poll every 6 hours, who knows?

**Comment by JonasDralle** [comment]
I'm not good at answering that question. I don't use notifications at all.

**Comment by JonasDralle** [comment]
I can't find doc on the 15 minute limit. What exactly does android limit and where? I feel like my apps are (sometimes) using the network much more heavier even when in background.

I looked at
- [Minimize the effect of regular updates](https://developer.android.com/training/efficient-downloads/regular_updates)
- [JobScheduler Doc](https://developer.android.com/reference/android/app/job/JobScheduler)
- [AlarmManager Doc](https://developer.android.com/reference/android/app/AlarmManager)
- [Schedule jobs intelligently](https://developer.android.com/topic/performance/scheduling)

There's no mentioning of 15 minutes. This number is only mentioned in the `AlarmManager` Doc and that's not the same context as this

**Comment by connyduck** [comment]
https://developer.android.com/reference/android/app/job/JobInfo.html#getMinPeriodMillis()
Its different from Android version to Android version, but its 15 minutes in the recent ones.

**Comment by JonasDralle** [comment]
You're not evil enough to just launch a service and/or schedule a job and reschedule every time the job is executed?

**Comment by connyduck** [comment]
No I won't do that, battery life is important

**Comment by connyduck** [comment]
The notification setting interval has been removed, it is now always 15min. See #826
