### ISSUE TITLE
Feature Request: Add @ and # characters to compose window

### ISSUE THREAD

**Issue by bannisdale** [tuskyapp/Tusky#810]
As # and @ are characters, people usually don't use a lot outside of social networks, it's sometimes kinda cumbersome to use them with your keyboard of choice on a mobile device. Given that these are very essential characters for the Fediverse, though, it might be helpful to have them at hand directly in the compose window.

In my opinion, there is a lot of unused space in the upper bar that would be perfect. My personal proposition would be to add them (and maybe other characters, too?) in the upper-right corner, left of the profile picture of the posting account.

**Comment by mal0ki** [comment]
So I just checked my Twitter app of choice, since it's the only app that's remotely similar, and lo and behold they do have # and @ just above the compose window next to the character limit. 

Interesting. I've never noticed before, and never used it. 

It's a good idea.

**Comment by charlag** [comment]
It may be a nice idea but I we barely made enough space for all the options when @connyduck was re-designing it last time. Would be nice if some layout options were proposed by the champion ;)

**Comment by charlag** [comment]
Hey @Tak is this a part of some PR or it's just in your fork? How does it work on small screens? I guess we could just add it if there's enough space but oh boy we have more functions than Twitter with CWs and sensitive images and custom emojis.

**Comment by bannisdale** [comment]
@charlag I haven't examined the Tak-Commit but given that we have 6 areas in the lower bar already (Attachment, Visibility, CW, Emojis, Sign Count, 'TOOT!' button) and just 2 areas in the upper bar (close ... ... ... avatar), I would assume that adding '#' and '@' next to the avatar (lefthand side, of course) shouldn't result in space problems. :)

**Comment by Tak** [comment]
Oh, I was experimenting in my fork - I didn't realize that referencing the issue in the commit on my fork would create a reference here. :smiley: 
My first attempt was to add them in the lower bar, and there's not enough room on smaller devices.
I also considered adding them in the emoji picker, but that's not terribly intuitive, and makes the emoji picker code less nice.
Maybe the upper bar could be a decent option...

**Comment by charlag** [comment]
I think that we should ask Connyduck about design stuff, I'm quite terrible at such UI things :D

**Comment by bannisdale** [comment]
@connyduck Any opinion on that? :)

**Comment by bannisdale** [comment]
So ... Uhm ... Would anyone mind to ask the duck? :D

**Comment by connyduck** [comment]
The compose screen is already crammed with buttons, I would really prefer to not include any that can be accessed via the keyboard. The screen is missing scheduling and polls which definitely have higher priority. 
If somebody would send a PR that adds @ and # buttons and there are no other arguments against it I would probably still merge it though.

**Comment by bannisdale** [comment]
@Tak Thanks for this! :)
