### ISSUE TITLE
Use Moshi instead of Gson

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#811]
https://github.com/square/moshi

Moshi has better Kotlin support and can use codegen, in my tests thats 25-50% perf improvement, depending on the Json used. Also allegedly it has less impact on apk size.

**Comment by charlag** [comment]
Huh? Did you mean to close it?

**Comment by connyduck** [comment]
Yes, my measurements where not correct and the 50% perf improvement is not true. I will test with a different setup and may reopen this if I find Moshi to be superior, but this has no priority right now.

**Comment by Goooler** [comment]
It's worth doing.
