### ISSUE TITLE
add error screen and two more elephant friends

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#813]
Currently we just show the progress bar forever when an error occurs in most places.
There should be an error screen that has an retry button, a short explanation about what happened and one of the elephant friends depending on the type of the error instead.

https://github.com/tuskyapp/artwork/blob/master/art/tusky_error.svg
https://github.com/tuskyapp/artwork/blob/master/art/tusky_offline.svg

**Comment by charlag** [comment]
I could work on that?

**Comment by connyduck** [comment]
Yes if you want, please do. Check out the other elephants we already have so you get the colors right.
And its probably best to do timelines last and start with blocked users/ favourites and such.

**Comment by charlag** [comment]
Yes, I think we don't need it at least for the home timeline and we should start with other places, I agree.
