### ISSUE TITLE
Tusky fails to authenticate against SAML enabled instance

### ISSUE THREAD

**Issue by moritzheiber** [tuskyapp/Tusky#816]
It would appear the latest release (3.0) fails to authenticate against SAML-enabled instances. Whenever I'm trying to log into the instance `toot.thoughtworks.com` I'm presented with the following modal after a while:

![signal-attachment-2018-08-28-124241](https://user-images.githubusercontent.com/616813/44718607-df347580-aac0-11e8-88b4-9502c8849ee4.png)

The instance has the regular login disabled and only allows for SAML logins.

* * * *
- Tusky Version: 3.0 (F-Droid)
- Android Version: 7.1.1
- Android Device: BlackBerry KeyOne
- Mastodon instance (if applicable): [toot.thoughtworks.com](https://toot.thoughtworks.com) (running 2.4.5)

- [:heavy_check_mark:] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Cannot reproduce on any of my devices or an 7.1.1 emulator. I always reach the login page.
Maybe the instance was down or some other network problem? Maybe an obscure Blackberry specific bug? 🤔

**Comment by cz8s** [comment]
Tusky 3.0 works for me on toot.thoughtworks.com. I upgraded tusky. Didn't have to login again.

**Comment by moritzheiber** [comment]
@cz8s Would version of Android is that?

I'll restart my phone again just to be sure.

**Comment by moritzheiber** [comment]
Okay, a second restart apparently is the charm with this phone. It didn't redirect me to the authorization modal but rather to my timeline, but that's a whole 'nother can of worms.

Closing.

**Comment by lucamp** [comment]
Hi,
I do not know if my issue is the same but I can not login to mastodon.social instance with tusky as I got the same error in the screenshot. Tusky was installed for the first time and I can login with Mastalab. Other instances like toot.thoughtworks.com work
