### ISSUE TITLE
Notifications: Control over the in-app notifications shown

### ISSUE THREAD

**Issue by arunsathiya** [tuskyapp/Tusky#817]
I am referring to the notifications app inside the app in this context, and not the Android app notifications or push notifications.

## Suggestion 

It would be a good idea to have an option on settings (`Preferences`) to hide notifications about new followers and new likes on the toots.

A few users would prefer to see notifications only for replies, and having more granular control over what kind of notifications are seen helps.

## Additional reason why

Additionally, when notifications about new followers and new likes on toots are shown, they are not grouped together. This causes a wastage of screen space which is why disabling these notifications entirely is a better idea, IMO.

* * * *
- Tusky Version: 3.0 beta 2
- Android Version: 8.1.0
- Android Device: OnePlus 5 
- Mastodon instance (if applicable): mastodon.social 

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by xpac1985** [comment]
As somebody said: Twitter made us post things to farm likes/retweets. Being able to not adhere to such "popularity farming" would be nice, so I came here because I'd love to have this feature available.

**Comment by charlag** [comment]
This is a valid case but timelines are a little bit hard to change.
To load things with scrolling, we have to remember first/last IDs of the elements loaded.
To display things on the screen, we need some way to map positions of items on the screen to positions of items in the statuses list. Right now it's very simple 1-1 mapping. If we don't show certain types of statuses, it becomes harder (please keep in mind that things can be changed/deleted and we need to react to that).
If anyone has ideas how to implement this, I would be glad to hear them.

**Comment by xpac1985** [comment]
I'm not a Java/Android coder, just have some Python experience, so I don't know in detail.
I assume each Notification is some kind of object of a certain class, so I'd keep a list of those objects, or get one. I'd then, on a change of the setting, scan that list and turn each element of the corresponding type invisible.
This is however a pretty rough idea because I don't understand enough of the Tusky code to actually make a better suggestion, sorry.

**Comment by charlag** [comment]
Well, we could use invisible cells, that's true, not sure how performant it would be though

**Comment by xpac1985** [comment]
Alternatively - reload the notifications when the setting is changed. The same you do when the account is created first - just trash all notifications, reload, filter on that data. You would still have the most recent notification, even if it wasn't displayed.

**Comment by digitalcircuit** [comment]
If we're adding options for the Notification column, I'd suggest following the web UI and allow disabling follower and mention notifications, too.

**Mastodon web UI Notification column settings**
![Mastodon's notification column web UI](https://zorro.casa/sync/Hosting/Utilities/Development/Tusky/issues/notifications-hide-boosts-favs/Mastodon%20web%20UI%20notification%20settings.png#v1 )

*Somehow I missed this issue despite searching for it when filing https://github.com/tuskyapp/Tusky/issues/841 ...  Oops.*

**Comment by nazco** [comment]
Do we have a chance for such a feature in a future release?

**Comment by charlag** [comment]
I think this is useful but no one is working at it right now. It would require changing notifications screen quite a lot. Our maintainer is taking a break, when he's back we can prepare a feature set for the next release. If someone wants to implement it, we will gladly accept a PR.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/1168
