### ISSUE TITLE
[feature request] View profile in browser

### ISSUE THREAD

**Issue by kevquirk** [tuskyapp/Tusky#819]
When viewing a new profile that your instance hasn't yet federated with, you cannot see previous Toots. It woudk be good to have a link in the profile hamburger menu to view the profile in browser.

This way, people can see all public Toots that account has made, regardless of federation.

Thanks!

**Comment by connyduck** [comment]
![img_20180829_120626](https://user-images.githubusercontent.com/10157047/44781219-0dc75480-ab84-11e8-88cb-57bc487b5023.jpg)

There is a link? Or do you mean something else?

**Comment by kevquirk** [comment]
It's already a feature. For some reason I couldn't see it before.
