### ISSUE TITLE
Feature Request: Share images from posts directly to other application

### ISSUE THREAD

**Issue by vanitasvitae** [tuskyapp/Tusky#822]
Hi!

Right now I have to download images from posts and then manually share them to other apps from my file manager/gallery. It would be nice to be able to share an image to another app directly from Tuskys image viewer.

**Comment by charlag** [comment]
hi!
I see your point but wouldn't sharing actual posts better than images?

**Comment by vanitasvitae** [comment]
That is already possible, isn't it? Still, in instant messaging I prefer to share the image, so the recipient receives a preview instead of a link.
