### ISSUE TITLE
Remove the notification check interval option

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#826]
I would like to remove the notification check interval option entirely and just check notifications every 15 minutes if they are on. 
- From my measurements, 15 minute checking does not have a significant battery impact. Android schedules the checks intelligently, executes them only when network available etc
- A huge majority of users want notifications either as fast as possible or never (imho)
- Tusky already has a lot of settings and it looks like they are going to become even more. 
- Removing the option could be done with the big preference redesign that is planned for Tusky 4 #716

please discuss or vote with 👍👎

**Comment by connyduck** [comment]
Android doesn't allow to check more often than about every 15 minutes.

**Comment by jaranta** [comment]
I wouldn't mind them disappearing (15 min works for me), but I think this issue is unlikely to reach a majority of the users who might have use cases that are obvious for them but not for us.

**Comment by tdemin** [comment]
no notifications configuration and still no push notifications? how come?

**Comment by Kjwon15** [comment]
Just on/off looks fine

**Comment by Sandmonster** [comment]
Is there any technical reason to remove this setting?

**Comment by charlag** [comment]
@Sandmonster yes and no. We believe that our goal is to make a pleasant client which is easy to use. Every option has a maintenance and UX cost so we try to keep them minimal

**Comment by Sandmonster** [comment]
@charlag well, it seems reasonable, I support your decision

**Comment by kitkatloyalist** [comment]
instead create a hidden expert menu to avoid challenging troglodytes.  Reveal menu similar to mode of exposing android's developer settings.

**Comment by connyduck** [comment]
#891
