### ISSUE TITLE
bug: copy/pasting large text makes it disappear

### ISSUE THREAD

**Issue by igalic** [tuskyapp/Tusky#828]
tusky doesn't allow to select which text to copy, and it's default behaviour is to copy the entire text of a post. 

pasting all that text in to quote only a portion, however, doesn't work, as it makes all of the text disappear:
![empty text field with -2471 characters left](https://i.imgur.com/ZGGgbK1.png)

i realise that I'm effectively reporting two bugs at once, but they are closely related when it comes to _work flow_

**Comment by connyduck** [comment]
Android 8? 
This is probably the same issue as this one: https://github.com/tuskyapp/Tusky/issues/795

**Comment by igalic** [comment]
LineageOS 15.1, which is based on Android 8.1

**Comment by connyduck** [comment]
It is caused by this fix https://github.com/tuskyapp/Tusky/pull/731 which is only in place because of a bug in Android 8 🙄
Lets see if I can find a workaround for the workaround.

**Comment by connyduck** [comment]
-> #795
