### ISSUE TITLE
Upload continues after draft discarded

### ISSUE THREAD

**Issue by ghost** [tuskyapp/Tusky#838]
I took a photo in the app, discarded the toot but noticed via a bandwidth meter overlay on my phone that the upload continued.

A problem as:
* Drained mobile data unecassarily
* Avoidable load on the instance

* * * *
- Tusky Version: 3.1
- Android Version: 8.1.0
- Android Device: Xiaomi Mi A1

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
fixed in #1189
