### ISSUE TITLE
Feature Request: Shorten texts which exceeds mastodon char limit.

### ISSUE THREAD

**Issue by bennibaermann** [tuskyapp/Tusky#840]
It would be nice if texts, which exceeds some char limit could be shortened with a more-button. This would be escpecially useful for federated statuses for example from gnu.social, which have a far greater char limit than mastodon.

* * * *
- Tusky Version: 3.1
- Android Version: 7.1.1
- Android Device: 
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/825

**Comment by charlag** [comment]
UI is a little bit weird but it's there (in Nightly now)
