### ISSUE TITLE
Optionally hide Boosts/Favorites from Notifications column

### ISSUE THREAD

**Issue by digitalcircuit** [tuskyapp/Tusky#841]
### In brief
* Add options for what shows in the Notifications column
  * Mimics option to hide boosts/favorites/followers/mentions from device notifications
  * Mirrors functionality of Mastodon web UI
  * Helps people who opt-in avoid social media addiction

### Rationale

Mastodon's web UI allows choosing what kinds of notifications to show in the notification columns independently from the notification emails.  This can help avoid the addictive aspects of seeing how popular your toots become.

For example, I keep favorite/boost emails on (since I like having a long-term personal archive), but I disable the notifications in Mastodon's web UI so it's not in my face.  Some others prefer to disable all notifications, or even leave them all enabled - there's not really a simplifying "one size fits all" solution here.

**Mastodon web UI Notification column settings**
![Mastodon's notification column web UI](https://zorro.casa/sync/Hosting/Utilities/Development/Tusky/issues/notifications-hide-boosts-favs/Mastodon%20web%20UI%20notification%20settings.png#v1 )

*This is separate from the notification email settings.*

* * * *
- Tusky Version: `3.1`
- Android Version: `8.1`, i.e. [`lineage-15.1-20180904-nightly-shamu-signed.zip`](https://download.lineageos.org/shamu )
- Android Device: [Nexus 6, `shamu`](https://wiki.lineageos.org/devices/shamu )
- Mastodon instance (if applicable): N/A
  - Worthwhile noting: screenshot has `Favorites` as `Licks` and `Boosts` as `Awoos`

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

(*And I'm pretty sure, though I may have missed an issue.*)

**Comment by digitalcircuit** [comment]
Well.. huh.  I searched with several different terms, yet somehow still missed https://github.com/tuskyapp/Tusky/issues/817 - my bad!  Closing this issue in favor of that one.

**Comment by charlag** [comment]
Oh, I've already started writing a reply :sweat_smile:
