### ISSUE TITLE
[minor bug/annoyance] Links to deleted toots redirect to an outside page

### ISSUE THREAD

**Issue by jooooop** [tuskyapp/Tusky#844]
I saw a toot which linked another toot, which had been deleted. When clicking on this link instead of showing a 404 inside tusky it first took me out of tusky (to external browser) and then showed me the upset elephant. 

see for example this toot I made: https://todon.nl/@joop/100702959531094239

fwiw the web view does the same thing, where it opens in a new tab. 

* * * *
- Tusky Version: 3.0
- Android Version: 8.1
- Android Device: wileyfox (irrelevant though)

- [check mark] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi!
I wouldn't consider this a bug. We try to open links which look like possible posts/profiles but if it fails we just open browser

**Comment by jooooop** [comment]
Hence the annoyance in the title, because I was unsure if it would qualify :) 

It's definitely not a huge issue, just a slight bother at times.
