### ISSUE TITLE
Links have a too large hitbox

### ISSUE THREAD

**Issue by noiob** [tuskyapp/Tusky#846]
When there's a link right at the end of the toot text, hitting anywhere to the right of it will open that link instead of the toot, as usual. That's kind of an inconvenience. "Link" includes ats and hashtags, so all blue text.

* * * *
- Tusky Version: 3.1 (beta)
- Android Version: 8.0
- Android Device: LG G6 h870

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! Sorry to say this, but I'm not sure we can do anything about that, it's handled by the system.

**Comment by mde5UmMC** [comment]
would adding a non-link character at the end of the text be possible? maybe a zero width non-breaking space would be enough

**Comment by charlag** [comment]
That it a good idea. Not sure it will aolve everything but doesn't hurt to try I guess
