### ISSUE TITLE
[multi-account] Ability to choose account when boosting

### ISSUE THREAD

**Issue by xuv** [tuskyapp/Tusky#849]
**The problem:** I have multiple accounts. And when browsing the timeline with one, I sometimes see a toot I'd like to boost with my other account. (I make the assumption that most people will have multiple accounts because they talk about different things and subjects depending on the account)

The way to do this at the moment, is I grab the url of the toot I'd like to boost, switch account, paste that url in the search bar, wait for the toot to appear (and btw, it appears multiple times), then boost the toot.

**Proposed feature:** I would not change the way boosting works. Clicking the boost icon should automatically boost from the account I'm logged in. But in the submenu that appears behind the […] under each toot, I would add an entry that says: "Boost with another account" and propose to choose from a list of other accounts that I have set up.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Thanks for detailed motivation, but it is already tracked at #517. The issue waits for it's champion, it's totally doable now
