### ISSUE TITLE
Option to use Emojione instead of system emoji

### ISSUE THREAD

**Issue by dpogue** [tuskyapp/Tusky#85]
Particularly on older phones that don't get the latest OS updates, the newer emoji characters render as sad little boxes.  The art style and visual meaning of the emoji can also be lost in translation between icon sets sometimes.

The Mastodon web client uses [EmojiOne](http://emojione.com/)

**Comment by daycode** [comment]
I wanted to use mastodon's emoji from Tusky too. I'm not and android developer but I'll see how to implement it and perhaps I'll do a pull request.

**Comment by pythe** [comment]
At work we just tore EmojiOne out of our Android app. It may be worth considering Noto: https://www.google.com/get/noto/

**Comment by Lionirdeadman** [comment]
Mastodon now uses Twemoji as of 2.0 so that'd be better.

**Comment by charlag** [comment]
We could use Google's downloadable fonts for emoji, there's a PR but it's very old.

**Comment by connyduck** [comment]
The google emoji support library only works with the standard Android emojis.
We could use this library https://github.com/vanniktech/Emoji
I already use it in other projects, it is really easy to plug in, but it will increase our apk size significally. Personally, I would be willing to make that tradeoff, but i am not sure everybody agrees with that.

**Comment by charlag** [comment]
@connyduck that's not true, you can configure any font and font provider you want.

**Comment by connyduck** [comment]
Oh I see, cool. Lets try it out!

**Comment by dpogue** [comment]
I was poking around at updating [my EmojiCompat PR](https://github.com/Vavassor/Tusky/pull/364) last night, and realized that the only downloadable font provider right now is Google Play Services.

There is a way to have EmojiCompat bundle the fonts with the application, but as you noted that would result in a larger apk size. However, that might also allow us to generate our own "TwemojiCompat" font to bundle so that the emoji would be consistent with the web version of Mastodon rather than Android's Noto Emoji.

**Comment by charlag** [comment]
I'm still not sure what's the best way to deal with this issue. The library mentioned by @connyduck doesn't provide you with choice as far as I understand. i'd go with EmojiCompat + bundled font (noto or emoji one).

**Comment by charlag** [comment]
I've tried using EmojiCompat to use EmojiOne bundled font but it won't work just like that, it needs some metadata in the font.
We *could* try to generate such metadata but it seems crazy.
So, we could either use NotoColorEmoji with EmojiCompat (which is open source too) or we could use [Emoji](https://github.com/vanniktech/Emoji) mentioneed by @connyduck. Using either should be pretty simple.

**Comment by connyduck** [comment]
So, bad news.
EmojiCombat does only support Android Emojis ("Noto" font).
Also downloadable fonts require Google Play Services to be installed.

Then I tried out the library I mentioned https://github.com/vanniktech/Emoji (I use it in a project, but with iOS emojis).

![screenshot_20171104-224512](https://user-images.githubusercontent.com/10157047/32409833-dd01c6c4-c1b3-11e7-92c7-447536b46735.png)

Works fine, but the spacing between the emojis is really ugly 😲
I don't think this is acceptable?

I opened a issue here https://github.com/vanniktech/Emoji/issues/217
So this is not happening for Tusky 1.3.0, but I will keep an eye on it.

**Comment by charlag** [comment]
@connyduck as I said before a) you can use any font but you have to generate a metadata for it but we don't have time for this I guess
b) you don't need play services if you bundle the font with the app (as opposed to "downloadable  fonts" in runtime)
I am okay with Noto myself,  I'd just go with bundled Noto for now, if you ask.

**Comment by connyduck** [comment]
But how does this metadata thing work? Do you have a link? I know how to bundle a custom font, but not how to use it for emojis.

**Comment by charlag** [comment]
@connyduck here: https://stackoverflow.com/questions/46493174/custom-font-for-emojicompat
I had to write my own copy of the config class to make it try to load another font.

**Comment by remi6397** [comment]
It looks like this issue has a significant priority, as most of people use [outdated/unsupported versions](https://developer.android.com/about/dashboards/index.html#Platform) of Android. @charlag, are you still trying to implement that EmojiCompat thing? Or, have you got experimental patches somewhere?

**Comment by connyduck** [comment]
Well since Mastodon web narrowed the space between the emojis this now looks almost exactly like the web ui so I guess we will go with it. 
![](https://user-images.githubusercontent.com/10157047/32409833-dd01c6c4-c1b3-11e7-92c7-447536b46735.png)

I think it is definitely wort the increase in apk size.

**Comment by charlag** [comment]
Looks nice! I didn't touch thus issue for quire some time.

**Comment by remi6397** [comment]
Also, we may need to create custom emoji input method, to make it possible to insert new emoji on legacy devices.

**Comment by C1710** [comment]
I just had a look at the classes that load all the stuff for EmojiCompat and I _think_ it could be possible to modify these classes to load the EmojiCompat font from a file located anywhere in the internal storage.
This would potentially enable users to choose whether they want to have EmojiCompat support (which would require them to download a compatible font file) and (which is the most important part for me as I'm still a fan of the Blob emojis) it would enable them to choose _which_ emoji font to use.

**Comment by charlag** [comment]
Ah, so, you did the thing which I named "crazy" last year and it worked, neat :D

**Comment by C1710** [comment]
@connyduck At least for the Blob emojis I already made a fork which uses the bundled style.
The only issues remaining are:
1. The APK size is much bigger
2. It only applies EmojiCompat to _some_ parts of the app
3. There are some (stupid) people who don't like the Blobs
4. I don't know anything about licenses, so I'm not sure how to make this Apache 2.0 stuff compatible...

https://github.com/C1710/Tusky/

**Comment by C1710** [comment]
Well, I think I made a working EmojiCompat implementation which relies on an external file.
And coincidentally it won't make any problems if there are any issues with loading this font.
The only thing it needs is the storage permission.

**Comment by connyduck** [comment]
What if we host the files on some server, e.g https://tuskyapp.github.io/ and then load them into the apps private storage, then we need no permission and have no big apk

**Comment by C1710** [comment]
This is more or less the solution I'm just trying - just with downloading and another file location. But somehow there are some weird difficulties as I currently have issues using the original NotoColorEmojiCompat.ttf...

**Comment by remi6397** [comment]
@connyduck what about people with poor internet connection or small data plan? Will it be possible to add previously downloaded zipped emoji pack manually? 😕

**Comment by C1710** [comment]
@remi6397 I think this could be totally possible since you could simply add an option to choose another location than somewhere within the apps private storage.

**Comment by C1710** [comment]
So I just uploaded this highly experimental [file-based EmojiCompat version](https://github.com/C1710/Tusky/tree/fEmojiCompat).
But please note that it currently requires a compatible font at `/storage/emulated/0/NotoColorEmojiCompat.ttf` and storage permission in order to work.

**Comment by connyduck** [comment]
#600
