### ISSUE TITLE
Toots don't appear boosted in local timeline when boosted in home timeline

### ISSUE THREAD

**Issue by issueseverywhere** [tuskyapp/Tusky#851]
Hi!

When i boost a toot in my home timeline, the "boost" button appears blue.
Then, if i go to my local timeline, the "boost" button of this same toot is still grey.

I have to open the toot thread to see the "boost" button being blue.

It it quiet misleading, as seeing the same toots i boosted with a grey icon makes me wonder if i actually boosted it, or if there was a connection/network/instance problem.

Good thing is clicking the grey "boost" button in the local timeline doesn't seem to invert the process (un-boost): even after doing that, the "boost" button stays blue in the toot thread.

* * * *
- Tusky Version: Tusky 3.1-e866890
 Android Version: 7.1.2
- Android Device: crosscall action-x3
- Mastodon instance (if applicable): mamot.fr

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Huh, that's really weird, thanks for reporting!

**Comment by connyduck** [comment]
This is definitely fixed, not sure since when
