### ISSUE TITLE
Feature request: support for LaTeX

### ISSUE THREAD

**Issue by SWannell** [tuskyapp/Tusky#854]
As Mastodon has a growing mathematics user base, with instances like mathstodon.xyz, it would be great to get LaTeX formatting (e.g. for mathematical formulae) built into Tusky as standard.

As it stands now, LaTeX isn't formatted properly by Tusky e.g. [this toot](https://mathstodon.xyz/@christianp/100666590381157002) appears as
![x9pgwreo](https://user-images.githubusercontent.com/20322648/45685130-45506d80-bb40-11e8-9713-16b16ecc54b5.jpg)

* * * *
- Tusky Version: N/A
- Android Version: N/A
- Android Device: N/A
- Mastodon instance (if applicable): N/A

- [✓] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
It's quite specific and probably has performance hit. so I'm personally not sure about that. I think that Mastodon is usually not correct media for that.

**Comment by connyduck** [comment]
I just researched how to show LaTeX on Android and I could not find any good, maintained implementation. The performance impact would be huge anyway.
Sorry, this is totally out of scope for Tusky.
But out of curiosity, do these LaTeX instances have API support, e.g. a flag that would tell us when to render LaTeX and when not?
