### ISSUE TITLE
HTTP 410 results in empty app

### ISSUE THREAD

**Issue by lfuelling** [tuskyapp/Tusky#855]
I just took down my instance and noticed that Tusky just is empty (empty timeline, empty notifications) when getting 410 (gone) for everything. It shows a Network error when viewing my profile though. 

It would be better to show the login screen along with an error message (maybe even the HTTP code) imo.

* * * *
- Tusky Version: 3.1
- Android Version: 9.0
- Android Device: Pixel 2
- Mastodon instance (if applicable): comm.network

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (Gone, 410)

**Comment by connyduck** [comment]
this is planned for Tusky 4, see #813
