### ISSUE TITLE
Add moderator and admin badges to profiles

### ISSUE THREAD

**Issue by transaimee** [tuskyapp/Tusky#859]
Feature request in the title.  It would be nice to be able to see who's a mod or admin on their profile, displayed like the masto web client does.  Badge similar to the [bot] badge.

* * * *
- Tusky Version: Stable 3.1
- Android Version: 8.0.0 Oreo
- Android Device: Samsung Galaxy Note 8 T-Mobile
- Mastodon instance (if applicable): yiff.life

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
We would love to do that, but it is actually not possible, because we don't get that data from the Mastodon api.
Mastodon Ticket is here: https://github.com/tootsuite/mastodon/issues/6702

**Comment by charlag** [comment]
I would keep this open to track it when Mastodon API kicks in
