### ISSUE TITLE
Allowing users to download videos

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tuskyapp/Tusky#861]
It would be a nice thing to be able to download videos. Images can be already downloaded from within the app, but why not allowing to download videos?

* * * *
- Tusky Version: 3.1
- Android Version: 6.0
- Android Device: Wiko Ufeel Lite

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
It is already in progress! #852

**Comment by koyuawsmbrtn** [comment]
Nice thing!
