### ISSUE TITLE
Change to a component/feature oriented package system

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#863]
Current packages:
- top level (activities)
- adapter ❌
- appstore
- db
- di
- entity
- fragment ❌
- interfaces ❌
- json ✖️
- network 
- pager ❌
- receiver ❌
- service ❌
- util
- view ❌
- viewdata ❌
- viewmodel ❌

So I propose we remove the packages marked with ❌ and replace them with component oriented packages

- top level ( BaseFragment, BaseActivity, MainActivity, TuskyApplication)
- timelines
- notifications
- compose
- edit profile
- lists
- preferences
- about
- account lists
- ...

✖️ json package has only one class, lets move it somewhere else

Advantages: when working on a feature, you have to touch only one package and stuff is easier to find.

**Comment by charlag** [comment]
@connyduck I don't have a strong opinion on that but I'm not sure if you just didn't have time for this or don't want to decide on that. It's still relevant I think.
