### ISSUE TITLE
Add moderation / administration panel to mobile client

### ISSUE THREAD

**Issue by transaimee** [tuskyapp/Tusky#868]
I was wondering if it was possible to add support for the admin/moderation panels Into the tusky app.
* * * *
- Tusky Version: 3.1 stable
- Android Version: 8.0 Oreo
- Android Device: Galaxy note 8
- Mastodon instance (if applicable): yiff.life

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! While I think it's possible,
1) we don't have resources for this now - we dot even have pinned toots
2) it's out of our scope. there should be probably another app which does this.

**Comment by kitkatloyalist** [comment]
is there a future for plugins?  (like used for Conversations [xmpp texting app])

**Comment by charlag** [comment]
I don't think we want plugins tbh. We want to make a simple app which is easy and pleasant to use. We believe other clients can be better suitable for this purpose.
