### ISSUE TITLE
[UI] Compose FAB doesn't always disappear/reappear when scrolling/stopping

### ISSUE THREAD

**Issue by HellPie** [tuskyapp/Tusky#875]
When the "Hide compose button while scrolling" option is enabled the Compose FAB obtains this behavior:
- Timeline scrolling:
    - Scrolling up: FAB does not disappear
    - Scrolling down: FAB disappears
- Timeline stops scrolling:
    - Scrolling up: FAB is already there
    - Scrolling down: FAB does not disappear

My expected behavior instead is:
- Timeline scrolling:
    - FAB disappears
- Timeline stops scrolling:
    - FAB reappears

* * * *
- Tusky Version: `3.1`
- Android Version: `8.0`
- Android Device: `oneplus3`

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Well, it makes sense to me actually. You only need to hide FAB when you want to see something below and so you scroll to it.
On the other hand, I see how people may read bottom-to-top and just don't want to see FAB.
Need more input here.

**Comment by HellPie** [comment]
I can understand that, but I mean, the second I lift the finger, if I'm not scrolling, I am more likely to be done reading the tiny part of content the FAB hides, which should usually show the FAB again just in case I want to reply, write a new post etc, and as of now if I am missing content and I'm scrolling up, I still need to scroll down and scroll up again once I'm done because scrolling up simply never hides the FAB.

**Comment by connyduck** [comment]
The FAB hiding on scroll has been removed
