### ISSUE TITLE
Reply is sometimes shown twice in the thread view

### ISSUE THREAD

**Issue by Tak** [tuskyapp/Tusky#880]
My reply to a thread is often shown twice in my thread view. It's intermittent (I didn't manage to get a screenshot for this issue, for example), but there seems to be a correlation with when posting is non-instantaneous.

Refreshing the view fixes the display, so it's a minor issue, but it always makes me think at first that I accidentally double-posted.

* * * *
- Tusky Version: 3.1
- Android Version: 6.0.1
- Android Device: Yotaphone 2
- Mastodon instance (if applicable): cybre.space

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Is this solved by #879 now?

**Comment by Tak** [comment]
I think so? I haven't seen it happen recently...

**Comment by charlag** [comment]
I'll close it then, feel free to reopen :wink:
