### ISSUE TITLE
Bio does not show character counter

### ISSUE THREAD

**Issue by vlladdrakk** [tuskyapp/Tusky#881]
When trying to update my bio I was shown a message saying that I was over the 160 character limit, but there was no character counter. That made it difficult to get my bio under the limit, I had to randomly remove parts, then try to save and hope I was within the limit.

* * * *
- Tusky Version: 3.1
- Android Version: 8.0
- Android Device: Asus Zenfone 3 (ZE552KL)
- Mastodon instance (if applicable): linuxrocks.online

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
closed by #991
