### ISSUE TITLE
Show Reply Count in Timeline (NOT DUPLICATE)

### ISSUE THREAD

**Issue by RadarNyan** [tuskyapp/Tusky#882]
![image](https://user-images.githubusercontent.com/2091529/46815263-84778480-cdb5-11e8-800c-d9eaf6b28a87.png)
I need to see the reply count in the timeline, the official web UI (https://mastodon.social/web/) already does this and it's very useful, especially when "show replies" is turned off for Home timeline.

Personally I don't care about boosts count, the official web UI don't have it yet, but since there's also an option for "show boosts", it would make sense to show that count in the timeline as well.

I'm aware of #79 and I ensure you this is not a duplicate. At the end of that issue, it only accomplished showing count for Boosts and Favorites, **not Replies** - in the detailed view only, not in timeline.

* * * *
- Tusky Version: 3.1
- Android Version: 8.1
- Android Device: Mi Mix 2
- Mastodon instance (if applicable): Mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey, thanks for reporting.
Yeah, we probably could display it but I am personally not a fan of it, especially of all these zeroes. I would maybe add some indicators for "there is a reply", pretty much likeweb but without "empty" state.

**Comment by charlag** [comment]
I'm closing it because #885 is closed
