### ISSUE TITLE
Saved images have timestamps added after their endings

### ISSUE THREAD

**Issue by bonsaiheldin** [tuskyapp/Tusky#886]
When you look at images and save them using the Download button on the top right, it adds a timestamp after their ending. This makes them unrecognizable as images by Android making it always ask with which app you want to open them. Also, gallery apps ignore them.

[![screenshot_2018-10-13-15-03-11_com android fileexplorer](http://i63.tinypic.com/sxog1c_th.png)](http://oi63.tinypic.com/sxog1c.jpg)

* * * *
- Tusky Version: 3.1
- Android Version: 6.0.1
- Mastodon instance: chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Had a look at the code, Tusky takes the file name directly from the url of the image.
What instance are you on? Can you send me a link to an affected image?

**Comment by bonsaiheldin** [comment]
> Had a look at the code, Tusky takes the file name directly from the url of the image.
> What instance are you on? Can you send me a link to an affected image?

I'm on chaos.social and thought that wasn't important. I guess will better always include that info from now on, just to be sure.

It appears it's not a bug of Tusky. The images seem to be delivered that way by my instance, i get the same timestamps in the web client, too. Also, it doesn't seem to matter from which instance the toots come. Albeit i'm not sure if this is a Mastodon or a chaos.social thing. However, the issue can be closed, there is none. 🙄

**Comment by connyduck** [comment]
I wonder how exactly browsers handle that? Do they just strip everything after the last dot and add the fileending according to the mime type? 🤔

**Comment by bonsaiheldin** [comment]
I'm not sure what browsers do. If the endings or the MIME types are unknown, they usually just download the files, so i don't think they change the endings at all.

Check this toot and its image for example (try to display it using the web interface of your instance):
https://octodon.social/@miramarco/100894178232214475
Displayed via octodon.social the (original) URL of the image is:
https://assets.octodon.social/media_attachments/files/003/186/875/original/1ebf458d74817136.jpeg
Displayed via chaos.social there is a "system" folder, no "assets"-subdomain and the added timestamp:
https://chaos.social/system/media_attachments/files/001/794/739/original/f5e62fcd70aa4bb0.jpeg?1539522986

https://chaos.social seems to save attachments on its own hard drive. I don't know if that is default for all instances, but i would guess there are more doing this. I'm not sure of they always add stuff after file ending, but i would like to keep this issue open nonetheless. I think Tusky could just remove everything after the question mark, including the question mark itself, leaving the ending and the MIME type untouched. Stuff after question marks isn't needed anyway.

**Comment by charlag** [comment]
We can extract main part of the URL without query, that's true. I think we can try this but I guess it doesn't have any priority for now.

**Comment by connyduck** [comment]
closed by #989
