### ISSUE TITLE
"Filter out by regular expressions" feature doesn't consider image descriptions

### ISSUE THREAD

**Issue by qguv** [tuskyapp/Tusky#893]
When using the regular expression filter feature, image description is not considered part of the post, so posts that include images with descriptions you've filtered out still appear in all timelines.

* * * *
- Tusky Version: 3.1
- Android Version: 8.1.0
- Android Device: not relevant
- Mastodon instance (if applicable): not relevant

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi! Thanks for reporting.
Just to not make surprises for anyone, do you know if it works the same way in web client? thanks.

**Comment by qguv** [comment]
Yes, it looks like the behavior is the same. Now that web is storing its filters on a separate page (namely /filters), those are now done API-side. I'll file an issue upstream.

**Comment by charlag** [comment]
Wait, I don't think that server filters things, I think that it just stores filters but idk if we should do this for description . I would like to hear more people.

**Comment by qguv** [comment]
Right, filters are stored API-side but pulled down and used in the Web UI to handle filtering. Gargron commented on the upstream issue that he thinks it would be too much of a performance hit for Web to filter out both body text and image descriptions. If Tusky wants feature parity with Web, it probably makes sense not to filter out matching image descriptions.

**Comment by charlag** [comment]
Yup, thanks for investigating. it's no technical challenge to us I guess but it would be surprising to have different timelines if we aim for similar experience

**Comment by kitkatloyalist** [comment]
More filtering is more better.  Fewer magical thinking topics is less vexing.  Image descriptors with high veracity like tags helps to not-see nsfc (not safe for chaste).

**Comment by connyduck** [comment]
Tusky will implement the filters saved on the serverside soon, see https://github.com/tuskyapp/Tusky/issues/740
So we won't improve the current filters anymore.
