### ISSUE TITLE
Image descriptions aren't saved if added before images are done uploading

### ISSUE THREAD

**Issue by Siphonay** [tuskyapp/Tusky#896]
When you add a description to an image, and hit confirm before it's done uploading, it doesn't do anything, and you lose the description you just typed. It is a bit frustrating when you spent time to write a descriptive text while waiting for the image to upload with a slow connection.

If it's not technically possible to assign a description to images that aren't done uploading, perhaps it would be nice not having the possibility of adding a description until the image is done uploading?

Have a nice day!

* * * *
- Tusky Version: 3.1
- Android Version: 8.0
- Android Device: Samsung Galaxy S9

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Is this solved by #898 now?

**Comment by Siphonay** [comment]
Yes, it seems to be fixed!

**Comment by charlag** [comment]
Thanks!
