### ISSUE TITLE
4.4.4 auth woes?

### ISSUE THREAD

**Issue by kitkatloyalist** [tuskyapp/Tusky#903]
is this tusky woe because of the alleged cipher suite "limit" of kitkat?

> Android has supported TLS 1.2 since API 16 (android 4.1) but enabled it by default only since API 20 (android "4.4W").

http://developer.android.com/reference/javax/net/ssl/SSLSocket.html

**Comment by charlag** [comment]
We are not going to support Android 4.4, sorry #476

**Comment by kitkatloyalist** [comment]
> Android has supported TLS 1.2 since API 16 (android 4.1) but enabled it by default only since API 20 (android "4.4W")

**Comment by charlag** [comment]
All of this is irrelevant already, we dropped the support. Please, stop bombing the repo with your opinions. You are free to fork and support KitKat for eternity but you cannot demand it from us. Most comments from you show that you didn't read the discussion and I am afraid that if you won't stop we would have to take measures. Do not take it personally, we're just trying to build a good Mastodon client here according to our goals - easy & pleasant to use. We appreciate contribution in the form of the code and opinions but please take care to listen to others and put some thought when you think you need to comment. Thank you.
