### ISSUE TITLE
Images are not rendered at all (black box)

### ISSUE THREAD

**Issue by 3demax** [tuskyapp/Tusky#910]
More often than not images in the post are displayed as a black box with the eye icon in the corner. E.g. this one: https://mastodon.social/users/Privacymatters/statuses/101002150360132060
Clicking the eye icon doesn't help.

This is a fresh installation, logged to mastodon first time.
I will not clear data cache for now, let me know if there a way to extract some debug logs and if that will be helpful at all.

![image](https://user-images.githubusercontent.com/128981/48038287-01401900-e13e-11e8-8042-8802a32c0526.png)
![image](https://user-images.githubusercontent.com/128981/48038295-09985400-e13e-11e8-9192-65579a97e020.png)
![image](https://user-images.githubusercontent.com/128981/48038309-0e5d0800-e13e-11e8-9c01-ad9bd263dffc.png)

* * * *
- Tusky Version: 3.1
- Android Version: 8.1.0 (Android One)
- Android Device: Mi A1
- Mastodon instance (if applicable): repost from mastodon.social to mastodon.technology

- [ YES ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi!
Sorry, I forgot about this completely. Does this still happen to you? We can try to extract logs if it does.

**Comment by 3demax** [comment]
Hi! Yes, it still does.
I've been following the latest updates from F-droid. Current version is 4.1.
I tried clearing cache and app data, and it worked fine until I switched to my second account.
First, the issues mention appeared only in second account. I switched back to first account, and now issue is manifesting in both of them.

**Comment by charlag** [comment]
@3demax we changed the image loading library in the meantime, does it still happen?

**Comment by 3demax** [comment]
Nope, all works well now!
Thanks for addressing this.
