### ISSUE TITLE
Can't read and write DMs anymore since Mastodon 2.6

### ISSUE THREAD

**Issue by bonsaiheldin** [tuskyapp/Tusky#912]
Mastodon 2.6 brought a new view for DMs. They were removed from the main timeline, put into their own and are now displayed as threads instead of chronological.

My instance updated and now i can't easily read and write DMs anymore. When i write one it just doesn't appear on the screen, like there was an error and it couldn't be sent. And received ones can only be read through the notifications tab.

Guess it's time for a sixth button in the top bar, with an envelope. 😒

* * * *
- Tusky Version: 3.1
- Android Version: 6.01
- Android Device: Xiaomi Redmi 3S
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
We will make the tabs fully customizable to solve this problem, see here https://github.com/tuskyapp/Tusky/issues/832
