### ISSUE TITLE
Profile pages can't be reloaded if bio or custom fields too long

### ISSUE THREAD

**Issue by bonsaiheldin** [tuskyapp/Tusky#913]
Reloading a profile page works by scrolling on top of the toot list. When the bio of someone is too long or the person has many custom fields, it's impossible to do so as the toot list is not visible. Scrolling does nothing.

![screenshot_2018-11-06-11-30-55_com keylesspalace tusky](https://user-images.githubusercontent.com/11500053/48059399-5e2ce500-e1b9-11e8-825a-99bde3858ac0.png)

I guess the best would be to just put the reload thing above the whole page.

* * * *
- Tusky Version: 3.1
- Android Version: 6.0.1
- Android Device: Xiaomi Redmi 3S
- Device resolution: 720x1280
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Yes, this is really annoying.
This page has some more problems as well, see here https://github.com/tuskyapp/Tusky/issues/745
