### ISSUE TITLE
Timestamp obscured by username in timeline

### ISSUE THREAD

**Issue by archaeme** [tuskyapp/Tusky#920]
Minor cosmetic bug. Some long usernames end up obscuring the timestamp of a post on the timeline.
![screenshot_20181114-215401__01](https://user-images.githubusercontent.com/802788/48527082-e7968400-e857-11e8-8b35-c51ff27652b3.jpg)

* * * *
- Tusky Version: 3.1
- Android Version: 9
- Android Device: OnePlus 6
- Mastodon instance (if applicable): niu.moe

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
duplicate of https://github.com/tuskyapp/Tusky/issues/481

**Comment by archaeme** [comment]
Huh, somehow didn't catch that on my initial search. Thanks.
