### ISSUE TITLE
[Feature Request] Auto-expand CW statuses

### ISSUE THREAD

**Issue by Zacqary** [tuskyapp/Tusky#927]
With the addition of https://github.com/tootsuite/mastodon/pull/8762 to the web client, I'd enjoy seeing the same preference in Tusky: a preference to automatically expand CW'd statuses.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey!
I'm not quite sure if it's available from the API but it looks like it's saved on the server at least. Do you know something about that?

**Comment by charlag** [comment]
We have a setting for this for some time.
