### ISSUE TITLE
Can we add firebase ? Instead of mastodon sign up?

### ISSUE THREAD

**Issue by israkhann** [tuskyapp/Tusky#939]
[I want to made a app that sign in and made data base of firebase is tjat possible to convert this app on firebase?].

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I guess its somehow possible if you add your own backend? You can fork Tusky and do whatever you want, as long as you adhere to GPL 3.

**Comment by israkhann** [comment]
That great i want to make data base on Firebase
