### ISSUE TITLE
[Discussion] should we include Conscrypt for TLS 1.3 support?

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#945]
Previously I was against including Conscrypt just to fix TLS compatibility of old Android versions, because it increases apk size significally (I think it was ~5Mb).
But adding it to support TLS 1.3 is something I would really like to discuss. On Google Play we have Android App Bundles, so at least for users who load Tusky from there the size increase won't be that bad. There are already quite a few Mastodon instances that support TLS 1.3.

A nice sideeffect would be that the strange elliptic curve bug on Android 7 will be goine as well.

👍 = yes TLS 1.3 
👎  = I prefer super small apk

**Comment by charlag** [comment]
I think these days 5mb is *nothing*. If it's 15 or 30, then we should think about it maybe

**Comment by mimi89999** [comment]
I think that it is a good idea to include Conscrypt. Other applications like Conversations already include it.

**Comment by tateisu** [comment]
which instances support TLS1.3 ?

**Comment by connyduck** [comment]
mamot.fr mstdn.jp are the bigger ones I know.

**Comment by stom79** [comment]
Just my two cents about conscrypt. Take care of the releases. Currently 1.3 is stable 1.4 and 1.4.1 created a lot of troubles with Mastalab.
