### ISSUE TITLE
How exactly do I  view my Direct Messages?

### ISSUE THREAD

**Issue by sprite-1** [tuskyapp/Tusky#946]
I'm not sure I understand how I'm supposed to view my Direct Messages on Tusky. Am I just missing something?

Edit:
Okay I'm just dumb. It's on my profile view, along with my toots and boosts. Wish there was a more organized way of viewing it.

* * * *
- Tusky Version: 4.0
- Android Version: Any
- Android Device: Any

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bonsaiheldin** [comment]
No, you're not dumb and even if you were (however that would be defined), it would be okay. :)

This is since Mastodon 2.6 introduced the new DM column. The Tusky team is working on it, see #912 and #832.

**Comment by sprite-1** [comment]
Nice, I'll wait for that then 👍
