### ISSUE TITLE
Sidebar still opened when going to your own profile and then going back

### ISSUE THREAD

**Issue by bonsaiheldin** [tuskyapp/Tusky#948]
When i open my own profile using the sidebar and then go back using the back button, the sidebar is still opened and i have to close it every time to see the main timeline. This only happens when i go to my profile. When i go to the settings or the profile edit screen or any of the other sidebar entries, the sidebar is closed when i go back.

This could be related to #947.

* * * *
- Tusky Version: 4.0
- Android Version: 6.0.1
- Android Device: Xiaomi Redmi 3S
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Never noticed that until now, but you are right this is annoying.
