### ISSUE TITLE
[Feature Request] Add option for uncropped images in timeline

### ISSUE THREAD

**Issue by th3noname** [tuskyapp/Tusky#949]
It would be nice if there was an option to show images uncropped whithin the timeline. Fixed width, dynamic height. 

* * * *
- Tusky Version: 4.0
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi
We discussed that a little bit and we think that it doesn't really fit into current layout, it has to be something more photo-oriented then Tusky, e.g. Pixelfed.

**Comment by charlag** [comment]
One client who does this is Pinafore.
