### ISSUE TITLE
[Feature Request] 3-dotted menu > Open the link in account...

### ISSUE THREAD

**Issue by sprite-1** [tuskyapp/Tusky#958]
Hi! I would love for an added option in the 3-dotted menu beneath every post to have an option below the "Copy the link" called "Open the link in..." which would prompt the user to pick one of the logged in accounts from other instances to open the link in. It would really help with people who have one main account they use to interact with others. But also have an account in other instances just to see that instance's local timeline in Tusky.

Right now, it takes too many steps of:
1. Tap the 3-dotted menu
2. Tap "Copy the link"
3. Go back to main account.
4. Pull up the search
5. Paste the URL.
6. Finally be able to interact with the toot.

If this feature is implemented it would shorten the above steps into:
1. Tap the 3-dotted menu
2. Tap "Open the link in..."
3. Pick the account and interact

* * * *
- Tusky Version: 4.1

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
closed by #988
