### ISSUE TITLE
[feature request] timeline content playing 

### ISSUE THREAD

**Issue by herold33** [tuskyapp/Tusky#961]
Regarding many people looking for some kind of peaceful place after being banned from Tumblr. Especially porn community. It would be nice if at least gifs were played instantly while scrolling without need of clicking it and opening in new window. Playing videos in timeline would be also great. Just like Tumblr app did. 

* * * *
- Tusky Version: 4.1
- Android Version: 8.0
- Android Device: Galaxy Note8
- Mastodon instance (if applicable): humblr.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hey
Honestly, I'm not a big fan of automatic playback:
- It is a waste of bandwith and energy for all parties
- It is associated with autoplaying videos on websites
- It is a mechanism to drive engagement, to turn it into TV to show you ads

I don't doubt it has advantages as well but for me technical difficulty of embedding image player and arguments listed above overweight everything else.

I would like to hear what others think.

**Comment by charlag** [comment]
Since we don't plan to show full-height media in the timeline yet, I think this should also be closed
