### ISSUE TITLE
Add a media download button to cards on timelime

### ISSUE THREAD

**Issue by cun-tee** [tuskyapp/Tusky#966]
Add a media download button to cards on timelime. The current implementation is clunky and inefficient.

C.

* * * *
- Tusky Version: 4.1
- Android Version: oreo
- Android Device: samsung
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Hi!
Would you mind describing your use case and why current implementation doesn't work for you? Thanks.

**Comment by cun-tee** [comment]
Yes when downloading artwork from blogs have to find the art  open it, then click again a few times to get the download button. I'm sure others have this issue and just slows down the process. 4/5 times on each item to get to the download link versus 1 button press on the item download button on the timeline.

C.

**Comment by cun-tee** [comment]
When scrolling through a lost of artwork, I have to 1) click once to open it, then 2) click it again as the buttons have disappeared, then 3) press the download button, then 4) press the back button, then 5) scroll down and repeat.

other apps have the download button on the timeline (see Tumbviewer on play store) so I have to 1) press download and 2) scroll down. Which is 60% less steps and over time is a lot faster and efficient.

C.

**Comment by cun-tee** [comment]
Tumbviewer here https://play.google.com/store/apps/details?id=com.nutrition.humblr

**Comment by Tak** [comment]
This one can be closed, right?

**Comment by Tak** [comment]
Implemented in #1121
