### ISSUE TITLE
Redesign ReportActivity

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#971]
The report activity has several problems and looks ugly af in my opinion.

- toots don't recycle properly
- toots show no media attachments
- it has no "report to remote instance" toggle

So I propose the following redesign:

- split the reporting process into three steps:
  - select toots
  - add note, "report to remote instance" toggle & send button
  - done screen with possibility to mute&block the user
- rewrite everything in Kotlin using a good architecture with ViewModels

**Comment by charlag** [comment]
You're good at designing stuff so maybe you should do it when you have time.
I could do everything else but I don't know it if makes sense.

**Comment by pandasoft0** [comment]
@connyduck I can work on this issue if @charlag hasn't started yet.
So, i have some questions:
1. Do you want to implement it like a wizard? I.e.
- first screen: Select toot, button "Add note"
- second screen: Note, report to remote, button "Send"
- third screen: Account info, buttons: Block, Mute, Close.

2. Select toot screen. Do you want to reuse exists TimelineAdapter for this screen or create a new one? Do you want to have pagination there or load limited count of toots is enough?

3. Done screen. Do you want to show account info like at AccountActivity. Or just simple account info(name, avatar...)+block+mute buttons would be enough?

I can work on the task at this and next week.

**Comment by connyduck** [comment]
I would really like to implement it myself, but I do not have too much time at hand, so you can do it if you want. 

Here is a rough sketch of my ideas:

![report_sketch](https://user-images.githubusercontent.com/10157047/57951005-372e3900-78e9-11e9-8c52-968d97dab4a1.jpg)

I would make one Activity with 3 Fragments that change with an animation. (So yes you can call that a wizard) With the back button one can get back from the 2nd to the 1st screen, but not from the 3rd screen. The x in the Toolbar always closes everything. The "add note" (or "next", or "continue"?), "report" and "done" buttons should be primary buttons, the "block" and "mute" buttons secondary.

> Do you want to reuse the existing TimelineAdapter

No, that one is already a mess and the functionality is different enough to a make a seperate setup. I would really go for a clean rewrite in Kotlin here, preferably based on `PagedList`.

> Done screen. Do you want to show account info like at AccountActivity. Or just simple account info(name, avatar...)+block+mute buttons would be enough?

Account info is enough, avatar is bonus. I would definitely put Block and mute buttons on the screen, maybe even a "block instance" button.

Be careful when testing reports to not annoy some instance admins 😉

**Comment by connyduck** [comment]
#1295
