### ISSUE TITLE
Save search of hashtag

### ISSUE THREAD

**Issue by justinabrahms** [tuskyapp/Tusky#972]
I'd love the ability to save a search for a hashtag (#solarpunk, for instance). Currently, I have to re-search, which is a bit of a pain.

* * * *
- Tusky Version: 4.1
- Android Version: Pie
- Android Device: Pixel 2 XL
- Mastodon instance (if applicable): N/A

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
Perhaps this will be solved when we'll add hashtag columns?

**Comment by justinabrahms** [comment]
This seems exactly like what I want, yes.

**Comment by connyduck** [comment]
Hashtag columns will be added, lets track them with this ticket -> https://github.com/tuskyapp/Tusky/issues/465
