### ISSUE TITLE
[Feature Suggestion] Specify if report should be passed on to origin instance

### ISSUE THREAD

**Issue by averageunicorn** [tuskyapp/Tusky#980]
For a while now, Mastodon has had an option when reporting a toot from a different instance to "forward to [instance the toot is from]". It makes sure that the admin of that instance is aware of the problem with one of their users. It would be nice to have this option in Tusky, too.

* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
see https://github.com/tuskyapp/Tusky/issues/971

**Comment by averageunicorn** [comment]
thanks, I totally didn't see that one.
