### ISSUE TITLE
Toots very narrow

### ISSUE THREAD

**Issue by averageunicorn** [tuskyapp/Tusky#983]
Only happens with toots that don't have a CW.

![the toot text is taking up less than half the width](https://user-images.githubusercontent.com/10791840/51023917-6eca5480-1588-11e9-8a21-da4fc7236297.png)

* * * *
- Tusky Version: 4.1-de6246a
- Android Version: 7.1.2
- Android Device: Asus z00ed
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
It's already fixed and enrolling

**Comment by averageunicorn** [comment]
Ah, thanks! Sorry, I looked through stuff but from the titles didn't recognize the one that was about this ^^;

**Comment by charlag** [comment]
NP! 😉
