### ISSUE TITLE
Problem with toot cache when logging in with a new account

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#990]
Steps to reproduce:
Start with a fresh installation of Tusky.
Log in with A. Notice the timeline loading.
Log in with another user B. Notice the timeline already being filled but suddenly changing. Some toots will be shown that obviously belong to the timeline of A.
The problem resolves itself when switching accounts to A and back to B.

Tusky 4.1-922f165

**Comment by charlag** [comment]
I've tried it but the only error I could reproduce (sometimes) is that one status is duplicated and cannot be opened.
I can think about couple of possible reasons:
- it asks for the wrong account
- fragment is somehow persisted and old data is still there
- SQL query is somehow incorrect

If you can reproduce it reliably, I would ask you to add some logging to the `TimelineRepository#getStatuses()` to see for which account statuses are requested (and maybe what is returned).

**Comment by charlag** [comment]
Another possible reason is that deepEquals on viewData does not work somehow but the data set should be cleared before anyway

**Comment by connyduck** [comment]
> it asks for the wrong account

Yes, thats the reason. When logging in, `AccountManager.addAccount` is called. A dummy `AccountEntity` is created with **ID=0**. For every new account. They get their correct id after the first call to `AccountManager.updateActiveAccount` where the account is saved to database, which only happens when the first network call to `verify_credentials` succeeded. (This is to prevent saving the same account twice to database - we can only detect duplicate accounts if we have all info). But for toot cache it totally messes up the indexes.

I will try to come up with a fix. It probably just needs setting of the correct id in `AccountManager.addAccount`

**Comment by charlag** [comment]
This reads as a good detective story!
Thanks for the investigation. I had no idea it is set up as dummy.
Wouldn't full username be a unique thing (which can act as a primary key)? It should prevent duplicates or do I miss something?
If I can help with something, just ask me!

**Comment by charlag** [comment]
Ah, I looked at the code and I think I understand now. Maybe we shouldn't leave login screen until we save the account but that's not really important rn.
