### ISSUE TITLE
Wrong avatar and displayname in drawer.

### ISSUE THREAD

**Issue by kyori19** [tuskyapp/Tusky#992]
Steps to reproduce
1. In account A, use "Open as ..." menu to switch to account B.
2. Press back button to back to MainActivity.
3. Open drawer and there is **A**'s displayname, **A**'s @username@domain, **A**'s avatar and **B**'s header.

* * * *
- Tusky Version: v4.1-91fba293
- Android Version: 8.0.0
- Android Device: Sony Xperia XZ1 Compact G8441
- Mastodon instance (if applicable): tested on odakyu.app, itabashi.0j0.jp, mstdn.jp.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
I'm looking at this one.

**Comment by connyduck** [comment]
closed by #996
